import {render,screen,fireEvent,waitFor} from '@testing-library/react';
import {it,expect,vi,beforeEach} from 'vitest';
import ProductPersonalLink from './ProductPersonalLink';
import * as api from '../../services/api';
vi.mock('../../services/api',()=>({mapShoppingProduct:vi.fn(),getShoppingCatalogCategories:vi.fn()}));
const row={name:'Exact milk brand',product_code:'7622210453327',quantity:'2',unit:'יח׳',price:'7.50',resolved_product:{source:'open_food_facts',full_name:'Exact milk brand',package_quantity:'1',package_unit:'l'}};
beforeEach(()=>vi.resetAllMocks());
it('name similarity is an optional selection proposal and never saves a mapping automatically',()=>{
 render(<ProductPersonalLink row={{...row,suggested_personal_items:[{id:'1',name:'Milk'}]}} catalog={[{id:1,name:'Milk',default_unit:'l'}]} onMapped={()=>{}}/>);
 fireEvent.click(screen.getByText('שיוך לפריט אישי'));
 expect(screen.getByLabelText('פריט אישי לשיוך')).toHaveValue('');
 fireEvent.click(screen.getByRole('button',{name:'Milk',exact:true}));
 expect(screen.getByLabelText('פריט אישי לשיוך')).toHaveValue('1');
 expect(api.mapShoppingProduct).not.toHaveBeenCalled();
});
it('link selection is explicit, uses package evidence and retains payload/key on lost response',async()=>{
 const mapped=vi.fn();render(<ProductPersonalLink row={row} catalog={[{id:1,name:'חלב 3%',default_unit:'ליטר'},{id:2,name:'חלב ללא לקטוז',default_unit:'ליטר'}]} onMapped={mapped}/>);
 fireEvent.click(screen.getByText('שיוך לפריט אישי'));
 expect(api.mapShoppingProduct).not.toHaveBeenCalled();
 fireEvent.change(screen.getByLabelText('פריט אישי לשיוך'),{target:{value:'1'}});
 expect(screen.getByLabelText('מקדם המרה מאושר')).toHaveValue(null);
 api.mapShoppingProduct.mockRejectedValueOnce(new Error('lost response'));
 fireEvent.click(screen.getByRole('button',{name:'שמירת שיוך בלבד'}));
 await screen.findByText(/השיוך לא נשמר/);
 const request=api.mapShoppingProduct.mock.calls[0][0];
 expect(request.personal_item_id).toBe('1');expect(request.package_quantity).toBe('1');expect(request.planning_unit).toBe('ליטר');expect(request.factor).toBeNull();
 api.mapShoppingProduct.mockResolvedValueOnce({data:{mapping_revision:1,mapping:{personal_item_id:'1',factor:'1'}}});
 fireEvent.click(screen.getByRole('button',{name:'שמירת שיוך בלבד'}));
 await waitFor(()=>expect(mapped).toHaveBeenCalledOnce());
 expect(api.mapShoppingProduct.mock.calls[1][0]).toEqual(request);
 expect(row.quantity).toBe('2');expect(row.price).toBe('7.50');
});
it('creating a personal item requires explicit name/unit/category; regular status is never sent',async()=>{
 api.getShoppingCatalogCategories.mockResolvedValue({data:[{id:7,name:'מזון'}]});
 render(<ProductPersonalLink row={row} catalog={[]} listTypeId={1} onMapped={()=>{}}/>);
 fireEvent.click(screen.getByText('שיוך לפריט אישי'));
 fireEvent.change(screen.getByLabelText('פריט אישי לשיוך'),{target:{value:'new'}});
 await screen.findByRole('option',{name:'מזון'});
 expect(screen.getByRole('button',{name:'יצירה ושיוך בלבד'})).toBeDisabled();
 fireEvent.change(screen.getByLabelText('שם הפריט האישי החדש'),{target:{value:'חלב 3%'}});
 fireEvent.change(screen.getByLabelText('יחידת תכנון לשיוך'),{target:{value:'ליטר'}});
 fireEvent.change(screen.getByLabelText('קטגוריית הפריט האישי'),{target:{value:'7'}});
 api.mapShoppingProduct.mockResolvedValue({data:{mapping_revision:1,mapping:{personal_item_id:'9',factor:'1'}}});
 fireEvent.click(screen.getByRole('button',{name:'יצירה ושיוך בלבד'}));
 await waitFor(()=>expect(api.mapShoppingProduct).toHaveBeenCalledOnce());
 const body=api.mapShoppingProduct.mock.calls[0][0];
 expect(body.new_personal).toEqual({name:'חלב 3%',unit:'ליטר',category_id:'7'});
 expect(body).not.toHaveProperty('regular');expect(body).not.toHaveProperty('price');
});
