-- =============================================
-- FULL DATABASE SCHEMA - FINANCE APP
-- Date: 02/02/2026
-- =============================================

-- 1. טבלת קטגוריות (Categories)
-- הטבלה הזו מחזיקה את השמות, האייקונים ומילות המפתח ללמידה אוטומטית
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  type TEXT CHECK (type IN ('income', 'expense')) NOT NULL DEFAULT 'expense',
  keywords TEXT[] DEFAULT '{}', -- מערך מילים לזיהוי אוטומטי
  icon TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. טבלת אמצעי תשלום (Payment Sources)
CREATE TABLE IF NOT EXISTS payment_sources (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  method TEXT NOT NULL, -- credit_card, cash, bank_transfer, bit
  owner TEXT,
  slug TEXT NOT NULL UNIQUE,
  is_active BOOLEAN NOT NULL DEFAULT true,
  issuer TEXT,
  last4 TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. טבלת תנועות ראשיות (Transactions)
-- הטבלה המרכזית. (category_id, payment_source_id)
CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transaction_date DATE NOT NULL DEFAULT CURRENT_DATE,
  description TEXT NOT NULL,
  movement_type TEXT CHECK (movement_type IN ('income', 'expense')) NOT NULL,
  category_id BIGINT REFERENCES categories(id),
  payment_source_id BIGINT REFERENCES payment_sources(id),
  total_amount NUMERIC NOT NULL DEFAULT 0,
  global_discount NUMERIC DEFAULT 0,
  tags TEXT,
  notes TEXT DEFAULT NULL,
  original_amount NUMERIC DEFAULT NULL,
  currency TEXT DEFAULT 'ILS',
  installments_info TEXT DEFAULT NULL,
  exchange_rate NUMERIC DEFAULT NULL,
  charge_date DATE NOT NULL DEFAULT CURRENT_DATE,
  loan_id BIGINT REFERENCES loans(id) DEFAULT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. טבלת פריטים (Transaction Items)
-- הפירוט של כל חשבונית (חלב, לחם, או סט לגו ספציפי)
CREATE TABLE IF NOT EXISTS transaction_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transaction_id BIGINT REFERENCES transactions(id) ON DELETE CASCADE, 
  item_name TEXT NOT NULL,
  quantity INTEGER DEFAULT 1,
  price_per_unit NUMERIC DEFAULT 0,
  
  -- שדות ספציפיים ללגו
  set_number TEXT,
  theme TEXT,
  img_url TEXT,
  
  -- שדות הנחה לפריט
  discount_type TEXT CHECK (discount_type IN ('amount', 'percent')) DEFAULT 'amount',
  discount_value NUMERIC DEFAULT 0,
  
  tags TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. טבלת תקציב חודשי (Budgets)
-- תקציב מתוכנן לכל קטגוריה בכל חודש
CREATE TABLE IF NOT EXISTS budgets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id BIGINT REFERENCES categories(id) ON DELETE CASCADE,
  month TEXT NOT NULL, -- פורמט: '2026-02'
  amount NUMERIC NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(category_id, month)
);

-- =============================================
-- Security Policies (RLS)
-- =============================================

ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE transaction_items ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Access Categories" ON categories FOR ALL USING (true);
CREATE POLICY "Public Access Payment Sources" ON payment_sources FOR ALL USING (true);
CREATE POLICY "Public Access Transactions" ON transactions FOR ALL USING (true);
CREATE POLICY "Public Access Items" ON transaction_items FOR ALL USING (true);

ALTER TABLE budgets ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Public Access Budgets" ON budgets FOR ALL USING (true);