-- =============================================
-- FULL DATABASE SCHEMA - FINANCE TRACKER
-- Last updated: 2026-08-13
-- Source of truth: docs/db_snapshot.md
-- =============================================
-- Table creation order respects FK dependencies.
-- Only constraints confirmed by the DB snapshot are included.
-- RLS policies are included for the original 5 tables only.
-- =============================================


-- =============================================
-- SECTION 1: FOUNDATION TABLES (no domain deps)
-- =============================================

-- Categories: transaction classification with auto-learning keywords
CREATE TABLE IF NOT EXISTS categories (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL,
  type        TEXT NOT NULL DEFAULT 'expense' CHECK (type IN ('income', 'expense')),
  keywords    TEXT[] DEFAULT '{}',
  icon        TEXT,
  is_active   BOOLEAN NOT NULL DEFAULT true,
  created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Payment sources: credit cards, bank accounts, cash, etc.
CREATE TABLE IF NOT EXISTS payment_sources (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL,
  method      TEXT NOT NULL CHECK (method IN ('credit_card', 'debit_card', 'cash', 'bank_transfer', 'digital_wallet', 'check')),
  owner       TEXT,
  slug        TEXT NOT NULL UNIQUE,
  is_active   BOOLEAN NOT NULL DEFAULT true,
  issuer      TEXT,
  last4       TEXT,
  created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Shopping list templates (e.g. grocery, pharmacy)
CREATE TABLE IF NOT EXISTS shopping_list_types (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL,
  slug        TEXT NOT NULL UNIQUE,
  is_active   BOOLEAN NOT NULL DEFAULT true,
  created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Shopping catalog categories (separate from financial categories)
CREATE TABLE IF NOT EXISTS shopping_catalog_categories (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL UNIQUE,
  icon        TEXT,
  is_active   BOOLEAN NOT NULL DEFAULT true,
  created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Loans: must be defined before transactions due to FK on transactions.loan_id
CREATE TABLE IF NOT EXISTS loans (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  name                    TEXT NOT NULL,
  lender_name             TEXT,
  loan_type               TEXT,
  original_amount         NUMERIC NOT NULL,
  current_balance         NUMERIC NOT NULL,
  monthly_payment         NUMERIC,
  interest_rate           NUMERIC,
  linkage_type            TEXT,
  total_installments      INTEGER,
  remaining_installments  INTEGER,
  start_date              DATE,
  end_date                DATE,
  status                  TEXT DEFAULT 'active' CHECK (status IN ('active', 'paid', 'defaulted')),
  notes                   TEXT,
  amortization_type       TEXT DEFAULT 'spitzer',
  interest_type           TEXT DEFAULT 'fixed',
  prime_margin            NUMERIC DEFAULT 0,
  indexation_type         TEXT NOT NULL DEFAULT 'none'
                          CHECK (indexation_type IN ('none', 'cpi')),
  base_index              NUMERIC(18,4)
                          CHECK (base_index IS NULL OR base_index > 0),
  balloon_amount          NUMERIC DEFAULT 0,
  grace_months            INTEGER DEFAULT 0,
  calculation_mode        TEXT NOT NULL DEFAULT 'legacy'
                          CHECK (calculation_mode IN ('legacy', 'loan_payments')),
  next_payment_date       DATE,
  payment_source_id       BIGINT REFERENCES payment_sources(id),
  auto_payment_enabled    BOOLEAN NOT NULL DEFAULT true,
  closed_date             DATE
);

CREATE INDEX idx_loans_status ON loans (status);


-- =============================================
-- SECTION 2: CORE FINANCIAL TABLES
-- =============================================

-- Main transaction records.
-- Note: id uses the legacy serial/sequence style (INTEGER, not BIGINT IDENTITY).
-- payment_method and payment_source are legacy columns superseded by payment_source_id.
-- current_installment is a legacy field; installment_number/count are the current fields.
CREATE TABLE IF NOT EXISTS transactions (
  id                      SERIAL PRIMARY KEY,
  transaction_date        DATE NOT NULL,
  description             CHARACTER VARYING,
  movement_type           CHARACTER VARYING NOT NULL CHECK (movement_type IN ('expense', 'income')),
  total_amount            NUMERIC NOT NULL,
  charge_date             DATE NOT NULL DEFAULT CURRENT_DATE,
  category_id             BIGINT REFERENCES categories(id),
  payment_source_id       BIGINT REFERENCES payment_sources(id),
  loan_id                 BIGINT REFERENCES loans(id),
  global_discount         NUMERIC DEFAULT 0,
  global_discount_source  TEXT CHECK (
    global_discount_source IS NULL
    OR global_discount_source IN ('loyalty_points', 'coupon', 'store_credit', 'other')
  ),
  original_amount         NUMERIC,
  currency                TEXT DEFAULT 'ILS',
  exchange_rate           NUMERIC,
  installments_info       TEXT,
  installment_number      INTEGER,
  installment_count       INTEGER,
  parent_transaction_id   BIGINT REFERENCES transactions(id),
  current_installment     INTEGER,                    -- legacy field, superseded by installment_number
  payment_method          CHARACTER VARYING,          -- legacy field, superseded by payment_source_id
  payment_source          TEXT,                       -- legacy field, superseded by payment_source_id
  tags                    TEXT,
  notes                   TEXT,
  created_at              TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at              TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE INDEX idx_transactions_loan_id ON transactions (loan_id);
CREATE INDEX idx_transactions_payment_source_id ON transactions (payment_source_id);

-- Added by migrations/003_transaction_pagination_and_aggregates.sql
-- Backs the default list branch: ORDER BY transaction_date DESC, id DESC, its
-- keyset seek, and the from/to range filter. One ordered index scan serves the
-- sort and the cursor together.
--
-- It does NOT fully serve the ascending branch, which orders by
-- (transaction_date ASC, id DESC): a backward scan of this index yields
-- (transaction_date ASC, id ASC), so Postgres adds a sort node there. The
-- id DESC tiebreaker is kept uniform across branches on purpose.
--
-- No index is defined for the amount or description sort branches; see the
-- migration for the cost analysis and the four indexes that would be needed.
CREATE INDEX idx_transactions_date_id_desc ON transactions (transaction_date DESC, id DESC);

-- Authoritative amortization/accounting entries for audited loans. Cash
-- activity remains in transactions; principal and interest live here.
CREATE TABLE IF NOT EXISTS loan_payments (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  loan_id               BIGINT NOT NULL REFERENCES loans(id) ON DELETE CASCADE,
  transaction_id        BIGINT REFERENCES transactions(id) ON DELETE SET NULL,
  installment_number    INTEGER,
  payment_date          DATE NOT NULL,
  payment_amount        NUMERIC(18, 2) NOT NULL CHECK (payment_amount >= 0),
  principal_amount      NUMERIC(24, 10) NOT NULL CHECK (principal_amount >= 0),
  interest_amount       NUMERIC(24, 10) NOT NULL CHECK (interest_amount >= 0),
  annual_interest_rate  NUMERIC(12, 6) CHECK (
    annual_interest_rate IS NULL OR annual_interest_rate >= 0
  ),
  source_kind           TEXT NOT NULL
                        CHECK (source_kind IN ('existing_transaction', 'reconstructed', 'manual', 'generated')),
  payment_kind          TEXT NOT NULL DEFAULT 'installment'
                        CHECK (payment_kind IN ('installment', 'catch_up', 'balance_adjustment', 'early_payoff')),
  installments_covered  INTEGER NOT NULL DEFAULT 1,
  other_amount          NUMERIC(24, 10) NOT NULL DEFAULT 0,
  balance_adjustment_amount NUMERIC(24, 10) NOT NULL DEFAULT 0,
  notes                 TEXT,
  created_at            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  UNIQUE (transaction_id),
  CHECK (
    (payment_kind = 'installment' AND installment_number IS NOT NULL
      AND installment_number > 0 AND installments_covered = 1)
    OR (payment_kind = 'catch_up' AND installment_number IS NULL
      AND installments_covered >= 1)
    OR (payment_kind IN ('balance_adjustment', 'early_payoff')
      AND installment_number IS NULL AND installments_covered = 0)
  ),
  CONSTRAINT loan_payments_balance_adjustment_shape_check CHECK (
    payment_kind <> 'balance_adjustment'
    OR (transaction_id IS NULL AND payment_amount = 0
      AND principal_amount = 0 AND interest_amount = 0 AND other_amount = 0)
  ),
  CONSTRAINT loan_payments_components_reconcile CHECK (
    abs(payment_amount - principal_amount - interest_amount - other_amount)
      <= 0.00000001
  )
);

CREATE INDEX idx_loan_payments_loan_date
  ON loan_payments (loan_id, payment_date, installment_number);
CREATE UNIQUE INDEX loan_payments_unique_installment
  ON loan_payments (loan_id, installment_number)
  WHERE payment_kind = 'installment';
CREATE UNIQUE INDEX loan_payments_unique_early_payoff
  ON loan_payments (loan_id)
  WHERE payment_kind = 'early_payoff';

-- Line items for a transaction (individual products, LEGO sets, etc.)
-- Note: uses legacy SERIAL id. No created_at column in the real DB.
CREATE TABLE IF NOT EXISTS transaction_items (
  id                SERIAL PRIMARY KEY,
  transaction_id    INTEGER REFERENCES transactions(id),
  item_name         CHARACTER VARYING NOT NULL,
  quantity          INTEGER DEFAULT 1,
  price_per_unit    NUMERIC,
  total_item_price  NUMERIC,
  set_number        TEXT,
  theme             TEXT,
  brand             TEXT,
  pieces            INTEGER,
  image_url         TEXT,
  discount_type     TEXT DEFAULT 'amount' CHECK (discount_type IN ('amount', 'percent')),
  discount_value    NUMERIC DEFAULT 0,
  final_price       NUMERIC DEFAULT 0,
  allocated_global_discount NUMERIC NOT NULL DEFAULT 0 CHECK (allocated_global_discount >= 0),
  acquisition_type  TEXT NOT NULL DEFAULT 'purchase'
                    CHECK (acquisition_type IN ('purchase', 'gift', 'gwp')),
  tags              TEXT
);

-- LEGO set collection records. Created automatically on Lego-category transactions.
-- Note: id is UUID, not BIGINT. No CHECK constraints on status or brand in the DB.
CREATE TABLE IF NOT EXISTS lego_sets (
  id              UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  set_number      TEXT NOT NULL,
  name            TEXT NOT NULL,
  theme           TEXT,
  pieces          INTEGER,
  image_url       TEXT,
  purchase_price  NUMERIC,
  receipt_price   NUMERIC,
  original_price  NUMERIC DEFAULT 0,
  status          TEXT DEFAULT 'New',
  brand           TEXT DEFAULT 'LEGO',
  acquisition_type TEXT NOT NULL DEFAULT 'purchase'
                   CHECK (acquisition_type IN ('purchase', 'gift', 'gwp')),
  purchase_date   DATE,
  transaction_id  INTEGER REFERENCES transactions(id),
  created_at      TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Monthly budget targets per category
CREATE TABLE IF NOT EXISTS budgets (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id  BIGINT REFERENCES categories(id),
  month        TEXT NOT NULL,               -- format: 'YYYY-MM'
  amount       NUMERIC NOT NULL DEFAULT 0,
  created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  UNIQUE (category_id, month)
);


-- =============================================
-- SECTION 3: SHOPPING MODULE
-- =============================================

-- Reusable product catalog, scoped to a shopping catalog category
CREATE TABLE IF NOT EXISTS shopping_catalog_items (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id    BIGINT NOT NULL REFERENCES shopping_catalog_categories(id),
  name           TEXT NOT NULL,
  default_unit   TEXT,
  default_price  NUMERIC,
  is_active      BOOLEAN NOT NULL DEFAULT true,
  created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  UNIQUE (category_id, name)
);

CREATE INDEX idx_catalog_items_category ON shopping_catalog_items (category_id);

-- M2M: which catalog categories are available for each list type
CREATE TABLE IF NOT EXISTS shopping_catalog_category_list_types (
  category_id   BIGINT NOT NULL REFERENCES shopping_catalog_categories(id),
  list_type_id  BIGINT NOT NULL REFERENCES shopping_list_types(id),
  created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  PRIMARY KEY (category_id, list_type_id)
);

CREATE INDEX idx_category_list_types_list_type ON shopping_catalog_category_list_types (list_type_id, category_id);

-- Shopping list headers
CREATE TABLE IF NOT EXISTS shopping_lists (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title         TEXT NOT NULL,
  list_type_id  BIGINT NOT NULL REFERENCES shopping_list_types(id),
  status        TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('draft', 'active', 'checked_out', 'archived')),
  created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX idx_shopping_lists_type_status ON shopping_lists (list_type_id, status);

-- Individual items within a shopping list.
-- Each item is either a catalog item (catalog_item_id set) or a custom entry (custom_name set), never both.
CREATE TABLE IF NOT EXISTS shopping_list_items (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  list_id          BIGINT NOT NULL REFERENCES shopping_lists(id),
  catalog_item_id  BIGINT REFERENCES shopping_catalog_items(id),
  custom_name      TEXT,
  category_id      BIGINT NOT NULL REFERENCES shopping_catalog_categories(id),
  quantity         NUMERIC,
  unit             TEXT,
  price            NUMERIC,
  is_purchased     BOOLEAN NOT NULL DEFAULT false,
  purchased_at     TIMESTAMP WITH TIME ZONE,
  notes            TEXT,
  created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  CHECK (
    (catalog_item_id IS NOT NULL AND custom_name IS NULL)
    OR
    (catalog_item_id IS NULL AND custom_name IS NOT NULL AND trim(custom_name) <> '')
  )
);

CREATE INDEX idx_shopping_list_items_list ON shopping_list_items (list_id);
CREATE INDEX idx_shopping_list_items_list_category ON shopping_list_items (list_id, category_id);
CREATE INDEX idx_shopping_list_items_purchased ON shopping_list_items (list_id, is_purchased);

-- Records the checkout event for a shopping list.
-- One checkout per list (list_id is UNIQUE).
-- payment_source_id, category_id, transaction_id reference other tables but have no DB-level FK constraints.
CREATE TABLE IF NOT EXISTS shopping_checkouts (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  list_id           BIGINT NOT NULL UNIQUE REFERENCES shopping_lists(id),
  checkout_date     DATE NOT NULL DEFAULT (timezone('utc'::text, now()))::date,
  total_amount      NUMERIC NOT NULL CHECK (total_amount >= 0),
  payment_method    TEXT NOT NULL DEFAULT 'credit_card' CHECK (payment_method IN ('credit_card', 'cash', 'bank_transfer', 'direct_debit', 'bit', 'paypal', 'other')),
  payment_source_id BIGINT,
  category_id       BIGINT,
  transaction_id    BIGINT,
  created_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX idx_shopping_checkouts_date ON shopping_checkouts (checkout_date DESC);


-- =============================================
-- SECTION 5: ROW LEVEL SECURITY
-- Confirmed for original 5 tables only.
-- All policies use permissive USING (true) —
-- access control is handled at the application layer.
-- =============================================

ALTER TABLE categories       ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_sources  ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions     ENABLE ROW LEVEL SECURITY;
ALTER TABLE transaction_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE loan_payments    ENABLE ROW LEVEL SECURITY;
ALTER TABLE budgets          ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Access Categories"      ON categories       FOR ALL USING (true);
CREATE POLICY "Public Access Payment Sources" ON payment_sources  FOR ALL USING (true);
CREATE POLICY "Public Access Transactions"    ON transactions     FOR ALL USING (true);
CREATE POLICY "Public Access Items"           ON transaction_items FOR ALL USING (true);
CREATE POLICY "Public Access Budgets"         ON budgets          FOR ALL USING (true);


-- =============================================
-- SECTION 5A: LOAN ACCOUNTING FUNCTIONS/TRIGGERS
-- Source: migrations/008_loan_payment_accounting.sql through
-- migrations/012_irregular_loan_payment_accounting.sql
-- =============================================

CREATE OR REPLACE FUNCTION public.refresh_loan_summary(p_loan_id BIGINT)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_loan public.loans%ROWTYPE;
  v_installments_covered BIGINT := 0;
  v_early_payoff_count BIGINT := 0;
  v_paid_principal NUMERIC := 0;
  v_balance_adjustment NUMERIC := 0;
  v_cash_total NUMERIC := 0;
  v_balance NUMERIC := 0;
  v_remaining INTEGER := 0;
  v_closed_date DATE;
BEGIN
  IF p_loan_id IS NULL THEN RETURN; END IF;

  SELECT * INTO v_loan
  FROM public.loans
  WHERE id = p_loan_id
  FOR UPDATE;
  IF NOT FOUND THEN RETURN; END IF;

  IF v_loan.calculation_mode = 'loan_payments' THEN
    SELECT
      coalesce(sum(installments_covered) FILTER (
        WHERE payment_kind IN ('installment', 'catch_up')
      ), 0),
      count(*) FILTER (WHERE payment_kind = 'early_payoff'),
      coalesce(sum(principal_amount), 0),
      coalesce(sum(balance_adjustment_amount), 0)
    INTO v_installments_covered, v_early_payoff_count,
      v_paid_principal, v_balance_adjustment
    FROM public.loan_payments
    WHERE loan_id = p_loan_id;

    IF v_installments_covered > coalesce(v_loan.total_installments, 0) THEN
      RAISE EXCEPTION 'Loan % payment coverage exceeds total installments', p_loan_id;
    END IF;

    v_balance := round(greatest(
      v_loan.original_amount - v_paid_principal - v_balance_adjustment,
      0
    ), 2);

    IF v_early_payoff_count > 0 AND v_balance > 0.005 THEN
      RAISE EXCEPTION 'Loan % early payoff does not clear its outstanding principal',
        p_loan_id;
    END IF;

    IF v_balance <= 0.005 THEN
      SELECT payment_date INTO v_closed_date
      FROM public.loan_payments
      WHERE loan_id = p_loan_id
      ORDER BY
        CASE WHEN payment_kind = 'early_payoff' THEN 0 ELSE 1 END,
        payment_date DESC,
        id DESC
      LIMIT 1;
      v_remaining := 0;
    ELSE
      v_closed_date := NULL;
      v_remaining := greatest(
        coalesce(v_loan.total_installments, 0) - v_installments_covered,
        0
      )::integer;
    END IF;

    UPDATE public.loans
    SET
      current_balance = CASE WHEN v_balance <= 0.005 THEN 0 ELSE v_balance END,
      remaining_installments = v_remaining,
      next_payment_date = CASE
        WHEN v_balance <= 0.005 THEN NULL
        ELSE next_payment_date
      END,
      auto_payment_enabled = CASE
        WHEN v_balance <= 0.005 THEN false
        ELSE auto_payment_enabled
      END,
      closed_date = v_closed_date,
      status = CASE
        WHEN v_balance <= 0.005 THEN 'paid'
        WHEN v_loan.status = 'defaulted' THEN 'defaulted'
        ELSE 'active'
      END
    WHERE id = p_loan_id;
  ELSE
    SELECT count(*), coalesce(sum(total_amount), 0)
    INTO v_installments_covered, v_cash_total
    FROM public.transactions
    WHERE loan_id = p_loan_id;

    UPDATE public.loans
    SET
      current_balance = v_loan.original_amount - v_cash_total,
      remaining_installments = coalesce(v_loan.total_installments, 0) - v_installments_covered
    WHERE id = p_loan_id;
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.recalculate_loan_status()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    PERFORM public.refresh_loan_summary(NEW.loan_id);
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    PERFORM public.refresh_loan_summary(OLD.loan_id);
    RETURN OLD;
  END IF;
  IF OLD.loan_id IS DISTINCT FROM NEW.loan_id THEN
    PERFORM public.refresh_loan_summary(OLD.loan_id);
  END IF;
  PERFORM public.refresh_loan_summary(NEW.loan_id);
  RETURN NEW;
END;
$$;

CREATE TRIGGER on_transaction_change
AFTER INSERT OR UPDATE OR DELETE ON transactions
FOR EACH ROW
EXECUTE FUNCTION public.recalculate_loan_status();

CREATE OR REPLACE FUNCTION public.refresh_loan_summary_from_payment()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    PERFORM public.refresh_loan_summary(NEW.loan_id);
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    PERFORM public.refresh_loan_summary(OLD.loan_id);
    RETURN OLD;
  END IF;
  IF OLD.loan_id IS DISTINCT FROM NEW.loan_id THEN
    PERFORM public.refresh_loan_summary(OLD.loan_id);
  END IF;
  PERFORM public.refresh_loan_summary(NEW.loan_id);
  RETURN NEW;
END;
$$;

CREATE TRIGGER on_loan_payment_change
AFTER INSERT OR UPDATE OR DELETE ON loan_payments
FOR EACH ROW
EXECUTE FUNCTION public.refresh_loan_summary_from_payment();

CREATE OR REPLACE FUNCTION public.sync_loan_payment_from_transaction(
  p_transaction_id BIGINT,
  p_record_loan_payment BOOLEAN DEFAULT true
)
RETURNS public.loan_payments
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_transaction public.transactions%ROWTYPE;
  v_loan public.loans%ROWTYPE;
  v_existing public.loan_payments%ROWTYPE;
  v_result public.loan_payments%ROWTYPE;
  v_installment_number INTEGER;
  v_installments_covered BIGINT := 0;
  v_opening_principal NUMERIC;
  v_payment NUMERIC;
  v_interest NUMERIC;
  v_principal NUMERIC;
BEGIN
  SELECT * INTO v_transaction FROM public.transactions
  WHERE id = p_transaction_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Transaction % does not exist', p_transaction_id;
  END IF;

  SELECT * INTO v_existing FROM public.loan_payments
  WHERE transaction_id = p_transaction_id FOR UPDATE;
  IF v_existing.id IS NOT NULL AND v_existing.source_kind <> 'existing_transaction' THEN
    RAISE EXCEPTION
      'Transaction % is linked to a % loan payment and cannot be synchronized automatically',
      p_transaction_id, v_existing.source_kind;
  END IF;

  IF NOT p_record_loan_payment OR v_transaction.loan_id IS NULL THEN
    IF v_existing.id IS NOT NULL THEN
      DELETE FROM public.loan_payments WHERE id = v_existing.id RETURNING * INTO v_result;
    END IF;
    RETURN v_result;
  END IF;

  SELECT * INTO v_loan FROM public.loans
  WHERE id = v_transaction.loan_id FOR UPDATE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Loan % does not exist', v_transaction.loan_id;
  END IF;

  IF v_loan.calculation_mode <> 'loan_payments' THEN
    IF v_existing.id IS NOT NULL THEN
      DELETE FROM public.loan_payments WHERE id = v_existing.id RETURNING * INTO v_result;
    END IF;
    RETURN v_result;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.loan_payments
    WHERE loan_id = v_loan.id
      AND payment_kind = 'early_payoff'
      AND id IS DISTINCT FROM v_existing.id
  ) THEN
    RAISE EXCEPTION 'Loan % has an early payoff and cannot accept another regular installment',
      v_loan.id;
  END IF;

  SELECT coalesce(sum(installments_covered), 0)
  INTO v_installments_covered
  FROM public.loan_payments
  WHERE loan_id = v_loan.id
    AND payment_kind IN ('installment', 'catch_up')
    AND id IS DISTINCT FROM v_existing.id;

  IF v_transaction.installment_number IS NOT NULL
    AND v_transaction.installment_number > 0 THEN
    v_installment_number := v_transaction.installment_number;
  ELSIF v_existing.id IS NOT NULL AND v_existing.loan_id = v_loan.id THEN
    v_installment_number := v_existing.installment_number;
  ELSE
    v_installment_number := v_installments_covered + 1;
  END IF;

  IF v_loan.total_installments IS NOT NULL
    AND v_installment_number > v_loan.total_installments THEN
    RAISE EXCEPTION 'Installment % exceeds total installments % for loan %',
      v_installment_number, v_loan.total_installments, v_loan.id;
  END IF;

  IF EXISTS (SELECT 1 FROM public.loan_payments later
    WHERE later.loan_id = v_loan.id
      AND later.payment_kind = 'installment'
      AND later.installment_number > v_installment_number
      AND later.id IS DISTINCT FROM v_existing.id) THEN
    RAISE EXCEPTION
      'Cannot insert or reprice installment % while later loan payments exist',
      v_installment_number;
  END IF;

  SELECT greatest(
    v_loan.original_amount
      - coalesce(sum(principal_amount), 0)
      - coalesce(sum(balance_adjustment_amount), 0),
    0
  )
  INTO v_opening_principal FROM public.loan_payments
  WHERE loan_id = v_loan.id
    AND id IS DISTINCT FROM v_existing.id
    AND (
      (payment_kind = 'installment' AND installment_number < v_installment_number)
      OR (payment_kind IN ('catch_up', 'balance_adjustment')
        AND payment_date <= v_transaction.charge_date)
    );

  v_payment := round(abs(v_transaction.total_amount), 2);
  IF v_loan.interest_type = 'fixed' THEN
    v_interest := round(v_opening_principal * coalesce(v_loan.interest_rate, 0) / 1200, 2);
  ELSE
    v_interest := round(v_opening_principal * coalesce(v_loan.interest_rate, 0) / 1200, 10);
  END IF;
  v_principal := round(v_payment - v_interest, 10);
  IF v_principal < 0 THEN
    RAISE EXCEPTION 'Loan payment % is less than calculated interest % for transaction %',
      v_payment, v_interest, p_transaction_id;
  END IF;
  IF v_principal > v_opening_principal THEN
    v_principal := round(v_opening_principal, 10);
    v_interest := round(v_payment - v_principal, 10);
  END IF;

  INSERT INTO public.loan_payments (
    loan_id, transaction_id, installment_number, payment_date,
    payment_amount, principal_amount, interest_amount,
    annual_interest_rate, source_kind, notes,
    payment_kind, installments_covered, other_amount, balance_adjustment_amount
  ) VALUES (
    v_loan.id, v_transaction.id, v_installment_number,
    v_transaction.charge_date, v_payment, v_principal, v_interest,
    v_loan.interest_rate, 'existing_transaction',
    'Generated from an actual loan-linked ledger transaction',
    'installment', 1, 0, 0
  )
  ON CONFLICT (transaction_id) DO UPDATE SET
    loan_id = EXCLUDED.loan_id,
    installment_number = EXCLUDED.installment_number,
    payment_date = EXCLUDED.payment_date,
    payment_amount = EXCLUDED.payment_amount,
    principal_amount = EXCLUDED.principal_amount,
    interest_amount = EXCLUDED.interest_amount,
    annual_interest_rate = EXCLUDED.annual_interest_rate,
    source_kind = EXCLUDED.source_kind,
    payment_kind = 'installment',
    installments_covered = 1,
    other_amount = 0,
    balance_adjustment_amount = 0,
    updated_at = timezone('utc'::text, now())
  RETURNING * INTO v_result;

  UPDATE public.transactions SET
    installment_number = v_installment_number,
    installment_count = v_loan.total_installments,
    installments_info = CASE
      WHEN v_loan.total_installments IS NULL THEN v_installment_number::text
      ELSE v_installment_number::text || '/' || v_loan.total_installments::text
    END
  WHERE id = p_transaction_id;
  RETURN v_result;
END;
$$;

CREATE OR REPLACE FUNCTION public.create_transaction_with_loan_payment(
  p_transaction JSONB, p_record_loan_payment BOOLEAN DEFAULT true
)
RETURNS BIGINT LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE v_transaction_id BIGINT;
BEGIN
  IF p_transaction IS NULL THEN RAISE EXCEPTION 'Transaction payload is required'; END IF;
  INSERT INTO public.transactions (
    description, movement_type, category_id, total_amount, global_discount,
    global_discount_source, payment_source_id, transaction_date, charge_date,
    tags, loan_id, original_amount, currency, exchange_rate, installments_info,
    installment_number, installment_count, parent_transaction_id, notes
  ) VALUES (
    p_transaction->>'description', p_transaction->>'movement_type',
    nullif(p_transaction->>'category_id', '')::BIGINT,
    (p_transaction->>'total_amount')::NUMERIC,
    coalesce(nullif(p_transaction->>'global_discount', '')::NUMERIC, 0),
    nullif(p_transaction->>'global_discount_source', ''),
    nullif(p_transaction->>'payment_source_id', '')::BIGINT,
    (p_transaction->>'transaction_date')::DATE,
    coalesce(nullif(p_transaction->>'charge_date', '')::DATE,
      (p_transaction->>'transaction_date')::DATE),
    p_transaction->>'tags', nullif(p_transaction->>'loan_id', '')::BIGINT,
    nullif(p_transaction->>'original_amount', '')::NUMERIC,
    coalesce(nullif(p_transaction->>'currency', ''), 'ILS'),
    nullif(p_transaction->>'exchange_rate', '')::NUMERIC,
    nullif(p_transaction->>'installments_info', ''),
    nullif(p_transaction->>'installment_number', '')::INTEGER,
    nullif(p_transaction->>'installment_count', '')::INTEGER,
    nullif(p_transaction->>'parent_transaction_id', '')::BIGINT,
    p_transaction->>'notes'
  ) RETURNING id INTO v_transaction_id;
  IF nullif(p_transaction->>'loan_id', '') IS NOT NULL THEN
    PERFORM public.sync_loan_payment_from_transaction(v_transaction_id, p_record_loan_payment);
  END IF;
  RETURN v_transaction_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.update_transaction_with_loan_payment(
  p_transaction_id BIGINT, p_transaction JSONB,
  p_record_loan_payment BOOLEAN DEFAULT NULL
)
RETURNS BIGINT LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_old_transaction public.transactions%ROWTYPE;
  v_existing public.loan_payments%ROWTYPE;
  v_new_loan_id BIGINT;
  v_new_amount NUMERIC;
  v_requested_installment INTEGER;
  v_should_record_payment BOOLEAN;
  v_accounting_change BOOLEAN;
BEGIN
  SELECT * INTO v_old_transaction FROM public.transactions
  WHERE id = p_transaction_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Transaction % does not exist', p_transaction_id; END IF;
  SELECT * INTO v_existing FROM public.loan_payments
  WHERE transaction_id = p_transaction_id FOR UPDATE;

  v_new_loan_id := nullif(p_transaction->>'loan_id', '')::BIGINT;
  v_new_amount := (p_transaction->>'total_amount')::NUMERIC;
  v_requested_installment := CASE
    WHEN p_transaction ? 'installment_number'
      THEN nullif(p_transaction->>'installment_number', '')::INTEGER
    ELSE v_old_transaction.installment_number
  END;
  v_should_record_payment := coalesce(
    p_record_loan_payment,
    CASE
      WHEN v_existing.id IS NOT NULL THEN true
      WHEN v_old_transaction.loan_id = v_new_loan_id
        AND v_requested_installment IS NULL THEN false
      ELSE true
    END
  );
  PERFORM 1 FROM public.loans
  WHERE id IN (v_old_transaction.loan_id, v_new_loan_id)
  ORDER BY id FOR UPDATE;
  IF v_new_loan_id IS NOT NULL
    AND NOT EXISTS (SELECT 1 FROM public.loans WHERE id = v_new_loan_id) THEN
    RAISE EXCEPTION 'Loan % does not exist', v_new_loan_id;
  END IF;

  IF v_existing.id IS NOT NULL THEN
    v_accounting_change := v_old_transaction.loan_id IS DISTINCT FROM v_new_loan_id
      OR round(abs(v_old_transaction.total_amount), 2)
        IS DISTINCT FROM round(abs(v_new_amount), 2)
      OR (v_requested_installment IS NOT NULL
        AND v_requested_installment IS DISTINCT FROM v_existing.installment_number)
      OR NOT v_should_record_payment;
    IF v_existing.source_kind <> 'existing_transaction' AND v_accounting_change THEN
      RAISE EXCEPTION
        'Reconstructed/manual loan payment % cannot be repriced through transaction update',
        v_existing.id;
    END IF;
    IF v_existing.source_kind = 'existing_transaction' AND v_accounting_change
      AND EXISTS (SELECT 1 FROM public.loan_payments later
        WHERE later.loan_id = v_existing.loan_id
          AND later.installment_number > v_existing.installment_number) THEN
      RAISE EXCEPTION
        'Cannot change installment % while later loan payments exist; reconcile the schedule first',
        v_existing.installment_number;
    END IF;
  END IF;

  UPDATE public.transactions SET
    description = p_transaction->>'description',
    movement_type = p_transaction->>'movement_type',
    category_id = nullif(p_transaction->>'category_id', '')::BIGINT,
    total_amount = v_new_amount,
    global_discount = coalesce(nullif(p_transaction->>'global_discount', '')::NUMERIC, 0),
    global_discount_source = nullif(p_transaction->>'global_discount_source', ''),
    payment_source_id = nullif(p_transaction->>'payment_source_id', '')::BIGINT,
    transaction_date = (p_transaction->>'transaction_date')::DATE,
    charge_date = coalesce(nullif(p_transaction->>'charge_date', '')::DATE,
      (p_transaction->>'transaction_date')::DATE),
    tags = p_transaction->>'tags', loan_id = v_new_loan_id,
    original_amount = nullif(p_transaction->>'original_amount', '')::NUMERIC,
    currency = coalesce(nullif(p_transaction->>'currency', ''), 'ILS'),
    exchange_rate = nullif(p_transaction->>'exchange_rate', '')::NUMERIC,
    installments_info = nullif(p_transaction->>'installments_info', ''),
    installment_number = v_requested_installment,
    installment_count = CASE
      WHEN p_transaction ? 'installment_count'
        THEN nullif(p_transaction->>'installment_count', '')::INTEGER
      ELSE installment_count
    END,
    notes = p_transaction->>'notes', updated_at = timezone('utc'::text, now())
  WHERE id = p_transaction_id;

  IF v_existing.id IS NOT NULL AND v_existing.source_kind <> 'existing_transaction' THEN
    RETURN p_transaction_id;
  END IF;
  IF v_existing.id IS NOT NULL AND NOT v_accounting_change THEN
    UPDATE public.loan_payments SET
      payment_date = coalesce(nullif(p_transaction->>'charge_date', '')::DATE,
        (p_transaction->>'transaction_date')::DATE),
      updated_at = timezone('utc'::text, now())
    WHERE id = v_existing.id;
    RETURN p_transaction_id;
  END IF;
  PERFORM public.sync_loan_payment_from_transaction(p_transaction_id, v_should_record_payment);
  RETURN p_transaction_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.delete_transaction_with_loan_payment(p_transaction_id BIGINT)
RETURNS BIGINT LANGUAGE plpgsql SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_transaction public.transactions%ROWTYPE;
  v_existing public.loan_payments%ROWTYPE;
BEGIN
  SELECT * INTO v_transaction FROM public.transactions
  WHERE id = p_transaction_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Transaction % does not exist', p_transaction_id; END IF;
  SELECT * INTO v_existing FROM public.loan_payments
  WHERE transaction_id = p_transaction_id FOR UPDATE;
  IF v_existing.id IS NOT NULL AND v_existing.source_kind = 'existing_transaction' THEN
    IF EXISTS (SELECT 1 FROM public.loan_payments later
      WHERE later.loan_id = v_existing.loan_id
        AND later.installment_number > v_existing.installment_number) THEN
      RAISE EXCEPTION
        'Cannot delete installment % while later loan payments exist; reconcile the schedule first',
        v_existing.installment_number;
    END IF;
    DELETE FROM public.loan_payments WHERE id = v_existing.id;
  END IF;
  DELETE FROM public.lego_sets WHERE transaction_id = p_transaction_id;
  DELETE FROM public.transaction_items WHERE transaction_id = p_transaction_id;
  DELETE FROM public.transactions WHERE id = p_transaction_id;
  RETURN p_transaction_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.create_due_loan_payment(
  p_loan_id BIGINT,
  p_expected_due_date DATE,
  p_expected_installment_number INTEGER,
  p_payment_amount NUMERIC,
  p_principal_amount NUMERIC,
  p_interest_amount NUMERIC,
  p_annual_interest_rate NUMERIC,
  p_category_id BIGINT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_loan public.loans%ROWTYPE;
  v_existing public.loan_payments%ROWTYPE;
  v_transaction_id BIGINT;
  v_payment_id BIGINT;
  v_covered_count BIGINT := 0;
  v_precise_balance NUMERIC(24, 10) := 0;
  v_refreshed_balance NUMERIC := 0;
  v_refreshed_remaining INTEGER := 0;
  v_next_payment_date DATE;
  v_today DATE := (clock_timestamp() AT TIME ZONE 'Asia/Jerusalem')::date;
BEGIN
  SELECT * INTO v_loan FROM public.loans
  WHERE id = p_loan_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Loan % does not exist', p_loan_id; END IF;
  IF v_loan.calculation_mode <> 'loan_payments' THEN
    RAISE EXCEPTION 'Loan % is not in loan_payments mode', p_loan_id;
  END IF;
  SELECT * INTO v_existing FROM public.loan_payments
  WHERE loan_id = p_loan_id
    AND payment_kind = 'installment'
    AND installment_number = p_expected_installment_number
  FOR UPDATE;
  IF FOUND THEN
    SELECT coalesce(sum(installments_covered), 0)
    INTO v_covered_count
    FROM public.loan_payments
    WHERE loan_id = p_loan_id
      AND payment_kind IN ('installment', 'catch_up');
    IF v_existing.installment_number <> v_covered_count THEN
      RAISE EXCEPTION 'Loan % existing installment is not the latest accounting row', p_loan_id;
    END IF;
    IF p_expected_due_date > v_today THEN
      RAISE EXCEPTION 'Loan % is not due on Jerusalem business date %', p_loan_id, v_today;
    END IF;
    IF v_loan.next_payment_date IS DISTINCT FROM p_expected_due_date
      AND v_loan.next_payment_date IS DISTINCT FROM
        (p_expected_due_date + INTERVAL '1 month')::date
      AND v_loan.next_payment_date IS NOT NULL THEN
      RAISE EXCEPTION 'Loan % due date no longer matches the processed installment', p_loan_id;
    END IF;
    IF v_loan.next_payment_date = p_expected_due_date THEN
      IF NOT v_loan.auto_payment_enabled OR v_loan.status <> 'active' THEN
        RAISE EXCEPTION 'Loan % is not eligible for automatic payment', p_loan_id;
      END IF;
      UPDATE public.loans SET next_payment_date = CASE
        WHEN current_balance <= 0.005 OR remaining_installments <= 0 THEN NULL
        ELSE (p_expected_due_date + INTERVAL '1 month')::date
      END WHERE id = p_loan_id RETURNING next_payment_date INTO v_next_payment_date;
    ELSE
      v_next_payment_date := v_loan.next_payment_date;
    END IF;
    RETURN jsonb_build_object(
      'status', 'already_processed', 'loan_id', p_loan_id,
      'transaction_id', v_existing.transaction_id,
      'loan_payment_id', v_existing.id,
      'installment_number', v_existing.installment_number,
      'next_payment_date', v_next_payment_date
    );
  END IF;

  IF NOT v_loan.auto_payment_enabled THEN
    RAISE EXCEPTION 'Automatic payment is disabled for loan %', p_loan_id;
  END IF;
  IF v_loan.status <> 'active' THEN
    RAISE EXCEPTION 'Loan % is not active', p_loan_id;
  END IF;

  IF v_loan.remaining_installments IS NULL OR v_loan.remaining_installments <= 0 THEN
    RAISE EXCEPTION 'Loan % has no remaining installments', p_loan_id;
  END IF;
  IF v_loan.next_payment_date IS NULL OR v_loan.next_payment_date <> p_expected_due_date THEN
    RAISE EXCEPTION 'Loan % due date changed from expected %', p_loan_id, p_expected_due_date;
  END IF;
  IF p_expected_due_date > v_today THEN
    RAISE EXCEPTION 'Loan % is not due on Jerusalem business date %', p_loan_id, v_today;
  END IF;
  IF v_loan.payment_source_id IS NULL THEN
    RAISE EXCEPTION 'Loan % has no payment source', p_loan_id;
  END IF;
  IF v_loan.total_installments IS NULL OR v_loan.total_installments <= 0 THEN
    RAISE EXCEPTION 'Loan % has invalid total installments', p_loan_id;
  END IF;
  IF v_loan.monthly_payment IS NULL OR v_loan.monthly_payment <= 0 THEN
    RAISE EXCEPTION 'Loan % has invalid monthly payment', p_loan_id;
  END IF;
  IF v_loan.interest_rate IS NULL OR v_loan.interest_rate < 0 THEN
    RAISE EXCEPTION 'Loan % has invalid interest rate', p_loan_id;
  END IF;
  IF p_annual_interest_rate IS NULL
    OR abs(p_annual_interest_rate - v_loan.interest_rate) > 0.000001 THEN
    RAISE EXCEPTION 'Loan % interest rate changed during processing', p_loan_id;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM public.categories
    WHERE id = p_category_id AND type = 'expense' AND is_active = true) THEN
    RAISE EXCEPTION 'Loan payment category % is not an active expense category', p_category_id;
  END IF;

  SELECT
    coalesce(sum(installments_covered) FILTER (
      WHERE payment_kind IN ('installment', 'catch_up')
    ), 0),
    round(greatest(
      v_loan.original_amount
        - coalesce(sum(principal_amount), 0)
        - coalesce(sum(balance_adjustment_amount), 0),
      0
    ), 10)
  INTO v_covered_count, v_precise_balance
  FROM public.loan_payments WHERE loan_id = p_loan_id;
  IF v_covered_count > v_loan.total_installments THEN
    RAISE EXCEPTION 'Loan % payment coverage exceeds total installments', p_loan_id;
  END IF;
  IF v_loan.remaining_installments <> v_loan.total_installments - v_covered_count THEN
    RAISE EXCEPTION 'Loan % remaining-installment summary has drifted', p_loan_id;
  END IF;
  IF p_expected_installment_number <> v_covered_count + 1
    OR p_expected_installment_number > v_loan.total_installments THEN
    RAISE EXCEPTION 'Loan % expected installment % but received %',
      p_loan_id, v_covered_count + 1, p_expected_installment_number;
  END IF;
  IF p_payment_amount IS NULL OR round(p_payment_amount, 2) <= 0
    OR p_payment_amount <> round(p_payment_amount, 2)
    OR p_principal_amount IS NULL OR p_principal_amount < 0
    OR p_interest_amount IS NULL OR p_interest_amount < 0
    OR abs(p_payment_amount - p_principal_amount - p_interest_amount) > 0.00000001 THEN
    RAISE EXCEPTION 'Loan % payment components do not reconcile', p_loan_id;
  END IF;
  IF p_principal_amount > v_precise_balance + 0.00000001 THEN
    RAISE EXCEPTION 'Loan % principal component exceeds outstanding principal', p_loan_id;
  END IF;
  IF p_expected_installment_number < v_loan.total_installments
    AND abs(p_payment_amount - round(v_loan.monthly_payment, 2)) > 0.00000001 THEN
    RAISE EXCEPTION 'Loan % payment amount changed from configured monthly payment', p_loan_id;
  END IF;
  IF p_expected_installment_number = v_loan.total_installments
    AND abs(p_principal_amount - v_precise_balance) > 0.00000001 THEN
    RAISE EXCEPTION 'Loan % final installment does not clear principal', p_loan_id;
  END IF;

  INSERT INTO public.transactions (
    transaction_date, charge_date, description, movement_type, total_amount,
    category_id, payment_source_id, loan_id, original_amount, currency,
    installments_info, installment_number, installment_count, notes
  ) VALUES (
    p_expected_due_date, p_expected_due_date,
    'תשלום הלוואה אוטומטי - ' || v_loan.name, 'expense', p_payment_amount,
    p_category_id, v_loan.payment_source_id, v_loan.id, v_loan.original_amount, 'ILS',
    p_expected_installment_number::text || '/' || v_loan.total_installments::text,
    p_expected_installment_number, v_loan.total_installments,
    'Generated automatically when the loan installment became due'
  ) RETURNING id INTO v_transaction_id;

  INSERT INTO public.loan_payments (
    loan_id, transaction_id, installment_number, payment_date, payment_amount,
    principal_amount, interest_amount, annual_interest_rate, source_kind, notes,
    payment_kind, installments_covered, other_amount, balance_adjustment_amount
  ) VALUES (
    v_loan.id, v_transaction_id, p_expected_installment_number,
    p_expected_due_date, p_payment_amount, p_principal_amount, p_interest_amount,
    p_annual_interest_rate, 'generated',
    'Generated automatically from loans.next_payment_date',
    'installment', 1, 0, 0
  ) RETURNING id INTO v_payment_id;

  SELECT current_balance, remaining_installments
  INTO v_refreshed_balance, v_refreshed_remaining
  FROM public.loans WHERE id = p_loan_id;
  v_next_payment_date := CASE
    WHEN v_refreshed_balance <= 0.005 OR v_refreshed_remaining <= 0 THEN NULL
    ELSE (p_expected_due_date + INTERVAL '1 month')::date
  END;
  UPDATE public.loans SET next_payment_date = v_next_payment_date WHERE id = p_loan_id;
  RETURN jsonb_build_object(
    'status', 'processed', 'loan_id', p_loan_id,
    'transaction_id', v_transaction_id, 'loan_payment_id', v_payment_id,
    'installment_number', p_expected_installment_number,
    'next_payment_date', v_next_payment_date
  );
END;
$$;

-- Normalize Supabase default function grants. Internal helpers remain callable
-- only by their owner (including through triggers/SECURITY DEFINER RPCs); only
-- the bounded application entry points are exposed to service_role.
REVOKE ALL ON FUNCTION public.refresh_loan_summary(BIGINT)
  FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.recalculate_loan_status()
  FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.refresh_loan_summary_from_payment()
  FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.sync_loan_payment_from_transaction(BIGINT, BOOLEAN)
  FROM PUBLIC, anon, authenticated, service_role;

REVOKE ALL ON FUNCTION public.create_transaction_with_loan_payment(JSONB, BOOLEAN)
  FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.update_transaction_with_loan_payment(BIGINT, JSONB, BOOLEAN)
  FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.delete_transaction_with_loan_payment(BIGINT)
  FROM PUBLIC, anon, authenticated, service_role;
REVOKE ALL ON FUNCTION public.create_due_loan_payment(
  BIGINT, DATE, INTEGER, NUMERIC, NUMERIC, NUMERIC, NUMERIC, BIGINT
) FROM PUBLIC, anon, authenticated, service_role;

GRANT EXECUTE ON FUNCTION public.create_transaction_with_loan_payment(JSONB, BOOLEAN) TO service_role;
GRANT EXECUTE ON FUNCTION public.update_transaction_with_loan_payment(BIGINT, JSONB, BOOLEAN) TO service_role;
GRANT EXECUTE ON FUNCTION public.delete_transaction_with_loan_payment(BIGINT) TO service_role;
GRANT EXECUTE ON FUNCTION public.create_due_loan_payment(
  BIGINT, DATE, INTEGER, NUMERIC, NUMERIC, NUMERIC, NUMERIC, BIGINT
) TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.loan_payments TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.loan_payments_id_seq TO service_role;


-- =============================================
-- SECTION 6: TASK JOURNAL
-- Added: 2026-05-01
-- =============================================

CREATE TABLE IF NOT EXISTS tasks (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title          TEXT NOT NULL,
  notes          TEXT,
  status         TEXT NOT NULL DEFAULT 'open'
                 CHECK (status IN ('open', 'in_progress', 'waiting', 'done', 'cancelled')),
  priority       TEXT NOT NULL DEFAULT 'medium'
                 CHECK (priority IN ('low', 'medium', 'high', 'urgent')),
  category       TEXT NOT NULL DEFAULT 'personal'
                 CHECK (category IN ('finance', 'personal', 'work', 'system', 'other')),
  due_date       DATE,
  completed_at   TIMESTAMP WITH TIME ZONE,
  source         TEXT NOT NULL DEFAULT 'manual'
                 CHECK (source IN ('manual', 'system', 'ai')),
  transaction_id INTEGER REFERENCES transactions(id) ON DELETE SET NULL,
  loan_id        BIGINT  REFERENCES loans(id)         ON DELETE SET NULL,
  created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE INDEX idx_tasks_status   ON tasks (status);
CREATE INDEX idx_tasks_due_date ON tasks (due_date);
CREATE INDEX idx_tasks_priority ON tasks (priority);
CREATE INDEX idx_tasks_category ON tasks (category);



-- =============================================
-- SECTION 7: READ-ONLY FUNCTIONS (RPC)
-- Source: migrations/003_transaction_pagination_and_aggregates.sql
--
-- These are the authoritative definitions for transaction filtering, sorting
-- and financial aggregation. All are read-only (STABLE, or IMMUTABLE for the
-- pure string helper) and all are SECURITY INVOKER. None writes data.
--
-- The bodies below are kept byte-identical to the migration. If you change one,
-- change both — this file must stay a standalone reproducible schema.
--
-- Pre-existing, defined outside this file:
--   get_unique_tags()  -> distinct tag list for autocomplete.
-- =============================================

-- 7.1 SEARCH PATTERN (single owner of the escaping rule)
-- =============================================

-- Turns raw user search text into an ILIKE pattern, escaping the LIKE wildcards
-- so a user searching for "50%" or "a_b" gets a literal match instead of a
-- pattern. Backslash is escaped first, or it would double-escape the escapes
-- added afterwards.
--
-- This exists as its own IMMUTABLE function rather than as a CTE inside
-- transactions_filtered() for two reasons:
--   * one owner for the escaping rule, referenced from every predicate;
--   * a CTE in the body would make transactions_filtered() ineligible for
--     planner inlining, which is what lets the index be used at all.
-- Being IMMUTABLE with a constant argument, it is folded once at plan time —
-- it is not evaluated per row.
CREATE OR REPLACE FUNCTION public.transactions_search_pattern(p_search text)
RETURNS text
LANGUAGE sql
IMMUTABLE
SECURITY INVOKER
AS $$
  SELECT CASE
           WHEN p_search IS NULL OR pg_catalog.btrim(p_search) = '' THEN NULL
           ELSE '%' || pg_catalog.replace(
                         pg_catalog.replace(
                           pg_catalog.replace(pg_catalog.btrim(p_search),
                             '\', '\\'),
                           '%', '\%'),
                         '_', '\_') || '%'
         END;
$$;


-- =============================================
-- 7.2 FILTERED TRANSACTION SET
-- =============================================

-- THE single owner of transaction filter semantics.
--
-- Both the page slice and the totals are derived from this one function, which
-- is what guarantees the summary bar can never disagree with the rows the user
-- is looking at. It is not a view because it is parameterised.
--
-- row_json is byte-compatible with the previous PostgREST response shape: the
-- full transactions row plus embedded `categories` and `payment_sources`
-- objects, so existing consumers need no field remapping.
--
-- Inlining contract (deliberate, do not "tidy" this away):
--   This function has NO `SET search_path`, because a SET clause makes a SQL
--   function ineligible for planner inlining — and without inlining the sort
--   and LIMIT could not use an index. To stay safe without a pinned search
--   path, every object referenced below is schema-qualified. It remains
--   SECURITY INVOKER, so it grants no privilege of its own.
CREATE OR REPLACE FUNCTION public.transactions_filtered(
  p_from                date    DEFAULT NULL,
  p_to                  date    DEFAULT NULL,
  p_category_id         bigint  DEFAULT NULL,
  p_payment_source_id   bigint  DEFAULT NULL,
  p_uncategorized_only  boolean DEFAULT false,
  p_search              text    DEFAULT NULL
)
RETURNS TABLE (
  id                integer,
  transaction_date  date,
  description       text,
  movement_type     text,
  total_amount      numeric,
  row_json          jsonb
)
LANGUAGE sql
STABLE
SECURITY INVOKER
AS $$
  SELECT
    t.id,
    t.transaction_date,
    t.description::text,
    t.movement_type::text,
    t.total_amount,
    pg_catalog.to_jsonb(t) || pg_catalog.jsonb_build_object(
      'categories',
      CASE WHEN c.id IS NULL THEN NULL
           ELSE pg_catalog.jsonb_build_object('name', c.name, 'icon', c.icon) END,
      'payment_sources',
      CASE WHEN ps.id IS NULL THEN NULL
           ELSE pg_catalog.jsonb_build_object(
             'id',     ps.id,
             'name',   ps.name,
             'method', ps.method,
             'slug',   ps.slug,
             'issuer', ps.issuer,
             'last4',  ps.last4
           ) END
    )
  FROM public.transactions t
  -- LEFT JOIN is required: transactions with no category or no payment source
  -- must still appear (the "uncategorized only" filter depends on it).
  LEFT JOIN public.categories      c  ON c.id  = t.category_id
  LEFT JOIN public.payment_sources ps ON ps.id = t.payment_source_id
  WHERE (p_from IS NULL OR t.transaction_date >= p_from)
    AND (p_to   IS NULL OR t.transaction_date <= p_to)
    AND (p_category_id IS NULL OR t.category_id = p_category_id)
    AND (p_payment_source_id IS NULL OR t.payment_source_id = p_payment_source_id)
    AND (NOT COALESCE(p_uncategorized_only, false) OR t.category_id IS NULL)
    AND (
      public.transactions_search_pattern(p_search) IS NULL
      -- Mirrors the previous client-side search exactly: description,
      -- amount-as-text, category name, payment source name. Notes are NOT
      -- searched, because the old implementation did not search them.
      OR t.description        ILIKE public.transactions_search_pattern(p_search) ESCAPE '\'
      OR t.total_amount::text ILIKE public.transactions_search_pattern(p_search) ESCAPE '\'
      OR c.name               ILIKE public.transactions_search_pattern(p_search) ESCAPE '\'
      OR ps.name              ILIKE public.transactions_search_pattern(p_search) ESCAPE '\'
    );
$$;


-- =============================================
-- 7.3 PAGINATED + SORTED TRANSACTION LIST
-- =============================================

-- Returns one jsonb object:
--   {
--     "data":     [ <transaction row>, ... ],   -- at most p_limit rows
--     "has_more": true | false,
--     "next_key": { ...keyset position... } | null,
--     "totals":   { "count": n, "income": n, "expense": n } | null
--   }
--
-- SORTING
--   Six fully static branches, one per (sort field, direction). There is no
--   dynamic SQL anywhere: p_sort_by and p_sort_direction only *select* a
--   branch, they are never interpolated into a statement. An unrecognised
--   combination raises, rather than silently falling through to an arbitrary
--   order — defence in depth behind the allowlist in
--   server/utils/transactionQuery.js.
--
--   Every branch ends with `id DESC`, a unique column, so the ordering is
--   always total and deterministic and no row can straddle a page boundary.
--
--   Description ordering uses COLLATE "C". That makes it deterministic and
--   independent of the database's locale, and it preserves the expected order
--   for this application's Hebrew and English descriptions. It is byte /
--   code-point ordering, whereas the old browser-side comparator used UTF-16
--   code units; those agree across the BMP but may differ for supplementary
--   characters such as some emoji. No claim of exact equivalence is made.
--
--   COLLATION INVARIANT (do not weaken): the description branches must apply
--   COLLATE "C" to BOTH SIDES of every description comparison — the inequality
--   AND the equality that guards the transaction_date/id tiebreakers — and in
--   the ORDER BY of both the inner LIMIT query and the outer jsonb_agg calls.
--   A cursor predicate that compared under the database-default collation while
--   the rows were ordered under "C" would place the boundary somewhere the sort
--   never put it, skipping and repeating rows across the page edge. The
--   NULL-block transition uses IS NULL, which is collation-independent.
--
--   NULL descriptions: `(description IS NULL) ASC` is promoted to the leading
--   sort key, so rows with no description sort to the BOTTOM in BOTH
--   directions. This is a deliberate product decision. Postgres' own defaults
--   (NULLS LAST for ASC, NULLS FIRST for DESC) would move them to the top on a
--   descending sort and would make the cursor predicate direction-dependent in
--   a much more error-prone way.
--
-- PAGINATION
--   Keyset (cursor), never OFFSET. The probe row lives entirely inside this
--   function: it selects p_limit + 1 rows, returns at most p_limit, and reports
--   has_more separately. The probe row is structurally incapable of reaching
--   the response.
--
--   next_key is built here rather than in JavaScript on purpose. total_amount
--   is NUMERIC; if the caller read it back off a JSON row it would already have
--   been through a double. It is emitted as ::text so the cursor boundary is
--   exact, and transaction_date via to_char so it is DateStyle-independent.
--
-- TOTALS
--   Computed only when asked for, inside a real IF. The previous version used
--   `CASE WHEN p_include_totals THEN (SELECT ...) END`, which Postgres may hoist
--   into an InitPlan and evaluate regardless of the condition — meaning every
--   "load more" would have re-aggregated the entire filtered set.
CREATE OR REPLACE FUNCTION public.transactions_page(
  p_from                        date    DEFAULT NULL,
  p_to                          date    DEFAULT NULL,
  p_category_id                 bigint  DEFAULT NULL,
  p_payment_source_id           bigint  DEFAULT NULL,
  p_uncategorized_only          boolean DEFAULT false,
  p_search                      text    DEFAULT NULL,
  p_limit                       integer DEFAULT 100,
  p_sort_by                     text    DEFAULT 'transaction_date',
  p_sort_direction              text    DEFAULT 'desc',
  p_cursor_id                   bigint  DEFAULT NULL,
  p_cursor_date                 date    DEFAULT NULL,
  p_cursor_amount               numeric DEFAULT NULL,
  p_cursor_description          text    DEFAULT NULL,
  p_cursor_description_is_null  boolean DEFAULT NULL,
  p_include_totals              boolean DEFAULT false
)
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY INVOKER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_probe     integer;
  v_rows      jsonb;
  v_keys      jsonb;
  v_has_more  boolean := false;
  v_next_key  jsonb   := NULL;
  v_totals    jsonb   := NULL;
BEGIN
  IF p_limit IS NULL OR p_limit < 1 THEN
    RAISE EXCEPTION 'transactions_page: p_limit must be a positive integer, got %', p_limit;
  END IF;

  -- One row beyond the page, so has_more is derived from real data rather than
  -- guessed from a full page.
  v_probe := p_limit + 1;

  -- ---------------------------------------------------------------------
  -- transaction_date DESC, id DESC   (the default view)
  -- ---------------------------------------------------------------------
  IF p_sort_by = 'transaction_date' AND p_sort_direction = 'desc' THEN
    SELECT jsonb_agg(p.row_json ORDER BY p.transaction_date DESC, p.id DESC),
           jsonb_agg(p.k        ORDER BY p.transaction_date DESC, p.id DESC)
      INTO v_rows, v_keys
    FROM (
      SELECT f.transaction_date,
             f.id,
             f.row_json,
             jsonb_build_object(
               'td', to_char(f.transaction_date, 'YYYY-MM-DD'),
               'id', f.id
             ) AS k
      FROM public.transactions_filtered(
             p_from, p_to, p_category_id, p_payment_source_id,
             p_uncategorized_only, p_search) f
      WHERE p_cursor_id IS NULL
         OR f.transaction_date < p_cursor_date
         OR (f.transaction_date = p_cursor_date AND f.id < p_cursor_id)
      ORDER BY f.transaction_date DESC, f.id DESC
      LIMIT v_probe
    ) p;

  -- ---------------------------------------------------------------------
  -- transaction_date ASC, id DESC
  -- ---------------------------------------------------------------------
  ELSIF p_sort_by = 'transaction_date' AND p_sort_direction = 'asc' THEN
    SELECT jsonb_agg(p.row_json ORDER BY p.transaction_date ASC, p.id DESC),
           jsonb_agg(p.k        ORDER BY p.transaction_date ASC, p.id DESC)
      INTO v_rows, v_keys
    FROM (
      SELECT f.transaction_date,
             f.id,
             f.row_json,
             jsonb_build_object(
               'td', to_char(f.transaction_date, 'YYYY-MM-DD'),
               'id', f.id
             ) AS k
      FROM public.transactions_filtered(
             p_from, p_to, p_category_id, p_payment_source_id,
             p_uncategorized_only, p_search) f
      WHERE p_cursor_id IS NULL
         OR f.transaction_date > p_cursor_date
         OR (f.transaction_date = p_cursor_date AND f.id < p_cursor_id)
      ORDER BY f.transaction_date ASC, f.id DESC
      LIMIT v_probe
    ) p;

  -- ---------------------------------------------------------------------
  -- total_amount DESC, transaction_date DESC, id DESC
  -- ---------------------------------------------------------------------
  ELSIF p_sort_by = 'total_amount' AND p_sort_direction = 'desc' THEN
    SELECT jsonb_agg(p.row_json ORDER BY p.total_amount DESC, p.transaction_date DESC, p.id DESC),
           jsonb_agg(p.k        ORDER BY p.total_amount DESC, p.transaction_date DESC, p.id DESC)
      INTO v_rows, v_keys
    FROM (
      SELECT f.transaction_date,
             f.id,
             f.total_amount,
             f.row_json,
             jsonb_build_object(
               -- ::text, not a JSON number: NUMERIC must not round-trip a double.
               'av', f.total_amount::text,
               'td', to_char(f.transaction_date, 'YYYY-MM-DD'),
               'id', f.id
             ) AS k
      FROM public.transactions_filtered(
             p_from, p_to, p_category_id, p_payment_source_id,
             p_uncategorized_only, p_search) f
      WHERE p_cursor_id IS NULL
         OR f.total_amount < p_cursor_amount
         OR (f.total_amount = p_cursor_amount
             AND (f.transaction_date < p_cursor_date
                  OR (f.transaction_date = p_cursor_date AND f.id < p_cursor_id)))
      ORDER BY f.total_amount DESC, f.transaction_date DESC, f.id DESC
      LIMIT v_probe
    ) p;

  -- ---------------------------------------------------------------------
  -- total_amount ASC, transaction_date DESC, id DESC
  -- ---------------------------------------------------------------------
  ELSIF p_sort_by = 'total_amount' AND p_sort_direction = 'asc' THEN
    SELECT jsonb_agg(p.row_json ORDER BY p.total_amount ASC, p.transaction_date DESC, p.id DESC),
           jsonb_agg(p.k        ORDER BY p.total_amount ASC, p.transaction_date DESC, p.id DESC)
      INTO v_rows, v_keys
    FROM (
      SELECT f.transaction_date,
             f.id,
             f.total_amount,
             f.row_json,
             jsonb_build_object(
               'av', f.total_amount::text,
               'td', to_char(f.transaction_date, 'YYYY-MM-DD'),
               'id', f.id
             ) AS k
      FROM public.transactions_filtered(
             p_from, p_to, p_category_id, p_payment_source_id,
             p_uncategorized_only, p_search) f
      WHERE p_cursor_id IS NULL
         OR f.total_amount > p_cursor_amount
         OR (f.total_amount = p_cursor_amount
             AND (f.transaction_date < p_cursor_date
                  OR (f.transaction_date = p_cursor_date AND f.id < p_cursor_id)))
      ORDER BY f.total_amount ASC, f.transaction_date DESC, f.id DESC
      LIMIT v_probe
    ) p;

  -- ---------------------------------------------------------------------
  -- description ASC, transaction_date DESC, id DESC   (NULL descriptions last)
  -- ---------------------------------------------------------------------
  ELSIF p_sort_by = 'description' AND p_sort_direction = 'asc' THEN
    SELECT jsonb_agg(p.row_json ORDER BY (p.description IS NULL) ASC,
                                         p.description COLLATE "C" ASC,
                                         p.transaction_date DESC, p.id DESC),
           jsonb_agg(p.k        ORDER BY (p.description IS NULL) ASC,
                                         p.description COLLATE "C" ASC,
                                         p.transaction_date DESC, p.id DESC)
      INTO v_rows, v_keys
    FROM (
      SELECT f.transaction_date,
             f.id,
             f.description,
             f.row_json,
             jsonb_build_object(
               'dn', (f.description IS NULL),
               'dv', f.description,
               'td', to_char(f.transaction_date, 'YYYY-MM-DD'),
               'id', f.id
             ) AS k
      FROM public.transactions_filtered(
             p_from, p_to, p_category_id, p_payment_source_id,
             p_uncategorized_only, p_search) f
      WHERE p_cursor_id IS NULL
         OR (
           CASE
             -- Still inside the non-NULL block: everything that sorts after the
             -- cursor value, plus the entire NULL block that follows it.
             WHEN NOT p_cursor_description_is_null THEN
                  f.description IS NULL
               OR f.description COLLATE "C" > p_cursor_description COLLATE "C"
               OR (f.description COLLATE "C" = p_cursor_description COLLATE "C"
                   AND (f.transaction_date < p_cursor_date
                        OR (f.transaction_date = p_cursor_date AND f.id < p_cursor_id)))
             -- Already inside the trailing NULL block: only later NULL rows.
             ELSE
               f.description IS NULL
               AND (f.transaction_date < p_cursor_date
                    OR (f.transaction_date = p_cursor_date AND f.id < p_cursor_id))
           END
         )
      ORDER BY (f.description IS NULL) ASC,
               f.description COLLATE "C" ASC,
               f.transaction_date DESC, f.id DESC
      LIMIT v_probe
    ) p;

  -- ---------------------------------------------------------------------
  -- description DESC, transaction_date DESC, id DESC  (NULL descriptions last)
  -- ---------------------------------------------------------------------
  ELSIF p_sort_by = 'description' AND p_sort_direction = 'desc' THEN
    SELECT jsonb_agg(p.row_json ORDER BY (p.description IS NULL) ASC,
                                         p.description COLLATE "C" DESC,
                                         p.transaction_date DESC, p.id DESC),
           jsonb_agg(p.k        ORDER BY (p.description IS NULL) ASC,
                                         p.description COLLATE "C" DESC,
                                         p.transaction_date DESC, p.id DESC)
      INTO v_rows, v_keys
    FROM (
      SELECT f.transaction_date,
             f.id,
             f.description,
             f.row_json,
             jsonb_build_object(
               'dn', (f.description IS NULL),
               'dv', f.description,
               'td', to_char(f.transaction_date, 'YYYY-MM-DD'),
               'id', f.id
             ) AS k
      FROM public.transactions_filtered(
             p_from, p_to, p_category_id, p_payment_source_id,
             p_uncategorized_only, p_search) f
      WHERE p_cursor_id IS NULL
         OR (
           CASE
             WHEN NOT p_cursor_description_is_null THEN
                  f.description IS NULL
               OR f.description COLLATE "C" < p_cursor_description COLLATE "C"
               OR (f.description COLLATE "C" = p_cursor_description COLLATE "C"
                   AND (f.transaction_date < p_cursor_date
                        OR (f.transaction_date = p_cursor_date AND f.id < p_cursor_id)))
             ELSE
               f.description IS NULL
               AND (f.transaction_date < p_cursor_date
                    OR (f.transaction_date = p_cursor_date AND f.id < p_cursor_id))
           END
         )
      ORDER BY (f.description IS NULL) ASC,
               f.description COLLATE "C" DESC,
               f.transaction_date DESC, f.id DESC
      LIMIT v_probe
    ) p;

  ELSE
    RAISE EXCEPTION 'transactions_page: unsupported sort % %', p_sort_by, p_sort_direction;
  END IF;

  -- jsonb_agg over an empty set returns NULL, not '[]'.
  v_rows := COALESCE(v_rows, '[]'::jsonb);
  v_keys := COALESCE(v_keys, '[]'::jsonb);

  v_has_more := jsonb_array_length(v_rows) > p_limit;

  IF v_has_more THEN
    -- Drop the probe row. The explicit ORDER BY on the ordinality keeps the
    -- page order intact through the re-aggregation.
    SELECT jsonb_agg(e ORDER BY o)
      INTO v_rows
    FROM jsonb_array_elements(v_rows) WITH ORDINALITY AS x(e, o)
    WHERE o <= p_limit;

    -- Keyset position of the LAST ROW ACTUALLY RETURNED (0-based index),
    -- never the probe row.
    v_next_key := v_keys -> (p_limit - 1);
  END IF;

  -- Totals cover the whole filtered set, not the returned page: summing a
  -- single page would understate the user's real totals. Requested on the
  -- first page only, which is why this must be a real conditional.
  IF COALESCE(p_include_totals, false) THEN
    SELECT jsonb_build_object(
             'count',   COUNT(*),
             -- The income/expense split follows the existing movement_type
             -- contract: total_amount carries the magnitude and movement_type
             -- carries the direction. Unchanged from calculateSummaryStats.
             -- (Note: there is no CHECK constraint forcing total_amount >= 0;
             -- this mirrors whatever is stored, it does not assume a sign.)
             'income',  COALESCE(SUM(f.total_amount) FILTER (WHERE f.movement_type = 'income'),  0),
             'expense', COALESCE(SUM(f.total_amount) FILTER (WHERE f.movement_type = 'expense'), 0)
           )
      INTO v_totals
    FROM public.transactions_filtered(
           p_from, p_to, p_category_id, p_payment_source_id,
           p_uncategorized_only, p_search) f;
  END IF;

  RETURN jsonb_build_object(
    'data',     v_rows,
    'has_more', v_has_more,
    'next_key', v_next_key,
    'totals',   v_totals
  );
END;
$$;


-- =============================================
-- 7.4 DASHBOARD AGGREGATES
-- =============================================

-- Period totals for the Dashboard KPI cards.
-- Replaces downloading every transaction into the browser and summing it in
-- calculateSummaryStats(). Same income/expense/balance rule, computed in SQL.
CREATE OR REPLACE FUNCTION public.dashboard_summary(
  p_from date,
  p_to   date
)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public, pg_temp
AS $$
  SELECT jsonb_build_object(
    'income',   COALESCE(SUM(total_amount) FILTER (WHERE movement_type = 'income'),  0),
    'expenses', COALESCE(SUM(total_amount) FILTER (WHERE movement_type = 'expense'), 0),
    'balance',  COALESCE(SUM(total_amount) FILTER (WHERE movement_type = 'income'),  0)
              - COALESCE(SUM(total_amount) FILTER (WHERE movement_type = 'expense'), 0),
    'count',    COUNT(*)
  )
  FROM public.transactions
  WHERE (p_from IS NULL OR transaction_date >= p_from)
    AND (p_to   IS NULL OR transaction_date <= p_to);
$$;


-- Trailing-N-month income/expense series for the Dashboard trend chart.
-- Replaces prepareMonthlyChartData(), which bucketed the full downloaded array
-- in JavaScript. Months with no transactions are returned with zeros so the
-- chart keeps a continuous axis (generate_series + LEFT JOIN), matching the
-- previous behaviour where an empty month produced {income: 0, expenses: 0}.
CREATE OR REPLACE FUNCTION public.dashboard_monthly_series(
  p_months integer DEFAULT 6
)
RETURNS jsonb
LANGUAGE sql
STABLE
SECURITY INVOKER
SET search_path = public, pg_temp
AS $$
  WITH bounds AS (
    SELECT date_trunc('month', CURRENT_DATE)::date AS current_month_start,
           GREATEST(COALESCE(p_months, 6), 1)      AS months
  ),
  months AS (
    SELECT generate_series(
             (SELECT current_month_start - ((months - 1) || ' months')::interval FROM bounds),
             (SELECT current_month_start FROM bounds),
             '1 month'::interval
           )::date AS month_start
  ),
  per_month AS (
    SELECT
      m.month_start,
      COALESCE(SUM(t.total_amount) FILTER (WHERE t.movement_type = 'income'),  0) AS income,
      COALESCE(SUM(t.total_amount) FILTER (WHERE t.movement_type = 'expense'), 0) AS expenses
    FROM months m
    LEFT JOIN public.transactions t
      ON t.transaction_date >= m.month_start
     AND t.transaction_date <  (m.month_start + interval '1 month')
    GROUP BY m.month_start
  )
  SELECT COALESCE(jsonb_agg(
           jsonb_build_object(
             'month',    to_char(per_month.month_start, 'YYYY-MM'),
             'income',   per_month.income,
             'expenses', per_month.expenses
           )
           ORDER BY per_month.month_start
         ), '[]'::jsonb)
  FROM per_month;
$$;


-- =============================================
-- 7.5 GRANTS
-- =============================================
--
-- PostgreSQL grants EXECUTE to PUBLIC by default. Without the REVOKEs below,
-- every function above would be callable through PostgREST by `anon` and
-- `authenticated`, bypassing the Express requireAuth middleware entirely — and
-- the RLS policies on these tables are `USING (true)`, so RLS is no backstop.
--
-- These statements only NARROW access from the PostgreSQL default. They grant
-- nothing that was not already implicitly granted to everyone.
--
-- If SUPABASE_KEY on the server is ever changed to an anon key, these REVOKEs
-- will break every endpoint. Confirm the key's JWT `role` claim is
-- `service_role` before applying this migration.

REVOKE ALL ON FUNCTION public.transactions_search_pattern(text)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.transactions_search_pattern(text)
  TO service_role;

REVOKE ALL ON FUNCTION public.transactions_filtered(date,date,bigint,bigint,boolean,text)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.transactions_filtered(date,date,bigint,bigint,boolean,text)
  TO service_role;

REVOKE ALL ON FUNCTION public.transactions_page(date,date,bigint,bigint,boolean,text,integer,text,text,bigint,date,numeric,text,boolean,boolean)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.transactions_page(date,date,bigint,bigint,boolean,text,integer,text,text,bigint,date,numeric,text,boolean,boolean)
  TO service_role;

REVOKE ALL ON FUNCTION public.dashboard_summary(date,date)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.dashboard_summary(date,date)
  TO service_role;

REVOKE ALL ON FUNCTION public.dashboard_monthly_series(integer)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.dashboard_monthly_series(integer)
  TO service_role;
