-- =============================================
-- FULL DATABASE SCHEMA - FINANCE TRACKER
-- Last updated: 2026-03-19
-- Source of truth: docs/db_snapshot.md
-- =============================================
-- Table creation order respects FK dependencies.
-- Only constraints confirmed by the DB snapshot are included.
-- RLS policies are included for the original 5 tables only.
-- =============================================


-- =============================================
-- SECTION 1: FOUNDATION TABLES (no domain deps)
-- =============================================

-- Categories: transaction classification with auto-learning keywords
CREATE TABLE IF NOT EXISTS categories (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL,
  type        TEXT NOT NULL DEFAULT 'expense' CHECK (type IN ('income', 'expense')),
  keywords    TEXT[] DEFAULT '{}',
  icon        TEXT,
  created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Payment sources: credit cards, bank accounts, cash, etc.
CREATE TABLE IF NOT EXISTS payment_sources (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL,
  method      TEXT NOT NULL CHECK (method IN ('credit_card', 'debit_card', 'cash', 'bank_transfer', 'digital_wallet', 'check')),
  owner       TEXT,
  slug        TEXT NOT NULL UNIQUE,
  is_active   BOOLEAN NOT NULL DEFAULT true,
  issuer      TEXT,
  last4       TEXT,
  created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Shopping list templates (e.g. grocery, pharmacy)
CREATE TABLE IF NOT EXISTS shopping_list_types (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL,
  slug        TEXT NOT NULL UNIQUE,
  is_active   BOOLEAN NOT NULL DEFAULT true,
  created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Shopping catalog categories (separate from financial categories)
CREATE TABLE IF NOT EXISTS shopping_catalog_categories (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT NOT NULL UNIQUE,
  icon        TEXT,
  is_active   BOOLEAN NOT NULL DEFAULT true,
  created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now())
);

-- Loans: must be defined before transactions due to FK on transactions.loan_id
CREATE TABLE IF NOT EXISTS loans (
  id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at              TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  name                    TEXT NOT NULL,
  lender_name             TEXT,
  loan_type               TEXT,
  original_amount         NUMERIC NOT NULL,
  current_balance         NUMERIC NOT NULL,
  monthly_payment         NUMERIC,
  interest_rate           NUMERIC,
  linkage_type            TEXT,
  total_installments      INTEGER,
  remaining_installments  INTEGER,
  start_date              DATE,
  end_date                DATE,
  status                  TEXT DEFAULT 'active' CHECK (status IN ('active', 'paid', 'defaulted')),
  notes                   TEXT,
  amortization_type       TEXT DEFAULT 'spitzer',
  interest_type           TEXT DEFAULT 'fixed',
  prime_margin            NUMERIC DEFAULT 0,
  balloon_amount          NUMERIC DEFAULT 0,
  grace_months            INTEGER DEFAULT 0
);

CREATE INDEX idx_loans_status ON loans (status);


-- =============================================
-- SECTION 2: CORE FINANCIAL TABLES
-- =============================================

-- Main transaction records.
-- Note: id uses the legacy serial/sequence style (INTEGER, not BIGINT IDENTITY).
-- payment_method and payment_source are legacy columns superseded by payment_source_id.
-- current_installment is a legacy field; installment_number/count are the current fields.
CREATE TABLE IF NOT EXISTS transactions (
  id                      SERIAL PRIMARY KEY,
  transaction_date        DATE NOT NULL,
  description             CHARACTER VARYING,
  movement_type           CHARACTER VARYING NOT NULL CHECK (movement_type IN ('expense', 'income')),
  total_amount            NUMERIC NOT NULL,
  charge_date             DATE NOT NULL DEFAULT CURRENT_DATE,
  category_id             BIGINT REFERENCES categories(id),
  payment_source_id       BIGINT REFERENCES payment_sources(id),
  loan_id                 BIGINT REFERENCES loans(id),
  global_discount         NUMERIC DEFAULT 0,
  original_amount         NUMERIC,
  currency                TEXT DEFAULT 'ILS',
  exchange_rate           NUMERIC,
  installments_info       TEXT,
  installment_number      INTEGER,
  installment_count       INTEGER,
  parent_transaction_id   BIGINT REFERENCES transactions(id),
  current_installment     INTEGER,                    -- legacy field, superseded by installment_number
  payment_method          CHARACTER VARYING,          -- legacy field, superseded by payment_source_id
  payment_source          TEXT,                       -- legacy field, superseded by payment_source_id
  tags                    TEXT,
  notes                   TEXT,
  created_at              TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at              TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

CREATE INDEX idx_transactions_loan_id ON transactions (loan_id);
CREATE INDEX idx_transactions_payment_source_id ON transactions (payment_source_id);

-- Line items for a transaction (individual products, LEGO sets, etc.)
-- Note: uses legacy SERIAL id. No created_at column in the real DB.
CREATE TABLE IF NOT EXISTS transaction_items (
  id                SERIAL PRIMARY KEY,
  transaction_id    INTEGER REFERENCES transactions(id),
  item_name         CHARACTER VARYING NOT NULL,
  quantity          INTEGER DEFAULT 1,
  price_per_unit    NUMERIC,
  total_item_price  NUMERIC,
  set_number        TEXT,
  theme             TEXT,
  discount_type     TEXT DEFAULT 'amount' CHECK (discount_type IN ('amount', 'percent')),
  discount_value    NUMERIC DEFAULT 0,
  final_price       NUMERIC DEFAULT 0,
  tags              TEXT
);

-- LEGO set collection records. Created automatically on Lego-category transactions.
-- Note: id is UUID, not BIGINT. No CHECK constraints on status or brand in the DB.
CREATE TABLE IF NOT EXISTS lego_sets (
  id              UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  set_number      TEXT NOT NULL,
  name            TEXT NOT NULL,
  theme           TEXT,
  pieces          INTEGER,
  purchase_price  NUMERIC,
  market_value    NUMERIC,
  original_price  NUMERIC DEFAULT 0,
  status          TEXT DEFAULT 'New',
  brand           TEXT DEFAULT 'LEGO',
  purchase_date   DATE,
  transaction_id  INTEGER REFERENCES transactions(id),
  created_at      TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Monthly budget targets per category
CREATE TABLE IF NOT EXISTS budgets (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id  BIGINT REFERENCES categories(id),
  month        TEXT NOT NULL,               -- format: 'YYYY-MM'
  amount       NUMERIC NOT NULL DEFAULT 0,
  created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  UNIQUE (category_id, month)
);


-- =============================================
-- SECTION 3: MAPPING / AUTOMATION TABLES
-- =============================================

-- WhatsApp bot: maps merchant names to categories per user (wa_id)
CREATE TABLE IF NOT EXISTS merchant_category_map (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wa_id                TEXT NOT NULL,
  merchant_normalized  TEXT NOT NULL,
  category_id          BIGINT REFERENCES categories(id),
  created_at           TIMESTAMP WITH TIME ZONE DEFAULT now(),
  UNIQUE (wa_id, merchant_normalized)
);

-- WhatsApp bot: pending actions awaiting user confirmation
CREATE TABLE IF NOT EXISTS whatsapp_pending_actions (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wa_id        TEXT NOT NULL,
  payload_json JSONB NOT NULL,
  created_at   TIMESTAMP WITH TIME ZONE DEFAULT now()
);

CREATE INDEX idx_pending_wa_id ON whatsapp_pending_actions (wa_id);


-- =============================================
-- SECTION 4: SHOPPING MODULE
-- =============================================

-- Reusable product catalog, scoped to a shopping catalog category
CREATE TABLE IF NOT EXISTS shopping_catalog_items (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id    BIGINT NOT NULL REFERENCES shopping_catalog_categories(id),
  name           TEXT NOT NULL,
  default_unit   TEXT,
  default_price  NUMERIC,
  is_active      BOOLEAN NOT NULL DEFAULT true,
  created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  UNIQUE (category_id, name)
);

CREATE INDEX idx_catalog_items_category ON shopping_catalog_items (category_id);

-- M2M: which catalog categories are available for each list type
CREATE TABLE IF NOT EXISTS shopping_catalog_category_list_types (
  category_id   BIGINT NOT NULL REFERENCES shopping_catalog_categories(id),
  list_type_id  BIGINT NOT NULL REFERENCES shopping_list_types(id),
  created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  PRIMARY KEY (category_id, list_type_id)
);

CREATE INDEX idx_category_list_types_list_type ON shopping_catalog_category_list_types (list_type_id, category_id);

-- Shopping list headers
CREATE TABLE IF NOT EXISTS shopping_lists (
  id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title         TEXT NOT NULL,
  list_type_id  BIGINT NOT NULL REFERENCES shopping_list_types(id),
  status        TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('draft', 'active', 'checked_out', 'archived')),
  created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX idx_shopping_lists_type_status ON shopping_lists (list_type_id, status);

-- Individual items within a shopping list.
-- Each item is either a catalog item (catalog_item_id set) or a custom entry (custom_name set), never both.
CREATE TABLE IF NOT EXISTS shopping_list_items (
  id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  list_id          BIGINT NOT NULL REFERENCES shopping_lists(id),
  catalog_item_id  BIGINT REFERENCES shopping_catalog_items(id),
  custom_name      TEXT,
  category_id      BIGINT NOT NULL REFERENCES shopping_catalog_categories(id),
  quantity         NUMERIC,
  unit             TEXT,
  price            NUMERIC,
  is_purchased     BOOLEAN NOT NULL DEFAULT false,
  purchased_at     TIMESTAMP WITH TIME ZONE,
  notes            TEXT,
  created_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at       TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  CHECK (
    (catalog_item_id IS NOT NULL AND custom_name IS NULL)
    OR
    (catalog_item_id IS NULL AND custom_name IS NOT NULL AND trim(custom_name) <> '')
  )
);

CREATE INDEX idx_shopping_list_items_list ON shopping_list_items (list_id);
CREATE INDEX idx_shopping_list_items_list_category ON shopping_list_items (list_id, category_id);
CREATE INDEX idx_shopping_list_items_purchased ON shopping_list_items (list_id, is_purchased);

-- Records the checkout event for a shopping list.
-- One checkout per list (list_id is UNIQUE).
-- payment_source_id, category_id, transaction_id reference other tables but have no DB-level FK constraints.
CREATE TABLE IF NOT EXISTS shopping_checkouts (
  id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  list_id           BIGINT NOT NULL UNIQUE REFERENCES shopping_lists(id),
  checkout_date     DATE NOT NULL DEFAULT (timezone('utc'::text, now()))::date,
  total_amount      NUMERIC NOT NULL CHECK (total_amount >= 0),
  payment_method    TEXT NOT NULL DEFAULT 'credit_card' CHECK (payment_method IN ('credit_card', 'cash', 'bank_transfer', 'direct_debit', 'bit', 'paypal', 'other')),
  payment_source_id BIGINT,
  category_id       BIGINT,
  transaction_id    BIGINT,
  created_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE INDEX idx_shopping_checkouts_date ON shopping_checkouts (checkout_date DESC);


-- =============================================
-- SECTION 5: ROW LEVEL SECURITY
-- Confirmed for original 5 tables only.
-- All policies use permissive USING (true) —
-- access control is handled at the application layer.
-- =============================================

ALTER TABLE categories       ENABLE ROW LEVEL SECURITY;
ALTER TABLE payment_sources  ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions     ENABLE ROW LEVEL SECURITY;
ALTER TABLE transaction_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE budgets          ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Access Categories"      ON categories       FOR ALL USING (true);
CREATE POLICY "Public Access Payment Sources" ON payment_sources  FOR ALL USING (true);
CREATE POLICY "Public Access Transactions"    ON transactions     FOR ALL USING (true);
CREATE POLICY "Public Access Items"           ON transaction_items FOR ALL USING (true);
CREATE POLICY "Public Access Budgets"         ON budgets          FOR ALL USING (true);


-- =============================================
-- SECTION 6: TASK JOURNAL
-- Added: 2026-05-01
-- =============================================

CREATE TABLE IF NOT EXISTS tasks (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title          TEXT NOT NULL,
  notes          TEXT,
  status         TEXT NOT NULL DEFAULT 'open'
                 CHECK (status IN ('open', 'in_progress', 'waiting', 'done', 'cancelled')),
  priority       TEXT NOT NULL DEFAULT 'medium'
                 CHECK (priority IN ('low', 'medium', 'high', 'urgent')),
  category       TEXT NOT NULL DEFAULT 'personal'
                 CHECK (category IN ('finance', 'personal', 'work', 'system', 'other')),
  due_date       DATE,
  completed_at   TIMESTAMP WITH TIME ZONE,
  source         TEXT NOT NULL DEFAULT 'manual'
                 CHECK (source IN ('manual', 'system', 'ai')),
  transaction_id INTEGER REFERENCES transactions(id) ON DELETE SET NULL,
  loan_id        BIGINT  REFERENCES loans(id)         ON DELETE SET NULL,
  created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

CREATE INDEX idx_tasks_status   ON tasks (status);
CREATE INDEX idx_tasks_due_date ON tasks (due_date);
CREATE INDEX idx_tasks_priority ON tasks (priority);
CREATE INDEX idx_tasks_category ON tasks (category);
