// Explicit disposable-PostgreSQL verification for migration 017.
// Run: node --test test/fundedBudgetPostgres.local.test.js
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { spawn, spawnSync } = require('node:child_process');
const { after, before, test } = require('node:test');

const container = `finance-budget-017-${process.pid}`;
const password = 'finance_test';
const migration = fs.readFileSync(
  path.join(__dirname, '..', 'migrations', '017_funded_budget_foundation.sql'),
  'utf8',
);
const recurringMigration = fs.readFileSync(
  path.join(__dirname, '..', 'migrations', '018_recurring_budget_defaults.sql'),
  'utf8',
);
const fullSchema = fs.readFileSync(path.join(__dirname, '..', 'full_schema.sql'), 'utf8');

const docker = (args, input, allowFailure = false) => {
  const result = spawnSync('docker', args, { input, encoding: 'utf8', maxBuffer: 16 * 1024 * 1024 });
  if (!allowFailure && result.status !== 0) {
    throw new Error(`docker ${args.join(' ')} failed:\n${result.stdout}\n${result.stderr}`);
  }
  return result;
};

const psql = (database, sql, allowFailure = false) => docker([
  'exec', '-i', container, 'psql', '-U', 'postgres', '-d', database,
  '-v', 'ON_ERROR_STOP=1', '-At',
], sql, allowFailure);

const psqlAsync = (database, sql) => new Promise((resolve) => {
  const child = spawn('docker', [
    'exec', '-i', container, 'psql', '-U', 'postgres', '-d', database,
    '-v', 'ON_ERROR_STOP=1', '-At',
  ]);
  let stdout = '';
  let stderr = '';
  child.stdout.setEncoding('utf8');
  child.stderr.setEncoding('utf8');
  child.stdout.on('data', (chunk) => { stdout += chunk; });
  child.stderr.on('data', (chunk) => { stderr += chunk; });
  child.on('close', (status) => resolve({ status, stdout, stderr }));
  child.stdin.end(sql);
});

const delay = (milliseconds) => new Promise((resolve) => setTimeout(resolve, milliseconds));

const createDatabase = (name) => {
  psql('postgres', `CREATE DATABASE ${name};`);
};

const fixture = ({ unique = true, categoryForeignKey = true } = {}) => `
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  type TEXT NOT NULL DEFAULT 'expense',
  icon TEXT,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE public.transactions (
  id SERIAL PRIMARY KEY,
  transaction_date DATE NOT NULL,
  movement_type VARCHAR NOT NULL,
  total_amount NUMERIC NOT NULL,
  category_id BIGINT REFERENCES public.categories(id)
);
CREATE TABLE public.budgets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id BIGINT${categoryForeignKey ? ' REFERENCES public.categories(id)' : ''},
  month TEXT NOT NULL,
  amount NUMERIC NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
  ${unique ? ', UNIQUE(category_id, month)' : ''}
);
INSERT INTO public.categories(id,name,type) VALUES
  (1,'Food','expense'),(2,'Fuel','expense'),(3,'Other','expense');
`;

const expectMigrationFailure = (database, expected) => {
  const result = psql(database, migration, true);
  assert.notEqual(result.status, 0, `migration unexpectedly succeeded for ${database}`);
  assert.match(`${result.stdout}\n${result.stderr}`, expected);
  const rolledBack = psql(database, "SELECT to_regclass('public.budget_months') IS NULL;").stdout.trim();
  assert.equal(rolledBack, 't');
};

const applyRecurringFoundation = (database) => {
  psql(database, migration);
  psql(database, recurringMigration);
};

before(() => {
  docker(['run', '--detach', '--rm', '--name', container, '-e', `POSTGRES_PASSWORD=${password}`, 'postgres:16-alpine']);
  let ready = false;
  for (let attempt = 0; attempt < 30; attempt += 1) {
    const result = docker(['exec', container, 'pg_isready', '-U', 'postgres'], undefined, true);
    if (result.status === 0) {
      ready = true;
      break;
    }
    Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, 250);
  }
  assert.equal(ready, true, 'disposable PostgreSQL did not become ready');
  // public_probe has no explicit grants or memberships, so its effective
  // privileges are exactly those inherited from PostgreSQL PUBLIC. Supabase's
  // service_role bypasses RLS in production; model that property explicitly.
  psql('postgres', 'CREATE ROLE public_probe; CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role BYPASSRLS;');
});

after(() => {
  docker(['stop', container], undefined, true);
});

test('valid legacy rows backfill deterministically and reconcile exactly', () => {
  createDatabase('valid_backfill');
  psql('valid_backfill', `${fixture()}
    INSERT INTO budgets(id,category_id,month,amount,created_at,updated_at) VALUES
      (11,1,'2026-07',1000.00,'2026-07-01','2026-07-01'),
      (12,2,'2026-07',0.00,'2026-07-01','2026-07-01'),
      (13,1,'2026-08',500.00,'2026-08-01','2026-08-01');
  `);
  psql('valid_backfill', migration);
  const result = psql('valid_backfill', `
    SELECT
      (SELECT count(*) FROM budget_months),
      (SELECT count(*) FROM budget_funding_entries WHERE source_kind='legacy_import'),
      (SELECT count(*) FROM budget_lifecycle_events WHERE state='active'),
      (SELECT count(*) FROM budgets WHERE starting_amount=amount AND starting_kind='legacy_import'),
      (SELECT count(*) FROM budget_month_funding_state WHERE available=total_allocated AND unallocated=0),
      (SELECT nextval(pg_get_serial_sequence('budgets','id')));
  `).stdout.trim();
  assert.equal(result, '2|2|3|3|2|14');
  assert.equal(psql('valid_backfill', 'SELECT count(*) FROM transactions;').stdout.trim(), '0');
});

test('full_schema creates the funded foundation cleanly from an empty database', () => {
  createDatabase('full_schema_clean');
  psql('full_schema_clean', fullSchema);
  const objects = psql('full_schema_clean', `
    SELECT
      to_regclass('public.budget_months') IS NOT NULL,
      to_regclass('public.budget_operations') IS NOT NULL,
      to_regclass('public.budget_category_state') IS NOT NULL,
      to_regprocedure('public.get_funded_budget_month(text)') IS NOT NULL,
      to_regprocedure('public.remove_funded_budget(bigint,uuid,text)') IS NOT NULL;
  `).stdout.trim();
  assert.equal(objects, 't|t|t|t|t');
});

test('preflight rejects invalid month and rolls the transaction back', () => {
  createDatabase('bad_month');
  psql('bad_month', `${fixture()} INSERT INTO budgets(category_id,month,amount) VALUES (1,'2026-13',10);`);
  expectMigrationFailure('bad_month', /invalid legacy budget month rows/i);
});

test('preflight rejects null categories and duplicate logical rows', () => {
  createDatabase('bad_shape_rows');
  psql('bad_shape_rows', `${fixture({ unique: false })}
    INSERT INTO budgets(category_id,month,amount) VALUES
      (1,'2026-07',10),(1,'2026-07',20),(NULL,'2026-08',5);
  `);
  expectMigrationFailure('bad_shape_rows', /null legacy budget categories/i);

  createDatabase('duplicate_rows');
  psql('duplicate_rows', `${fixture({ unique: false })}
    INSERT INTO budgets(category_id,month,amount) VALUES (1,'2026-07',10),(1,'2026-07',20);
  `);
  expectMigrationFailure('duplicate_rows', /duplicate logical budget rows/i);
});

test('preflight rejects negative, over-precision, and missing-category rows', () => {
  createDatabase('bad_amount');
  psql('bad_amount', `${fixture()} INSERT INTO budgets(category_id,month,amount) VALUES (1,'2026-07',-1);`);
  expectMigrationFailure('bad_amount', /invalid legacy budget amounts/i);

  createDatabase('bad_precision');
  psql('bad_precision', `${fixture()} INSERT INTO budgets(category_id,month,amount) VALUES (1,'2026-07',1.001);`);
  expectMigrationFailure('bad_precision', /invalid legacy budget amounts/i);

  createDatabase('missing_category');
  psql('missing_category', `${fixture({ categoryForeignKey: false })}
    INSERT INTO budgets(category_id,month,amount) VALUES (999,'2026-07',10);
  `);
  expectMigrationFailure('missing_category', /reference missing categories/i);
});

test('preflight rejects legacy non-finite amounts accepted by PostgreSQL NUMERIC', () => {
  for (const [database, value] of [
    ['legacy_nan', 'NaN'],
    ['legacy_infinity', 'Infinity'],
    ['legacy_negative_infinity', '-Infinity'],
  ]) {
    createDatabase(database);
    psql(database, `${fixture()} INSERT INTO budgets(category_id,month,amount) VALUES (1,'2026-07','${value}'::numeric);`);
    expectMigrationFailure(database, /invalid legacy budget amounts/i);
  }
});

test('sequence restart and all schema work roll back after a later migration failure', () => {
  createDatabase('sequence_rollback');
  psql('sequence_rollback', `${fixture()}
    INSERT INTO budgets(id,category_id,month,amount) VALUES (50,1,'2026-07',100);
    ALTER SEQUENCE public.budgets_id_seq RESTART WITH 77;
    CREATE TABLE public.budget_category_state(marker integer);
  `);
  const beforeState = psql('sequence_rollback', 'SELECT last_value,is_called FROM public.budgets_id_seq;').stdout.trim();
  assert.equal(beforeState, '77|f');

  const result = psql('sequence_rollback', migration, true);
  assert.notEqual(result.status, 0);
  assert.match(result.stderr, /budget_category_state.*already exists/i);
  assert.equal(psql('sequence_rollback', 'SELECT last_value,is_called FROM public.budgets_id_seq;').stdout.trim(), beforeState);
  assert.equal(psql('sequence_rollback', "SELECT to_regclass('public.budget_months') IS NULL;").stdout.trim(), 't');
  assert.equal(psql('sequence_rollback', "SELECT count(*) FROM information_schema.columns WHERE table_schema='public' AND table_name='budgets' AND column_name='starting_amount';").stdout.trim(), '0');
});

test('RPCs enforce funding, explicit zero, idempotency, removal, and reactivation', () => {
  createDatabase('rpc_domain');
  psql('rpc_domain', fixture());
  psql('rpc_domain', migration);
  psql('rpc_domain', `
    SELECT add_manual_budget_funding('2026-09',1000,'Confirmed opening cash','11111111-1111-4111-8111-111111111111');
    SELECT add_manual_budget_funding('2026-09',1000,'Confirmed opening cash','11111111-1111-4111-8111-111111111111');
    SELECT establish_funded_budget('2026-09',2,0,'manual','22222222-2222-4222-8222-222222222222');
    SELECT establish_funded_budget('2026-09',1,600,'manual','33333333-3333-4333-8333-333333333333');
    SELECT set_funded_budget_amount(
      (SELECT budget_id FROM budget_category_state WHERE month='2026-09' AND category_id=1),
      700,'44444444-4444-4444-8444-444444444444'
    );
    INSERT INTO transactions(transaction_date,movement_type,total_amount,category_id)
      VALUES ('2026-09-10','expense',250,1),('2026-09-11','expense',50,3),('2026-09-12','expense',50,2);
    SELECT remove_funded_budget(
      (SELECT budget_id FROM budget_category_state WHERE month='2026-09' AND category_id=1),
      '55555555-5555-4555-8555-555555555555'
    );
    SELECT remove_funded_budget(
      (SELECT budget_id FROM budget_category_state WHERE month='2026-09' AND category_id=2),
      '66666666-6666-4666-8666-666666666666'
    );
    SELECT reactivate_funded_budget(
      (SELECT budget_id FROM budget_category_state WHERE month='2026-09' AND category_id=1),
      100,'77777777-7777-4777-8777-777777777777'
    );
  `);
  const state = JSON.parse(psql('rpc_domain', "SELECT get_funded_budget_month('2026-09');").stdout.trim());
  assert.equal(state.funding.available, '1000.00');
  assert.equal(state.funding.total_allocated, '350.00');
  assert.equal(state.funding.unallocated, '650.00');
  assert.equal(state.actuals.total, '350.00');
  assert.equal(state.actuals.budgeted, '250.00');
  assert.equal(state.actuals.unbudgeted, '100.00');
  assert.equal(state.history.filter((operation) => operation.operation_type === 'manual_funding').length, 1);
  const food = state.categories.find((category) => category.category_id === 1);
  const fuel = state.categories.find((category) => category.category_id === 2);
  assert.equal(food.starting_amount, '600.00');
  assert.equal(food.adjustment_total, '-250.00');
  assert.equal(food.final_funded, '350.00');
  assert.equal(food.lifecycle_state, 'active');
  assert.equal(fuel.final_funded, '0.00');
  assert.equal(fuel.lifecycle_state, 'inactive');
  assert.equal(fuel.actual_spent, '50.00');
  const fuelRemoval = state.history.flatMap((operation) => operation.lifecycle_events)
    .find((event) => event.budget_id === fuel.budget_id && event.state === 'inactive');
  assert.equal(fuelRemoval.actual_spent_snapshot, '50.00');
});

test('RPC failures are atomic and append-only protections reject rewrites', () => {
  const insufficient = psql('rpc_domain', `
    SELECT establish_funded_budget('2026-09',3,700,'manual','88888888-8888-4888-8888-888888888888');
  `, true);
  assert.notEqual(insufficient.status, 0);
  assert.match(insufficient.stderr, /Insufficient unallocated funds/i);
  assert.equal(psql('rpc_domain', "SELECT count(*) FROM budgets b JOIN budget_months bm ON bm.id=b.budget_month_id WHERE bm.month_start='2026-09-01' AND b.category_id=3;").stdout.trim(), '0');

  const nonFinite = psql('rpc_domain', "SELECT add_manual_budget_funding('2026-09','NaN'::numeric,'Invalid','12121212-1212-4212-8212-121212121212');", true);
  assert.notEqual(nonFinite.status, 0);
  assert.match(nonFinite.stderr, /positive two-decimal value/i);

  const budgetId = psql('rpc_domain', "SELECT budget_id FROM budget_category_state WHERE month='2026-09' AND category_id=1;").stdout.trim();
  const spentRelease = psql('rpc_domain', `SELECT set_funded_budget_amount(${budgetId},200,'99999999-9999-4999-8999-999999999999');`, true);
  assert.notEqual(spentRelease.status, 0);
  assert.match(spentRelease.stderr, /Cannot release spent funding/i);

  for (const sql of [
    `UPDATE budgets SET starting_amount=999 WHERE id=${budgetId};`,
    'UPDATE budget_operations SET reason=\'rewrite\' WHERE id=(SELECT min(id) FROM budget_operations);',
    'DELETE FROM budget_movements;',
    'DELETE FROM budgets WHERE id=' + budgetId + ';',
  ]) {
    const result = psql('rpc_domain', sql, true);
    assert.notEqual(result.status, 0);
    assert.match(result.stderr, /immutable|append-only/i);
  }
});

test('funded tables reject non-finite money and non-finite actuals abort removal atomically', () => {
  createDatabase('finite_money');
  psql('finite_money', fixture());
  psql('finite_money', migration);
  psql('finite_money', `
    SELECT add_manual_budget_funding('2027-01',1000,'Finite funds','20202020-2020-4020-8020-202020202020');
    SELECT establish_funded_budget('2027-01',1,500,'manual','21212121-2121-4121-8121-212121212121');
  `);
  const budgetId = psql('finite_money', "SELECT budget_id FROM budget_category_state WHERE month='2027-01' AND category_id=1;").stdout.trim();
  const monthId = psql('finite_money', "SELECT id FROM budget_months WHERE month_start='2027-01-01';").stdout.trim();
  psql('finite_money', `
    INSERT INTO budget_operations(budget_month_id,request_key,request_fingerprint,operation_type,effective_date)
    VALUES
      (${monthId},'29292929-2929-4929-8929-292929292920','finite-funding','manual_funding','2027-01-01'),
      (${monthId},'29292929-2929-4929-8929-292929292921','finite-movement','adjustment','2027-01-01'),
      (${monthId},'29292929-2929-4929-8929-292929292922','finite-lifecycle','removal','2027-01-01'),
      (${monthId},'29292929-2929-4929-8929-292929292923','finite-budget','establish_budget','2027-01-01');
  `);

  for (const sql of [
    `INSERT INTO budget_funding_entries(operation_id,amount_delta,source_kind,source_label) VALUES ((SELECT id FROM budget_operations WHERE request_fingerprint='finite-funding'),'NaN','manual_available_funds','bad');`,
    `INSERT INTO budget_movements(operation_id,destination_budget_id,amount) VALUES ((SELECT id FROM budget_operations WHERE request_fingerprint='finite-movement'),${budgetId},'NaN');`,
    `INSERT INTO budget_lifecycle_events(operation_id,budget_id,state,actual_spent_snapshot) VALUES ((SELECT id FROM budget_operations WHERE request_fingerprint='finite-lifecycle'),${budgetId},'inactive','NaN');`,
    `INSERT INTO budgets(category_id,month,amount,budget_month_id,starting_amount,starting_kind,created_by_operation_id)
      VALUES (2,'2027-01','NaN',${monthId},'NaN','manual',(SELECT id FROM budget_operations WHERE request_fingerprint='finite-budget'));`,
  ]) {
    const result = psql('finite_money', sql, true);
    assert.notEqual(result.status, 0);
  }

  for (const value of ['Infinity', '-Infinity']) {
    const result = psql('finite_money', `SELECT add_manual_budget_funding('2027-01','${value}'::numeric,'bad','${value === 'Infinity' ? '22222222-2222-4222-8222-222222222220' : '22222222-2222-4222-8222-222222222221'}');`, true);
    assert.notEqual(result.status, 0);
    assert.match(result.stderr, /positive two-decimal value/i);
  }

  const countsBefore = psql('finite_money', `SELECT
    (SELECT count(*) FROM budget_operations WHERE budget_month_id=${monthId}),
    (SELECT count(*) FROM budget_movements),
    (SELECT count(*) FROM budget_lifecycle_events);`).stdout.trim();
  psql('finite_money', "INSERT INTO transactions(transaction_date,movement_type,total_amount,category_id) VALUES ('2027-01-10','expense','NaN',1);");
  const removal = psql('finite_money', `SELECT remove_funded_budget(${budgetId},'23232323-2323-4323-8323-232323232323');`, true);
  assert.notEqual(removal.status, 0);
  assert.match(removal.stderr, /non-finite amount/i);
  const countsAfter = psql('finite_money', `SELECT
    (SELECT count(*) FROM budget_operations WHERE budget_month_id=${monthId}),
    (SELECT count(*) FROM budget_movements),
    (SELECT count(*) FROM budget_lifecycle_events);`).stdout.trim();
  assert.equal(countsAfter, countsBefore);
  assert.equal(psql('finite_money', `SELECT lifecycle_state FROM budget_category_state WHERE budget_id=${budgetId};`).stdout.trim(), 'active');
});

test('no-op adjustment reserves its request key and retry cannot mutate intervening state', () => {
  createDatabase('noop_idempotency');
  psql('noop_idempotency', fixture());
  psql('noop_idempotency', migration);
  psql('noop_idempotency', `
    SELECT add_manual_budget_funding('2027-02',1500,'No-op funds','24242424-2424-4424-8424-242424242424');
    SELECT establish_funded_budget('2027-02',1,1000,'manual','25252525-2525-4525-8525-252525252525');
  `);
  const budgetId = psql('noop_idempotency', "SELECT budget_id FROM budget_category_state WHERE month='2027-02' AND category_id=1;").stdout.trim();
  psql('noop_idempotency', `SELECT set_funded_budget_amount(${budgetId},1000,'26262626-2626-4626-8626-262626262626');`);
  assert.equal(psql('noop_idempotency', "SELECT count(*) FROM budget_operations WHERE request_key='26262626-2626-4626-8626-262626262626';").stdout.trim(), '1');
  assert.equal(psql('noop_idempotency', "SELECT count(*) FROM budget_movements m JOIN budget_operations o ON o.id=m.operation_id WHERE o.request_key='26262626-2626-4626-8626-262626262626';").stdout.trim(), '0');

  psql('noop_idempotency', `SELECT set_funded_budget_amount(${budgetId},1200,'27272727-2727-4727-8727-272727272727');`);
  psql('noop_idempotency', `SELECT set_funded_budget_amount(${budgetId},1000,'26262626-2626-4626-8626-262626262626');`);
  assert.equal(psql('noop_idempotency', `SELECT final_funded FROM budget_category_state WHERE budget_id=${budgetId};`).stdout.trim(), '1200.00');

  const mismatch = psql('noop_idempotency', `SELECT set_funded_budget_amount(${budgetId},900,'26262626-2626-4626-8626-262626262626');`, true);
  assert.notEqual(mismatch.status, 0);
  assert.match(mismatch.stderr, /different budget operation/i);
  assert.equal(psql('noop_idempotency', `SELECT final_funded FROM budget_category_state WHERE budget_id=${budgetId};`).stdout.trim(), '1200.00');
});

test('runtime RPCs reject out-of-range and over-precision monetary inputs', () => {
  createDatabase('money_shape');
  psql('money_shape', fixture());
  psql('money_shape', migration);
  for (const [value, pattern] of [
    ['1.001', /two-decimal/i],
    ['10000000000000000.00', /two-decimal/i],
  ]) {
    const result = psql('money_shape', `SELECT add_manual_budget_funding('2027-03','${value}'::numeric,'shape','28282828-2828-4828-8828-${value === '1.001' ? '282828282820' : '282828282821'}');`, true);
    assert.notEqual(result.status, 0);
    assert.match(result.stderr, pattern);
  }
  assert.equal(psql('money_shape', 'SELECT count(*) FROM budget_operations;').stdout.trim(), '0');
});

test('canonical read preserves exact decimal strings above JavaScript safe integer range', () => {
  createDatabase('exact_transport');
  psql('exact_transport', fixture());
  psql('exact_transport', migration);
  psql('exact_transport', `
    SELECT add_manual_budget_funding('2027-03',9007199254740993.01,'Large exact funds','47474747-4747-4747-8747-474747474740');
    SELECT add_manual_budget_funding('2027-03',0.30,'Decimal funds','47474747-4747-4747-8747-474747474741');
    SELECT establish_funded_budget('2027-03',1,9007199254740993.01,'manual','47474747-4747-4747-8747-474747474742');
    SELECT establish_funded_budget('2027-03',2,0.30,'manual','47474747-4747-4747-8747-474747474743');
  `);
  const state = JSON.parse(psql('exact_transport', "SELECT get_funded_budget_month('2027-03');").stdout.trim());
  assert.equal(state.funding.available, '9007199254740993.31');
  assert.equal(state.funding.total_allocated, '9007199254740993.31');
  assert.equal(state.funding.unallocated, '0.00');
  assert.equal(state.categories.find((category) => category.category_id === 1).final_funded, '9007199254740993.01');
  assert.equal(state.categories.find((category) => category.category_id === 2).final_funded, '0.30');
  assert.equal(psql('exact_transport', "SELECT string_agg(final_funded_text,',' ORDER BY category_id) FROM budget_category_state WHERE month='2027-03';").stdout.trim(), '9007199254740993.01,0.30');
});

test('concurrent allocations serialize on the month and cannot oversubscribe funding', async () => {
  createDatabase('concurrent_allocations');
  psql('concurrent_allocations', fixture());
  psql('concurrent_allocations', migration);
  psql('concurrent_allocations', "SELECT add_manual_budget_funding('2026-12',1000,'Concurrent test funds','13131313-1313-4313-8313-131313131313');");
  const attempts = await Promise.all([
    psqlAsync('concurrent_allocations', "SELECT establish_funded_budget('2026-12',1,700,'manual','14141414-1414-4414-8414-141414141414');"),
    psqlAsync('concurrent_allocations', "SELECT establish_funded_budget('2026-12',2,700,'manual','15151515-1515-4515-8515-151515151515');"),
  ]);
  assert.equal(attempts.filter((attempt) => attempt.status === 0).length, 1);
  assert.equal(attempts.filter((attempt) => /Insufficient unallocated funds/i.test(attempt.stderr)).length, 1);
  const totals = psql('concurrent_allocations', "SELECT total_allocated,unallocated FROM budget_month_funding_state WHERE month='2026-12';").stdout.trim();
  assert.equal(totals, '700.00|300.00');
});

test('all funded history tables reject real UPDATE and DELETE operations', () => {
  createDatabase('immutable_history');
  psql('immutable_history', fixture());
  psql('immutable_history', migration);
  psql('immutable_history', `
    SELECT add_manual_budget_funding('2027-04',1000,'Immutable funds','30303030-3030-4030-8030-303030303030');
    SELECT establish_funded_budget('2027-04',1,500,'manual','31313131-3131-4131-8131-313131313131');
    SELECT set_funded_budget_amount(
      (SELECT budget_id FROM budget_category_state WHERE month='2027-04' AND category_id=1),
      600,'32323232-3232-4232-8232-323232323232'
    );
  `);
  const mutations = [
    "UPDATE budget_months SET currency_code='ILS' WHERE month_start='2027-04-01'",
    "DELETE FROM budget_months WHERE month_start='2027-04-01'",
    'UPDATE budgets SET starting_amount=starting_amount WHERE id=(SELECT min(id) FROM budgets)',
    'DELETE FROM budgets WHERE id=(SELECT min(id) FROM budgets)',
    "UPDATE budget_operations SET reason='rewrite' WHERE id=(SELECT min(id) FROM budget_operations)",
    'DELETE FROM budget_operations WHERE id=(SELECT min(id) FROM budget_operations)',
    'UPDATE budget_funding_entries SET amount_delta=amount_delta WHERE id=(SELECT min(id) FROM budget_funding_entries)',
    'DELETE FROM budget_funding_entries WHERE id=(SELECT min(id) FROM budget_funding_entries)',
    'UPDATE budget_movements SET amount=amount WHERE id=(SELECT min(id) FROM budget_movements)',
    'DELETE FROM budget_movements WHERE id=(SELECT min(id) FROM budget_movements)',
    'UPDATE budget_lifecycle_events SET state=state WHERE id=(SELECT min(id) FROM budget_lifecycle_events)',
    'DELETE FROM budget_lifecycle_events WHERE id=(SELECT min(id) FROM budget_lifecycle_events)',
  ];
  for (const sql of mutations) {
    const result = psql('immutable_history', `${sql};`, true);
    assert.notEqual(result.status, 0, `${sql} unexpectedly succeeded`);
    assert.match(result.stderr, /immutable|append-only/i);
  }
});

test('lifecycle rules distinguish active zero from inactive and reject repeated states', () => {
  createDatabase('lifecycle_rules');
  psql('lifecycle_rules', fixture());
  psql('lifecycle_rules', migration);
  psql('lifecycle_rules', `
    SELECT add_manual_budget_funding('2027-05',1000,'Lifecycle funds','33333333-3333-4333-8333-333333333330');
    SELECT establish_funded_budget('2027-05',1,0,'manual','33333333-3333-4333-8333-333333333331');
    SELECT establish_funded_budget('2027-05',2,500,'manual','33333333-3333-4333-8333-333333333332');
    SELECT remove_funded_budget(
      (SELECT budget_id FROM budget_category_state WHERE month='2027-05' AND category_id=2),
      '33333333-3333-4333-8333-333333333333'
    );
    INSERT INTO transactions(transaction_date,movement_type,total_amount,category_id)
      VALUES ('2027-05-10','expense',200,1),('2027-05-11','expense',200,2);
  `);
  const state = JSON.parse(psql('lifecycle_rules', "SELECT get_funded_budget_month('2027-05');").stdout.trim());
  const activeZero = state.categories.find((category) => category.category_id === 1);
  const inactive = state.categories.find((category) => category.category_id === 2);
  assert.equal(activeZero.is_active_zero, true);
  assert.equal(activeZero.is_unbudgeted, false);
  assert.equal(activeZero.deficit, '200.00');
  assert.equal(inactive.lifecycle_state, 'inactive');
  assert.equal(inactive.is_unbudgeted, true);
  assert.equal(state.actuals.budgeted, '200.00');
  assert.equal(state.actuals.unbudgeted, '200.00');

  const activeId = activeZero.budget_id;
  const inactiveId = inactive.budget_id;
  const monthId = psql('lifecycle_rules', "SELECT id FROM budget_months WHERE month_start='2027-05-01';").stdout.trim();
  psql('lifecycle_rules', `
    INSERT INTO budget_operations(budget_month_id,request_key,request_fingerprint,operation_type,effective_date)
    VALUES
      (${monthId},'34343434-3434-4434-8434-343434343430','repeat-active','reactivation','2027-05-01'),
      (${monthId},'34343434-3434-4434-8434-343434343431','repeat-inactive','removal','2027-05-01');
  `);
  for (const sql of [
    `INSERT INTO budget_lifecycle_events(operation_id,budget_id,state) VALUES ((SELECT id FROM budget_operations WHERE request_fingerprint='repeat-active'),${activeId},'active');`,
    `INSERT INTO budget_lifecycle_events(operation_id,budget_id,state,actual_spent_snapshot) VALUES ((SELECT id FROM budget_operations WHERE request_fingerprint='repeat-inactive'),${inactiveId},'inactive',200);`,
    `SELECT remove_funded_budget(${inactiveId},'35353535-3535-4535-8535-353535353530');`,
    `SELECT reactivate_funded_budget(${activeId},0,'35353535-3535-4535-8535-353535353531');`,
  ]) {
    const result = psql('lifecycle_rules', sql, true);
    assert.notEqual(result.status, 0);
    assert.match(result.stderr, /invalid|not active|not inactive/i);
  }
});

test('movement constraints and category-to-category accounting reconcile exactly', () => {
  createDatabase('movement_rules');
  psql('movement_rules', fixture());
  psql('movement_rules', migration);
  psql('movement_rules', `
    SELECT add_manual_budget_funding('2027-06',3000,'Movement funds','36363636-3636-4636-8636-363636363630');
    SELECT establish_funded_budget('2027-06',1,1000,'manual','36363636-3636-4636-8636-363636363631');
    SELECT establish_funded_budget('2027-06',2,1000,'manual','36363636-3636-4636-8636-363636363632');
    SELECT add_manual_budget_funding('2027-07',500,'Other month','36363636-3636-4636-8636-363636363633');
    SELECT establish_funded_budget('2027-07',3,500,'manual','36363636-3636-4636-8636-363636363634');
  `);
  const monthId = psql('movement_rules', "SELECT id FROM budget_months WHERE month_start='2027-06-01';").stdout.trim();
  const sourceId = psql('movement_rules', "SELECT budget_id FROM budget_category_state WHERE month='2027-06' AND category_id=1;").stdout.trim();
  const destinationId = psql('movement_rules', "SELECT budget_id FROM budget_category_state WHERE month='2027-06' AND category_id=2;").stdout.trim();
  const otherMonthId = psql('movement_rules', "SELECT budget_id FROM budget_category_state WHERE month='2027-07' AND category_id=3;").stdout.trim();
  psql('movement_rules', `
    INSERT INTO budget_operations(budget_month_id,request_key,request_fingerprint,operation_type,effective_date)
    VALUES
      (${monthId},'37373737-3737-4737-8737-373737373730','category-transfer','adjustment','2027-06-01'),
      (${monthId},'37373737-3737-4737-8737-373737373731','empty-endpoints','adjustment','2027-06-01'),
      (${monthId},'37373737-3737-4737-8737-373737373732','same-endpoints','adjustment','2027-06-01'),
      (${monthId},'37373737-3737-4737-8737-373737373733','cross-month','adjustment','2027-06-01');
    INSERT INTO budget_movements(operation_id,source_budget_id,destination_budget_id,amount)
    VALUES ((SELECT id FROM budget_operations WHERE request_fingerprint='category-transfer'),${sourceId},${destinationId},300);
    SELECT budget_assert_reconciled(${monthId});
  `);
  assert.equal(psql('movement_rules', `SELECT string_agg(category_id || ':' || final_funded,',' ORDER BY category_id) FROM budget_category_state WHERE budget_month_id=${monthId};`).stdout.trim(), '1:700.00,2:1300.00');
  assert.equal(psql('movement_rules', `SELECT total_allocated,unallocated FROM budget_month_funding_state WHERE budget_month_id=${monthId};`).stdout.trim(), '2000.00|1000.00');

  for (const [fingerprint, source, destination, pattern] of [
    ['empty-endpoints', 'NULL', 'NULL', /endpoints/i],
    ['same-endpoints', sourceId, sourceId, /endpoints/i],
    ['cross-month', sourceId, otherMonthId, /outside the operation month/i],
  ]) {
    const result = psql('movement_rules', `INSERT INTO budget_movements(operation_id,source_budget_id,destination_budget_id,amount)
      VALUES ((SELECT id FROM budget_operations WHERE request_fingerprint='${fingerprint}'),${source},${destination},10);`, true);
    assert.notEqual(result.status, 0);
    assert.match(result.stderr, pattern);
  }
});

test('adjustment reversal is compensating and unsafe reversal is atomic', () => {
  createDatabase('adjustment_reversal');
  psql('adjustment_reversal', fixture());
  psql('adjustment_reversal', migration);
  psql('adjustment_reversal', `
    SELECT add_manual_budget_funding('2027-08',2000,'Reversal funds','38383838-3838-4838-8838-383838383830');
    SELECT establish_funded_budget('2027-08',1,1000,'manual','38383838-3838-4838-8838-383838383831');
  `);
  const budgetId = psql('adjustment_reversal', "SELECT budget_id FROM budget_category_state WHERE month='2027-08' AND category_id=1;").stdout.trim();
  psql('adjustment_reversal', `
    SELECT set_funded_budget_amount(${budgetId},1200,'38383838-3838-4838-8838-383838383832');
    SELECT reverse_funded_budget_operation(
      (SELECT id FROM budget_operations WHERE request_key='38383838-3838-4838-8838-383838383832'),
      '38383838-3838-4838-8838-383838383833'
    );
  `);
  assert.equal(psql('adjustment_reversal', `SELECT final_funded FROM budget_category_state WHERE budget_id=${budgetId};`).stdout.trim(), '1000.00');
  psql('adjustment_reversal', `
    SELECT set_funded_budget_amount(${budgetId},1200,'38383838-3838-4838-8838-383838383834');
    INSERT INTO transactions(transaction_date,movement_type,total_amount,category_id)
      VALUES ('2027-08-10','expense',1150,1);
  `);
  const reversalsBefore = psql('adjustment_reversal', "SELECT count(*) FROM budget_operations WHERE operation_type='reversal';").stdout.trim();
  const unsafe = psql('adjustment_reversal', `SELECT reverse_funded_budget_operation(
    (SELECT id FROM budget_operations WHERE request_key='38383838-3838-4838-8838-383838383834'),
    '38383838-3838-4838-8838-383838383835'
  );`, true);
  assert.notEqual(unsafe.status, 0);
  assert.match(unsafe.stderr, /release spent funding/i);
  assert.equal(psql('adjustment_reversal', "SELECT count(*) FROM budget_operations WHERE operation_type='reversal';").stdout.trim(), reversalsBefore);
  assert.equal(psql('adjustment_reversal', `SELECT final_funded FROM budget_category_state WHERE budget_id=${budgetId};`).stdout.trim(), '1200.00');
});

test('effective ACL matrix restricts tables, views, bounded RPCs, and internal helpers', () => {
  createDatabase('budget_acl');
  psql('budget_acl', fixture());
  psql('budget_acl', migration);
  const roles = ['public_probe', 'anon', 'authenticated', 'service_role'];
  const protectedTables = [
    'budget_months', 'budgets', 'budget_operations', 'budget_funding_entries',
    'budget_movements', 'budget_lifecycle_events',
  ];
  const readSurfaces = [
    ...protectedTables,
    'budget_category_state', 'budget_month_funding_state', 'budget_month_category_actuals',
  ];
  const boundedFunctions = [
    'get_funded_budget_month(text)',
    'add_manual_budget_funding(text,numeric,text,uuid,text)',
    'establish_funded_budget(text,bigint,numeric,text,uuid,text)',
    'set_funded_budget_amount(bigint,numeric,uuid,text)',
    'remove_funded_budget(bigint,uuid,text)',
    'reactivate_funded_budget(bigint,numeric,uuid,text)',
    'reverse_funded_budget_operation(bigint,uuid,text)',
    'copy_funded_budget_month(text,text,uuid,text)',
  ];
  const internalFunctions = [
    'prevent_budget_history_mutation()',
    'validate_budget_snapshot_insert()',
    'validate_budget_operation_insert()',
    'validate_budget_movement_insert()',
    'validate_budget_lifecycle_insert()',
    'budget_month_start_from_key(text)',
    'budget_assert_reconciled(bigint)',
  ];
  const sqlArray = (values) => `ARRAY[${values.map((value) => `'${value}'`).join(',')}]::text[]`;

  const mutationRows = psql('budget_acl', `
    SELECT role_name, table_name,
      has_table_privilege(role_name, format('public.%I', table_name), 'INSERT'),
      has_table_privilege(role_name, format('public.%I', table_name), 'UPDATE'),
      has_table_privilege(role_name, format('public.%I', table_name), 'DELETE')
    FROM unnest(${sqlArray(roles)}) AS role_name
    CROSS JOIN unnest(${sqlArray(protectedTables)}) AS table_name
    ORDER BY role_name, table_name;
  `).stdout.trim().split('\n');
  assert.equal(mutationRows.length, roles.length * protectedTables.length);
  for (const row of mutationRows) {
    const [role, table, insert, update, remove] = row.split('|');
    assert.deepEqual([insert, update, remove], ['f', 'f', 'f'], `${role} can mutate ${table}`);
  }

  // Supplement the effective privilege matrix with representative operations
  // executed under each actual role, including the PUBLIC-only probe.
  for (const [role, statement] of [
    ['public_probe', "INSERT INTO budget_months(month_start) VALUES ('2027-09-01')"],
    ['anon', 'UPDATE budgets SET amount = amount'],
    ['authenticated', 'DELETE FROM budget_operations'],
    ['service_role', 'INSERT INTO budget_movements DEFAULT VALUES'],
  ]) {
    const result = psql('budget_acl', `SET ROLE ${role}; ${statement};`, true);
    assert.notEqual(result.status, 0, `${role} unexpectedly performed a direct mutation`);
    assert.match(result.stderr, /permission denied/i);
  }

  const readRows = psql('budget_acl', `
    SELECT role_name, surface,
      has_table_privilege(role_name, format('public.%I', surface), 'SELECT')
    FROM unnest(${sqlArray(roles)}) AS role_name
    CROSS JOIN unnest(${sqlArray(readSurfaces)}) AS surface
    ORDER BY role_name, surface;
  `).stdout.trim().split('\n');
  assert.equal(readRows.length, roles.length * readSurfaces.length);
  for (const row of readRows) {
    const [role, surface, canRead] = row.split('|');
    assert.equal(canRead, role === 'service_role' ? 't' : 'f', `${role} SELECT on ${surface}`);
  }

  const boundedRows = psql('budget_acl', `
    SELECT role_name, signature,
      has_function_privilege(role_name, 'public.' || signature, 'EXECUTE')
    FROM unnest(${sqlArray(roles)}) AS role_name
    CROSS JOIN unnest(${sqlArray(boundedFunctions)}) AS signature
    ORDER BY role_name, signature;
  `).stdout.trim().split('\n');
  assert.equal(boundedRows.length, roles.length * boundedFunctions.length);
  for (const row of boundedRows) {
    const [role, signature, canExecute] = row.split('|');
    assert.equal(canExecute, role === 'service_role' ? 't' : 'f', `${role} EXECUTE on ${signature}`);
  }

  const helperRows = psql('budget_acl', `
    SELECT role_name, signature,
      has_function_privilege(role_name, 'public.' || signature, 'EXECUTE')
    FROM unnest(${sqlArray(roles)}) AS role_name
    CROSS JOIN unnest(${sqlArray(internalFunctions)}) AS signature
    ORDER BY role_name, signature;
  `).stdout.trim().split('\n');
  assert.equal(helperRows.length, roles.length * internalFunctions.length);
  for (const row of helperRows) {
    const [role, signature, canExecute] = row.split('|');
    assert.equal(canExecute, 'f', `${role} can execute internal helper ${signature}`);
  }

  for (const [role, statement] of [
    ['public_probe', "SELECT get_funded_budget_month('2027-09')"],
    ['anon', "SELECT add_manual_budget_funding('2027-09',100,'Denied','39393939-3939-4939-8939-393939393930')"],
    ['authenticated', "SELECT copy_funded_budget_month('2027-08','2027-09','39393939-3939-4939-8939-393939393931')"],
    ['service_role', 'SELECT budget_assert_reconciled(1)'],
  ]) {
    const result = psql('budget_acl', `SET ROLE ${role}; ${statement};`, true);
    assert.notEqual(result.status, 0, `${role} unexpectedly executed ${statement}`);
    assert.match(result.stderr, /permission denied/i);
  }

  // The server role can execute a bounded write and read every intended table
  // or view. BYPASSRLS mirrors Supabase's production service_role attribute.
  psql('budget_acl', `SET ROLE service_role;
    SELECT add_manual_budget_funding('2027-09',100,'Service bounded call','39393939-3939-4939-8939-393939393939');
    SELECT get_funded_budget_month('2027-09');
    SELECT count(*) FROM budgets;
    SELECT count(*) FROM budget_months;
    SELECT count(*) FROM budget_operations;
    SELECT count(*) FROM budget_funding_entries;
    SELECT count(*) FROM budget_movements;
    SELECT count(*) FROM budget_lifecycle_events;
    SELECT count(*) FROM budget_category_state;
    SELECT count(*) FROM budget_month_funding_state;
    SELECT count(*) FROM budget_month_category_actuals;
    RESET ROLE;
  `);
});

test('copy and lifecycle mutation complete without deadlock under month-first locks', async () => {
  createDatabase('copy_lifecycle_concurrency');
  psql('copy_lifecycle_concurrency', fixture());
  psql('copy_lifecycle_concurrency', migration);
  psql('copy_lifecycle_concurrency', `
    SELECT add_manual_budget_funding('2027-10',1000,'Source','40404040-4040-4040-8040-404040404040');
    SELECT establish_funded_budget('2027-10',1,400,'manual','41414141-4141-4141-8141-414141414141');
    SELECT add_manual_budget_funding('2027-11',1000,'Target','42424242-4242-4242-8242-424242424242');
    SELECT establish_funded_budget('2027-11',1,300,'manual','43434343-4343-4343-8343-434343434343');
    SELECT remove_funded_budget(
      (SELECT budget_id FROM budget_category_state WHERE month='2027-11' AND category_id=1),
      '44444444-4444-4444-8444-444444444440'
    );
  `);
  const targetBudgetId = psql('copy_lifecycle_concurrency', "SELECT budget_id FROM budget_category_state WHERE month='2027-11' AND category_id=1;").stdout.trim();
  const copyPromise = psqlAsync('copy_lifecycle_concurrency', `BEGIN;
    SELECT id FROM budget_months WHERE month_start IN ('2027-10-01','2027-11-01') ORDER BY id FOR UPDATE;
    SELECT pg_sleep(0.5);
    SELECT copy_funded_budget_month('2027-10','2027-11','45454545-4545-4545-8545-454545454545');
    COMMIT;`);
  await delay(100);
  const reactivatePromise = psqlAsync('copy_lifecycle_concurrency', `SELECT reactivate_funded_budget(
    ${targetBudgetId},0,'46464646-4646-4646-8646-464646464646'
  );`);
  const [copyResult, reactivateResult] = await Promise.all([copyPromise, reactivatePromise]);
  assert.equal(copyResult.status, 0, copyResult.stderr);
  assert.notEqual(reactivateResult.status, 0);
  assert.doesNotMatch(reactivateResult.stderr, /deadlock|40P01/i);
  assert.match(reactivateResult.stderr, /not inactive/i);
  assert.equal(psql('copy_lifecycle_concurrency', `SELECT lifecycle_state,final_funded FROM budget_category_state WHERE budget_id=${targetBudgetId};`).stdout.trim(), 'active|400.00');
  psql('copy_lifecycle_concurrency', "SELECT budget_assert_reconciled(id) FROM budget_months WHERE month_start='2027-11-01';");
  assert.equal(psql('copy_lifecycle_concurrency', "SELECT total_allocated,unallocated FROM budget_month_funding_state WHERE month='2027-11';").stdout.trim(), '400.00|600.00');
});

test('manual funding correction is compensating and copy requires destination funds', () => {
  psql('rpc_domain', `
    SELECT add_manual_budget_funding('2026-10',100,'Correction test','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa');
    SELECT reverse_funded_budget_operation(
      (SELECT id FROM budget_operations WHERE request_key='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa'),
      'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','Remove mistaken funding'
    );
  `);
  const october = JSON.parse(psql('rpc_domain', "SELECT get_funded_budget_month('2026-10');").stdout.trim());
  assert.equal(october.funding.available, '0.00');
  assert.equal(october.history.length, 2);
  assert.ok(october.history[1].reverses_operation_id);

  const copyFailure = psql('rpc_domain', "SELECT copy_funded_budget_month('2026-09','2026-11','cccccccc-cccc-4ccc-8ccc-cccccccccccc');", true);
  assert.notEqual(copyFailure.status, 0);
  assert.match(copyFailure.stderr, /Destination month needs/i);
  assert.equal(psql('rpc_domain', "SELECT count(*) FROM budgets b JOIN budget_months bm ON bm.id=b.budget_month_id WHERE bm.month_start='2026-11-01';").stdout.trim(), '0');

  psql('rpc_domain', `
    SELECT add_manual_budget_funding('2026-11',350,'Confirmed destination cash','dddddddd-dddd-4ddd-8ddd-dddddddddddd');
    SELECT copy_funded_budget_month('2026-09','2026-11','eeeeeeee-eeee-4eee-8eee-eeeeeeeeeeee');
  `);
  const november = JSON.parse(psql('rpc_domain', "SELECT get_funded_budget_month('2026-11');").stdout.trim());
  assert.equal(november.funding.unallocated, '0.00');
  assert.equal(november.funding.active_allocated, '350.00');
  assert.equal(november.categories.filter((category) => category.lifecycle_state === 'active').length, 1);

  psql('rpc_domain', `
    SELECT add_manual_budget_funding('2026-12',450,'Confirmed reactivation cash','16161616-1616-4616-8616-161616161616');
    SELECT establish_funded_budget('2026-12',1,100,'manual','17171717-1717-4717-8717-171717171717');
    SELECT remove_funded_budget(
      (SELECT budget_id FROM budget_category_state WHERE month='2026-12' AND category_id=1),
      '18181818-1818-4818-8818-181818181818'
    );
    SELECT copy_funded_budget_month('2026-09','2026-12','19191919-1919-4919-8919-191919191919');
  `);
  const december = JSON.parse(psql('rpc_domain', "SELECT get_funded_budget_month('2026-12');").stdout.trim());
  const reactivated = december.categories.find((category) => category.category_id === 1);
  assert.equal(reactivated.lifecycle_state, 'active');
  assert.equal(reactivated.starting_amount, '100.00');
  assert.equal(reactivated.final_funded, '350.00');
  assert.equal(december.funding.unallocated, '100.00');
});

test('recurring defaults enforce exact money, explicit zero, expense categories, and disable semantics', () => {
  createDatabase('recurring_configuration');
  psql('recurring_configuration', `${fixture()}
    INSERT INTO categories(id,name,type) VALUES (4,'Salary','income');
  `);
  applyRecurringFoundation('recurring_configuration');

  assert.equal(
    JSON.parse(psql('recurring_configuration', 'SELECT set_budget_recurring_default(1,0);').stdout.trim()).amount,
    '0.00',
  );
  assert.equal(
    JSON.parse(psql('recurring_configuration', "SELECT set_budget_recurring_default(1,9007199254740993.01);").stdout.trim()).amount,
    '9007199254740993.01',
  );
  assert.equal(psql('recurring_configuration', 'SELECT amount_text FROM budget_recurring_defaults_read WHERE category_id=1;').stdout.trim(), '9007199254740993.01');

  for (const [sql, diagnostic] of [
    ["SELECT set_budget_recurring_default(4,100);", /expense categories/i],
    ["SELECT set_budget_recurring_default(2,'NaN'::numeric);", /finite nonnegative/i],
    ["SELECT set_budget_recurring_default(2,'Infinity'::numeric);", /finite nonnegative/i],
    ["SELECT set_budget_recurring_default(2,'-Infinity'::numeric);", /finite nonnegative/i],
    ['SELECT set_budget_recurring_default(2,-1);', /finite nonnegative/i],
    ['SELECT set_budget_recurring_default(2,1.001);', /two-decimal/i],
    ['SELECT set_budget_recurring_default(2,10000000000000000);', /two-decimal/i],
  ]) {
    const result = psql('recurring_configuration', sql, true);
    assert.notEqual(result.status, 0);
    assert.match(result.stderr, diagnostic);
  }

  const typeChange = psql('recurring_configuration', "UPDATE categories SET type='income' WHERE id=1;", true);
  assert.notEqual(typeChange.status, 0);
  assert.match(typeChange.stderr, /Disable the recurring budget/i);
  const disabled = JSON.parse(psql('recurring_configuration', 'SELECT set_budget_recurring_default(1,NULL);').stdout.trim());
  assert.equal(disabled.enabled, false);
  assert.equal(psql('recurring_configuration', 'SELECT count(*) FROM budget_recurring_defaults;').stdout.trim(), '0');
});

test('explicit recurring initialization is exact, all-or-nothing, and preserves zero and inactive-category exclusion', () => {
  createDatabase('recurring_initialization');
  psql('recurring_initialization', `${fixture()}
    UPDATE categories SET is_active=false WHERE id=3;
  `);
  applyRecurringFoundation('recurring_initialization');
  psql('recurring_initialization', `
    SELECT set_budget_recurring_default(1,100.00);
    SELECT set_budget_recurring_default(2,0.00);
    SELECT set_budget_recurring_default(3,50.00);
    SELECT add_manual_budget_funding('2099-01',100.00,'Recurring funds','50101010-1010-4010-8010-101010101010');
  `);

  const preview = JSON.parse(psql('recurring_initialization', "SELECT get_funded_budget_month('2099-01');").stdout.trim());
  assert.equal(preview.recurring.pending_count, 2);
  assert.equal(preview.recurring.required, '100.00');
  assert.equal(preview.recurring.unallocated, '100.00');
  assert.equal(preview.recurring.shortfall, '0.00');
  assert.equal(preview.recurring.can_apply, true);
  assert.equal(psql('recurring_initialization', "SELECT count(*) FROM budget_operations WHERE operation_type='month_initialization';").stdout.trim(), '0');

  const applied = JSON.parse(psql('recurring_initialization', "SELECT initialize_budget_recurring_defaults('2099-01','50101010-1010-4010-8010-101010101011');").stdout.trim());
  assert.equal(applied.recurring.initialized, true);
  assert.equal(applied.recurring.pending_count, 0);
  assert.equal(applied.funding.total_allocated, '100.00');
  assert.equal(applied.funding.unallocated, '0.00');
  assert.equal(psql('recurring_initialization', "SELECT count(*) FROM budgets WHERE month='2099-01' AND starting_kind='recurring_default';").stdout.trim(), '2');
  assert.equal(psql('recurring_initialization', "SELECT count(*) FROM budgets WHERE month='2099-01' AND category_id=2 AND starting_amount=0;").stdout.trim(), '1');
  assert.equal(psql('recurring_initialization', "SELECT count(*) FROM budgets WHERE month='2099-01' AND category_id=3;").stdout.trim(), '0');
  assert.equal(psql('recurring_initialization', "SELECT count(*) FROM budget_lifecycle_events le JOIN budgets b ON b.id=le.budget_id WHERE b.month='2099-01' AND le.state='active';").stdout.trim(), '2');

  psql('recurring_initialization', 'SELECT set_budget_recurring_default(1,200.00);');
  assert.equal(psql('recurring_initialization', "SELECT starting_amount FROM budgets WHERE month='2099-01' AND category_id=1;").stdout.trim(), '100.00');
});

test('insufficient recurring funding writes no initialization operation, snapshot, or lifecycle event', () => {
  createDatabase('recurring_insufficient');
  psql('recurring_insufficient', fixture());
  applyRecurringFoundation('recurring_insufficient');
  psql('recurring_insufficient', `
    SELECT set_budget_recurring_default(1,200);
    SELECT set_budget_recurring_default(2,100);
    SELECT add_manual_budget_funding('2099-02',250,'Insufficient','50202020-2020-4020-8020-202020202020');
  `);
  const before = psql('recurring_insufficient', `SELECT
    (SELECT count(*) FROM budget_operations),
    (SELECT count(*) FROM budgets),
    (SELECT count(*) FROM budget_lifecycle_events);`).stdout.trim();
  const result = psql('recurring_insufficient', "SELECT initialize_budget_recurring_defaults('2099-02','50202020-2020-4020-8020-202020202021');", true);
  assert.notEqual(result.status, 0);
  assert.match(result.stderr, /required 300.00, available 250.00, shortfall 50.00/i);
  const afterState = psql('recurring_insufficient', `SELECT
    (SELECT count(*) FROM budget_operations),
    (SELECT count(*) FROM budgets),
    (SELECT count(*) FROM budget_lifecycle_events);`).stdout.trim();
  assert.equal(afterState, before);
  const preview = JSON.parse(psql('recurring_insufficient', "SELECT get_funded_budget_month('2099-02');").stdout.trim());
  assert.equal(preview.recurring.shortfall, '50.00');
  assert.equal(preview.recurring.can_apply, false);
});

test('existing active and inactive snapshots take precedence over recurring defaults', () => {
  createDatabase('recurring_precedence');
  psql('recurring_precedence', fixture());
  applyRecurringFoundation('recurring_precedence');
  psql('recurring_precedence', `
    SELECT set_budget_recurring_default(1,500);
    SELECT set_budget_recurring_default(2,400);
    SELECT set_budget_recurring_default(3,300);
    SELECT add_manual_budget_funding('2099-03',1000,'Precedence','50303030-3030-4030-8030-303030303030');
    SELECT establish_funded_budget('2099-03',1,100,'manual','50303030-3030-4030-8030-303030303031');
    SELECT establish_funded_budget('2099-03',2,200,'manual','50303030-3030-4030-8030-303030303032');
    SELECT remove_funded_budget(
      (SELECT budget_id FROM budget_category_state WHERE month='2099-03' AND category_id=2),
      '50303030-3030-4030-8030-303030303033'
    );
    SELECT initialize_budget_recurring_defaults('2099-03','50303030-3030-4030-8030-303030303034');
  `);
  assert.equal(psql('recurring_precedence', "SELECT string_agg(category_id || ':' || starting_amount || ':' || starting_kind,',' ORDER BY category_id) FROM budgets WHERE month='2099-03';").stdout.trim(), '1:100.00:manual,2:200.00:manual,3:300.00:recurring_default');
  assert.equal(psql('recurring_precedence', "SELECT lifecycle_state FROM budget_category_state WHERE month='2099-03' AND category_id=2;").stdout.trim(), 'inactive');
});

test('recurring initialization is idempotent, rejects conflicting keys, and never applies historically', () => {
  createDatabase('recurring_idempotency');
  psql('recurring_idempotency', fixture());
  applyRecurringFoundation('recurring_idempotency');
  psql('recurring_idempotency', `
    SELECT set_budget_recurring_default(1,100);
    SELECT add_manual_budget_funding('2099-04',100,'Idempotency','50404040-4040-4040-8040-404040404040');
    SELECT initialize_budget_recurring_defaults('2099-04','50404040-4040-4040-8040-404040404041');
    SELECT initialize_budget_recurring_defaults('2099-04','50404040-4040-4040-8040-404040404041');
  `);
  assert.equal(psql('recurring_idempotency', "SELECT count(*) FROM budget_operations WHERE operation_type='month_initialization';").stdout.trim(), '1');
  assert.equal(psql('recurring_idempotency', "SELECT count(*) FROM budget_movements WHERE operation_id=(SELECT id FROM budget_operations WHERE operation_type='month_initialization');").stdout.trim(), '0');

  const conflict = psql('recurring_idempotency', "SELECT initialize_budget_recurring_defaults('2099-05','50404040-4040-4040-8040-404040404041');", true);
  assert.notEqual(conflict.status, 0);
  assert.match(conflict.stderr, /different budget operation/i);
  const historical = psql('recurring_idempotency', "SELECT initialize_budget_recurring_defaults('2020-01','50404040-4040-4040-8040-404040404042');", true);
  assert.notEqual(historical.status, 0);
  assert.match(historical.stderr, /historical month/i);
  assert.equal(psql('recurring_idempotency', "SELECT count(*) FROM budget_months WHERE month_start='2020-01-01';").stdout.trim(), '0');
});

test('recurring exact values above 2^53 remain exact through preview and initialization', () => {
  createDatabase('recurring_exact');
  psql('recurring_exact', fixture());
  applyRecurringFoundation('recurring_exact');
  psql('recurring_exact', `
    SELECT set_budget_recurring_default(1,9007199254740993.01);
    SELECT set_budget_recurring_default(2,0.10);
    SELECT set_budget_recurring_default(3,0.20);
    SELECT add_manual_budget_funding('2099-06',9007199254740993.31,'Exact','50606060-6060-4060-8060-606060606060');
  `);
  const preview = JSON.parse(psql('recurring_exact', "SELECT get_funded_budget_month('2099-06');").stdout.trim());
  assert.equal(preview.recurring.required, '9007199254740993.31');
  psql('recurring_exact', "SELECT initialize_budget_recurring_defaults('2099-06','50606060-6060-4060-8060-606060606061');");
  assert.equal(psql('recurring_exact', "SELECT total_allocated || '|' || unallocated FROM budget_month_funding_state WHERE month='2099-06';").stdout.trim(), '9007199254740993.31|0.00');
  assert.equal(psql('recurring_exact', "SELECT string_agg(starting_amount::text,',' ORDER BY category_id) FROM budgets WHERE month='2099-06';").stdout.trim(), '9007199254740993.01,0.10,0.20');
});

test('recurring initialization serializes safely with copy and concurrent funding', async () => {
  createDatabase('recurring_concurrency');
  psql('recurring_concurrency', fixture());
  applyRecurringFoundation('recurring_concurrency');
  psql('recurring_concurrency', `
    SELECT set_budget_recurring_default(2,200);
    SELECT add_manual_budget_funding('2099-07',100,'Source','50707070-7070-4070-8070-707070707070');
    SELECT establish_funded_budget('2099-07',1,100,'manual','50707070-7070-4070-8070-707070707071');
    SELECT add_manual_budget_funding('2099-08',300,'Target','50808080-8080-4080-8080-808080808080');
  `);
  const [copyResult, initializeResult] = await Promise.all([
    psqlAsync('recurring_concurrency', "SELECT copy_funded_budget_month('2099-07','2099-08','50808080-8080-4080-8080-808080808081');"),
    psqlAsync('recurring_concurrency', "SELECT initialize_budget_recurring_defaults('2099-08','50808080-8080-4080-8080-808080808082');"),
  ]);
  assert.equal(copyResult.status, 0, copyResult.stderr);
  assert.equal(initializeResult.status, 0, initializeResult.stderr);
  assert.equal(psql('recurring_concurrency', "SELECT total_allocated || '|' || unallocated FROM budget_month_funding_state WHERE month='2099-08';").stdout.trim(), '300.00|0.00');

  psql('recurring_concurrency', `
    SELECT set_budget_recurring_default(2,NULL);
    SELECT set_budget_recurring_default(3,100);
    SELECT add_manual_budget_funding('2099-09',150,'Initial','50909090-9090-4090-8090-909090909090');
  `);
  const [fundingResult, secondInitialization] = await Promise.all([
    psqlAsync('recurring_concurrency', "SELECT add_manual_budget_funding('2099-09',50,'Concurrent','50909090-9090-4090-8090-909090909091');"),
    psqlAsync('recurring_concurrency', "SELECT initialize_budget_recurring_defaults('2099-09','50909090-9090-4090-8090-909090909092');"),
  ]);
  assert.equal(fundingResult.status, 0, fundingResult.stderr);
  assert.equal(secondInitialization.status, 0, secondInitialization.stderr);
  assert.equal(psql('recurring_concurrency', "SELECT available || '|' || total_allocated || '|' || unallocated FROM budget_month_funding_state WHERE month='2099-09';").stdout.trim(), '200.00|100.00|100.00');
});

test('recurring default ACLs expose only bounded service-role reads and commands', () => {
  createDatabase('recurring_acl');
  psql('recurring_acl', fixture());
  applyRecurringFoundation('recurring_acl');
  const roles = ['public_probe', 'anon', 'authenticated', 'service_role'];
  const sqlArray = (values) => `ARRAY[${values.map((value) => `'${value}'`).join(',')}]::text[]`;

  const tablePrivileges = psql('recurring_acl', `
    SELECT role_name,
      has_table_privilege(role_name,'public.budget_recurring_defaults','SELECT'),
      has_table_privilege(role_name,'public.budget_recurring_defaults','INSERT'),
      has_table_privilege(role_name,'public.budget_recurring_defaults','UPDATE'),
      has_table_privilege(role_name,'public.budget_recurring_defaults','DELETE'),
      has_table_privilege(role_name,'public.budget_recurring_defaults_read','SELECT')
    FROM unnest(${sqlArray(roles)}) role_name ORDER BY role_name;
  `).stdout.trim().split('\n');
  for (const row of tablePrivileges) {
    const [role, read, insert, update, remove, viewRead] = row.split('|');
    assert.deepEqual([insert, update, remove], ['f', 'f', 'f']);
    assert.equal(read, role === 'service_role' ? 't' : 'f');
    assert.equal(viewRead, role === 'service_role' ? 't' : 'f');
  }

  for (const signature of [
    'get_funded_budget_month(text)',
    'set_budget_recurring_default(bigint,numeric)',
    'initialize_budget_recurring_defaults(text,uuid,text)',
  ]) {
    const privileges = psql('recurring_acl', `SELECT role_name,
      has_function_privilege(role_name,'public.${signature}','EXECUTE')
      FROM unnest(${sqlArray(roles)}) role_name ORDER BY role_name;`).stdout.trim().split('\n');
    for (const row of privileges) {
      const [role, execute] = row.split('|');
      assert.equal(execute, role === 'service_role' ? 't' : 'f');
    }
  }

  for (const signature of [
    'validate_budget_recurring_default()',
    'prevent_category_type_with_recurring_default()',
    'get_budget_recurring_preview(text)',
    'get_funded_budget_month_foundation(text)',
  ]) {
    const privileges = psql('recurring_acl', `SELECT bool_or(
      has_function_privilege(role_name,'public.${signature}','EXECUTE'))
      FROM unnest(${sqlArray(roles)}) role_name;`).stdout.trim();
    assert.equal(privileges, 'f', signature);
  }

  psql('recurring_acl', `SET ROLE service_role;
    SELECT set_budget_recurring_default(1,100);
    SELECT amount_text FROM budget_recurring_defaults_read WHERE category_id=1;
    SELECT add_manual_budget_funding('2099-10',100,'ACL','51010101-0101-4101-8101-010101010101');
    SELECT initialize_budget_recurring_defaults('2099-10','51010101-0101-4101-8101-010101010102');
    SELECT get_funded_budget_month('2099-10');
    RESET ROLE;
  `);
  for (const role of ['public_probe', 'anon', 'authenticated']) {
    const directRead = psql('recurring_acl', `SET ROLE ${role}; SELECT get_funded_budget_month('2099-10');`, true);
    assert.notEqual(directRead.status, 0, `${role} unexpectedly executed get_funded_budget_month(text)`);
    assert.match(directRead.stderr, /permission denied/i);
  }
  const directWrite = psql('recurring_acl', "SET ROLE service_role; UPDATE budget_recurring_defaults SET amount=200;", true);
  assert.notEqual(directWrite.status, 0);
  assert.match(directWrite.stderr, /permission denied/i);
});
