const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

const { normalizeLoanHandling } = require('../utils/manualLoanPayment');

const migration = fs.readFileSync(path.join(
  __dirname, '..', 'migrations', '015_manual_loan_repayments.sql',
), 'utf8');
const schema = fs.readFileSync(path.join(__dirname, '..', 'full_schema.sql'), 'utf8');

const getLatestFunction = (sql, name) => (
  sql.match(new RegExp(
    `CREATE OR REPLACE FUNCTION public\\.${name}\\([\\s\\S]*?\\n\\$\\$;`,
    'g',
  ))?.at(-1) || ''
);

const applyManualSchedule = ({ nextScheduledDueDate }) => nextScheduledDueDate;

test('manual repayment split is normalized with exact cent arithmetic', () => {
  assert.deepEqual(normalizeLoanHandling({
    transaction: { loan_id: 1, total_amount: '1611.58' },
    loanHandling: {
      mode: 'repayment',
      principal_amount: '1103.36',
      interest_amount: '508.22',
      other_amount: '0',
      next_scheduled_due_date: '2026-09-15',
    },
  }), {
    mode: 'repayment',
    payment: {
      principal_amount: '1103.36',
      interest_amount: '508.22',
      other_amount: '0.00',
      next_scheduled_due_date: '2026-09-15',
    },
  });
  assert.throws(() => normalizeLoanHandling({
    transaction: { loan_id: 1, total_amount: '1611.58' },
    loanHandling: {
      mode: 'repayment',
      principal_amount: '1103.36',
      interest_amount: '508.21',
      other_amount: '0',
      next_scheduled_due_date: '2026-09-15',
    },
  }), /do not reconcile/);
});

test('loan payment IDs preserve and validate the existing identity allocator', () => {
  assert.match(migration, /LOCK TABLE public\.loan_payments IN ACCESS EXCLUSIVE MODE/);
  assert.match(migration, /c\.is_identity[\s\S]*v_is_identity IS DISTINCT FROM 'YES'/);
  assert.match(migration, /pg_catalog\.pg_get_serial_sequence\(\s*'public\.loan_payments',\s*'id'\s*\)/);
  assert.match(migration, /v_identity_sequence IS NULL[\s\S]*RAISE EXCEPTION/);
  assert.match(migration, /SELECT coalesce\(max\(lp\.id\), 0\) \+ 1[\s\S]*INTO v_next_id/);
  assert.match(migration, /pg_catalog\.setval\(\s*v_identity_sequence::regclass,\s*v_next_id,\s*false\s*\)/);
  assert.doesNotMatch(migration, /UPDATE\s+public\.loan_payments\s+SET\s+id/i);
  assert.doesNotMatch(migration, /CREATE\s+SEQUENCE/i);
  assert.doesNotMatch(migration, /ALTER\s+SEQUENCE[\s\S]*OWNED\s+BY/i);
  assert.doesNotMatch(migration, /ALTER\s+COLUMN\s+id\s+SET\s+DEFAULT/i);
  assert.doesNotMatch(migration, /GRANT[\s\S]*ON\s+SEQUENCE\s+public\.loan_payments_id_seq/i);

  assert.match(schema, /id\s+BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY/);
  assert.doesNotMatch(schema, /id\s+BIGINT[^\n]*DEFAULT\s+nextval/i);
  assert.doesNotMatch(schema, /ALTER\s+SEQUENCE\s+loan_payments_id_seq\s+OWNED\s+BY/i);
  const syncFunction = getLatestFunction(migration, 'sync_manual_loan_payment_from_transaction');
  assert.doesNotMatch(syncFunction, /max\(id\)\s*\+\s*1/i);
  assert.match(syncFunction, /INSERT INTO public\.loan_payments \(\s*loan_id, transaction_id/);
  assert.doesNotMatch(syncFunction, /INSERT INTO public\.loan_payments \(\s*id,/);
});

test('identity synchronization is idempotent and leaves existing IDs unchanged', () => {
  const existingIds = [1, 60, 187, 248];
  const synchronize = (ids) => ({
    lastValue: Math.max(0, ...ids) + 1,
    isCalled: false,
  });
  const nextGeneratedValue = ({ lastValue, isCalled }) => (
    isCalled ? lastValue + 1 : lastValue
  );

  const firstSync = synchronize(existingIds);
  assert.deepEqual(firstSync, { lastValue: 249, isCalled: false });
  assert.equal(nextGeneratedValue(firstSync), 249);
  assert.deepEqual(synchronize(existingIds), firstSync);
  assert.deepEqual(existingIds, [1, 60, 187, 248]);
});

test('omitted or explicit link-only handling can never manufacture accounting data', () => {
  assert.deepEqual(normalizeLoanHandling({
    transaction: { loan_id: 1, total_amount: '5000.00' },
  }), { mode: 'link_only', payment: null });
  assert.deepEqual(normalizeLoanHandling({
    transaction: { loan_id: 1, total_amount: '5000.00' },
    loanHandling: { mode: 'link_only' },
  }), { mode: 'link_only', payment: null });
});

test('migration owns create/update repayment atomicity and authoritative installment allocation', () => {
  for (const sql of [migration, schema]) {
    assert.match(sql, /CREATE OR REPLACE FUNCTION public\.create_transaction_with_manual_loan_payment\(\s*p_transaction JSONB,\s*p_loan_payment JSONB/);
    assert.match(sql, /CREATE OR REPLACE FUNCTION public\.update_transaction_with_manual_loan_payment\(\s*p_transaction_id BIGINT,\s*p_transaction JSONB,\s*p_loan_payment JSONB/);
    assert.match(sql, /PERFORM public\.sync_manual_loan_payment_from_transaction\([\s\S]*p_loan_payment/);
    assert.match(sql, /v_installment_number := v_covered_without_existing \+ 1/);
    assert.match(sql, /source_kind[\s\S]*'manual'[\s\S]*'installment', 1, v_other, 0/);
    assert.match(sql, /Principal component exceeds outstanding principal/);
    assert.match(sql, /FOR UPDATE/);
  }
});

test('manual schedule applies the submitted bank date regardless of posting date', () => {
  for (const postingDate of ['2026-08-15', '2026-08-16', '2026-08-17']) {
    assert.equal(
      applyManualSchedule({
        scheduledDueDate: '2026-08-16',
        nextScheduledDueDate: '2026-09-15',
        postingDate,
      }),
      '2026-09-15',
    );
  }

  for (const sql of [migration, schema]) {
    const syncFunction = getLatestFunction(sql, 'sync_manual_loan_payment_from_transaction');
    assert.match(sql, /scheduled_due_date\s+DATE/);
    assert.match(sql, /next_scheduled_due_date\s+DATE/);
    assert.match(syncFunction, /v_scheduled_due_date := v_loan\.next_payment_date/);
    assert.match(syncFunction, /v_next_scheduled_due_date := nullif\([\s\S]*p_loan_payment->>'next_scheduled_due_date'/);
    assert.match(syncFunction, /ELSE v_next_scheduled_due_date/);
    assert.doesNotMatch(syncFunction, /\(v_scheduled_due_date \+ INTERVAL '1 month'\)::date/);
    assert.doesNotMatch(syncFunction, /\(v_payment_date \+ INTERVAL '1 month'\)::date/);
    assert.doesNotMatch(sql, /INTERVAL '30 days'/i);
  }
});

test('D-E: split and payment-date edits retain one immutable schedule anchor', () => {
  for (const sql of [migration, schema]) {
    const syncFunction = getLatestFunction(sql, 'sync_manual_loan_payment_from_transaction');
    assert.match(syncFunction, /v_existing\.loan_id = v_loan\.id[\s\S]*v_scheduled_due_date := v_existing\.scheduled_due_date/);
    assert.match(syncFunction, /ELSE v_existing\.next_scheduled_due_date/);
    assert.match(syncFunction, /scheduled_due_date = v_scheduled_due_date/);
    assert.match(syncFunction, /next_scheduled_due_date = v_next_scheduled_due_date/);
    assert.doesNotMatch(syncFunction, /v_scheduled_due_date := v_payment_date/);
  }
});

test('editing the submitted next date intentionally updates only the latest transition', () => {
  for (const sql of [migration, schema]) {
    const syncFunction = getLatestFunction(sql, 'sync_manual_loan_payment_from_transaction');
    assert.match(syncFunction, /p_loan_payment \? 'next_scheduled_due_date'[\s\S]*p_loan_payment->>'next_scheduled_due_date'/);
    assert.match(syncFunction, /v_has_later_covered[\s\S]*v_next_scheduled_due_date IS DISTINCT FROM v_existing\.next_scheduled_due_date[\s\S]*Cannot change the schedule transition/);
    assert.match(syncFunction, /SET next_payment_date = CASE[\s\S]*ELSE v_next_scheduled_due_date/);
  }
});

test('F-G: unlink and delete restore the exact prior scheduled due date', () => {
  for (const sql of [migration, schema]) {
    const syncFunction = getLatestFunction(sql, 'sync_manual_loan_payment_from_transaction');
    const deleteFunction = getLatestFunction(sql, 'delete_transaction_with_loan_payment');
    for (const functionSql of [syncFunction, deleteFunction]) {
      assert.match(functionSql, /v_old_scheduled_due_date := v_existing\.scheduled_due_date/);
      assert.match(functionSql, /ELSE v_old_scheduled_due_date/);
      assert.match(functionSql, /auto_payment_enabled_before/);
      assert.doesNotMatch(functionSql, /SET next_payment_date = v_existing\.payment_date/);
    }
  }
});

test('H: link-only to repayment captures and advances the current schedule once', () => {
  for (const sql of [migration, schema]) {
    const syncFunction = getLatestFunction(sql, 'sync_manual_loan_payment_from_transaction');
    assert.match(syncFunction, /IF v_existing\.id IS NULL THEN[\s\S]*INSERT INTO public\.loan_payments/);
    assert.match(syncFunction, /v_scheduled_due_date := v_loan\.next_payment_date/);
    assert.match(syncFunction, /IF v_existing\.id IS NULL[\s\S]*ELSE v_next_scheduled_due_date/);
  }
});

test('I: moving a repayment restores loan A and advances loan B from separate anchors', () => {
  for (const sql of [migration, schema]) {
    const syncFunction = getLatestFunction(sql, 'sync_manual_loan_payment_from_transaction');
    assert.match(syncFunction, /v_old_scheduled_due_date := CASE[\s\S]*v_existing\.scheduled_due_date/);
    assert.match(syncFunction, /v_old_loan_id IS DISTINCT FROM v_loan\.id[\s\S]*ELSE v_old_scheduled_due_date/);
    assert.match(syncFunction, /destination side of a move[\s\S]*v_scheduled_due_date := v_loan\.next_payment_date/);
    assert.match(syncFunction, /v_old_loan_id IS DISTINCT FROM v_loan\.id[\s\S]*ELSE v_next_scheduled_due_date/);
  }
});

test('final repayment keeps a reversible due-date and automation snapshot', () => {
  for (const sql of [migration, schema]) {
    const syncFunction = getLatestFunction(sql, 'sync_manual_loan_payment_from_transaction');
    assert.match(sql, /auto_payment_enabled_before\s+BOOLEAN/);
    assert.match(syncFunction, /WHEN current_balance <= 0\.005 OR remaining_installments <= 0 THEN NULL/);
    assert.match(syncFunction, /ELSE v_old_scheduled_due_date/);
    assert.match(syncFunction, /coalesce\(v_old_auto_payment_enabled, auto_payment_enabled\)/);
  }
});

test('manual repayment deletion removes accounting before the ledger transaction', () => {
  for (const sql of [migration, schema]) {
    const deleteFunction = getLatestFunction(sql, 'delete_transaction_with_loan_payment');
    assert.match(deleteFunction, /source_kind NOT IN \('manual', 'existing_transaction'\)/);
    assert.ok(
      deleteFunction.indexOf('DELETE FROM public.loan_payments')
        < deleteFunction.indexOf('DELETE FROM public.transactions'),
    );
    assert.match(deleteFunction, /DELETE FROM public\.loan_payments[\s\S]*ELSE v_old_scheduled_due_date/);
  }
});

test('moving a repayment locks both loans and refreshes both through the payment trigger', () => {
  for (const sql of [migration, schema]) {
    assert.match(sql, /WHERE id IN \(v_old_transaction\.loan_id, v_new_loan_id\)[\s\S]*ORDER BY id[\s\S]*FOR UPDATE/);
    assert.match(sql, /UPDATE public\.loan_payments[\s\S]*SET loan_id = v_loan\.id/);
    assert.match(sql, /v_old_loan_id IS DISTINCT FROM v_loan\.id[\s\S]*ELSE v_old_scheduled_due_date/);
  }
  assert.match(schema, /CREATE TRIGGER on_loan_payment_change[\s\S]*AFTER INSERT OR UPDATE OR DELETE/);
});

test('manual migration leaves the automatic due-payment implementation untouched', () => {
  assert.doesNotMatch(migration, /CREATE OR REPLACE FUNCTION public\.create_due_loan_payment/);
  assert.match(schema, /'generated'[\s\S]*'installment', 1, 0, 0/);
});

test('new RPC exposure is narrow and the synchronization helper stays internal', () => {
  assert.match(migration, /REVOKE ALL ON FUNCTION public\.sync_manual_loan_payment_from_transaction\(BIGINT, JSONB\)[\s\S]*FROM PUBLIC, anon, authenticated, service_role/);
  assert.match(migration, /GRANT EXECUTE ON FUNCTION public\.create_transaction_with_manual_loan_payment\(JSONB, JSONB\)[\s\S]*TO service_role/);
  assert.match(migration, /GRANT EXECUTE ON FUNCTION public\.update_transaction_with_manual_loan_payment\(BIGINT, JSONB, JSONB\)[\s\S]*TO service_role/);
  assert.doesNotMatch(migration, /GRANT EXECUTE ON ALL FUNCTIONS/i);
});
