import { beforeEach, expect, it, vi } from 'vitest';
import { render, screen, waitFor, within } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import BudgetSavingsTransfers from './BudgetSavingsTransfers';
import * as api from '../../services/api';
vi.mock('../../services/api', () => Object.fromEntries(['applyBudgetMonthClose','applySavingsSurplus','getPaymentSources','getSavingsAccounts','getSavingsSurplusPreview','getSettingsCategories','reverseSavingsSurplus'].map(k => [k,vi.fn()])));
const state={categories:[{category_id:100,is_active_budget:true,remaining:'300.00',categories:{name:'מזון'}}],savings_transfer_history:[]};
const preview={fingerprint:'abcdef',category_id:'100',category_name:'מזון',account_name:'חיסכון בדיקה',amount:'300.00',eligible_surplus:'300.00',funded_before:'1000.00',funded_after:'700.00',savings_before:'0.00',savings_after:'300.00',payment_source_name:'בנק',cash_date:'2026-09-13'};
beforeEach(()=>{vi.clearAllMocks();api.getSavingsAccounts.mockResolvedValue({data:[{account_id:'1',name:'חיסכון בדיקה',status:'active'},{account_id:'2',name:'ארכיון',status:'archived'}]});api.getPaymentSources.mockResolvedValue({data:[{id:1,name:'בנק',is_active:true}]});api.getSettingsCategories.mockResolvedValue({data:[{id:100,savings_account_id:'1'}]});api.getSavingsSurplusPreview.mockResolvedValue({data:preview});api.applySavingsSurplus.mockResolvedValue({data:{affected_account_ids:['1']}});});
async function fill(){await userEvent.click(screen.getByRole('button',{name:'העברת עודף לחיסכון'}));const d=screen.getByRole('dialog');await waitFor(()=>expect(within(d).getByRole('button',{name:'סקירת ההעברה'})).toBeEnabled());await userEvent.selectOptions(within(d).getByLabelText('קטגוריית מקור'),'100');await userEvent.selectOptions(within(d).getByLabelText('אמצעי תשלום של ההוצאה'),'1');return d;}
it('previews exact values, requires confirmation and posts one complete command',async()=>{
 const onApplied=vi.fn();render(<BudgetSavingsTransfers month="2026-09" state={state} onApplied={onApplied}/>);const d=await fill();expect(within(d).getByLabelText('סכום להעברה')).toHaveValue('300.00');expect(within(d).getByLabelText('חשבון חיסכון יעד')).toHaveValue('1');await userEvent.click(within(d).getByText('סקירת ההעברה'));await screen.findByText('מזון → חיסכון בדיקה');expect(within(d).getByText('אישור הפעולה')).toBeDisabled();await userEvent.click(within(d).getByRole('checkbox'));await userEvent.dblClick(within(d).getByText('אישור הפעולה'));await waitFor(()=>expect(onApplied).toHaveBeenCalledTimes(1));expect(api.applySavingsSurplus).toHaveBeenCalledTimes(1);expect(api.applySavingsSurplus.mock.calls[0][0].command).toMatchObject({amount:'300.00',account_id:'1',category_id:'100',payment_source_id:'1',source_month:'2026-09'});
});
it('changing an input invalidates the preview and cancellation does not write',async()=>{
 render(<BudgetSavingsTransfers month="2026-09" state={state} onApplied={vi.fn()}/>);const d=await fill();await userEvent.click(within(d).getByText('סקירת ההעברה'));await screen.findByText('מזון → חיסכון בדיקה');await userEvent.type(within(d).getByLabelText('סכום להעברה'),'1');expect(within(d).queryByText('אישור הפעולה')).not.toBeInTheDocument();await userEvent.click(within(d).getByText('חזרה'));expect(api.applySavingsSurplus).not.toHaveBeenCalled();
});
it('invalid archived destination remains visible and server rejection is actionable',async()=>{
 api.getSettingsCategories.mockResolvedValue({data:[{id:100,savings_account_id:'2'}]});api.getSavingsSurplusPreview.mockRejectedValue({response:{data:{error:'החשבון בארכיון. בחרו חשבון פעיל.'}}});render(<BudgetSavingsTransfers month="2026-09" state={state} onApplied={vi.fn()}/>);const d=await fill();expect(within(d).getByLabelText('חשבון חיסכון יעד')).toHaveValue('2');await userEvent.click(within(d).getByText('סקירת ההעברה'));await screen.findByText('החשבון בארכיון. בחרו חשבון פעיל.');expect(api.applySavingsSurplus).not.toHaveBeenCalled();
});
it('stale execution clears confirmation and requests current Budget state',async()=>{
 api.applySavingsSurplus.mockRejectedValue({response:{status:409,data:{error:'הנתונים השתנו'}}});const onApplied=vi.fn();render(<BudgetSavingsTransfers month="2026-09" state={state} onApplied={onApplied}/>);const d=await fill();await userEvent.click(within(d).getByText('סקירת ההעברה'));await screen.findByText('מזון → חיסכון בדיקה');await userEvent.click(within(d).getByRole('checkbox'));await userEvent.click(within(d).getByText('אישור הפעולה'));await screen.findByText('הנתונים השתנו');expect(onApplied).toHaveBeenCalledOnce();expect(within(d).queryByText('אישור הפעולה')).not.toBeInTheDocument();
});
it('whole reversal uses Budget provenance, a reason and explicit confirmation',async()=>{
 api.reverseSavingsSurplus.mockResolvedValue({data:{}});render(<BudgetSavingsTransfers month="2026-09" state={{...state,savings_transfer_history:[{...preview,operation_id:'20',source_month:'2026-09',reversible:true}]}} onApplied={vi.fn()}/>);await userEvent.click(screen.getByText('ביטול מלא'));const d=screen.getByRole('dialog');await userEvent.type(within(d).getByLabelText(/סיבת הביטול/),'תיקון הסכום');await userEvent.click(within(d).getByRole('checkbox'));await userEvent.click(within(d).getByText('אישור הפעולה'));await waitFor(()=>expect(api.reverseSavingsSurplus).toHaveBeenCalledWith('20',expect.objectContaining({reason:'תיקון הסכום',preview_fingerprint:'abcdef'})));expect(api.applySavingsSurplus).not.toHaveBeenCalled();
});
it('month close previews cumulative account effects and submits every confirmed candidate together',async()=>{
 const closePreview={fingerprint:'close',categories:[{category_id:'100',eligible_unused:'300.00',status:'ready',policy:'savings_account',savings_account:{id:'1'}},{category_id:'101',eligible_unused:'50.00',status:'ready',policy:'savings_account',savings_account:{id:'1'}}]};
 api.getSavingsSurplusPreview.mockImplementation(async c=>({data:{...preview,category_id:c.category_id,amount:c.amount,account_id:'1'}}));api.applyBudgetMonthClose.mockResolvedValue({data:{}});
 render(<BudgetSavingsTransfers month="2026-08" state={state} closePreview={closePreview} onCloseReview={vi.fn()} onApplied={vi.fn()}/>);
 const d=await screen.findByRole('dialog');await waitFor(()=>expect(within(d).getByText('סקירת ההעברה')).toBeEnabled());await userEvent.selectOptions(within(d).getByLabelText('אמצעי תשלום של ההוצאה'),'1');await userEvent.click(within(d).getByText('סקירת ההעברה'));await waitFor(()=>expect(d).toHaveTextContent('350'));await userEvent.click(within(d).getByRole('checkbox'));await userEvent.click(within(d).getByText('אישור הפעולה'));await waitFor(()=>expect(api.applyBudgetMonthClose).toHaveBeenCalledOnce());expect(api.applyBudgetMonthClose.mock.calls[0][0].cash_confirmations.map(c=>c.amount)).toEqual(['300.00','50.00']);expect(api.applySavingsSurplus).not.toHaveBeenCalled();
});
