// Print the pinned SQL normalizer for migration 036. Unicode upgrades require a
// deliberate normalization-version decision, not automatic production regeneration.
// node server/test/helpers/apyUnicode.js (stdout only, never changes schema/files).
const escape = n => '\\' + (n > 65535 ? '+' + n.toString(16).padStart(6, '0') : n.toString(16).padStart(4, '0'));
const literal = value => [...value].map(c => escape(c.codePointAt(0))).join('');
const ranges = [];let first = null, last = null, upper = '', lower = '', expanded = [];
for (let n = 0; n <= 0x10ffff; n++) {
  const c = String.fromCodePoint(n), l = c.toLowerCase();
  if (c !== l) { if ([...l].length === 1) { upper += c; lower += l; } else expanded.push([c,l]); }
  if (/[\p{P}\p{S}\s]/u.test(c)) { if (first === null) first = n; last = n; }
  else if (first !== null) { ranges.push([first,last]); first = null; }
}
if (first !== null) ranges.push([first,last]);
const separators = '[' + ranges.map(([a,b]) => escape(a) + (a === b ? '' : '-' + escape(b))).join('') + ']+';
let fold = `translate(regexp_replace(normalize(p,NFKC),U&'[\\061C\\200E\\200F\\202A-\\202E\\2066-\\2069]','','g'),U&'${literal(upper)}',U&'${literal(lower)}')`;
for (const [from,to] of expanded) fold = `replace(${fold},U&'${literal(from)}',U&'${literal(to)}')`;
process.stdout.write(`CREATE OR REPLACE FUNCTION public.apy_merchant(p TEXT) RETURNS TEXT LANGUAGE sql IMMUTABLE SET search_path=pg_catalog,public,pg_temp AS $$\n -- Unicode ${process.versions.unicode}, normalization v1: invariant per-codepoint lowercase and P/S/whitespace.\n -- Generated by server/test/helpers/apyUnicode.js; avoids locale-sensitive loss of combining marks.\n SELECT btrim(regexp_replace(${fold},U&'${separators}',' ','g'));\n$$;`);
