-- Migration 008: separate loan accounting from the cash transaction ledger.
--
-- Existing loans stay in `legacy` mode and retain the historical transaction
-- total/count summary behavior. A loan is moved to `loan_payments` only by an
-- explicit migration/repair or by the server-owned new-loan creation path.

BEGIN;

ALTER TABLE public.loans
  ADD COLUMN IF NOT EXISTS calculation_mode TEXT NOT NULL DEFAULT 'legacy',
  ADD COLUMN IF NOT EXISTS next_payment_date DATE,
  ADD COLUMN IF NOT EXISTS payment_source_id BIGINT REFERENCES public.payment_sources(id);

ALTER TABLE public.loans
  DROP CONSTRAINT IF EXISTS loans_calculation_mode_check;

ALTER TABLE public.loans
  ADD CONSTRAINT loans_calculation_mode_check
  CHECK (calculation_mode IN ('legacy', 'loan_payments'));

CREATE TABLE IF NOT EXISTS public.loan_payments (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  loan_id               BIGINT NOT NULL REFERENCES public.loans(id) ON DELETE CASCADE,
  transaction_id        BIGINT REFERENCES public.transactions(id) ON DELETE SET NULL,
  installment_number    INTEGER NOT NULL CHECK (installment_number > 0),
  payment_date          DATE NOT NULL,
  payment_amount        NUMERIC(18, 2) NOT NULL CHECK (payment_amount >= 0),
  principal_amount      NUMERIC(24, 10) NOT NULL CHECK (principal_amount >= 0),
  interest_amount       NUMERIC(24, 10) NOT NULL CHECK (interest_amount >= 0),
  annual_interest_rate  NUMERIC(12, 6) CHECK (
    annual_interest_rate IS NULL OR annual_interest_rate >= 0
  ),
  source_kind           TEXT NOT NULL CHECK (
    source_kind IN ('existing_transaction', 'reconstructed', 'manual')
  ),
  notes                 TEXT,
  created_at            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT loan_payments_loan_installment_key UNIQUE (loan_id, installment_number),
  CONSTRAINT loan_payments_transaction_key UNIQUE (transaction_id),
  CONSTRAINT loan_payments_components_reconcile CHECK (
    abs(payment_amount - principal_amount - interest_amount) <= 0.00000001
  )
);

CREATE INDEX IF NOT EXISTS idx_loan_payments_loan_date
  ON public.loan_payments (loan_id, payment_date, installment_number);

ALTER TABLE public.loan_payments ENABLE ROW LEVEL SECURITY;

-- One authoritative summary path. SECURITY DEFINER is used because both
-- table triggers and the service-role RPC below call this function. Pinning
-- search_path and schema-qualifying every relation prevents object shadowing.
CREATE OR REPLACE FUNCTION public.refresh_loan_summary(p_loan_id BIGINT)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_loan public.loans%ROWTYPE;
  v_payment_count BIGINT := 0;
  v_paid_principal NUMERIC := 0;
  v_cash_total NUMERIC := 0;
  v_balance NUMERIC := 0;
  v_remaining INTEGER := 0;
BEGIN
  IF p_loan_id IS NULL THEN
    RETURN;
  END IF;

  SELECT *
  INTO v_loan
  FROM public.loans
  WHERE id = p_loan_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RETURN;
  END IF;

  IF v_loan.calculation_mode = 'loan_payments' THEN
    SELECT
      count(*),
      coalesce(sum(principal_amount), 0)
    INTO v_payment_count, v_paid_principal
    FROM public.loan_payments
    WHERE loan_id = p_loan_id;

    -- Components remain high precision in loan_payments. The displayed/stored
    -- loan summary is monetary and therefore rounded once to agorot here.
    v_balance := round(greatest(v_loan.original_amount - v_paid_principal, 0), 2);
    v_remaining := greatest(
      coalesce(v_loan.total_installments, 0) - v_payment_count,
      0
    )::integer;

    UPDATE public.loans
    SET
      current_balance = v_balance,
      remaining_installments = v_remaining,
      status = CASE
        -- Debt status is principal-based. Exhausting the expected installment
        -- count does not forgive a residual balance.
        WHEN v_balance <= 0.005 THEN 'paid'
        -- Refreshing an in-arrears loan must not silently cure a deliberate
        -- defaulted status merely because its principal is still positive.
        WHEN v_loan.status = 'defaulted' THEN 'defaulted'
        ELSE 'active'
      END
    WHERE id = p_loan_id;
  ELSE
    -- Compatibility mode: intentionally preserve the old live behavior for
    -- loans that have not yet been audited/migrated.
    SELECT count(*), coalesce(sum(total_amount), 0)
    INTO v_payment_count, v_cash_total
    FROM public.transactions
    WHERE loan_id = p_loan_id;

    UPDATE public.loans
    SET
      current_balance = v_loan.original_amount - v_cash_total,
      remaining_installments = coalesce(v_loan.total_installments, 0) - v_payment_count
    WHERE id = p_loan_id;
  END IF;
END;
$$;

-- Preserve the existing trigger/function identity so the live
-- on_transaction_change trigger and repository schema converge. In
-- loan_payments mode this refresh reads principal components only; transaction
-- cash amounts can no longer reduce principal directly.
CREATE OR REPLACE FUNCTION public.recalculate_loan_status()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    PERFORM public.refresh_loan_summary(NEW.loan_id);
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    PERFORM public.refresh_loan_summary(OLD.loan_id);
    RETURN OLD;
  END IF;

  IF OLD.loan_id IS DISTINCT FROM NEW.loan_id THEN
    PERFORM public.refresh_loan_summary(OLD.loan_id);
  END IF;
  PERFORM public.refresh_loan_summary(NEW.loan_id);
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_transaction_change ON public.transactions;
CREATE TRIGGER on_transaction_change
AFTER INSERT OR UPDATE OR DELETE ON public.transactions
FOR EACH ROW
EXECUTE FUNCTION public.recalculate_loan_status();

CREATE OR REPLACE FUNCTION public.refresh_loan_summary_from_payment()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    PERFORM public.refresh_loan_summary(NEW.loan_id);
    RETURN NEW;
  ELSIF TG_OP = 'DELETE' THEN
    PERFORM public.refresh_loan_summary(OLD.loan_id);
    RETURN OLD;
  END IF;

  IF OLD.loan_id IS DISTINCT FROM NEW.loan_id THEN
    PERFORM public.refresh_loan_summary(OLD.loan_id);
  END IF;
  PERFORM public.refresh_loan_summary(NEW.loan_id);
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_loan_payment_change ON public.loan_payments;
CREATE TRIGGER on_loan_payment_change
AFTER INSERT OR UPDATE OR DELETE ON public.loan_payments
FOR EACH ROW
EXECUTE FUNCTION public.refresh_loan_summary_from_payment();

-- Internal accounting primitive. It is deliberately not granted to the API
-- role: application writes enter through the atomic create/update RPCs below.
-- PostgreSQL owns this calculation because the loan row must remain locked
-- while the opening balance and next installment are selected. Fixed loans use
-- the provider-validated monthly-cent rule; variable loans retain ten decimals.
CREATE OR REPLACE FUNCTION public.sync_loan_payment_from_transaction(
  p_transaction_id BIGINT,
  p_record_loan_payment BOOLEAN DEFAULT true
)
RETURNS public.loan_payments
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_transaction public.transactions%ROWTYPE;
  v_loan public.loans%ROWTYPE;
  v_existing public.loan_payments%ROWTYPE;
  v_result public.loan_payments%ROWTYPE;
  v_installment_number INTEGER;
  v_opening_principal NUMERIC;
  v_payment NUMERIC;
  v_interest NUMERIC;
  v_principal NUMERIC;
BEGIN
  SELECT *
  INTO v_transaction
  FROM public.transactions
  WHERE id = p_transaction_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Transaction % does not exist', p_transaction_id;
  END IF;

  SELECT *
  INTO v_existing
  FROM public.loan_payments
  WHERE transaction_id = p_transaction_id
  FOR UPDATE;

  IF v_existing.id IS NOT NULL
    AND v_existing.source_kind <> 'existing_transaction' THEN
    RAISE EXCEPTION
      'Transaction % is linked to a % loan payment and cannot be synchronized automatically',
      p_transaction_id, v_existing.source_kind;
  END IF;

  IF NOT p_record_loan_payment OR v_transaction.loan_id IS NULL THEN
    IF v_existing.id IS NOT NULL THEN
      DELETE FROM public.loan_payments
      WHERE id = v_existing.id
      RETURNING * INTO v_result;
    END IF;
    RETURN v_result;
  END IF;

  SELECT *
  INTO v_loan
  FROM public.loans
  WHERE id = v_transaction.loan_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Loan % does not exist', v_transaction.loan_id;
  END IF;

  IF v_loan.calculation_mode <> 'loan_payments' THEN
    -- A stale accounting row must not survive a move back to a legacy loan.
    IF v_existing.id IS NOT NULL THEN
      DELETE FROM public.loan_payments
      WHERE id = v_existing.id
      RETURNING * INTO v_result;
    END IF;
    RETURN v_result;
  END IF;

  IF v_transaction.installment_number IS NOT NULL
    AND v_transaction.installment_number > 0 THEN
    v_installment_number := v_transaction.installment_number;
  ELSIF v_existing.id IS NOT NULL AND v_existing.loan_id = v_loan.id THEN
    v_installment_number := v_existing.installment_number;
  ELSE
    SELECT coalesce(max(installment_number), 0) + 1
    INTO v_installment_number
    FROM public.loan_payments
    WHERE loan_id = v_loan.id;
  END IF;

  IF v_loan.total_installments IS NOT NULL
    AND v_installment_number > v_loan.total_installments THEN
    RAISE EXCEPTION
      'Installment % exceeds total installments % for loan %',
      v_installment_number, v_loan.total_installments, v_loan.id;
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.loan_payments later
    WHERE later.loan_id = v_loan.id
      AND later.installment_number > v_installment_number
      AND later.id IS DISTINCT FROM v_existing.id
  ) THEN
    RAISE EXCEPTION
      'Cannot insert or reprice installment % while later loan payments exist',
      v_installment_number;
  END IF;

  SELECT greatest(
    v_loan.original_amount - coalesce(sum(principal_amount), 0),
    0
  )
  INTO v_opening_principal
  FROM public.loan_payments
  WHERE loan_id = v_loan.id
    AND installment_number < v_installment_number
    AND id IS DISTINCT FROM v_existing.id;

  v_payment := round(abs(v_transaction.total_amount), 2);
  IF v_loan.interest_type = 'fixed' THEN
    v_interest := round(
      v_opening_principal * coalesce(v_loan.interest_rate, 0) / 1200,
      2
    );
  ELSE
    v_interest := round(
      v_opening_principal * coalesce(v_loan.interest_rate, 0) / 1200,
      10
    );
  END IF;

  v_principal := round(v_payment - v_interest, 10);
  IF v_principal < 0 THEN
    RAISE EXCEPTION
      'Loan payment % is less than calculated interest % for transaction %',
      v_payment, v_interest, p_transaction_id;
  END IF;

  IF v_principal > v_opening_principal THEN
    v_principal := round(v_opening_principal, 10);
    v_interest := round(v_payment - v_principal, 10);
  END IF;

  INSERT INTO public.loan_payments (
    loan_id,
    transaction_id,
    installment_number,
    payment_date,
    payment_amount,
    principal_amount,
    interest_amount,
    annual_interest_rate,
    source_kind,
    notes
  ) VALUES (
    v_loan.id,
    v_transaction.id,
    v_installment_number,
    v_transaction.charge_date,
    v_payment,
    v_principal,
    v_interest,
    v_loan.interest_rate,
    'existing_transaction',
    'Generated from an actual loan-linked ledger transaction'
  )
  ON CONFLICT (transaction_id) DO UPDATE
  SET
    loan_id = EXCLUDED.loan_id,
    installment_number = EXCLUDED.installment_number,
    payment_date = EXCLUDED.payment_date,
    payment_amount = EXCLUDED.payment_amount,
    principal_amount = EXCLUDED.principal_amount,
    interest_amount = EXCLUDED.interest_amount,
    annual_interest_rate = EXCLUDED.annual_interest_rate,
    source_kind = EXCLUDED.source_kind,
    updated_at = timezone('utc'::text, now())
  RETURNING * INTO v_result;

  UPDATE public.transactions
  SET
    installment_number = v_installment_number,
    installment_count = v_loan.total_installments,
    installments_info = CASE
      WHEN v_loan.total_installments IS NULL THEN v_installment_number::text
      ELSE v_installment_number::text || '/' || v_loan.total_installments::text
    END
  WHERE id = p_transaction_id;

  RETURN v_result;
END;
$$;

-- Inserts the cash-ledger row and, when applicable, its authoritative
-- existing_transaction loan payment in one PostgreSQL transaction. A legacy
-- loan intentionally receives only the ledger row; its compatibility trigger
-- continues to calculate from transactions.
CREATE OR REPLACE FUNCTION public.create_transaction_with_loan_payment(
  p_transaction JSONB,
  p_record_loan_payment BOOLEAN DEFAULT true
)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_transaction_id BIGINT;
BEGIN
  IF p_transaction IS NULL THEN
    RAISE EXCEPTION 'Transaction payload is required';
  END IF;

  INSERT INTO public.transactions (
    description,
    movement_type,
    category_id,
    total_amount,
    global_discount,
    global_discount_source,
    payment_source_id,
    transaction_date,
    charge_date,
    tags,
    loan_id,
    original_amount,
    currency,
    exchange_rate,
    installments_info,
    installment_number,
    installment_count,
    parent_transaction_id,
    notes
  ) VALUES (
    p_transaction->>'description',
    p_transaction->>'movement_type',
    nullif(p_transaction->>'category_id', '')::BIGINT,
    (p_transaction->>'total_amount')::NUMERIC,
    coalesce(nullif(p_transaction->>'global_discount', '')::NUMERIC, 0),
    nullif(p_transaction->>'global_discount_source', ''),
    nullif(p_transaction->>'payment_source_id', '')::BIGINT,
    (p_transaction->>'transaction_date')::DATE,
    coalesce(
      nullif(p_transaction->>'charge_date', '')::DATE,
      (p_transaction->>'transaction_date')::DATE
    ),
    p_transaction->>'tags',
    nullif(p_transaction->>'loan_id', '')::BIGINT,
    nullif(p_transaction->>'original_amount', '')::NUMERIC,
    coalesce(nullif(p_transaction->>'currency', ''), 'ILS'),
    nullif(p_transaction->>'exchange_rate', '')::NUMERIC,
    nullif(p_transaction->>'installments_info', ''),
    nullif(p_transaction->>'installment_number', '')::INTEGER,
    nullif(p_transaction->>'installment_count', '')::INTEGER,
    nullif(p_transaction->>'parent_transaction_id', '')::BIGINT,
    p_transaction->>'notes'
  )
  RETURNING id INTO v_transaction_id;

  IF nullif(p_transaction->>'loan_id', '') IS NOT NULL THEN
    PERFORM public.sync_loan_payment_from_transaction(
      v_transaction_id,
      p_record_loan_payment
    );
  END IF;

  RETURN v_transaction_id;
END;
$$;

-- Updates the ledger and its accounting row under one transaction. Historical
-- reconstructed/manual payment components are never repriced by editing their
-- optional ledger provenance. Changes that would invalidate later amortized
-- installments are rejected instead of leaving stale principal splits.
CREATE OR REPLACE FUNCTION public.update_transaction_with_loan_payment(
  p_transaction_id BIGINT,
  p_transaction JSONB,
  p_record_loan_payment BOOLEAN DEFAULT NULL
)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_old_transaction public.transactions%ROWTYPE;
  v_existing public.loan_payments%ROWTYPE;
  v_new_loan_id BIGINT;
  v_new_amount NUMERIC;
  v_requested_installment INTEGER;
  v_should_record_payment BOOLEAN;
  v_accounting_change BOOLEAN;
BEGIN
  SELECT *
  INTO v_old_transaction
  FROM public.transactions
  WHERE id = p_transaction_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Transaction % does not exist', p_transaction_id;
  END IF;

  SELECT *
  INTO v_existing
  FROM public.loan_payments
  WHERE transaction_id = p_transaction_id
  FOR UPDATE;

  v_new_loan_id := nullif(p_transaction->>'loan_id', '')::BIGINT;
  v_new_amount := (p_transaction->>'total_amount')::NUMERIC;
  v_requested_installment := CASE
    WHEN p_transaction ? 'installment_number'
      THEN nullif(p_transaction->>'installment_number', '')::INTEGER
    ELSE v_old_transaction.installment_number
  END;
  v_should_record_payment := coalesce(
    p_record_loan_payment,
    CASE
      WHEN v_existing.id IS NOT NULL THEN true
      -- A linked row with no installment metadata/payment is ancillary unless
      -- the caller explicitly promotes it. This safely round-trips rows such
      -- as bridging interest without requiring a new transaction column.
      WHEN v_old_transaction.loan_id = v_new_loan_id
        AND v_requested_installment IS NULL THEN false
      ELSE true
    END
  );

  -- Lock both loan rows in stable ID order. The payment trigger will refresh
  -- both summaries when an existing payment moves between them.
  PERFORM 1
  FROM public.loans
  WHERE id IN (v_old_transaction.loan_id, v_new_loan_id)
  ORDER BY id
  FOR UPDATE;

  IF v_new_loan_id IS NOT NULL
    AND NOT EXISTS (SELECT 1 FROM public.loans WHERE id = v_new_loan_id) THEN
    RAISE EXCEPTION 'Loan % does not exist', v_new_loan_id;
  END IF;

  IF v_existing.id IS NOT NULL THEN
    v_accounting_change :=
      v_old_transaction.loan_id IS DISTINCT FROM v_new_loan_id
      OR round(abs(v_old_transaction.total_amount), 2)
        IS DISTINCT FROM round(abs(v_new_amount), 2)
      OR (
        v_requested_installment IS NOT NULL
        AND v_requested_installment IS DISTINCT FROM v_existing.installment_number
      )
      OR NOT v_should_record_payment;

    IF v_existing.source_kind <> 'existing_transaction'
      AND v_accounting_change THEN
      RAISE EXCEPTION
        'Reconstructed/manual loan payment % cannot be repriced through transaction update',
        v_existing.id;
    END IF;

    IF v_existing.source_kind = 'existing_transaction'
      AND v_accounting_change
      AND EXISTS (
        SELECT 1
        FROM public.loan_payments later
        WHERE later.loan_id = v_existing.loan_id
          AND later.installment_number > v_existing.installment_number
      ) THEN
      RAISE EXCEPTION
        'Cannot change installment % while later loan payments exist; reconcile the schedule first',
        v_existing.installment_number;
    END IF;
  END IF;

  UPDATE public.transactions
  SET
    description = p_transaction->>'description',
    movement_type = p_transaction->>'movement_type',
    category_id = nullif(p_transaction->>'category_id', '')::BIGINT,
    total_amount = v_new_amount,
    global_discount = coalesce(
      nullif(p_transaction->>'global_discount', '')::NUMERIC,
      0
    ),
    global_discount_source = nullif(
      p_transaction->>'global_discount_source',
      ''
    ),
    payment_source_id = nullif(p_transaction->>'payment_source_id', '')::BIGINT,
    transaction_date = (p_transaction->>'transaction_date')::DATE,
    charge_date = coalesce(
      nullif(p_transaction->>'charge_date', '')::DATE,
      (p_transaction->>'transaction_date')::DATE
    ),
    tags = p_transaction->>'tags',
    loan_id = v_new_loan_id,
    original_amount = nullif(p_transaction->>'original_amount', '')::NUMERIC,
    currency = coalesce(nullif(p_transaction->>'currency', ''), 'ILS'),
    exchange_rate = nullif(p_transaction->>'exchange_rate', '')::NUMERIC,
    installments_info = nullif(p_transaction->>'installments_info', ''),
    installment_number = v_requested_installment,
    installment_count = CASE
      WHEN p_transaction ? 'installment_count'
        THEN nullif(p_transaction->>'installment_count', '')::INTEGER
      ELSE installment_count
    END,
    notes = p_transaction->>'notes',
    updated_at = timezone('utc'::text, now())
  WHERE id = p_transaction_id;

  IF v_existing.id IS NOT NULL
    AND v_existing.source_kind <> 'existing_transaction' THEN
    -- The optional cash-row date/description may change, but reconstructed or
    -- manual accounting remains authoritative and untouched.
    RETURN p_transaction_id;
  END IF;

  IF v_existing.id IS NOT NULL AND NOT v_accounting_change THEN
    -- A date/description edit does not alter amortization. Preserve the exact
    -- historical rate and components, especially for variable-rate loans.
    UPDATE public.loan_payments
    SET
      payment_date = coalesce(
        nullif(p_transaction->>'charge_date', '')::DATE,
        (p_transaction->>'transaction_date')::DATE
      ),
      updated_at = timezone('utc'::text, now())
    WHERE id = v_existing.id;
    RETURN p_transaction_id;
  END IF;

  PERFORM public.sync_loan_payment_from_transaction(
    p_transaction_id,
    v_should_record_payment
  );

  RETURN p_transaction_id;
END;
$$;

-- Deletes application-created accounting rows with their cash transaction.
-- Reconstructed/manual rows deliberately survive and become transaction-less
-- through the FK's ON DELETE SET NULL behavior.
CREATE OR REPLACE FUNCTION public.delete_transaction_with_loan_payment(
  p_transaction_id BIGINT
)
RETURNS BIGINT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_transaction public.transactions%ROWTYPE;
  v_existing public.loan_payments%ROWTYPE;
BEGIN
  SELECT *
  INTO v_transaction
  FROM public.transactions
  WHERE id = p_transaction_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Transaction % does not exist', p_transaction_id;
  END IF;

  SELECT *
  INTO v_existing
  FROM public.loan_payments
  WHERE transaction_id = p_transaction_id
  FOR UPDATE;

  IF v_existing.id IS NOT NULL
    AND v_existing.source_kind = 'existing_transaction' THEN
    IF EXISTS (
      SELECT 1
      FROM public.loan_payments later
      WHERE later.loan_id = v_existing.loan_id
        AND later.installment_number > v_existing.installment_number
    ) THEN
      RAISE EXCEPTION
        'Cannot delete installment % while later loan payments exist; reconcile the schedule first',
        v_existing.installment_number;
    END IF;

    DELETE FROM public.loan_payments
    WHERE id = v_existing.id;
  END IF;

  DELETE FROM public.lego_sets
  WHERE transaction_id = p_transaction_id;

  DELETE FROM public.transaction_items
  WHERE transaction_id = p_transaction_id;

  DELETE FROM public.transactions
  WHERE id = p_transaction_id;

  RETURN p_transaction_id;
END;
$$;

REVOKE ALL ON FUNCTION public.refresh_loan_summary(BIGINT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.sync_loan_payment_from_transaction(BIGINT, BOOLEAN) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.create_transaction_with_loan_payment(JSONB, BOOLEAN) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.update_transaction_with_loan_payment(BIGINT, JSONB, BOOLEAN) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.delete_transaction_with_loan_payment(BIGINT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.refresh_loan_summary(BIGINT) TO service_role;
GRANT EXECUTE ON FUNCTION public.create_transaction_with_loan_payment(JSONB, BOOLEAN) TO service_role;
GRANT EXECUTE ON FUNCTION public.update_transaction_with_loan_payment(BIGINT, JSONB, BOOLEAN) TO service_role;
GRANT EXECUTE ON FUNCTION public.delete_transaction_with_loan_payment(BIGINT) TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.loan_payments TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.loan_payments_id_seq TO service_role;

COMMIT;
