-- Migration 017: funded monthly budget foundation and immutable provenance.
--
-- IMPORTANT: this migration is intentionally self-contained and transactional.
-- It must be rehearsed against a disposable PostgreSQL database and verified
-- against the target catalog before any production execution. Finance Tracker
-- does not currently maintain an authoritative applied-migration ledger.

BEGIN;

-- ---------------------------------------------------------------------------
-- Legacy preflight. Never guess, merge, delete, or silently normalize rows.
-- ---------------------------------------------------------------------------

DO $$
DECLARE
  v_missing_columns TEXT;
  v_bad_rows TEXT;
BEGIN
  IF to_regclass('public.budgets') IS NULL THEN
    RAISE EXCEPTION 'Migration 017 preflight: public.budgets does not exist';
  END IF;

  SELECT string_agg(required.column_name, ', ' ORDER BY required.column_name)
  INTO v_missing_columns
  FROM (VALUES
    ('id'), ('category_id'), ('month'), ('amount'), ('created_at'), ('updated_at')
  ) AS required(column_name)
  WHERE NOT EXISTS (
    SELECT 1
    FROM information_schema.columns c
    WHERE c.table_schema = 'public'
      AND c.table_name = 'budgets'
      AND c.column_name = required.column_name
  );

  IF v_missing_columns IS NOT NULL THEN
    RAISE EXCEPTION
      'Migration 017 preflight: public.budgets has an unexpected shape; missing columns: %',
      v_missing_columns;
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM information_schema.columns c
    WHERE c.table_schema = 'public'
      AND c.table_name = 'budgets'
      AND c.column_name = 'month'
      AND c.data_type = 'text'
  ) OR NOT EXISTS (
    SELECT 1
    FROM information_schema.columns c
    WHERE c.table_schema = 'public'
      AND c.table_name = 'budgets'
      AND c.column_name = 'amount'
      AND c.data_type = 'numeric'
  ) THEN
    RAISE EXCEPTION
      'Migration 017 preflight: expected budgets.month TEXT and budgets.amount NUMERIC';
  END IF;

  SELECT string_agg(format('id=%s month=%L', id, month), ', ' ORDER BY id)
  INTO v_bad_rows
  FROM public.budgets
  WHERE month !~ '^\d{4}-(0[1-9]|1[0-2])$';
  IF v_bad_rows IS NOT NULL THEN
    RAISE EXCEPTION 'Migration 017 preflight: invalid legacy budget month rows: %', v_bad_rows;
  END IF;

  SELECT string_agg(format('id=%s month=%L', id, month), ', ' ORDER BY id)
  INTO v_bad_rows
  FROM public.budgets
  WHERE to_char(to_date(month || '-01', 'YYYY-MM-DD'), 'YYYY-MM') <> month;
  IF v_bad_rows IS NOT NULL THEN
    RAISE EXCEPTION 'Migration 017 preflight: non-canonical calendar month rows: %', v_bad_rows;
  END IF;

  SELECT string_agg(format('id=%s month=%s', id, month), ', ' ORDER BY id)
  INTO v_bad_rows
  FROM public.budgets
  WHERE category_id IS NULL;
  IF v_bad_rows IS NOT NULL THEN
    RAISE EXCEPTION 'Migration 017 preflight: null legacy budget categories: %', v_bad_rows;
  END IF;

  SELECT string_agg(format('category_id=%s month=%s count=%s', category_id, month, row_count), ', ')
  INTO v_bad_rows
  FROM (
    SELECT category_id, month, count(*) AS row_count
    FROM public.budgets
    GROUP BY category_id, month
    HAVING count(*) > 1
  ) duplicates;
  IF v_bad_rows IS NOT NULL THEN
    RAISE EXCEPTION 'Migration 017 preflight: duplicate logical budget rows: %', v_bad_rows;
  END IF;

  SELECT string_agg(format('id=%s amount=%s', id, amount), ', ' ORDER BY id)
  INTO v_bad_rows
  FROM public.budgets
  WHERE amount < 0
     OR amount::text IN ('NaN', 'Infinity', '-Infinity')
     OR amount <> round(amount, 2)
     OR amount > 9999999999999999.99;
  IF v_bad_rows IS NOT NULL THEN
    RAISE EXCEPTION
      'Migration 017 preflight: invalid legacy budget amounts (must be finite, nonnegative NUMERIC(18,2)): %',
      v_bad_rows;
  END IF;

  SELECT string_agg(format('budget_id=%s category_id=%s', b.id, b.category_id), ', ' ORDER BY b.id)
  INTO v_bad_rows
  FROM public.budgets b
  LEFT JOIN public.categories c ON c.id = b.category_id
  WHERE c.id IS NULL;
  IF v_bad_rows IS NOT NULL THEN
    RAISE EXCEPTION 'Migration 017 preflight: legacy budgets reference missing categories: %', v_bad_rows;
  END IF;
END;
$$;

-- ---------------------------------------------------------------------------
-- Canonical month, immutable operations, funding, movements and lifecycle.
-- BIGINT identity operation IDs provide compact, monotonic database ordering;
-- request_key provides client-visible idempotency independently of ordering.
-- ---------------------------------------------------------------------------

CREATE TABLE public.budget_months (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  month_start DATE NOT NULL UNIQUE,
  currency_code TEXT NOT NULL DEFAULT 'ILS' CHECK (currency_code = 'ILS'),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT budget_months_canonical_month CHECK (
    month_start = date_trunc('month', month_start)::date
  )
);

CREATE TABLE public.budget_operations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  budget_month_id BIGINT NOT NULL REFERENCES public.budget_months(id) ON DELETE RESTRICT,
  request_key UUID NOT NULL UNIQUE,
  request_fingerprint TEXT NOT NULL CHECK (btrim(request_fingerprint) <> ''),
  operation_type TEXT NOT NULL CHECK (operation_type IN (
    'legacy_import',
    'manual_funding',
    'establish_budget',
    'adjustment',
    'removal',
    'reactivation',
    'copy',
    'reversal'
  )),
  effective_date DATE NOT NULL,
  reason TEXT,
  reverses_operation_id BIGINT UNIQUE REFERENCES public.budget_operations(id) ON DELETE RESTRICT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT budget_operations_not_self_reversing CHECK (
    reverses_operation_id IS NULL OR reverses_operation_id <> id
  )
);

CREATE TABLE public.budget_funding_entries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operation_id BIGINT NOT NULL UNIQUE REFERENCES public.budget_operations(id) ON DELETE RESTRICT,
  amount_delta NUMERIC(18, 2) NOT NULL,
  source_kind TEXT NOT NULL CHECK (source_kind IN ('manual_available_funds', 'legacy_import')),
  source_label TEXT NOT NULL CHECK (btrim(source_label) <> ''),
  reverses_funding_entry_id BIGINT UNIQUE REFERENCES public.budget_funding_entries(id) ON DELETE RESTRICT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT budget_funding_entry_amount_shape CHECK (
    amount_delta::text NOT IN ('NaN', 'Infinity', '-Infinity')
    AND (
    (source_kind = 'legacy_import' AND amount_delta >= 0 AND reverses_funding_entry_id IS NULL)
    OR
    (source_kind = 'manual_available_funds' AND amount_delta <> 0)
    )
  )
);

ALTER TABLE public.budgets
  ADD COLUMN budget_month_id BIGINT REFERENCES public.budget_months(id) ON DELETE RESTRICT,
  ADD COLUMN starting_amount NUMERIC(18, 2),
  ADD COLUMN starting_kind TEXT,
  ADD COLUMN created_by_operation_id BIGINT REFERENCES public.budget_operations(id) ON DELETE RESTRICT;

CREATE TABLE public.budget_movements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operation_id BIGINT NOT NULL REFERENCES public.budget_operations(id) ON DELETE RESTRICT,
  source_budget_id BIGINT REFERENCES public.budgets(id) ON DELETE RESTRICT,
  destination_budget_id BIGINT REFERENCES public.budgets(id) ON DELETE RESTRICT,
  amount NUMERIC(18, 2) NOT NULL CHECK (
    amount::text NOT IN ('NaN', 'Infinity', '-Infinity') AND amount > 0
  ),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT budget_movements_endpoints CHECK (
    (source_budget_id IS NOT NULL OR destination_budget_id IS NOT NULL)
    AND source_budget_id IS DISTINCT FROM destination_budget_id
  )
);

CREATE TABLE public.budget_lifecycle_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operation_id BIGINT NOT NULL REFERENCES public.budget_operations(id) ON DELETE RESTRICT,
  budget_id BIGINT NOT NULL REFERENCES public.budgets(id) ON DELETE RESTRICT,
  state TEXT NOT NULL CHECK (state IN ('active', 'inactive')),
  actual_spent_snapshot NUMERIC(18, 2),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT budget_lifecycle_actual_snapshot CHECK (
    (state = 'active' AND actual_spent_snapshot IS NULL)
    OR
    (state = 'inactive'
      AND actual_spent_snapshot IS NOT NULL
      AND actual_spent_snapshot::text NOT IN ('NaN', 'Infinity', '-Infinity')
      AND actual_spent_snapshot >= 0)
  ),
  CONSTRAINT budget_lifecycle_operation_budget_key UNIQUE (operation_id, budget_id)
);

CREATE INDEX idx_budget_operations_month_order
  ON public.budget_operations (budget_month_id, id);
CREATE INDEX idx_budget_movements_source
  ON public.budget_movements (source_budget_id, id);
CREATE INDEX idx_budget_movements_destination
  ON public.budget_movements (destination_budget_id, id);
CREATE INDEX idx_budget_lifecycle_budget_order
  ON public.budget_lifecycle_events (budget_id, id DESC);

-- ---------------------------------------------------------------------------
-- Deterministic legacy backfill. One operation and one funding entry per month.
-- ---------------------------------------------------------------------------

INSERT INTO public.budget_months (month_start, created_at)
SELECT
  to_date(b.month || '-01', 'YYYY-MM-DD'),
  min(b.created_at)
FROM public.budgets b
GROUP BY b.month
ORDER BY b.month;

INSERT INTO public.budget_operations (
  budget_month_id,
  request_key,
  request_fingerprint,
  operation_type,
  effective_date,
  reason,
  created_at
)
SELECT
  bm.id,
  (
    substr(md5('finance-tracker:legacy-budget:' || to_char(bm.month_start, 'YYYY-MM')), 1, 8) || '-' ||
    substr(md5('finance-tracker:legacy-budget:' || to_char(bm.month_start, 'YYYY-MM')), 9, 4) || '-' ||
    substr(md5('finance-tracker:legacy-budget:' || to_char(bm.month_start, 'YYYY-MM')), 13, 4) || '-' ||
    substr(md5('finance-tracker:legacy-budget:' || to_char(bm.month_start, 'YYYY-MM')), 17, 4) || '-' ||
    substr(md5('finance-tracker:legacy-budget:' || to_char(bm.month_start, 'YYYY-MM')), 21, 12)
  )::uuid,
  'legacy_import|' || to_char(bm.month_start, 'YYYY-MM'),
  'legacy_import',
  bm.month_start,
  'Migration 017 legacy budget opening-state import',
  bm.created_at
FROM public.budget_months bm
ORDER BY bm.month_start;

INSERT INTO public.budget_funding_entries (
  operation_id,
  amount_delta,
  source_kind,
  source_label,
  created_at
)
SELECT
  bo.id,
  coalesce(sum(b.amount), 0)::numeric(18, 2),
  'legacy_import',
  'Legacy budget import assumption; historical real-world funding source is unknown',
  bo.created_at
FROM public.budget_operations bo
JOIN public.budget_months bm ON bm.id = bo.budget_month_id
LEFT JOIN public.budgets b ON b.month = to_char(bm.month_start, 'YYYY-MM')
WHERE bo.operation_type = 'legacy_import'
GROUP BY bo.id, bo.created_at;

UPDATE public.budgets b
SET budget_month_id = bm.id,
    starting_amount = b.amount::numeric(18, 2),
    starting_kind = 'legacy_import',
    created_by_operation_id = bo.id
FROM public.budget_months bm
JOIN public.budget_operations bo
  ON bo.budget_month_id = bm.id
 AND bo.operation_type = 'legacy_import'
WHERE b.month = to_char(bm.month_start, 'YYYY-MM');

INSERT INTO public.budget_lifecycle_events (
  operation_id,
  budget_id,
  state,
  actual_spent_snapshot,
  created_at
)
SELECT
  b.created_by_operation_id,
  b.id,
  'active',
  NULL,
  b.created_at
FROM public.budgets b
ORDER BY b.id;

-- Preserve every legacy ID while ensuring the next generated snapshot ID cannot
-- collide with an explicitly imported historical ID. ALTER SEQUENCE ... RESTART
-- is transactional, unlike setval(), so a failed migration restores sequence state.
DO $$
DECLARE
  v_sequence REGCLASS;
  v_next_id BIGINT;
BEGIN
  v_sequence := pg_get_serial_sequence('public.budgets', 'id')::regclass;
  IF v_sequence IS NULL THEN
    RAISE EXCEPTION 'Migration 017 preflight: budgets.id has no owned sequence';
  END IF;
  SELECT greatest(coalesce(max(id), 0) + 1, 1) INTO v_next_id FROM public.budgets;
  EXECUTE format('ALTER SEQUENCE %s RESTART WITH %s', v_sequence, v_next_id);
END;
$$;

ALTER TABLE public.budgets
  ALTER COLUMN category_id SET NOT NULL,
  ALTER COLUMN budget_month_id SET NOT NULL,
  ALTER COLUMN starting_amount SET NOT NULL,
  ALTER COLUMN starting_kind SET NOT NULL,
  ALTER COLUMN created_by_operation_id SET NOT NULL,
  ADD CONSTRAINT budgets_starting_amount_nonnegative CHECK (
    starting_amount::text NOT IN ('NaN', 'Infinity', '-Infinity')
    AND starting_amount >= 0
  ),
  ADD CONSTRAINT budgets_starting_kind_check CHECK (
    starting_kind IN ('manual', 'legacy_import', 'copied')
  ),
  ADD CONSTRAINT budgets_legacy_starting_match CHECK (amount = starting_amount),
  ADD CONSTRAINT budgets_month_category_key UNIQUE (budget_month_id, category_id);

-- ---------------------------------------------------------------------------
-- Database-enforced validation and append-only protection.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.prevent_budget_history_mutation()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
BEGIN
  RAISE EXCEPTION '% is append-only; use a compensating budget operation', TG_TABLE_NAME
    USING ERRCODE = '55000';
END;
$$;

CREATE OR REPLACE FUNCTION public.validate_budget_snapshot_insert()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_month public.budget_months%ROWTYPE;
  v_operation public.budget_operations%ROWTYPE;
BEGIN
  SELECT * INTO v_month FROM public.budget_months WHERE id = NEW.budget_month_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Budget month % does not exist', NEW.budget_month_id;
  END IF;
  IF NEW.month <> to_char(v_month.month_start, 'YYYY-MM') THEN
    RAISE EXCEPTION 'Legacy month % does not match canonical month %', NEW.month, v_month.month_start;
  END IF;
  IF NEW.amount::text IN ('NaN', 'Infinity', '-Infinity')
     OR NEW.starting_amount::text IN ('NaN', 'Infinity', '-Infinity') THEN
    RAISE EXCEPTION 'Budget starting values must be finite';
  END IF;
  IF NEW.amount <> NEW.starting_amount THEN
    RAISE EXCEPTION 'Legacy amount must equal immutable starting_amount on insert';
  END IF;
  SELECT * INTO v_operation FROM public.budget_operations WHERE id = NEW.created_by_operation_id;
  IF NOT FOUND OR v_operation.budget_month_id <> NEW.budget_month_id THEN
    RAISE EXCEPTION 'Budget creation operation does not belong to the budget month';
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.validate_budget_operation_insert()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_month_start DATE;
BEGIN
  SELECT month_start INTO v_month_start
  FROM public.budget_months
  WHERE id = NEW.budget_month_id;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Budget month % does not exist', NEW.budget_month_id;
  END IF;
  IF NEW.effective_date < v_month_start
     OR NEW.effective_date >= (v_month_start + interval '1 month')::date THEN
    RAISE EXCEPTION 'Budget operation effective_date must be within its budget month';
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.validate_budget_movement_insert()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_operation_month BIGINT;
  v_source_month BIGINT;
  v_destination_month BIGINT;
BEGIN
  SELECT budget_month_id INTO v_operation_month
  FROM public.budget_operations
  WHERE id = NEW.operation_id;

  IF NEW.source_budget_id IS NOT NULL THEN
    SELECT budget_month_id INTO v_source_month
    FROM public.budgets
    WHERE id = NEW.source_budget_id;
    IF v_source_month IS DISTINCT FROM v_operation_month THEN
      RAISE EXCEPTION 'Movement source budget is outside the operation month';
    END IF;
  END IF;

  IF NEW.destination_budget_id IS NOT NULL THEN
    SELECT budget_month_id INTO v_destination_month
    FROM public.budgets
    WHERE id = NEW.destination_budget_id;
    IF v_destination_month IS DISTINCT FROM v_operation_month THEN
      RAISE EXCEPTION 'Movement destination budget is outside the operation month';
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.validate_budget_lifecycle_insert()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_operation_month BIGINT;
  v_budget_month BIGINT;
  v_previous_state TEXT;
BEGIN
  SELECT budget_month_id INTO v_operation_month
  FROM public.budget_operations
  WHERE id = NEW.operation_id;
  SELECT budget_month_id INTO v_budget_month
  FROM public.budgets
  WHERE id = NEW.budget_id;

  IF v_operation_month IS DISTINCT FROM v_budget_month THEN
    RAISE EXCEPTION 'Lifecycle event budget is outside the operation month';
  END IF;

  SELECT state INTO v_previous_state
  FROM public.budget_lifecycle_events
  WHERE budget_id = NEW.budget_id
  ORDER BY id DESC
  LIMIT 1;

  IF v_previous_state IS NULL AND NEW.state <> 'active' THEN
    RAISE EXCEPTION 'A monthly category budget must begin active';
  END IF;
  IF v_previous_state = NEW.state THEN
    RAISE EXCEPTION 'Budget lifecycle transition % -> % is invalid', v_previous_state, NEW.state;
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER budgets_validate_insert
BEFORE INSERT ON public.budgets
FOR EACH ROW EXECUTE FUNCTION public.validate_budget_snapshot_insert();
CREATE TRIGGER budgets_immutable
BEFORE UPDATE OR DELETE ON public.budgets
FOR EACH ROW EXECUTE FUNCTION public.prevent_budget_history_mutation();

CREATE TRIGGER budget_months_immutable
BEFORE UPDATE OR DELETE ON public.budget_months
FOR EACH ROW EXECUTE FUNCTION public.prevent_budget_history_mutation();
CREATE TRIGGER budget_operations_validate_insert
BEFORE INSERT ON public.budget_operations
FOR EACH ROW EXECUTE FUNCTION public.validate_budget_operation_insert();
CREATE TRIGGER budget_operations_immutable
BEFORE UPDATE OR DELETE ON public.budget_operations
FOR EACH ROW EXECUTE FUNCTION public.prevent_budget_history_mutation();
CREATE TRIGGER budget_funding_entries_immutable
BEFORE UPDATE OR DELETE ON public.budget_funding_entries
FOR EACH ROW EXECUTE FUNCTION public.prevent_budget_history_mutation();
CREATE TRIGGER budget_movements_validate_insert
BEFORE INSERT ON public.budget_movements
FOR EACH ROW EXECUTE FUNCTION public.validate_budget_movement_insert();
CREATE TRIGGER budget_movements_immutable
BEFORE UPDATE OR DELETE ON public.budget_movements
FOR EACH ROW EXECUTE FUNCTION public.prevent_budget_history_mutation();
CREATE TRIGGER budget_lifecycle_validate_insert
BEFORE INSERT ON public.budget_lifecycle_events
FOR EACH ROW EXECUTE FUNCTION public.validate_budget_lifecycle_insert();
CREATE TRIGGER budget_lifecycle_immutable
BEFORE UPDATE OR DELETE ON public.budget_lifecycle_events
FOR EACH ROW EXECUTE FUNCTION public.prevent_budget_history_mutation();

-- ---------------------------------------------------------------------------
-- Canonical derived state. No mutable current-amount cache is authoritative.
-- ---------------------------------------------------------------------------

CREATE VIEW public.budget_category_state AS
SELECT
  b.id AS budget_id,
  b.budget_month_id,
  to_char(bm.month_start, 'YYYY-MM') AS month,
  bm.month_start,
  bm.currency_code,
  b.category_id,
  c.name AS category_name,
  c.icon AS category_icon,
  c.type AS category_type,
  b.starting_amount,
  b.starting_amount::text AS starting_amount_text,
  b.starting_kind,
  coalesce(movements.incoming, 0)::numeric(18, 2)
    - coalesce(movements.outgoing, 0)::numeric(18, 2) AS adjustment_total,
  (coalesce(movements.incoming, 0)::numeric(18, 2)
    - coalesce(movements.outgoing, 0)::numeric(18, 2))::text AS adjustment_total_text,
  b.starting_amount
    + coalesce(movements.incoming, 0)::numeric(18, 2)
    - coalesce(movements.outgoing, 0)::numeric(18, 2) AS final_funded,
  (b.starting_amount
    + coalesce(movements.incoming, 0)::numeric(18, 2)
    - coalesce(movements.outgoing, 0)::numeric(18, 2))::text AS final_funded_text,
  lifecycle.state AS lifecycle_state,
  lifecycle.id AS lifecycle_event_id
FROM public.budgets b
JOIN public.budget_months bm ON bm.id = b.budget_month_id
JOIN public.categories c ON c.id = b.category_id
LEFT JOIN LATERAL (
  SELECT
    sum(m.amount) FILTER (WHERE m.destination_budget_id = b.id) AS incoming,
    sum(m.amount) FILTER (WHERE m.source_budget_id = b.id) AS outgoing
  FROM public.budget_movements m
  WHERE m.source_budget_id = b.id OR m.destination_budget_id = b.id
) movements ON true
JOIN LATERAL (
  SELECT le.id, le.state
  FROM public.budget_lifecycle_events le
  WHERE le.budget_id = b.id
  ORDER BY le.id DESC
  LIMIT 1
) lifecycle ON true;

CREATE VIEW public.budget_month_funding_state AS
SELECT
  bm.id AS budget_month_id,
  to_char(bm.month_start, 'YYYY-MM') AS month,
  bm.month_start,
  bm.currency_code,
  coalesce(f.available, 0)::numeric(18, 2) AS available,
  coalesce(s.starting_total, 0)::numeric(18, 2) AS starting_total,
  coalesce(s.total_allocated, 0)::numeric(18, 2) AS total_allocated,
  coalesce(s.active_allocated, 0)::numeric(18, 2) AS active_allocated,
  (coalesce(s.total_allocated, 0) - coalesce(s.active_allocated, 0))::numeric(18, 2)
    AS inactive_retained_funding,
  (coalesce(f.available, 0) - coalesce(s.total_allocated, 0))::numeric(18, 2)
    AS unallocated
FROM public.budget_months bm
LEFT JOIN LATERAL (
  SELECT sum(fe.amount_delta) AS available
  FROM public.budget_funding_entries fe
  JOIN public.budget_operations bo ON bo.id = fe.operation_id
  WHERE bo.budget_month_id = bm.id
) f ON true
LEFT JOIN LATERAL (
  SELECT
    sum(cs.starting_amount) AS starting_total,
    sum(cs.final_funded) AS total_allocated,
    sum(cs.final_funded) FILTER (WHERE cs.lifecycle_state = 'active') AS active_allocated
  FROM public.budget_category_state cs
  WHERE cs.budget_month_id = bm.id
) s ON true;

-- Exact annual/monthly compatibility input. The amount is aggregated in
-- PostgreSQL and exposed as text so PostgREST never converts NUMERIC to a
-- JavaScript floating-point value.
CREATE VIEW public.budget_month_category_actuals AS
SELECT
  to_char(date_trunc('month', t.transaction_date), 'YYYY-MM') AS month,
  t.category_id,
  c.name AS category_name,
  c.icon AS category_icon,
  sum(t.total_amount)::numeric(18, 2)::text AS actual_spent_text
FROM public.transactions t
LEFT JOIN public.categories c ON c.id = t.category_id
WHERE t.movement_type = 'expense'
GROUP BY date_trunc('month', t.transaction_date), t.category_id, c.name, c.icon;

CREATE OR REPLACE FUNCTION public.budget_month_start_from_key(p_month TEXT)
RETURNS DATE
LANGUAGE plpgsql
IMMUTABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF p_month IS NULL OR p_month !~ '^\d{4}-(0[1-9]|1[0-2])$' THEN
    RAISE EXCEPTION 'month must be a canonical YYYY-MM value' USING ERRCODE = '22023';
  END IF;
  RETURN pg_catalog.to_date(p_month || '-01', 'YYYY-MM-DD');
END;
$$;

CREATE OR REPLACE FUNCTION public.budget_assert_reconciled(p_budget_month_id BIGINT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_state public.budget_month_funding_state%ROWTYPE;
  v_negative_budget BIGINT;
BEGIN
  SELECT * INTO v_state
  FROM public.budget_month_funding_state
  WHERE budget_month_id = p_budget_month_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Budget month % does not exist', p_budget_month_id;
  END IF;
  IF v_state.available::text IN ('NaN', 'Infinity', '-Infinity')
     OR v_state.starting_total::text IN ('NaN', 'Infinity', '-Infinity')
     OR v_state.total_allocated::text IN ('NaN', 'Infinity', '-Infinity')
     OR v_state.active_allocated::text IN ('NaN', 'Infinity', '-Infinity')
     OR v_state.inactive_retained_funding::text IN ('NaN', 'Infinity', '-Infinity')
     OR v_state.unallocated::text IN ('NaN', 'Infinity', '-Infinity')
     OR v_state.available < 0 OR v_state.total_allocated < 0 OR v_state.unallocated < 0 THEN
    RAISE EXCEPTION
      'Budget month % does not reconcile: available %, allocated %, unallocated %',
      p_budget_month_id, v_state.available, v_state.total_allocated, v_state.unallocated
      USING ERRCODE = '23514';
  END IF;

  SELECT budget_id INTO v_negative_budget
  FROM public.budget_category_state
  WHERE budget_month_id = p_budget_month_id
    AND (final_funded::text IN ('NaN', 'Infinity', '-Infinity') OR final_funded < 0)
  LIMIT 1;
  IF v_negative_budget IS NOT NULL THEN
    RAISE EXCEPTION 'Budget % has a negative final funded amount', v_negative_budget
      USING ERRCODE = '23514';
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_funded_budget_month(p_month TEXT)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_month_start DATE := public.budget_month_start_from_key(p_month);
  v_month_id BIGINT;
  v_funding JSONB;
  v_categories JSONB;
  v_history JSONB;
  v_total_actual NUMERIC(18, 2);
  v_budgeted_actual NUMERIC(18, 2);
BEGIN
  SELECT id INTO v_month_id
  FROM public.budget_months
  WHERE month_start = v_month_start;

  IF EXISTS (
    SELECT 1 FROM public.transactions
    WHERE movement_type = 'expense'
      AND transaction_date >= v_month_start
      AND transaction_date < (v_month_start + interval '1 month')::date
      AND total_amount::text IN ('NaN', 'Infinity', '-Infinity')
  ) THEN
    RAISE EXCEPTION 'Budget actual spending contains a non-finite amount' USING ERRCODE = '22003';
  END IF;

  SELECT jsonb_build_object(
    'available', coalesce(s.available, 0)::numeric(18, 2)::text,
    'starting_total', coalesce(s.starting_total, 0)::numeric(18, 2)::text,
    'total_allocated', coalesce(s.total_allocated, 0)::numeric(18, 2)::text,
    'active_allocated', coalesce(s.active_allocated, 0)::numeric(18, 2)::text,
    'inactive_retained_funding', coalesce(s.inactive_retained_funding, 0)::numeric(18, 2)::text,
    'unallocated', coalesce(s.unallocated, 0)::numeric(18, 2)::text
  ) INTO v_funding
  FROM (SELECT 1) seed
  LEFT JOIN public.budget_month_funding_state s ON s.budget_month_id = v_month_id;

  WITH actuals AS (
    SELECT category_id, sum(total_amount)::numeric(18, 2) AS actual_spent
    FROM public.transactions
    WHERE movement_type = 'expense'
      AND transaction_date >= v_month_start
      AND transaction_date < (v_month_start + interval '1 month')::date
    GROUP BY category_id
  ), category_keys AS (
    SELECT category_id FROM public.budget_category_state WHERE budget_month_id = v_month_id
    UNION
    SELECT category_id FROM actuals
  )
  SELECT coalesce(jsonb_agg(jsonb_build_object(
    'budget_id', cs.budget_id,
    'category_id', keys.category_id,
    'categories', CASE WHEN keys.category_id IS NULL THEN NULL ELSE jsonb_build_object(
      'name', c.name,
      'icon', c.icon,
      'type', c.type
    ) END,
    'lifecycle_state', coalesce(cs.lifecycle_state, 'no_budget'),
    'is_active_budget', coalesce(cs.lifecycle_state = 'active', false),
    'is_active_zero', coalesce(cs.lifecycle_state = 'active' AND cs.final_funded = 0, false),
    'is_unbudgeted', coalesce(cs.lifecycle_state <> 'active', true),
    'starting_amount', CASE WHEN cs.starting_amount IS NULL THEN NULL ELSE cs.starting_amount::numeric(18, 2)::text END,
    'starting_kind', cs.starting_kind,
    'adjustment_total', coalesce(cs.adjustment_total, 0)::numeric(18, 2)::text,
    'final_funded', CASE WHEN cs.final_funded IS NULL THEN NULL ELSE cs.final_funded::numeric(18, 2)::text END,
    'amount', CASE WHEN cs.final_funded IS NULL THEN NULL ELSE cs.final_funded::numeric(18, 2)::text END,
    'actual_spent', coalesce(a.actual_spent, 0)::numeric(18, 2)::text,
    'remaining', CASE WHEN cs.lifecycle_state = 'active'
      THEN (cs.final_funded - coalesce(a.actual_spent, 0))::numeric(18, 2)::text ELSE NULL END,
    'deficit', CASE WHEN cs.lifecycle_state = 'active'
      THEN greatest(coalesce(a.actual_spent, 0) - cs.final_funded, 0)::numeric(18, 2)::text ELSE '0.00' END
  ) ORDER BY coalesce(c.name, ''), keys.category_id), '[]'::jsonb)
  INTO v_categories
  FROM category_keys keys
  LEFT JOIN public.budget_category_state cs
    ON cs.budget_month_id = v_month_id
   AND cs.category_id IS NOT DISTINCT FROM keys.category_id
  LEFT JOIN actuals a ON a.category_id IS NOT DISTINCT FROM keys.category_id
  LEFT JOIN public.categories c ON c.id = keys.category_id;

  SELECT coalesce(sum(total_amount), 0)::numeric(18, 2)
  INTO v_total_actual
  FROM public.transactions
  WHERE movement_type = 'expense'
    AND transaction_date >= v_month_start
    AND transaction_date < (v_month_start + interval '1 month')::date;

  SELECT coalesce(sum(t.total_amount), 0)::numeric(18, 2)
  INTO v_budgeted_actual
  FROM public.transactions t
  WHERE t.movement_type = 'expense'
    AND t.transaction_date >= v_month_start
    AND t.transaction_date < (v_month_start + interval '1 month')::date
    AND EXISTS (
      SELECT 1
      FROM public.budget_category_state cs
      WHERE cs.budget_month_id = v_month_id
        AND cs.lifecycle_state = 'active'
        AND cs.category_id = t.category_id
    );

  SELECT coalesce(jsonb_agg(jsonb_build_object(
    'id', bo.id,
    'operation_type', bo.operation_type,
    'effective_date', bo.effective_date,
    'created_at', bo.created_at,
    'reason', bo.reason,
    'reverses_operation_id', bo.reverses_operation_id,
    'funding_entries', coalesce((
      SELECT jsonb_agg(jsonb_build_object(
        'id', fe.id,
        'amount_delta', fe.amount_delta::numeric(18, 2)::text,
        'source_kind', fe.source_kind,
        'source_label', fe.source_label,
        'reverses_funding_entry_id', fe.reverses_funding_entry_id
      ) ORDER BY fe.id)
      FROM public.budget_funding_entries fe WHERE fe.operation_id = bo.id
    ), '[]'::jsonb),
    'movements', coalesce((
      SELECT jsonb_agg(jsonb_build_object(
        'id', m.id,
        'source_budget_id', m.source_budget_id,
        'destination_budget_id', m.destination_budget_id,
        'amount', m.amount::numeric(18, 2)::text
      ) ORDER BY m.id)
      FROM public.budget_movements m WHERE m.operation_id = bo.id
    ), '[]'::jsonb),
    'lifecycle_events', coalesce((
      SELECT jsonb_agg(jsonb_build_object(
        'id', le.id,
        'budget_id', le.budget_id,
        'state', le.state,
        'actual_spent_snapshot', CASE WHEN le.actual_spent_snapshot IS NULL
          THEN NULL ELSE le.actual_spent_snapshot::numeric(18, 2)::text END
      ) ORDER BY le.id)
      FROM public.budget_lifecycle_events le WHERE le.operation_id = bo.id
    ), '[]'::jsonb)
  ) ORDER BY bo.id), '[]'::jsonb)
  INTO v_history
  FROM public.budget_operations bo
  WHERE bo.budget_month_id = v_month_id;

  RETURN jsonb_build_object(
    'month', p_month,
    'currency', 'ILS',
    'funding', v_funding,
    'actuals', jsonb_build_object(
      'total', v_total_actual::numeric(18, 2)::text,
      'budgeted', v_budgeted_actual::numeric(18, 2)::text,
      'unbudgeted', (v_total_actual - v_budgeted_actual)::numeric(18, 2)::text
    ),
    'categories', v_categories,
    'history', v_history
  );
END;
$$;

-- ---------------------------------------------------------------------------
-- Bounded mutation RPCs. All financial arithmetic remains NUMERIC in PostgreSQL.
-- ---------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.add_manual_budget_funding(
  p_month TEXT,
  p_amount NUMERIC,
  p_source_label TEXT,
  p_request_key UUID,
  p_reason TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_month_start DATE := public.budget_month_start_from_key(p_month);
  v_month_id BIGINT;
  v_existing public.budget_operations%ROWTYPE;
  v_fingerprint TEXT;
BEGIN
  IF p_amount IS NULL OR p_amount::text IN ('NaN', 'Infinity', '-Infinity')
     OR p_amount <= 0 OR p_amount <> round(p_amount, 2)
     OR p_amount > 9999999999999999.99 THEN
    RAISE EXCEPTION 'Manual funding amount must be a positive two-decimal value' USING ERRCODE = '22023';
  END IF;
  IF p_source_label IS NULL OR btrim(p_source_label) = '' THEN
    RAISE EXCEPTION 'Manual funding source label is required' USING ERRCODE = '22023';
  END IF;
  IF p_request_key IS NULL THEN
    RAISE EXCEPTION 'request_key is required' USING ERRCODE = '22023';
  END IF;

  INSERT INTO public.budget_months (month_start) VALUES (v_month_start)
  ON CONFLICT (month_start) DO NOTHING;
  SELECT id INTO v_month_id FROM public.budget_months
  WHERE month_start = v_month_start FOR UPDATE;

  v_fingerprint := 'manual_funding|' || p_month || '|' || p_amount::numeric(18, 2)::text || '|' || btrim(p_source_label);
  SELECT * INTO v_existing FROM public.budget_operations WHERE request_key = p_request_key;
  IF FOUND THEN
    IF v_existing.budget_month_id <> v_month_id
       OR v_existing.operation_type <> 'manual_funding'
       OR v_existing.request_fingerprint <> v_fingerprint THEN
      RAISE EXCEPTION 'request_key was already used for a different budget operation' USING ERRCODE = '23505';
    END IF;
    RETURN public.get_funded_budget_month(p_month);
  END IF;

  INSERT INTO public.budget_operations (
    budget_month_id, request_key, request_fingerprint, operation_type,
    effective_date, reason
  ) VALUES (
    v_month_id, p_request_key, v_fingerprint, 'manual_funding', v_month_start, p_reason
  ) RETURNING id INTO v_existing.id;

  INSERT INTO public.budget_funding_entries (
    operation_id, amount_delta, source_kind, source_label
  ) VALUES (
    v_existing.id, p_amount::numeric(18, 2), 'manual_available_funds', btrim(p_source_label)
  );

  PERFORM public.budget_assert_reconciled(v_month_id);
  RETURN public.get_funded_budget_month(p_month);
END;
$$;

CREATE OR REPLACE FUNCTION public.establish_funded_budget(
  p_month TEXT,
  p_category_id BIGINT,
  p_starting_amount NUMERIC,
  p_starting_kind TEXT,
  p_request_key UUID,
  p_reason TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_month_start DATE := public.budget_month_start_from_key(p_month);
  v_month_id BIGINT;
  v_operation_id BIGINT;
  v_budget_id BIGINT;
  v_existing public.budget_operations%ROWTYPE;
  v_unallocated NUMERIC(18, 2);
  v_fingerprint TEXT;
BEGIN
  IF p_starting_amount IS NULL OR p_starting_amount::text IN ('NaN', 'Infinity', '-Infinity')
     OR p_starting_amount < 0 OR p_starting_amount <> round(p_starting_amount, 2)
     OR p_starting_amount > 9999999999999999.99 THEN
    RAISE EXCEPTION 'starting_amount must be a nonnegative two-decimal value' USING ERRCODE = '22023';
  END IF;
  IF p_starting_kind NOT IN ('manual', 'copied') THEN
    RAISE EXCEPTION 'Runtime starting_kind must be manual or copied' USING ERRCODE = '22023';
  END IF;
  IF p_request_key IS NULL THEN
    RAISE EXCEPTION 'request_key is required' USING ERRCODE = '22023';
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM public.categories WHERE id = p_category_id AND type = 'expense'
  ) THEN
    RAISE EXCEPTION 'Category % is not an expense category', p_category_id USING ERRCODE = '23503';
  END IF;

  INSERT INTO public.budget_months (month_start) VALUES (v_month_start)
  ON CONFLICT (month_start) DO NOTHING;
  SELECT id INTO v_month_id FROM public.budget_months
  WHERE month_start = v_month_start FOR UPDATE;

  v_fingerprint := 'establish|' || p_month || '|' || p_category_id || '|' || p_starting_amount::numeric(18, 2)::text || '|' || p_starting_kind;
  SELECT * INTO v_existing FROM public.budget_operations WHERE request_key = p_request_key;
  IF FOUND THEN
    IF v_existing.budget_month_id <> v_month_id
       OR v_existing.operation_type <> 'establish_budget'
       OR v_existing.request_fingerprint <> v_fingerprint THEN
      RAISE EXCEPTION 'request_key was already used for a different budget operation' USING ERRCODE = '23505';
    END IF;
    RETURN public.get_funded_budget_month(p_month);
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.budgets
    WHERE budget_month_id = v_month_id AND category_id = p_category_id
  ) THEN
    RAISE EXCEPTION 'A monthly budget snapshot already exists for category %', p_category_id USING ERRCODE = '23505';
  END IF;

  SELECT unallocated INTO v_unallocated
  FROM public.budget_month_funding_state
  WHERE budget_month_id = v_month_id;
  IF p_starting_amount > coalesce(v_unallocated, 0) THEN
    RAISE EXCEPTION 'Insufficient unallocated funds: requested %, available %', p_starting_amount, coalesce(v_unallocated, 0)
      USING ERRCODE = '23514';
  END IF;

  INSERT INTO public.budget_operations (
    budget_month_id, request_key, request_fingerprint, operation_type,
    effective_date, reason
  ) VALUES (
    v_month_id, p_request_key, v_fingerprint, 'establish_budget', v_month_start, p_reason
  ) RETURNING id INTO v_operation_id;

  INSERT INTO public.budgets (
    category_id, month, amount, budget_month_id, starting_amount,
    starting_kind, created_by_operation_id
  ) VALUES (
    p_category_id, p_month, p_starting_amount, v_month_id, p_starting_amount,
    p_starting_kind, v_operation_id
  ) RETURNING id INTO v_budget_id;

  INSERT INTO public.budget_lifecycle_events (operation_id, budget_id, state)
  VALUES (v_operation_id, v_budget_id, 'active');

  PERFORM public.budget_assert_reconciled(v_month_id);
  RETURN public.get_funded_budget_month(p_month);
END;
$$;

CREATE OR REPLACE FUNCTION public.set_funded_budget_amount(
  p_budget_id BIGINT,
  p_target_amount NUMERIC,
  p_request_key UUID,
  p_reason TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_budget public.budgets%ROWTYPE;
  v_month public.budget_months%ROWTYPE;
  v_state public.budget_category_state%ROWTYPE;
  v_latest_state TEXT;
  v_actual NUMERIC(18, 2);
  v_unallocated NUMERIC(18, 2);
  v_delta NUMERIC(18, 2);
  v_operation_id BIGINT;
  v_existing public.budget_operations%ROWTYPE;
  v_fingerprint TEXT;
BEGIN
  IF p_target_amount IS NULL OR p_target_amount::text IN ('NaN', 'Infinity', '-Infinity')
     OR p_target_amount < 0 OR p_target_amount <> round(p_target_amount, 2)
     OR p_target_amount > 9999999999999999.99 THEN
    RAISE EXCEPTION 'target_amount must be a nonnegative two-decimal value' USING ERRCODE = '22023';
  END IF;
  IF p_request_key IS NULL THEN RAISE EXCEPTION 'request_key is required' USING ERRCODE = '22023'; END IF;

  SELECT * INTO v_budget FROM public.budgets WHERE id = p_budget_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'Budget % does not exist', p_budget_id USING ERRCODE = 'P0002'; END IF;
  SELECT * INTO v_month FROM public.budget_months WHERE id = v_budget.budget_month_id FOR UPDATE;
  SELECT * INTO v_budget FROM public.budgets WHERE id = p_budget_id FOR UPDATE;
  SELECT * INTO v_state FROM public.budget_category_state WHERE budget_id = p_budget_id;
  v_latest_state := v_state.lifecycle_state;

  v_fingerprint := 'set_amount|' || p_budget_id || '|' || p_target_amount::numeric(18, 2)::text;
  SELECT * INTO v_existing FROM public.budget_operations WHERE request_key = p_request_key;
  IF FOUND THEN
    IF v_existing.budget_month_id <> v_month.id
       OR v_existing.operation_type <> 'adjustment'
       OR v_existing.request_fingerprint <> v_fingerprint THEN
      RAISE EXCEPTION 'request_key was already used for a different budget operation' USING ERRCODE = '23505';
    END IF;
    RETURN public.get_funded_budget_month(to_char(v_month.month_start, 'YYYY-MM'));
  END IF;

  IF v_latest_state <> 'active' THEN
    RAISE EXCEPTION 'Budget % is inactive; reactivate it before adjusting funding', p_budget_id USING ERRCODE = '55000';
  END IF;
  v_delta := p_target_amount - v_state.final_funded;
  IF v_delta = 0 THEN
    INSERT INTO public.budget_operations (
      budget_month_id, request_key, request_fingerprint, operation_type, effective_date, reason
    ) VALUES (v_month.id, p_request_key, v_fingerprint, 'adjustment', v_month.month_start, p_reason);
    PERFORM public.budget_assert_reconciled(v_month.id);
    RETURN public.get_funded_budget_month(to_char(v_month.month_start, 'YYYY-MM'));
  END IF;

  SELECT unallocated INTO v_unallocated FROM public.budget_month_funding_state
  WHERE budget_month_id = v_month.id;
  IF EXISTS (
    SELECT 1 FROM public.transactions
    WHERE movement_type = 'expense' AND category_id = v_budget.category_id
      AND transaction_date >= v_month.month_start
      AND transaction_date < (v_month.month_start + interval '1 month')::date
      AND total_amount::text IN ('NaN', 'Infinity', '-Infinity')
  ) THEN
    RAISE EXCEPTION 'Budget actual spending contains a non-finite amount' USING ERRCODE = '22003';
  END IF;
  SELECT coalesce(sum(total_amount), 0)::numeric(18, 2) INTO v_actual
  FROM public.transactions
  WHERE movement_type = 'expense' AND category_id = v_budget.category_id
    AND transaction_date >= v_month.month_start
    AND transaction_date < (v_month.month_start + interval '1 month')::date;

  IF v_delta > 0 AND v_delta > v_unallocated THEN
    RAISE EXCEPTION 'Insufficient unallocated funds: requested %, available %', v_delta, v_unallocated USING ERRCODE = '23514';
  END IF;
  IF v_delta < 0 AND -v_delta > greatest(v_state.final_funded - v_actual, 0) THEN
    RAISE EXCEPTION 'Cannot release spent funding; eligible release is %', greatest(v_state.final_funded - v_actual, 0)
      USING ERRCODE = '23514';
  END IF;

  INSERT INTO public.budget_operations (
    budget_month_id, request_key, request_fingerprint, operation_type, effective_date, reason
  ) VALUES (v_month.id, p_request_key, v_fingerprint, 'adjustment', v_month.month_start, p_reason)
  RETURNING id INTO v_operation_id;

  INSERT INTO public.budget_movements (operation_id, source_budget_id, destination_budget_id, amount)
  VALUES (
    v_operation_id,
    CASE WHEN v_delta < 0 THEN p_budget_id ELSE NULL END,
    CASE WHEN v_delta > 0 THEN p_budget_id ELSE NULL END,
    abs(v_delta)
  );

  PERFORM public.budget_assert_reconciled(v_month.id);
  RETURN public.get_funded_budget_month(to_char(v_month.month_start, 'YYYY-MM'));
END;
$$;

CREATE OR REPLACE FUNCTION public.remove_funded_budget(
  p_budget_id BIGINT,
  p_request_key UUID,
  p_reason TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_budget public.budgets%ROWTYPE;
  v_month public.budget_months%ROWTYPE;
  v_state public.budget_category_state%ROWTYPE;
  v_actual NUMERIC(18, 2);
  v_release NUMERIC(18, 2);
  v_operation_id BIGINT;
  v_existing public.budget_operations%ROWTYPE;
  v_fingerprint TEXT;
BEGIN
  IF p_request_key IS NULL THEN RAISE EXCEPTION 'request_key is required' USING ERRCODE = '22023'; END IF;
  SELECT * INTO v_budget FROM public.budgets WHERE id = p_budget_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'Budget % does not exist', p_budget_id USING ERRCODE = 'P0002'; END IF;
  SELECT * INTO v_month FROM public.budget_months WHERE id = v_budget.budget_month_id FOR UPDATE;
  SELECT * INTO v_budget FROM public.budgets WHERE id = p_budget_id FOR UPDATE;
  v_fingerprint := 'remove|' || p_budget_id;
  SELECT * INTO v_existing FROM public.budget_operations WHERE request_key = p_request_key;
  IF FOUND THEN
    IF v_existing.budget_month_id <> v_month.id OR v_existing.operation_type <> 'removal'
       OR v_existing.request_fingerprint <> v_fingerprint THEN
      RAISE EXCEPTION 'request_key was already used for a different budget operation' USING ERRCODE = '23505';
    END IF;
    RETURN public.get_funded_budget_month(to_char(v_month.month_start, 'YYYY-MM'));
  END IF;

  SELECT * INTO v_state FROM public.budget_category_state WHERE budget_id = p_budget_id;
  IF v_state.lifecycle_state <> 'active' THEN
    RAISE EXCEPTION 'Budget % is not active', p_budget_id USING ERRCODE = '55000';
  END IF;
  IF EXISTS (
    SELECT 1 FROM public.transactions
    WHERE movement_type = 'expense' AND category_id = v_budget.category_id
      AND transaction_date >= v_month.month_start
      AND transaction_date < (v_month.month_start + interval '1 month')::date
      AND total_amount::text IN ('NaN', 'Infinity', '-Infinity')
  ) THEN
    RAISE EXCEPTION 'Budget actual spending contains a non-finite amount' USING ERRCODE = '22003';
  END IF;
  SELECT coalesce(sum(total_amount), 0)::numeric(18, 2) INTO v_actual
  FROM public.transactions
  WHERE movement_type = 'expense' AND category_id = v_budget.category_id
    AND transaction_date >= v_month.month_start
    AND transaction_date < (v_month.month_start + interval '1 month')::date;
  v_release := greatest(v_state.final_funded - v_actual, 0);

  INSERT INTO public.budget_operations (
    budget_month_id, request_key, request_fingerprint, operation_type, effective_date, reason
  ) VALUES (v_month.id, p_request_key, v_fingerprint, 'removal', v_month.month_start, p_reason)
  RETURNING id INTO v_operation_id;
  IF v_release > 0 THEN
    INSERT INTO public.budget_movements (operation_id, source_budget_id, destination_budget_id, amount)
    VALUES (v_operation_id, p_budget_id, NULL, v_release);
  END IF;
  INSERT INTO public.budget_lifecycle_events (operation_id, budget_id, state, actual_spent_snapshot)
  VALUES (v_operation_id, p_budget_id, 'inactive', v_actual);

  PERFORM public.budget_assert_reconciled(v_month.id);
  RETURN public.get_funded_budget_month(to_char(v_month.month_start, 'YYYY-MM'));
END;
$$;

CREATE OR REPLACE FUNCTION public.reactivate_funded_budget(
  p_budget_id BIGINT,
  p_additional_amount NUMERIC,
  p_request_key UUID,
  p_reason TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_budget public.budgets%ROWTYPE;
  v_month public.budget_months%ROWTYPE;
  v_state public.budget_category_state%ROWTYPE;
  v_unallocated NUMERIC(18, 2);
  v_operation_id BIGINT;
  v_existing public.budget_operations%ROWTYPE;
  v_fingerprint TEXT;
BEGIN
  IF p_additional_amount IS NULL OR p_additional_amount::text IN ('NaN', 'Infinity', '-Infinity')
     OR p_additional_amount < 0 OR p_additional_amount <> round(p_additional_amount, 2)
     OR p_additional_amount > 9999999999999999.99 THEN
    RAISE EXCEPTION 'additional_amount must be a nonnegative two-decimal value' USING ERRCODE = '22023';
  END IF;
  IF p_request_key IS NULL THEN RAISE EXCEPTION 'request_key is required' USING ERRCODE = '22023'; END IF;
  SELECT * INTO v_budget FROM public.budgets WHERE id = p_budget_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'Budget % does not exist', p_budget_id USING ERRCODE = 'P0002'; END IF;
  SELECT * INTO v_month FROM public.budget_months WHERE id = v_budget.budget_month_id FOR UPDATE;
  SELECT * INTO v_budget FROM public.budgets WHERE id = p_budget_id FOR UPDATE;
  v_fingerprint := 'reactivate|' || p_budget_id || '|' || p_additional_amount::numeric(18, 2)::text;
  SELECT * INTO v_existing FROM public.budget_operations WHERE request_key = p_request_key;
  IF FOUND THEN
    IF v_existing.budget_month_id <> v_month.id OR v_existing.operation_type <> 'reactivation'
       OR v_existing.request_fingerprint <> v_fingerprint THEN
      RAISE EXCEPTION 'request_key was already used for a different budget operation' USING ERRCODE = '23505';
    END IF;
    RETURN public.get_funded_budget_month(to_char(v_month.month_start, 'YYYY-MM'));
  END IF;
  SELECT * INTO v_state FROM public.budget_category_state WHERE budget_id = p_budget_id;
  IF v_state.lifecycle_state <> 'inactive' THEN
    RAISE EXCEPTION 'Budget % is not inactive', p_budget_id USING ERRCODE = '55000';
  END IF;
  SELECT unallocated INTO v_unallocated FROM public.budget_month_funding_state WHERE budget_month_id = v_month.id;
  IF p_additional_amount > v_unallocated THEN
    RAISE EXCEPTION 'Insufficient unallocated funds: requested %, available %', p_additional_amount, v_unallocated
      USING ERRCODE = '23514';
  END IF;

  INSERT INTO public.budget_operations (
    budget_month_id, request_key, request_fingerprint, operation_type, effective_date, reason
  ) VALUES (v_month.id, p_request_key, v_fingerprint, 'reactivation', v_month.month_start, p_reason)
  RETURNING id INTO v_operation_id;
  IF p_additional_amount > 0 THEN
    INSERT INTO public.budget_movements (operation_id, destination_budget_id, amount)
    VALUES (v_operation_id, p_budget_id, p_additional_amount);
  END IF;
  INSERT INTO public.budget_lifecycle_events (operation_id, budget_id, state)
  VALUES (v_operation_id, p_budget_id, 'active');

  PERFORM public.budget_assert_reconciled(v_month.id);
  RETURN public.get_funded_budget_month(to_char(v_month.month_start, 'YYYY-MM'));
END;
$$;

CREATE OR REPLACE FUNCTION public.reverse_funded_budget_operation(
  p_operation_id BIGINT,
  p_request_key UUID,
  p_reason TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_original public.budget_operations%ROWTYPE;
  v_month public.budget_months%ROWTYPE;
  v_existing public.budget_operations%ROWTYPE;
  v_funding public.budget_funding_entries%ROWTYPE;
  v_movement public.budget_movements%ROWTYPE;
  v_source_state public.budget_category_state%ROWTYPE;
  v_actual NUMERIC(18, 2);
  v_unallocated NUMERIC(18, 2);
  v_reversal_id BIGINT;
  v_fingerprint TEXT;
BEGIN
  IF p_request_key IS NULL THEN RAISE EXCEPTION 'request_key is required' USING ERRCODE = '22023'; END IF;
  SELECT * INTO v_original FROM public.budget_operations WHERE id = p_operation_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'Budget operation % does not exist', p_operation_id USING ERRCODE = 'P0002'; END IF;
  SELECT * INTO v_month FROM public.budget_months WHERE id = v_original.budget_month_id FOR UPDATE;
  SELECT * INTO v_original FROM public.budget_operations WHERE id = p_operation_id;
  v_fingerprint := 'reverse|' || p_operation_id;
  SELECT * INTO v_existing FROM public.budget_operations WHERE request_key = p_request_key;
  IF FOUND THEN
    IF v_existing.operation_type <> 'reversal' OR v_existing.reverses_operation_id <> p_operation_id
       OR v_existing.request_fingerprint <> v_fingerprint THEN
      RAISE EXCEPTION 'request_key was already used for a different budget operation' USING ERRCODE = '23505';
    END IF;
    RETURN public.get_funded_budget_month(to_char(v_month.month_start, 'YYYY-MM'));
  END IF;
  IF EXISTS (SELECT 1 FROM public.budget_operations WHERE reverses_operation_id = p_operation_id) THEN
    RAISE EXCEPTION 'Budget operation % has already been reversed', p_operation_id USING ERRCODE = '23505';
  END IF;

  IF v_original.operation_type = 'adjustment' THEN
    SELECT * INTO v_movement FROM public.budget_movements WHERE operation_id = p_operation_id;
    IF NOT FOUND THEN RAISE EXCEPTION 'Adjustment operation % has no movement', p_operation_id; END IF;
    PERFORM 1 FROM public.budgets
    WHERE id IN (v_movement.source_budget_id, v_movement.destination_budget_id)
    ORDER BY id FOR UPDATE;
  END IF;

  INSERT INTO public.budget_operations (
    budget_month_id, request_key, request_fingerprint, operation_type,
    effective_date, reason, reverses_operation_id
  ) VALUES (
    v_month.id, p_request_key, v_fingerprint, 'reversal', v_month.month_start,
    p_reason, p_operation_id
  ) RETURNING id INTO v_reversal_id;

  IF v_original.operation_type = 'manual_funding' THEN
    SELECT * INTO v_funding FROM public.budget_funding_entries WHERE operation_id = p_operation_id;
    IF v_funding.source_kind <> 'manual_available_funds' OR v_funding.amount_delta <= 0 THEN
      RAISE EXCEPTION 'Only positive manual funding operations can be reversed';
    END IF;
    SELECT unallocated INTO v_unallocated FROM public.budget_month_funding_state WHERE budget_month_id = v_month.id;
    IF v_funding.amount_delta > v_unallocated THEN
      RAISE EXCEPTION 'Funding reversal would make unallocated funds negative' USING ERRCODE = '23514';
    END IF;
    INSERT INTO public.budget_funding_entries (
      operation_id, amount_delta, source_kind, source_label, reverses_funding_entry_id
    ) VALUES (
      v_reversal_id, -v_funding.amount_delta, 'manual_available_funds',
      'Reversal: ' || v_funding.source_label, v_funding.id
    );
  ELSIF v_original.operation_type = 'adjustment' THEN
    IF v_movement.source_budget_id IS NULL THEN
      SELECT * INTO v_source_state FROM public.budget_category_state WHERE budget_id = v_movement.destination_budget_id;
      IF EXISTS (
        SELECT 1 FROM public.transactions t
        JOIN public.budgets b ON b.category_id = t.category_id
        WHERE b.id = v_movement.destination_budget_id
          AND t.movement_type = 'expense'
          AND t.transaction_date >= v_month.month_start
          AND t.transaction_date < (v_month.month_start + interval '1 month')::date
          AND t.total_amount::text IN ('NaN', 'Infinity', '-Infinity')
      ) THEN
        RAISE EXCEPTION 'Budget actual spending contains a non-finite amount' USING ERRCODE = '22003';
      END IF;
      SELECT coalesce(sum(t.total_amount), 0)::numeric(18, 2) INTO v_actual
      FROM public.transactions t
      JOIN public.budgets b ON b.category_id = t.category_id
      WHERE b.id = v_movement.destination_budget_id
        AND t.movement_type = 'expense'
        AND t.transaction_date >= v_month.month_start
        AND t.transaction_date < (v_month.month_start + interval '1 month')::date;
      IF v_movement.amount > greatest(v_source_state.final_funded - v_actual, 0) THEN
        RAISE EXCEPTION 'Adjustment reversal would release spent funding' USING ERRCODE = '23514';
      END IF;
    ELSE
      SELECT unallocated INTO v_unallocated FROM public.budget_month_funding_state WHERE budget_month_id = v_month.id;
      IF v_movement.amount > v_unallocated THEN
        RAISE EXCEPTION 'Adjustment reversal requires more unallocated funds than are available' USING ERRCODE = '23514';
      END IF;
    END IF;
    INSERT INTO public.budget_movements (
      operation_id, source_budget_id, destination_budget_id, amount
    ) VALUES (
      v_reversal_id, v_movement.destination_budget_id, v_movement.source_budget_id, v_movement.amount
    );
  ELSE
    RAISE EXCEPTION
      'Operation type % must be corrected through its lifecycle command, not generic reversal',
      v_original.operation_type USING ERRCODE = '0A000';
  END IF;

  PERFORM public.budget_assert_reconciled(v_month.id);
  RETURN public.get_funded_budget_month(to_char(v_month.month_start, 'YYYY-MM'));
END;
$$;

CREATE OR REPLACE FUNCTION public.copy_funded_budget_month(
  p_from_month TEXT,
  p_to_month TEXT,
  p_request_key UUID,
  p_reason TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_from_start DATE := public.budget_month_start_from_key(p_from_month);
  v_to_start DATE := public.budget_month_start_from_key(p_to_month);
  v_from_id BIGINT;
  v_to_id BIGINT;
  v_operation_id BIGINT;
  v_existing public.budget_operations%ROWTYPE;
  v_unallocated NUMERIC(18, 2);
  v_additions NUMERIC(18, 2) := 0;
  v_releases NUMERIC(18, 2) := 0;
  v_target_actual NUMERIC(18, 2);
  v_target_id BIGINT;
  v_target_final NUMERIC(18, 2);
  v_target_state TEXT;
  v_delta NUMERIC(18, 2);
  v_fingerprint TEXT;
  source_row RECORD;
BEGIN
  IF p_request_key IS NULL THEN RAISE EXCEPTION 'request_key is required' USING ERRCODE = '22023'; END IF;
  IF v_from_start = v_to_start THEN RAISE EXCEPTION 'Source and target budget months must differ' USING ERRCODE = '22023'; END IF;
  SELECT id INTO v_from_id FROM public.budget_months WHERE month_start = v_from_start;
  IF NOT FOUND THEN RAISE EXCEPTION 'Source month has no funded budget'; END IF;
  INSERT INTO public.budget_months (month_start) VALUES (v_to_start) ON CONFLICT (month_start) DO NOTHING;
  PERFORM 1 FROM public.budget_months WHERE id IN (v_from_id, (SELECT id FROM public.budget_months WHERE month_start = v_to_start)) ORDER BY id FOR UPDATE;
  SELECT id INTO v_to_id FROM public.budget_months WHERE month_start = v_to_start;
  PERFORM 1 FROM public.budgets
  WHERE budget_month_id IN (v_from_id, v_to_id)
  ORDER BY id FOR UPDATE;
  PERFORM public.budget_assert_reconciled(v_from_id);
  PERFORM public.budget_assert_reconciled(v_to_id);

  v_fingerprint := 'copy|' || p_from_month || '|' || p_to_month;
  SELECT * INTO v_existing FROM public.budget_operations WHERE request_key = p_request_key;
  IF FOUND THEN
    IF v_existing.budget_month_id <> v_to_id OR v_existing.operation_type <> 'copy'
       OR v_existing.request_fingerprint <> v_fingerprint THEN
      RAISE EXCEPTION 'request_key was already used for a different budget operation' USING ERRCODE = '23505';
    END IF;
    RETURN public.get_funded_budget_month(p_to_month);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM public.budget_category_state
    WHERE budget_month_id = v_from_id AND lifecycle_state = 'active'
  ) THEN
    RAISE EXCEPTION 'Source month has no active category budgets';
  END IF;

  FOR source_row IN
    SELECT * FROM public.budget_category_state
    WHERE budget_month_id = v_from_id AND lifecycle_state = 'active'
    ORDER BY category_id
  LOOP
    SELECT cs.budget_id, cs.final_funded, cs.lifecycle_state
    INTO v_target_id, v_target_final, v_target_state
    FROM public.budget_category_state cs
    WHERE cs.budget_month_id = v_to_id AND cs.category_id = source_row.category_id;
    IF NOT FOUND THEN
      v_additions := v_additions + source_row.final_funded;
    ELSE
      v_delta := source_row.final_funded - v_target_final;
      IF v_delta > 0 THEN
        v_additions := v_additions + v_delta;
      ELSIF v_delta < 0 THEN
        IF EXISTS (
          SELECT 1 FROM public.transactions
          WHERE movement_type = 'expense' AND category_id = source_row.category_id
            AND transaction_date >= v_to_start
            AND transaction_date < (v_to_start + interval '1 month')::date
            AND total_amount::text IN ('NaN', 'Infinity', '-Infinity')
        ) THEN
          RAISE EXCEPTION 'Budget actual spending contains a non-finite amount' USING ERRCODE = '22003';
        END IF;
        SELECT coalesce(sum(total_amount), 0)::numeric(18, 2) INTO v_target_actual
        FROM public.transactions
        WHERE movement_type = 'expense' AND category_id = source_row.category_id
          AND transaction_date >= v_to_start
          AND transaction_date < (v_to_start + interval '1 month')::date;
        IF -v_delta > greatest(v_target_final - v_target_actual, 0) THEN
          RAISE EXCEPTION 'Copy cannot release spent funding from target category %', source_row.category_id USING ERRCODE = '23514';
        END IF;
        v_releases := v_releases + (-v_delta);
      END IF;
    END IF;
  END LOOP;

  SELECT unallocated INTO v_unallocated FROM public.budget_month_funding_state WHERE budget_month_id = v_to_id;
  IF v_additions > v_unallocated + v_releases THEN
    RAISE EXCEPTION 'Destination month needs % additional funded money; only % is available',
      v_additions, v_unallocated + v_releases USING ERRCODE = '23514';
  END IF;

  INSERT INTO public.budget_operations (
    budget_month_id, request_key, request_fingerprint, operation_type, effective_date, reason
  ) VALUES (v_to_id, p_request_key, v_fingerprint, 'copy', v_to_start, p_reason)
  RETURNING id INTO v_operation_id;

  FOR source_row IN
    SELECT * FROM public.budget_category_state
    WHERE budget_month_id = v_from_id AND lifecycle_state = 'active'
    ORDER BY category_id
  LOOP
    SELECT cs.budget_id, cs.final_funded, cs.lifecycle_state
    INTO v_target_id, v_target_final, v_target_state
    FROM public.budget_category_state cs
    WHERE cs.budget_month_id = v_to_id AND cs.category_id = source_row.category_id;
    IF NOT FOUND THEN
      INSERT INTO public.budgets (
        category_id, month, amount, budget_month_id, starting_amount,
        starting_kind, created_by_operation_id
      ) VALUES (
        source_row.category_id, p_to_month, source_row.final_funded, v_to_id,
        source_row.final_funded, 'copied', v_operation_id
      ) RETURNING id INTO v_target_id;
      INSERT INTO public.budget_lifecycle_events (operation_id, budget_id, state)
      VALUES (v_operation_id, v_target_id, 'active');
    ELSE
      v_delta := source_row.final_funded - v_target_final;
      IF v_delta <> 0 THEN
        INSERT INTO public.budget_movements (
          operation_id, source_budget_id, destination_budget_id, amount
        ) VALUES (
          v_operation_id,
          CASE WHEN v_delta < 0 THEN v_target_id ELSE NULL END,
          CASE WHEN v_delta > 0 THEN v_target_id ELSE NULL END,
          abs(v_delta)
        );
      END IF;
      IF v_target_state = 'inactive' THEN
        INSERT INTO public.budget_lifecycle_events (operation_id, budget_id, state)
        VALUES (v_operation_id, v_target_id, 'active');
      END IF;
    END IF;
  END LOOP;

  PERFORM public.budget_assert_reconciled(v_to_id);
  RETURN public.get_funded_budget_month(p_to_month);
END;
$$;

-- ---------------------------------------------------------------------------
-- RLS and narrow privileges. Application writes are RPC-only after cutover.
-- ---------------------------------------------------------------------------

ALTER TABLE public.budget_months ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.budget_operations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.budget_funding_entries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.budget_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.budget_lifecycle_events ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.budgets FROM PUBLIC, anon, authenticated, service_role;
GRANT SELECT ON public.budgets TO service_role;

REVOKE ALL ON public.budget_months, public.budget_operations,
  public.budget_funding_entries, public.budget_movements,
  public.budget_lifecycle_events
  FROM PUBLIC, anon, authenticated, service_role;
GRANT SELECT ON public.budget_months, public.budget_operations,
  public.budget_funding_entries, public.budget_movements,
  public.budget_lifecycle_events
  TO service_role;

REVOKE ALL ON public.budget_category_state, public.budget_month_funding_state,
  public.budget_month_category_actuals
  FROM PUBLIC, anon, authenticated, service_role;
GRANT SELECT ON public.budget_category_state, public.budget_month_funding_state,
  public.budget_month_category_actuals
  TO service_role;

REVOKE ALL ON FUNCTION public.prevent_budget_history_mutation(),
  public.validate_budget_snapshot_insert(), public.validate_budget_operation_insert(),
  public.validate_budget_movement_insert(), public.validate_budget_lifecycle_insert(),
  public.budget_month_start_from_key(TEXT), public.budget_assert_reconciled(BIGINT)
  FROM PUBLIC, anon, authenticated, service_role;

REVOKE ALL ON FUNCTION public.get_funded_budget_month(TEXT),
  public.add_manual_budget_funding(TEXT, NUMERIC, TEXT, UUID, TEXT),
  public.establish_funded_budget(TEXT, BIGINT, NUMERIC, TEXT, UUID, TEXT),
  public.set_funded_budget_amount(BIGINT, NUMERIC, UUID, TEXT),
  public.remove_funded_budget(BIGINT, UUID, TEXT),
  public.reactivate_funded_budget(BIGINT, NUMERIC, UUID, TEXT),
  public.reverse_funded_budget_operation(BIGINT, UUID, TEXT),
  public.copy_funded_budget_month(TEXT, TEXT, UUID, TEXT)
  FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.get_funded_budget_month(TEXT),
  public.add_manual_budget_funding(TEXT, NUMERIC, TEXT, UUID, TEXT),
  public.establish_funded_budget(TEXT, BIGINT, NUMERIC, TEXT, UUID, TEXT),
  public.set_funded_budget_amount(BIGINT, NUMERIC, UUID, TEXT),
  public.remove_funded_budget(BIGINT, UUID, TEXT),
  public.reactivate_funded_budget(BIGINT, NUMERIC, UUID, TEXT),
  public.reverse_funded_budget_operation(BIGINT, UUID, TEXT),
  public.copy_funded_budget_month(TEXT, TEXT, UUID, TEXT)
  TO service_role;

-- Post-backfill reconciliation is part of the migration transaction.
DO $$
DECLARE
  v_month RECORD;
  v_lifecycle_count BIGINT;
  v_budget_count BIGINT;
BEGIN
  FOR v_month IN SELECT id, month_start FROM public.budget_months ORDER BY month_start LOOP
    PERFORM public.budget_assert_reconciled(v_month.id);
  END LOOP;

  SELECT count(*) INTO v_budget_count FROM public.budgets;
  SELECT count(*) INTO v_lifecycle_count
  FROM public.budget_lifecycle_events
  WHERE state = 'active';
  IF v_lifecycle_count <> v_budget_count THEN
    RAISE EXCEPTION
      'Migration 017 reconciliation: expected one initial active lifecycle event per budget, got % for % budgets',
      v_lifecycle_count, v_budget_count;
  END IF;
END;
$$;

COMMIT;
