-- Migration 019: balanced category budget carryover between adjacent months.
--
-- Carryover is an explicit, immutable, cross-month transfer. The source month
-- releases category funding and records an equal negative funding entry; the
-- destination month records equal positive funding and category allocation.
-- No read path in this migration creates financial state.

BEGIN;

DO $$
BEGIN
  IF to_regclass('public.budget_months') IS NULL
     OR to_regclass('public.budget_operations') IS NULL
     OR to_regclass('public.budget_recurring_defaults') IS NULL
     OR to_regprocedure('public.get_funded_budget_month(text)') IS NULL
     OR to_regprocedure('public.get_budget_recurring_preview(text)') IS NULL
     OR to_regprocedure('public.budget_assert_reconciled(bigint)') IS NULL THEN
    RAISE EXCEPTION 'Migration 019 preflight: funded budget foundation and recurring defaults from Migrations 017 and 018 are required';
  END IF;

  IF to_regclass('public.budget_carryover_settings') IS NOT NULL
     OR to_regclass('public.budget_carryover_batches') IS NOT NULL
     OR to_regclass('public.budget_carryover_transfers') IS NOT NULL THEN
    RAISE EXCEPTION 'Migration 019 preflight: unexpected partial carryover schema exists';
  END IF;
END;
$$;

ALTER TABLE public.budgets
  DROP CONSTRAINT budgets_starting_kind_check,
  ADD CONSTRAINT budgets_starting_kind_check CHECK (
    starting_kind IN (
      'manual', 'legacy_import', 'copied', 'recurring_default', 'carryover_only'
    )
  );

ALTER TABLE public.budget_operations
  DROP CONSTRAINT budget_operations_operation_type_check,
  ADD CONSTRAINT budget_operations_operation_type_check CHECK (operation_type IN (
    'legacy_import',
    'manual_funding',
    'establish_budget',
    'adjustment',
    'removal',
    'reactivation',
    'copy',
    'reversal',
    'month_initialization',
    'carryover_out',
    'carryover_in'
  ));

ALTER TABLE public.budget_funding_entries
  DROP CONSTRAINT budget_funding_entries_source_kind_check,
  ADD CONSTRAINT budget_funding_entries_source_kind_check CHECK (
    source_kind IN ('manual_available_funds', 'legacy_import', 'carryover_transfer')
  ),
  DROP CONSTRAINT budget_funding_entry_amount_shape,
  ADD CONSTRAINT budget_funding_entry_amount_shape CHECK (
    amount_delta::text NOT IN ('NaN', 'Infinity', '-Infinity')
    AND (
      (source_kind = 'legacy_import' AND amount_delta >= 0 AND reverses_funding_entry_id IS NULL)
      OR (source_kind = 'manual_available_funds' AND amount_delta <> 0)
      OR (source_kind = 'carryover_transfer' AND amount_delta <> 0)
    )
  );

CREATE TABLE public.budget_carryover_settings (
  category_id BIGINT PRIMARY KEY REFERENCES public.categories(id) ON DELETE RESTRICT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now())
);

CREATE TABLE public.budget_carryover_batches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_key UUID NOT NULL UNIQUE,
  request_fingerprint TEXT NOT NULL CHECK (btrim(request_fingerprint) <> ''),
  source_budget_month_id BIGINT NOT NULL REFERENCES public.budget_months(id) ON DELETE RESTRICT,
  destination_budget_month_id BIGINT NOT NULL REFERENCES public.budget_months(id) ON DELETE RESTRICT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT budget_carryover_batches_distinct_months CHECK (
    source_budget_month_id <> destination_budget_month_id
  )
);

CREATE TABLE public.budget_carryover_transfers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id BIGINT NOT NULL REFERENCES public.budget_carryover_batches(id) ON DELETE RESTRICT,
  source_budget_id BIGINT NOT NULL REFERENCES public.budgets(id) ON DELETE RESTRICT,
  destination_budget_id BIGINT NOT NULL REFERENCES public.budgets(id) ON DELETE RESTRICT,
  source_operation_id BIGINT NOT NULL UNIQUE REFERENCES public.budget_operations(id) ON DELETE RESTRICT,
  destination_operation_id BIGINT NOT NULL UNIQUE REFERENCES public.budget_operations(id) ON DELETE RESTRICT,
  amount NUMERIC(18, 2) NOT NULL,
  source_final_funded_snapshot NUMERIC(18, 2) NOT NULL,
  source_raw_actual_spent_snapshot NUMERIC(18, 2) NOT NULL,
  source_effective_actual_spent_snapshot NUMERIC(18, 2) NOT NULL,
  reverses_transfer_id BIGINT UNIQUE REFERENCES public.budget_carryover_transfers(id) ON DELETE RESTRICT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT budget_carryover_transfer_amount_check CHECK (
    amount::text NOT IN ('NaN', 'Infinity', '-Infinity') AND amount > 0
  ),
  CONSTRAINT budget_carryover_transfer_final_snapshot_check CHECK (
    source_final_funded_snapshot::text NOT IN ('NaN', 'Infinity', '-Infinity')
    AND source_final_funded_snapshot >= 0
  ),
  CONSTRAINT budget_carryover_transfer_raw_actual_snapshot_check CHECK (
    source_raw_actual_spent_snapshot::text NOT IN ('NaN', 'Infinity', '-Infinity')
  ),
  CONSTRAINT budget_carryover_transfer_effective_actual_snapshot_check CHECK (
    source_effective_actual_spent_snapshot::text NOT IN ('NaN', 'Infinity', '-Infinity')
    AND source_effective_actual_spent_snapshot >= 0
  ),
  CONSTRAINT budget_carryover_transfer_distinct_budgets CHECK (
    source_budget_id <> destination_budget_id
  ),
  CONSTRAINT budget_carryover_transfer_not_self_reversing CHECK (
    reverses_transfer_id IS NULL OR reverses_transfer_id <> id
  )
);

CREATE INDEX idx_budget_carryover_batches_months
  ON public.budget_carryover_batches (source_budget_month_id, destination_budget_month_id, id);
CREATE INDEX idx_budget_carryover_transfers_source
  ON public.budget_carryover_transfers (source_budget_id, destination_budget_id, id);
CREATE INDEX idx_budget_carryover_transfers_destination
  ON public.budget_carryover_transfers (destination_budget_id, id);

CREATE OR REPLACE FUNCTION public.validate_budget_carryover_setting()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM public.categories
    WHERE id = NEW.category_id AND type = 'expense'
  ) THEN
    RAISE EXCEPTION 'Carryover is available only for expense categories'
      USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER budget_carryover_settings_validate
BEFORE INSERT OR UPDATE ON public.budget_carryover_settings
FOR EACH ROW EXECUTE FUNCTION public.validate_budget_carryover_setting();

CREATE OR REPLACE FUNCTION public.prevent_category_type_with_carryover()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF OLD.type = 'expense' AND NEW.type <> 'expense' AND EXISTS (
    SELECT 1 FROM public.budget_carryover_settings WHERE category_id = OLD.id
  ) THEN
    RAISE EXCEPTION 'Disable budget carryover before changing this category type'
      USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER categories_carryover_type_guard
BEFORE UPDATE OF type ON public.categories
FOR EACH ROW EXECUTE FUNCTION public.prevent_category_type_with_carryover();

CREATE OR REPLACE FUNCTION public.validate_budget_carryover_batch_insert()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_source DATE;
  v_destination DATE;
BEGIN
  SELECT month_start INTO v_source FROM public.budget_months WHERE id = NEW.source_budget_month_id;
  SELECT month_start INTO v_destination FROM public.budget_months WHERE id = NEW.destination_budget_month_id;
  IF v_source IS NULL OR v_destination IS NULL
     OR v_destination <> (v_source + interval '1 month')::date THEN
    RAISE EXCEPTION 'Carryover must link consecutive calendar months'
      USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER budget_carryover_batches_validate
BEFORE INSERT ON public.budget_carryover_batches
FOR EACH ROW EXECUTE FUNCTION public.validate_budget_carryover_batch_insert();

CREATE OR REPLACE FUNCTION public.validate_budget_carryover_transfer_insert()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_batch public.budget_carryover_batches%ROWTYPE;
  v_source public.budgets%ROWTYPE;
  v_destination public.budgets%ROWTYPE;
  v_source_operation public.budget_operations%ROWTYPE;
  v_destination_operation public.budget_operations%ROWTYPE;
  v_source_funding public.budget_funding_entries%ROWTYPE;
  v_destination_funding public.budget_funding_entries%ROWTYPE;
  v_source_movement public.budget_movements%ROWTYPE;
  v_destination_movement public.budget_movements%ROWTYPE;
BEGIN
  SELECT * INTO v_batch FROM public.budget_carryover_batches WHERE id = NEW.batch_id;
  SELECT * INTO v_source FROM public.budgets WHERE id = NEW.source_budget_id;
  SELECT * INTO v_destination FROM public.budgets WHERE id = NEW.destination_budget_id;
  SELECT * INTO v_source_operation FROM public.budget_operations WHERE id = NEW.source_operation_id;
  SELECT * INTO v_destination_operation FROM public.budget_operations WHERE id = NEW.destination_operation_id;

  IF v_source.category_id IS DISTINCT FROM v_destination.category_id THEN
    RAISE EXCEPTION 'Carryover source and destination budgets must use the same category';
  END IF;
  IF v_source.budget_month_id IS DISTINCT FROM v_batch.source_budget_month_id
     OR v_destination.budget_month_id IS DISTINCT FROM v_batch.destination_budget_month_id THEN
    RAISE EXCEPTION 'Carryover budgets do not match the batch months';
  END IF;

  IF NEW.reverses_transfer_id IS NULL THEN
    IF v_source_operation.operation_type <> 'carryover_out'
       OR v_destination_operation.operation_type <> 'carryover_in' THEN
      RAISE EXCEPTION 'Original carryover operations have invalid directions';
    END IF;
    IF EXISTS (
      SELECT 1
      FROM public.budget_carryover_transfers prior
      WHERE prior.source_budget_id = NEW.source_budget_id
        AND prior.destination_budget_id = NEW.destination_budget_id
        AND prior.reverses_transfer_id IS NULL
        AND NOT EXISTS (
          SELECT 1 FROM public.budget_carryover_transfers correction
          WHERE correction.reverses_transfer_id = prior.id
        )
    ) THEN
      RAISE EXCEPTION 'An unreversed carryover already exists for this category and month pair'
        USING ERRCODE = '23505';
    END IF;
  ELSE
    IF v_source_operation.operation_type <> 'carryover_in'
       OR v_destination_operation.operation_type <> 'carryover_out' THEN
      RAISE EXCEPTION 'Carryover reversal operations have invalid directions';
    END IF;
    IF NOT EXISTS (
      SELECT 1 FROM public.budget_carryover_transfers original
      WHERE original.id = NEW.reverses_transfer_id
        AND original.reverses_transfer_id IS NULL
        AND original.source_budget_id = NEW.source_budget_id
        AND original.destination_budget_id = NEW.destination_budget_id
        AND original.amount = NEW.amount
    ) THEN
      RAISE EXCEPTION 'Carryover reversal does not match its original transfer';
    END IF;
  END IF;

  IF v_source_operation.budget_month_id IS DISTINCT FROM v_batch.source_budget_month_id
     OR v_destination_operation.budget_month_id IS DISTINCT FROM v_batch.destination_budget_month_id THEN
    RAISE EXCEPTION 'Carryover operations do not match the batch months';
  END IF;

  SELECT * INTO v_source_funding
  FROM public.budget_funding_entries WHERE operation_id = NEW.source_operation_id;
  SELECT * INTO v_destination_funding
  FROM public.budget_funding_entries WHERE operation_id = NEW.destination_operation_id;
  SELECT * INTO v_source_movement
  FROM public.budget_movements WHERE operation_id = NEW.source_operation_id;
  SELECT * INTO v_destination_movement
  FROM public.budget_movements WHERE operation_id = NEW.destination_operation_id;

  IF NEW.reverses_transfer_id IS NULL THEN
    IF v_source_funding.source_kind <> 'carryover_transfer'
       OR v_source_funding.amount_delta <> -NEW.amount
       OR v_source_movement.source_budget_id IS DISTINCT FROM NEW.source_budget_id
       OR v_source_movement.destination_budget_id IS NOT NULL
       OR v_source_movement.amount <> NEW.amount
       OR v_destination_funding.source_kind <> 'carryover_transfer'
       OR v_destination_funding.amount_delta <> NEW.amount
       OR v_destination_movement.source_budget_id IS NOT NULL
       OR v_destination_movement.destination_budget_id IS DISTINCT FROM NEW.destination_budget_id
       OR v_destination_movement.amount <> NEW.amount THEN
      RAISE EXCEPTION 'Carryover funding and movements are not balanced';
    END IF;
  ELSE
    IF v_source_funding.source_kind <> 'carryover_transfer'
       OR v_source_funding.amount_delta <> NEW.amount
       OR v_source_movement.source_budget_id IS NOT NULL
       OR v_source_movement.destination_budget_id IS DISTINCT FROM NEW.source_budget_id
       OR v_source_movement.amount <> NEW.amount
       OR v_destination_funding.source_kind <> 'carryover_transfer'
       OR v_destination_funding.amount_delta <> -NEW.amount
       OR v_destination_movement.source_budget_id IS DISTINCT FROM NEW.destination_budget_id
       OR v_destination_movement.destination_budget_id IS NOT NULL
       OR v_destination_movement.amount <> NEW.amount THEN
      RAISE EXCEPTION 'Carryover reversal funding and movements are not balanced';
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

CREATE TRIGGER budget_carryover_transfers_validate
BEFORE INSERT ON public.budget_carryover_transfers
FOR EACH ROW EXECUTE FUNCTION public.validate_budget_carryover_transfer_insert();

CREATE TRIGGER budget_carryover_batches_immutable
BEFORE UPDATE OR DELETE ON public.budget_carryover_batches
FOR EACH ROW EXECUTE FUNCTION public.prevent_budget_history_mutation();

CREATE TRIGGER budget_carryover_transfers_immutable
BEFORE UPDATE OR DELETE ON public.budget_carryover_transfers
FOR EACH ROW EXECUTE FUNCTION public.prevent_budget_history_mutation();

CREATE VIEW public.budget_carryover_settings_read AS
SELECT category_id, true AS enabled, created_at, updated_at
FROM public.budget_carryover_settings;

CREATE VIEW public.budget_category_carryover_state AS
WITH signed AS (
  SELECT
    t.source_budget_id,
    t.destination_budget_id,
    CASE WHEN t.reverses_transfer_id IS NULL THEN t.amount ELSE -t.amount END AS amount
  FROM public.budget_carryover_transfers t
)
SELECT
  b.id AS budget_id,
  coalesce(sum(s.amount) FILTER (WHERE s.destination_budget_id = b.id), 0)::numeric(18, 2)
    AS incoming_carryover,
  coalesce(sum(s.amount) FILTER (WHERE s.source_budget_id = b.id), 0)::numeric(18, 2)
    AS outgoing_carryover
FROM public.budgets b
LEFT JOIN signed s ON s.source_budget_id = b.id OR s.destination_budget_id = b.id
GROUP BY b.id;

CREATE OR REPLACE FUNCTION public.set_budget_carryover_enabled(
  p_category_id BIGINT,
  p_enabled BOOLEAN
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_category public.categories%ROWTYPE;
BEGIN
  IF p_category_id IS NULL OR p_enabled IS NULL THEN
    RAISE EXCEPTION 'category_id and enabled are required' USING ERRCODE = '22023';
  END IF;

  SELECT * INTO v_category FROM public.categories WHERE id = p_category_id FOR SHARE;
  IF NOT FOUND THEN
    RAISE EXCEPTION 'Category % does not exist', p_category_id USING ERRCODE = 'P0002';
  END IF;
  IF v_category.type <> 'expense' THEN
    RAISE EXCEPTION 'Carryover is available only for expense categories' USING ERRCODE = '23514';
  END IF;

  IF p_enabled THEN
    INSERT INTO public.budget_carryover_settings (category_id)
    VALUES (p_category_id)
    ON CONFLICT (category_id) DO UPDATE
    SET updated_at = timezone('utc'::text, now());
  ELSE
    DELETE FROM public.budget_carryover_settings WHERE category_id = p_category_id;
  END IF;

  RETURN jsonb_build_object('category_id', p_category_id, 'enabled', p_enabled);
END;
$$;

CREATE OR REPLACE FUNCTION public.budget_carryover_candidate_rows(p_destination_month TEXT)
RETURNS TABLE (
  category_id BIGINT,
  category_name TEXT,
  category_icon TEXT,
  source_budget_id BIGINT,
  destination_budget_id BIGINT,
  source_final_funded NUMERIC(18, 2),
  source_raw_actual_spent NUMERIC(18, 2),
  source_effective_actual_spent NUMERIC(18, 2),
  eligible_amount NUMERIC(18, 2),
  status TEXT,
  blocked_reason TEXT
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_destination_start DATE := public.budget_month_start_from_key(p_destination_month);
  v_source_start DATE := (v_destination_start - interval '1 month')::date;
  v_source_id BIGINT;
  v_destination_id BIGINT;
  v_destination_initialized BOOLEAN := false;
BEGIN
  SELECT id INTO v_source_id FROM public.budget_months WHERE month_start = v_source_start;
  SELECT id INTO v_destination_id FROM public.budget_months WHERE month_start = v_destination_start;
  IF v_destination_id IS NOT NULL THEN
    SELECT EXISTS (
      SELECT 1 FROM public.budget_operations
      WHERE budget_month_id = v_destination_id AND operation_type = 'month_initialization'
    ) INTO v_destination_initialized;
  END IF;

  IF EXISTS (
    SELECT 1 FROM public.transactions
    WHERE movement_type = 'expense'
      AND transaction_date >= v_source_start
      AND transaction_date < v_destination_start
      AND total_amount::text IN ('NaN', 'Infinity', '-Infinity')
  ) OR EXISTS (
    SELECT 1 FROM public.transactions
    WHERE movement_type = 'expense'
      AND transaction_date >= v_destination_start
      AND transaction_date < (v_destination_start + interval '1 month')::date
      AND total_amount::text IN ('NaN', 'Infinity', '-Infinity')
  ) THEN
    RAISE EXCEPTION 'Carryover actual spending contains a non-finite amount' USING ERRCODE = '22003';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM public.transactions t
    WHERE t.movement_type = 'expense'
      AND t.transaction_date >= v_source_start
      AND t.transaction_date < (v_destination_start + interval '1 month')::date
    GROUP BY t.category_id, date_trunc('month', t.transaction_date)
    HAVING sum(t.total_amount) <> round(sum(t.total_amount), 2)
      OR abs(sum(t.total_amount)) > 9999999999999999.99
  ) THEN
    RAISE EXCEPTION 'Carryover actual spending must fit finite NUMERIC(18,2) exactly'
      USING ERRCODE = '22003';
  END IF;

  RETURN QUERY
  WITH source_actuals AS (
    SELECT t.category_id, coalesce(sum(t.total_amount), 0)::numeric(18, 2) AS actual
    FROM public.transactions t
    WHERE t.movement_type = 'expense'
      AND t.transaction_date >= v_source_start
      AND t.transaction_date < v_destination_start
    GROUP BY t.category_id
  ), destination_actuals AS (
    SELECT t.category_id, coalesce(sum(t.total_amount), 0)::numeric(18, 2) AS actual
    FROM public.transactions t
    WHERE t.movement_type = 'expense'
      AND t.transaction_date >= v_destination_start
      AND t.transaction_date < (v_destination_start + interval '1 month')::date
    GROUP BY t.category_id
  ), candidate AS (
    SELECT
      c.id AS category_id,
      c.name,
      c.icon,
      src.budget_id AS source_budget_id,
      dst.budget_id AS destination_budget_id,
      coalesce(src.final_funded, 0)::numeric(18, 2) AS source_final_funded,
      coalesce(sa.actual, 0)::numeric(18, 2) AS source_raw_actual_spent,
      greatest(coalesce(sa.actual, 0), 0)::numeric(18, 2) AS source_effective_actual_spent,
      greatest(
        coalesce(src.final_funded, 0) - greatest(coalesce(sa.actual, 0), 0),
        0
      )::numeric(18, 2) AS eligible_amount,
      c.is_active,
      src.lifecycle_state AS source_lifecycle,
      dst.lifecycle_state AS destination_lifecycle,
      coalesce(da.actual, 0)::numeric(18, 2) AS destination_actual,
      coalesce(dst.final_funded, 0)::numeric(18, 2) AS destination_final,
      rd.category_id IS NOT NULL AND NOT v_destination_initialized AS recurring_pending,
      EXISTS (
        SELECT 1
        FROM public.budget_carryover_transfers original
        WHERE original.source_budget_id = src.budget_id
          AND original.reverses_transfer_id IS NULL
          AND NOT EXISTS (
            SELECT 1 FROM public.budget_carryover_transfers correction
            WHERE correction.reverses_transfer_id = original.id
          )
      ) AS already_applied
    FROM public.budget_carryover_settings setting
    JOIN public.categories c ON c.id = setting.category_id
    LEFT JOIN public.budget_category_state src
      ON src.budget_month_id = v_source_id AND src.category_id = c.id
    LEFT JOIN source_actuals sa ON sa.category_id = c.id
    LEFT JOIN public.budget_category_state dst
      ON dst.budget_month_id = v_destination_id AND dst.category_id = c.id
    LEFT JOIN destination_actuals da ON da.category_id = c.id
    LEFT JOIN public.budget_recurring_defaults rd ON rd.category_id = c.id
    WHERE c.type = 'expense'
  )
  SELECT
    candidate.category_id,
    candidate.name,
    candidate.icon,
    candidate.source_budget_id,
    candidate.destination_budget_id,
    candidate.source_final_funded,
    candidate.source_raw_actual_spent,
    candidate.source_effective_actual_spent,
    candidate.eligible_amount,
    CASE
      WHEN candidate.already_applied THEN 'already_applied'
      WHEN NOT candidate.is_active THEN 'blocked'
      WHEN candidate.source_budget_id IS NULL THEN 'blocked'
      WHEN candidate.source_lifecycle <> 'active' THEN 'blocked'
      WHEN candidate.eligible_amount <= 0 THEN 'blocked'
      WHEN candidate.destination_budget_id IS NOT NULL
        AND candidate.destination_lifecycle <> 'active' THEN 'blocked'
      WHEN candidate.destination_budget_id IS NULL AND candidate.recurring_pending THEN 'blocked'
      WHEN candidate.destination_budget_id IS NULL AND candidate.destination_actual > 0 THEN 'blocked'
      WHEN candidate.destination_budget_id IS NOT NULL
        AND candidate.destination_actual > candidate.destination_final THEN 'blocked'
      ELSE 'ready'
    END,
    CASE
      WHEN candidate.already_applied THEN NULL
      WHEN NOT candidate.is_active THEN 'CATEGORY_INACTIVE'
      WHEN candidate.source_budget_id IS NULL THEN 'SOURCE_BUDGET_MISSING'
      WHEN candidate.source_lifecycle <> 'active' THEN 'SOURCE_BUDGET_INACTIVE'
      WHEN candidate.eligible_amount <= 0 THEN 'NO_ELIGIBLE_BALANCE'
      WHEN candidate.destination_budget_id IS NOT NULL
        AND candidate.destination_lifecycle <> 'active' THEN 'DESTINATION_BUDGET_INACTIVE'
      WHEN candidate.destination_budget_id IS NULL AND candidate.recurring_pending
        THEN 'RECURRING_INITIALIZATION_REQUIRED'
      WHEN candidate.destination_budget_id IS NULL AND candidate.destination_actual > 0
        THEN 'UNBUDGETED_ACTUAL_EXISTS'
      WHEN candidate.destination_budget_id IS NOT NULL
        AND candidate.destination_actual > candidate.destination_final THEN 'DESTINATION_DEFICIT'
      ELSE NULL
    END
  FROM candidate
  ORDER BY candidate.name, candidate.category_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_budget_carryover_preview(p_destination_month TEXT)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_destination_start DATE := public.budget_month_start_from_key(p_destination_month);
  v_source_start DATE := (v_destination_start - interval '1 month')::date;
  v_current_start DATE := date_trunc(
    'month', timezone('Asia/Jerusalem', statement_timestamp())
  )::date;
  v_ready JSONB := '[]'::jsonb;
  v_blocked JSONB := '[]'::jsonb;
  v_applied JSONB := '[]'::jsonb;
  v_total NUMERIC(18, 2) := 0;
  v_material TEXT;
  v_fingerprint TEXT;
BEGIN
  IF v_destination_start <> v_current_start THEN
    RETURN jsonb_build_object(
      'eligible', false,
      'reason', 'CURRENT_MONTH_ONLY',
      'source_month', to_char(v_source_start, 'YYYY-MM'),
      'destination_month', p_destination_month,
      'fingerprint', md5('carryover|' || p_destination_month || '|ineligible'),
      'ready_categories', '[]'::jsonb,
      'ready_count', 0,
      'total_incoming', '0.00',
      'already_applied_categories', '[]'::jsonb,
      'blocked_categories', '[]'::jsonb,
      'can_apply', false
    );
  END IF;

  WITH rows AS (
    SELECT * FROM public.budget_carryover_candidate_rows(p_destination_month)
  )
  SELECT
    coalesce(jsonb_agg(jsonb_build_object(
      'category_id', category_id,
      'category', jsonb_build_object('name', category_name, 'icon', category_icon, 'type', 'expense'),
      'source_budget_id', source_budget_id,
      'destination_budget_id', destination_budget_id,
      'source_final_funded', source_final_funded::numeric(18, 2)::text,
      'source_raw_actual_spent', source_raw_actual_spent::numeric(18, 2)::text,
      'source_effective_actual_spent', source_effective_actual_spent::numeric(18, 2)::text,
      'amount', eligible_amount::numeric(18, 2)::text
    ) ORDER BY category_name, category_id) FILTER (WHERE status = 'ready'), '[]'::jsonb),
    coalesce(jsonb_agg(jsonb_build_object(
      'category_id', category_id,
      'category', jsonb_build_object('name', category_name, 'icon', category_icon, 'type', 'expense'),
      'source_raw_actual_spent', source_raw_actual_spent::numeric(18, 2)::text,
      'source_effective_actual_spent', source_effective_actual_spent::numeric(18, 2)::text,
      'amount', eligible_amount::numeric(18, 2)::text,
      'reason', blocked_reason
    ) ORDER BY category_name, category_id) FILTER (WHERE status = 'blocked'), '[]'::jsonb),
    coalesce(jsonb_agg(jsonb_build_object(
      'category_id', category_id,
      'category', jsonb_build_object('name', category_name, 'icon', category_icon, 'type', 'expense')
    ) ORDER BY category_name, category_id) FILTER (WHERE status = 'already_applied'), '[]'::jsonb),
    coalesce(sum(eligible_amount) FILTER (WHERE status = 'ready'), 0)::numeric(18, 2),
    coalesce(string_agg(
      category_id || '|' || coalesce(source_budget_id::text, '') || '|'
      || coalesce(destination_budget_id::text, '') || '|' || status || '|'
      || source_final_funded::numeric(18, 2)::text || '|'
      || source_raw_actual_spent::numeric(18, 2)::text || '|'
      || source_effective_actual_spent::numeric(18, 2)::text || '|'
      || eligible_amount::numeric(18, 2)::text || '|' || coalesce(blocked_reason, ''),
      ';' ORDER BY category_id
    ), '')
  INTO v_ready, v_blocked, v_applied, v_total, v_material
  FROM rows;

  v_fingerprint := md5(
    'carryover|' || to_char(v_source_start, 'YYYY-MM') || '|'
    || p_destination_month || '|' || v_material
  );

  RETURN jsonb_build_object(
    'eligible', true,
    'reason', NULL,
    'source_month', to_char(v_source_start, 'YYYY-MM'),
    'destination_month', p_destination_month,
    'fingerprint', v_fingerprint,
    'ready_categories', v_ready,
    'ready_count', jsonb_array_length(v_ready),
    'total_incoming', v_total::numeric(18, 2)::text,
    'already_applied_categories', v_applied,
    'blocked_categories', v_blocked,
    'can_apply', jsonb_array_length(v_ready) > 0
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.budget_derived_request_key(p_parent UUID, p_suffix TEXT)
RETURNS UUID
LANGUAGE sql
IMMUTABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
  SELECT (
    substr(md5(p_parent::text || '|' || p_suffix), 1, 8) || '-'
    || substr(md5(p_parent::text || '|' || p_suffix), 9, 4) || '-'
    || substr(md5(p_parent::text || '|' || p_suffix), 13, 4) || '-'
    || substr(md5(p_parent::text || '|' || p_suffix), 17, 4) || '-'
    || substr(md5(p_parent::text || '|' || p_suffix), 21, 12)
  )::uuid;
$$;

-- Preserve the recurring-aware Migration 018 read and add carryover preview,
-- per-category composition, and immutable transfer history.
ALTER FUNCTION public.get_funded_budget_month(TEXT)
  RENAME TO get_funded_budget_month_recurring;

CREATE OR REPLACE FUNCTION public.get_funded_budget_month(p_month TEXT)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_state JSONB := public.get_funded_budget_month_recurring(p_month);
  v_month_start DATE := public.budget_month_start_from_key(p_month);
  v_categories JSONB;
  v_history JSONB;
BEGIN
  SELECT coalesce(jsonb_agg(
    item || jsonb_build_object(
      'incoming_carryover', coalesce(cs.incoming_carryover, 0)::numeric(18, 2)::text,
      'outgoing_carryover', coalesce(cs.outgoing_carryover, 0)::numeric(18, 2)::text
    ) ORDER BY ordinality
  ), '[]'::jsonb)
  INTO v_categories
  FROM jsonb_array_elements(coalesce(v_state->'categories', '[]'::jsonb)) WITH ORDINALITY category(item, ordinality)
  LEFT JOIN public.budget_category_carryover_state cs
    ON cs.budget_id = NULLIF(item->>'budget_id', '')::bigint;

  SELECT coalesce(jsonb_agg(jsonb_build_object(
    'transfer_id', t.id,
    'batch_id', t.batch_id,
    'source_month', to_char(source_month.month_start, 'YYYY-MM'),
    'destination_month', to_char(destination_month.month_start, 'YYYY-MM'),
    'category_id', source_budget.category_id,
    'amount', t.amount::numeric(18, 2)::text,
    'source_final_funded_snapshot', t.source_final_funded_snapshot::numeric(18, 2)::text,
    'source_raw_actual_spent_snapshot', t.source_raw_actual_spent_snapshot::numeric(18, 2)::text,
    'source_effective_actual_spent_snapshot', t.source_effective_actual_spent_snapshot::numeric(18, 2)::text,
    'reverses_transfer_id', t.reverses_transfer_id,
    'created_at', t.created_at
  ) ORDER BY t.id), '[]'::jsonb)
  INTO v_history
  FROM public.budget_carryover_transfers t
  JOIN public.budget_carryover_batches batch ON batch.id = t.batch_id
  JOIN public.budget_months source_month ON source_month.id = batch.source_budget_month_id
  JOIN public.budget_months destination_month ON destination_month.id = batch.destination_budget_month_id
  JOIN public.budgets source_budget ON source_budget.id = t.source_budget_id
  WHERE source_month.month_start = v_month_start OR destination_month.month_start = v_month_start;

  RETURN v_state
    || jsonb_build_object('categories', v_categories)
    || jsonb_build_object('carryover', public.get_budget_carryover_preview(p_month))
    || jsonb_build_object('carryover_history', v_history);
END;
$$;

CREATE OR REPLACE FUNCTION public.apply_budget_carryover(
  p_destination_month TEXT,
  p_request_key UUID,
  p_preview_fingerprint TEXT,
  p_reason TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_destination_start DATE := public.budget_month_start_from_key(p_destination_month);
  v_source_start DATE := (v_destination_start - interval '1 month')::date;
  v_current_start DATE := date_trunc(
    'month', timezone('Asia/Jerusalem', statement_timestamp())
  )::date;
  v_source_month_id BIGINT;
  v_destination_month_id BIGINT;
  v_batch_id BIGINT;
  v_existing public.budget_carryover_batches%ROWTYPE;
  v_preview JSONB;
  v_fingerprint TEXT;
  v_source_operation_id BIGINT;
  v_destination_operation_id BIGINT;
  v_destination_budget_id BIGINT;
  candidate RECORD;
BEGIN
  IF p_request_key IS NULL OR p_preview_fingerprint IS NULL
     OR p_preview_fingerprint !~ '^[0-9a-f]{32}$' THEN
    RAISE EXCEPTION 'request_key and a valid preview fingerprint are required' USING ERRCODE = '22023';
  END IF;
  IF v_destination_start <> v_current_start THEN
    RAISE EXCEPTION 'Carryover can be applied only to the current Asia/Jerusalem month'
      USING ERRCODE = '22023';
  END IF;

  SELECT * INTO v_existing FROM public.budget_carryover_batches WHERE request_key = p_request_key;
  IF FOUND THEN
    IF v_existing.request_fingerprint <> 'carryover_apply|' || p_destination_month || '|' || p_preview_fingerprint THEN
      RAISE EXCEPTION 'request_key was already used for a different carryover request'
        USING ERRCODE = '23505';
    END IF;
    RETURN jsonb_build_object(
      'source', public.get_funded_budget_month(to_char(v_source_start, 'YYYY-MM')),
      'destination', public.get_funded_budget_month(p_destination_month)
    );
  END IF;

  SELECT id INTO v_source_month_id FROM public.budget_months WHERE month_start = v_source_start;
  IF v_source_month_id IS NULL THEN
    RAISE EXCEPTION 'Previous month has no funded budget state' USING ERRCODE = '23514';
  END IF;

  -- Transaction writes take ROW EXCLUSIVE on this table. Taking SHARE before
  -- any budget-month lock gives apply a short, deadlock-safe serialization
  -- boundary: the captured actuals cannot change through the final write.
  LOCK TABLE public.transactions IN SHARE MODE;

  INSERT INTO public.budget_months (month_start) VALUES (v_destination_start)
  ON CONFLICT (month_start) DO NOTHING;
  SELECT id INTO v_destination_month_id FROM public.budget_months WHERE month_start = v_destination_start;

  -- Canonical cross-month order: month rows by ID, budget rows by ID,
  -- settings/categories, then immutable operations and history.
  PERFORM 1 FROM public.budget_months
  WHERE id IN (v_source_month_id, v_destination_month_id)
  ORDER BY id FOR UPDATE;
  PERFORM 1 FROM public.budgets
  WHERE budget_month_id IN (v_source_month_id, v_destination_month_id)
  ORDER BY id FOR UPDATE;
  PERFORM 1 FROM public.categories c
  JOIN public.budget_carryover_settings setting ON setting.category_id = c.id
  ORDER BY c.id FOR SHARE OF c;
  PERFORM 1 FROM public.budget_carryover_settings
  ORDER BY category_id FOR SHARE;

  PERFORM public.budget_assert_reconciled(v_source_month_id);
  PERFORM public.budget_assert_reconciled(v_destination_month_id);

  -- A concurrent retry may have observed no batch before waiting on the
  -- canonical month locks. Re-check after serialization before writing.
  SELECT * INTO v_existing FROM public.budget_carryover_batches WHERE request_key = p_request_key;
  IF FOUND THEN
    IF v_existing.request_fingerprint <> 'carryover_apply|' || p_destination_month || '|' || p_preview_fingerprint THEN
      RAISE EXCEPTION 'request_key was already used for a different carryover request'
        USING ERRCODE = '23505';
    END IF;
    RETURN jsonb_build_object(
      'source', public.get_funded_budget_month(to_char(v_source_start, 'YYYY-MM')),
      'destination', public.get_funded_budget_month(p_destination_month)
    );
  END IF;

  v_preview := public.get_budget_carryover_preview(p_destination_month);
  v_fingerprint := v_preview->>'fingerprint';
  IF v_fingerprint IS DISTINCT FROM p_preview_fingerprint THEN
    RAISE EXCEPTION 'CARRYOVER_PREVIEW_STALE: carryover candidate material changed; refresh before applying'
      USING ERRCODE = '40001';
  END IF;

  INSERT INTO public.budget_carryover_batches (
    request_key, request_fingerprint, source_budget_month_id, destination_budget_month_id
  ) VALUES (
    p_request_key,
    'carryover_apply|' || p_destination_month || '|' || p_preview_fingerprint,
    v_source_month_id,
    v_destination_month_id
  ) RETURNING id INTO v_batch_id;

  FOR candidate IN
    SELECT item
    FROM jsonb_array_elements(v_preview->'ready_categories') AS captured(item)
    ORDER BY (item->>'category_id')::bigint
  LOOP
    INSERT INTO public.budget_operations (
      budget_month_id, request_key, request_fingerprint, operation_type, effective_date, reason
    ) VALUES (
      v_source_month_id,
      public.budget_derived_request_key(p_request_key, 'source|' || (candidate.item->>'category_id')),
      'carryover_out|' || v_batch_id || '|' || (candidate.item->>'category_id') || '|' || (candidate.item->>'amount'),
      'carryover_out', v_source_start, p_reason
    ) RETURNING id INTO v_source_operation_id;

    INSERT INTO public.budget_funding_entries (
      operation_id, amount_delta, source_kind, source_label
    ) VALUES (
      v_source_operation_id, -(candidate.item->>'amount')::numeric(18, 2), 'carryover_transfer',
      'Carryover to ' || p_destination_month
    );
    INSERT INTO public.budget_movements (
      operation_id, source_budget_id, destination_budget_id, amount
    ) VALUES (
      v_source_operation_id, (candidate.item->>'source_budget_id')::bigint, NULL,
      (candidate.item->>'amount')::numeric(18, 2)
    );

    INSERT INTO public.budget_operations (
      budget_month_id, request_key, request_fingerprint, operation_type, effective_date, reason
    ) VALUES (
      v_destination_month_id,
      public.budget_derived_request_key(p_request_key, 'destination|' || (candidate.item->>'category_id')),
      'carryover_in|' || v_batch_id || '|' || (candidate.item->>'category_id') || '|' || (candidate.item->>'amount'),
      'carryover_in', v_destination_start, p_reason
    ) RETURNING id INTO v_destination_operation_id;

    IF candidate.item->>'destination_budget_id' IS NULL THEN
      INSERT INTO public.budgets (
        category_id, month, amount, budget_month_id, starting_amount,
        starting_kind, created_by_operation_id
      ) VALUES (
        (candidate.item->>'category_id')::bigint, p_destination_month, 0, v_destination_month_id,
        0, 'carryover_only', v_destination_operation_id
      ) RETURNING id INTO v_destination_budget_id;
      INSERT INTO public.budget_lifecycle_events (operation_id, budget_id, state)
      VALUES (v_destination_operation_id, v_destination_budget_id, 'active');
    ELSE
      v_destination_budget_id := (candidate.item->>'destination_budget_id')::bigint;
    END IF;

    INSERT INTO public.budget_funding_entries (
      operation_id, amount_delta, source_kind, source_label
    ) VALUES (
      v_destination_operation_id, (candidate.item->>'amount')::numeric(18, 2), 'carryover_transfer',
      'Carryover from ' || to_char(v_source_start, 'YYYY-MM')
    );
    INSERT INTO public.budget_movements (
      operation_id, source_budget_id, destination_budget_id, amount
    ) VALUES (
      v_destination_operation_id, NULL, v_destination_budget_id,
      (candidate.item->>'amount')::numeric(18, 2)
    );

    INSERT INTO public.budget_carryover_transfers (
      batch_id, source_budget_id, destination_budget_id,
      source_operation_id, destination_operation_id, amount,
      source_final_funded_snapshot, source_raw_actual_spent_snapshot,
      source_effective_actual_spent_snapshot
    ) VALUES (
      v_batch_id, (candidate.item->>'source_budget_id')::bigint, v_destination_budget_id,
      v_source_operation_id, v_destination_operation_id,
      (candidate.item->>'amount')::numeric(18, 2),
      (candidate.item->>'source_final_funded')::numeric(18, 2),
      (candidate.item->>'source_raw_actual_spent')::numeric(18, 2),
      (candidate.item->>'source_effective_actual_spent')::numeric(18, 2)
    );
  END LOOP;

  PERFORM public.budget_assert_reconciled(v_source_month_id);
  PERFORM public.budget_assert_reconciled(v_destination_month_id);
  RETURN jsonb_build_object(
    'source', public.get_funded_budget_month(to_char(v_source_start, 'YYYY-MM')),
    'destination', public.get_funded_budget_month(p_destination_month)
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.reverse_budget_carryover(
  p_transfer_id BIGINT,
  p_request_key UUID,
  p_reason TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_original public.budget_carryover_transfers%ROWTYPE;
  v_batch public.budget_carryover_batches%ROWTYPE;
  v_source public.budget_category_state%ROWTYPE;
  v_destination public.budget_category_state%ROWTYPE;
  v_source_month public.budget_months%ROWTYPE;
  v_destination_month public.budget_months%ROWTYPE;
  v_destination_actual NUMERIC(18, 2);
  v_existing public.budget_operations%ROWTYPE;
  v_source_operation_id BIGINT;
  v_destination_operation_id BIGINT;
  v_source_funding public.budget_funding_entries%ROWTYPE;
  v_destination_funding public.budget_funding_entries%ROWTYPE;
BEGIN
  IF p_transfer_id IS NULL OR p_request_key IS NULL THEN
    RAISE EXCEPTION 'transfer_id and request_key are required' USING ERRCODE = '22023';
  END IF;
  SELECT * INTO v_original FROM public.budget_carryover_transfers WHERE id = p_transfer_id;
  IF NOT FOUND OR v_original.reverses_transfer_id IS NOT NULL THEN
    RAISE EXCEPTION 'Original carryover transfer % does not exist', p_transfer_id USING ERRCODE = 'P0002';
  END IF;
  SELECT * INTO v_batch FROM public.budget_carryover_batches WHERE id = v_original.batch_id;

  SELECT * INTO v_existing FROM public.budget_operations WHERE request_key = p_request_key;
  IF FOUND THEN
    IF v_existing.operation_type <> 'carryover_out'
       OR v_existing.request_fingerprint <> 'carryover_reverse|' || p_transfer_id THEN
      RAISE EXCEPTION 'request_key was already used for a different carryover request'
        USING ERRCODE = '23505';
    END IF;
    RETURN jsonb_build_object(
      'source', public.get_funded_budget_month((SELECT month FROM public.budget_month_funding_state WHERE budget_month_id = v_batch.source_budget_month_id)),
      'destination', public.get_funded_budget_month((SELECT month FROM public.budget_month_funding_state WHERE budget_month_id = v_batch.destination_budget_month_id))
    );
  END IF;
  IF EXISTS (SELECT 1 FROM public.budget_carryover_transfers WHERE reverses_transfer_id = p_transfer_id) THEN
    RAISE EXCEPTION 'Carryover transfer % has already been reversed', p_transfer_id USING ERRCODE = '23505';
  END IF;

  -- Keep the destination-spending safety check linearizable with transaction
  -- inserts, updates, and deletes for the duration of the compensating write.
  LOCK TABLE public.transactions IN SHARE MODE;

  PERFORM 1 FROM public.budget_months
  WHERE id IN (v_batch.source_budget_month_id, v_batch.destination_budget_month_id)
  ORDER BY id FOR UPDATE;
  PERFORM 1 FROM public.budgets
  WHERE id IN (v_original.source_budget_id, v_original.destination_budget_id)
  ORDER BY id FOR UPDATE;

  -- Re-check idempotency and prior reversal after the shared month/budget
  -- lock order has serialized concurrent correction attempts.
  SELECT * INTO v_existing FROM public.budget_operations WHERE request_key = p_request_key;
  IF FOUND THEN
    IF v_existing.operation_type <> 'carryover_out'
       OR v_existing.request_fingerprint <> 'carryover_reverse|' || p_transfer_id THEN
      RAISE EXCEPTION 'request_key was already used for a different carryover request'
        USING ERRCODE = '23505';
    END IF;
    RETURN jsonb_build_object(
      'source', public.get_funded_budget_month((SELECT month FROM public.budget_month_funding_state WHERE budget_month_id = v_batch.source_budget_month_id)),
      'destination', public.get_funded_budget_month((SELECT month FROM public.budget_month_funding_state WHERE budget_month_id = v_batch.destination_budget_month_id))
    );
  END IF;
  IF EXISTS (SELECT 1 FROM public.budget_carryover_transfers WHERE reverses_transfer_id = p_transfer_id) THEN
    RAISE EXCEPTION 'Carryover transfer % has already been reversed', p_transfer_id USING ERRCODE = '23505';
  END IF;

  SELECT * INTO v_source FROM public.budget_category_state WHERE budget_id = v_original.source_budget_id;
  SELECT * INTO v_destination FROM public.budget_category_state WHERE budget_id = v_original.destination_budget_id;
  SELECT * INTO v_source_month FROM public.budget_months WHERE id = v_batch.source_budget_month_id;
  SELECT * INTO v_destination_month FROM public.budget_months WHERE id = v_batch.destination_budget_month_id;
  IF v_source.lifecycle_state <> 'active' OR v_destination.lifecycle_state <> 'active' THEN
    RAISE EXCEPTION 'Carryover reversal requires active source and destination budgets'
      USING ERRCODE = '23514';
  END IF;
  IF EXISTS (
    SELECT 1 FROM public.transactions
    WHERE movement_type = 'expense'
      AND category_id = v_destination.category_id
      AND transaction_date >= v_destination_month.month_start
      AND transaction_date < (v_destination_month.month_start + interval '1 month')::date
      AND total_amount::text IN ('NaN', 'Infinity', '-Infinity')
  ) THEN
    RAISE EXCEPTION 'Carryover actual spending contains a non-finite amount' USING ERRCODE = '22003';
  END IF;
  SELECT greatest(coalesce(sum(total_amount), 0), 0)::numeric(18, 2)
  INTO v_destination_actual
  FROM public.transactions
  WHERE movement_type = 'expense'
    AND category_id = v_destination.category_id
    AND transaction_date >= v_destination_month.month_start
    AND transaction_date < (v_destination_month.month_start + interval '1 month')::date;
  IF v_original.amount > greatest(v_destination.final_funded - v_destination_actual, 0) THEN
    RAISE EXCEPTION 'Carryover reversal would release spent destination funding'
      USING ERRCODE = '23514';
  END IF;

  SELECT * INTO v_source_funding FROM public.budget_funding_entries
  WHERE operation_id = v_original.source_operation_id;
  SELECT * INTO v_destination_funding FROM public.budget_funding_entries
  WHERE operation_id = v_original.destination_operation_id;

  INSERT INTO public.budget_operations (
    budget_month_id, request_key, request_fingerprint, operation_type,
    effective_date, reason, reverses_operation_id
  ) VALUES (
    v_batch.destination_budget_month_id, p_request_key,
    'carryover_reverse|' || p_transfer_id, 'carryover_out',
    v_destination_month.month_start, p_reason, v_original.destination_operation_id
  ) RETURNING id INTO v_destination_operation_id;
  INSERT INTO public.budget_funding_entries (
    operation_id, amount_delta, source_kind, source_label, reverses_funding_entry_id
  ) VALUES (
    v_destination_operation_id, -v_original.amount, 'carryover_transfer',
    'Carryover reversal to ' || to_char(v_source_month.month_start, 'YYYY-MM'),
    v_destination_funding.id
  );
  INSERT INTO public.budget_movements (operation_id, source_budget_id, amount)
  VALUES (v_destination_operation_id, v_original.destination_budget_id, v_original.amount);

  INSERT INTO public.budget_operations (
    budget_month_id, request_key, request_fingerprint, operation_type,
    effective_date, reason, reverses_operation_id
  ) VALUES (
    v_batch.source_budget_month_id,
    public.budget_derived_request_key(p_request_key, 'source-return'),
    'carryover_reverse_return|' || p_transfer_id, 'carryover_in',
    v_source_month.month_start, p_reason, v_original.source_operation_id
  ) RETURNING id INTO v_source_operation_id;
  INSERT INTO public.budget_funding_entries (
    operation_id, amount_delta, source_kind, source_label, reverses_funding_entry_id
  ) VALUES (
    v_source_operation_id, v_original.amount, 'carryover_transfer',
    'Carryover reversal from ' || to_char(v_destination_month.month_start, 'YYYY-MM'),
    v_source_funding.id
  );
  INSERT INTO public.budget_movements (operation_id, destination_budget_id, amount)
  VALUES (v_source_operation_id, v_original.source_budget_id, v_original.amount);

  INSERT INTO public.budget_carryover_transfers (
    batch_id, source_budget_id, destination_budget_id,
    source_operation_id, destination_operation_id, amount,
    source_final_funded_snapshot, source_raw_actual_spent_snapshot,
    source_effective_actual_spent_snapshot,
    reverses_transfer_id
  ) VALUES (
    v_original.batch_id, v_original.source_budget_id, v_original.destination_budget_id,
    v_source_operation_id, v_destination_operation_id, v_original.amount,
    v_original.source_final_funded_snapshot, v_original.source_raw_actual_spent_snapshot,
    v_original.source_effective_actual_spent_snapshot,
    v_original.id
  );

  PERFORM public.budget_assert_reconciled(v_batch.source_budget_month_id);
  PERFORM public.budget_assert_reconciled(v_batch.destination_budget_month_id);
  RETURN jsonb_build_object(
    'source', public.get_funded_budget_month(to_char(v_source_month.month_start, 'YYYY-MM')),
    'destination', public.get_funded_budget_month(to_char(v_destination_month.month_start, 'YYYY-MM'))
  );
END;
$$;

ALTER TABLE public.budget_carryover_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.budget_carryover_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.budget_carryover_transfers ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.budget_carryover_settings,
  public.budget_carryover_batches,
  public.budget_carryover_transfers,
  public.budget_carryover_settings_read,
  public.budget_category_carryover_state
  FROM PUBLIC, anon, authenticated, service_role;
GRANT SELECT ON public.budget_carryover_settings,
  public.budget_carryover_batches,
  public.budget_carryover_transfers,
  public.budget_carryover_settings_read,
  public.budget_category_carryover_state
  TO service_role;

REVOKE ALL ON FUNCTION public.validate_budget_carryover_setting(),
  public.prevent_category_type_with_carryover(),
  public.validate_budget_carryover_batch_insert(),
  public.validate_budget_carryover_transfer_insert(),
  public.budget_carryover_candidate_rows(TEXT),
  public.get_budget_carryover_preview(TEXT),
  public.budget_derived_request_key(UUID, TEXT),
  public.get_funded_budget_month_recurring(TEXT)
  FROM PUBLIC, anon, authenticated, service_role;

REVOKE ALL ON FUNCTION public.set_budget_carryover_enabled(BIGINT, BOOLEAN),
  public.apply_budget_carryover(TEXT, UUID, TEXT, TEXT),
  public.reverse_budget_carryover(BIGINT, UUID, TEXT)
  FROM PUBLIC, anon, authenticated;

REVOKE EXECUTE ON FUNCTION public.get_funded_budget_month(TEXT)
  FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.get_funded_budget_month(TEXT),
  public.set_budget_carryover_enabled(BIGINT, BOOLEAN),
  public.apply_budget_carryover(TEXT, UUID, TEXT, TEXT),
  public.reverse_budget_carryover(BIGINT, UUID, TEXT)
  TO service_role;

-- The Migration 018 wrapper is now internal; the service role calls only the
-- Migration 019 canonical wrapper.
REVOKE EXECUTE ON FUNCTION public.get_funded_budget_month_recurring(TEXT)
  FROM service_role;

COMMIT;
