-- Migration 020: month-specific funded-budget base overrides.
--
-- Override rows are mutable planning configuration. Once a category snapshot
-- exists, the funded result is represented only by immutable operations,
-- movements, lifecycle events, and append-only override provenance.

BEGIN;

DO $$
BEGIN
  IF to_regclass('public.budget_months') IS NULL
     OR to_regclass('public.budget_carryover_transfers') IS NULL
     OR to_regclass('public.budget_recurring_defaults') IS NULL
     OR to_regprocedure('public.get_funded_budget_month(text)') IS NULL
     OR to_regprocedure('public.budget_derived_request_key(uuid,text)') IS NULL THEN
    RAISE EXCEPTION 'Migration 020 preflight: Migrations 017, 018, and 019 are required';
  END IF;
  IF to_regclass('public.budget_month_overrides') IS NOT NULL
     OR to_regclass('public.budget_month_override_events') IS NOT NULL
     OR to_regclass('public.budget_category_base_state') IS NOT NULL
     OR to_regprocedure('public.set_budget_month_override(text,bigint,numeric,uuid,text)') IS NOT NULL
     OR to_regprocedure('public.remove_budget_month_override(text,bigint,uuid,text)') IS NOT NULL THEN
    RAISE EXCEPTION 'Migration 020 preflight: unexpected partial month-override schema exists';
  END IF;
END;
$$;

ALTER TABLE public.budgets
  DROP CONSTRAINT budgets_starting_kind_check,
  ADD CONSTRAINT budgets_starting_kind_check CHECK (
    starting_kind IN (
      'manual', 'legacy_import', 'copied', 'recurring_default',
      'carryover_only', 'monthly_override'
    )
  );

ALTER TABLE public.budget_operations
  DROP CONSTRAINT budget_operations_operation_type_check,
  ADD CONSTRAINT budget_operations_operation_type_check CHECK (operation_type IN (
    'legacy_import', 'manual_funding', 'establish_budget', 'adjustment',
    'removal', 'reactivation', 'copy', 'reversal', 'month_initialization',
    'carryover_out', 'carryover_in', 'monthly_override_set',
    'monthly_override_remove'
  ));

CREATE TABLE public.budget_month_overrides (
  budget_month_id BIGINT NOT NULL REFERENCES public.budget_months(id) ON DELETE RESTRICT,
  category_id BIGINT NOT NULL REFERENCES public.categories(id) ON DELETE RESTRICT,
  amount NUMERIC(18, 2) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  PRIMARY KEY (budget_month_id, category_id),
  CONSTRAINT budget_month_overrides_amount_check CHECK (
    amount::text NOT IN ('NaN', 'Infinity', '-Infinity') AND amount >= 0
  )
);

CREATE TABLE public.budget_month_override_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_key UUID NOT NULL UNIQUE,
  request_fingerprint TEXT NOT NULL CHECK (btrim(request_fingerprint) <> ''),
  budget_month_id BIGINT NOT NULL REFERENCES public.budget_months(id) ON DELETE RESTRICT,
  category_id BIGINT NOT NULL REFERENCES public.categories(id) ON DELETE RESTRICT,
  budget_id BIGINT REFERENCES public.budgets(id) ON DELETE RESTRICT,
  financial_operation_id BIGINT REFERENCES public.budget_operations(id) ON DELETE RESTRICT,
  action TEXT NOT NULL CHECK (action IN ('set', 'remove', 'initialize')),
  requested_override_amount NUMERIC(18, 2),
  previous_effective_base NUMERIC(18, 2) NOT NULL,
  resulting_effective_base NUMERIC(18, 2) NOT NULL,
  fallback_base_snapshot NUMERIC(18, 2) NOT NULL,
  fallback_source TEXT NOT NULL CHECK (fallback_source IN (
    'none', 'manual', 'legacy_import', 'copied', 'recurring_default',
    'carryover_only', 'monthly_override'
  )),
  applied_base_delta NUMERIC(18, 2) NOT NULL,
  reverses_event_id BIGINT UNIQUE REFERENCES public.budget_month_override_events(id) ON DELETE RESTRICT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT budget_month_override_events_money_check CHECK (
    previous_effective_base::text NOT IN ('NaN', 'Infinity', '-Infinity')
    AND resulting_effective_base::text NOT IN ('NaN', 'Infinity', '-Infinity')
    AND fallback_base_snapshot::text NOT IN ('NaN', 'Infinity', '-Infinity')
    AND applied_base_delta::text NOT IN ('NaN', 'Infinity', '-Infinity')
    AND previous_effective_base >= 0
    AND resulting_effective_base >= 0
    AND fallback_base_snapshot >= 0
    AND (requested_override_amount IS NULL OR (
      requested_override_amount::text NOT IN ('NaN', 'Infinity', '-Infinity')
      AND requested_override_amount >= 0
    ))
  ),
  CONSTRAINT budget_month_override_events_action_amount_check CHECK (
    (action IN ('set', 'initialize') AND requested_override_amount IS NOT NULL)
    OR (action = 'remove' AND requested_override_amount IS NULL)
  ),
  CONSTRAINT budget_month_override_events_not_self_reversing CHECK (
    reverses_event_id IS NULL OR reverses_event_id <> id
  )
);

CREATE INDEX idx_budget_month_override_events_month_category
  ON public.budget_month_override_events (budget_month_id, category_id, id);
CREATE INDEX idx_budget_month_override_events_budget
  ON public.budget_month_override_events (budget_id, id)
  WHERE budget_id IS NOT NULL;

CREATE OR REPLACE FUNCTION public.validate_budget_month_override()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM public.categories
    WHERE id = NEW.category_id AND type = 'expense' AND is_active = true
  ) THEN
    RAISE EXCEPTION 'Month overrides are available only for active expense categories'
      USING ERRCODE = '23514';
  END IF;
  IF NEW.amount::text IN ('NaN', 'Infinity', '-Infinity') OR NEW.amount < 0 THEN
    RAISE EXCEPTION 'Month override amount must be a finite nonnegative NUMERIC(18,2) value'
      USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.prevent_category_type_with_month_override()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
BEGIN
  IF (OLD.type = 'expense' AND NEW.type <> 'expense'
      OR OLD.is_active = true AND NEW.is_active = false)
     AND EXISTS (
       SELECT 1 FROM public.budget_month_overrides WHERE category_id = OLD.id
     ) THEN
    RAISE EXCEPTION 'Remove month overrides before changing this category type or active state'
      USING ERRCODE = '23514';
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.validate_budget_month_override_event()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_budget public.budgets%ROWTYPE;
  v_operation public.budget_operations%ROWTYPE;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.categories WHERE id = NEW.category_id AND type = 'expense') THEN
    RAISE EXCEPTION 'Month override events require an expense category' USING ERRCODE = '23514';
  END IF;
  IF NEW.budget_id IS NOT NULL THEN
    SELECT * INTO v_budget FROM public.budgets WHERE id = NEW.budget_id;
    IF NOT FOUND OR v_budget.budget_month_id <> NEW.budget_month_id
       OR v_budget.category_id <> NEW.category_id THEN
      RAISE EXCEPTION 'Month override event budget does not match its month/category'
        USING ERRCODE = '23514';
    END IF;
  END IF;
  IF NEW.financial_operation_id IS NOT NULL THEN
    SELECT * INTO v_operation FROM public.budget_operations WHERE id = NEW.financial_operation_id;
    IF NOT FOUND OR v_operation.budget_month_id <> NEW.budget_month_id
       OR v_operation.operation_type NOT IN ('monthly_override_set', 'monthly_override_remove', 'month_initialization') THEN
      RAISE EXCEPTION 'Month override event operation does not match its month/action'
        USING ERRCODE = '23514';
    END IF;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER budget_month_overrides_validate
BEFORE INSERT OR UPDATE ON public.budget_month_overrides
FOR EACH ROW EXECUTE FUNCTION public.validate_budget_month_override();
CREATE TRIGGER categories_month_override_guard
BEFORE UPDATE OF type, is_active ON public.categories
FOR EACH ROW EXECUTE FUNCTION public.prevent_category_type_with_month_override();
CREATE TRIGGER budget_month_override_events_validate
BEFORE INSERT ON public.budget_month_override_events
FOR EACH ROW EXECUTE FUNCTION public.validate_budget_month_override_event();
CREATE TRIGGER budget_month_override_events_immutable
BEFORE UPDATE OR DELETE ON public.budget_month_override_events
FOR EACH ROW EXECUTE FUNCTION public.prevent_budget_history_mutation();

CREATE VIEW public.budget_month_overrides_read AS
SELECT
  mo.budget_month_id,
  to_char(bm.month_start, 'YYYY-MM') AS month,
  mo.category_id,
  mo.amount::numeric(18, 2)::text AS amount_text,
  mo.created_at,
  mo.updated_at
FROM public.budget_month_overrides mo
JOIN public.budget_months bm ON bm.id = mo.budget_month_id;

-- This view is the authoritative base/carryover/other-adjustment decomposition.
-- Starting snapshots and all movements remain immutable; no mutable override row
-- is used to calculate funded history.
CREATE VIEW public.budget_category_base_state AS
WITH override_events AS (
  SELECT
    e.budget_id,
    coalesce(sum(e.applied_base_delta) FILTER (
      WHERE e.financial_operation_id IS NOT NULL
        AND e.action IN ('set', 'remove')
    ), 0)::numeric(18, 2) AS override_adjustment_total
  FROM public.budget_month_override_events e
  WHERE e.budget_id IS NOT NULL
  GROUP BY e.budget_id
), initialization AS (
  SELECT DISTINCT ON (e.budget_id)
    e.budget_id, e.fallback_base_snapshot, e.fallback_source
  FROM public.budget_month_override_events e
  WHERE e.action = 'initialize' AND e.budget_id IS NOT NULL
  ORDER BY e.budget_id, e.id
)
SELECT
  cs.budget_id,
  cs.budget_month_id,
  cs.month,
  cs.month_start,
  cs.category_id,
  CASE WHEN cs.starting_kind = 'monthly_override'
    THEN coalesce(init.fallback_base_snapshot, 0)
    ELSE cs.starting_amount
  END::numeric(18, 2) AS fallback_base,
  CASE WHEN cs.starting_kind = 'monthly_override'
    THEN coalesce(init.fallback_source, 'none')
    ELSE cs.starting_kind
  END AS fallback_source,
  mo.amount AS current_override,
  coalesce(events.override_adjustment_total, 0)::numeric(18, 2) AS override_adjustment_total,
  (cs.starting_amount + coalesce(events.override_adjustment_total, 0))::numeric(18, 2)
    AS effective_base,
  coalesce(carry.incoming_carryover, 0)::numeric(18, 2) AS incoming_carryover,
  coalesce(carry.outgoing_carryover, 0)::numeric(18, 2) AS outgoing_carryover,
  (
    cs.adjustment_total - coalesce(events.override_adjustment_total, 0)
    - coalesce(carry.incoming_carryover, 0) + coalesce(carry.outgoing_carryover, 0)
  )::numeric(18, 2) AS other_adjustments,
  cs.final_funded,
  cs.lifecycle_state
FROM public.budget_category_state cs
LEFT JOIN override_events events ON events.budget_id = cs.budget_id
LEFT JOIN initialization init ON init.budget_id = cs.budget_id
LEFT JOIN public.budget_month_overrides mo
  ON mo.budget_month_id = cs.budget_month_id AND mo.category_id = cs.category_id
LEFT JOIN public.budget_category_carryover_state carry ON carry.budget_id = cs.budget_id;

CREATE OR REPLACE FUNCTION public.get_budget_month_override_preview(p_month TEXT)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_month_start DATE := public.budget_month_start_from_key(p_month);
  v_current_start DATE := date_trunc('month', timezone('Asia/Jerusalem', statement_timestamp()))::date;
  v_month_id BIGINT;
  v_rows JSONB;
BEGIN
  SELECT id INTO v_month_id FROM public.budget_months WHERE month_start = v_month_start;
  SELECT coalesce(jsonb_agg(jsonb_build_object(
    'category_id', mo.category_id,
    'category', jsonb_build_object('name', c.name, 'icon', c.icon, 'type', c.type),
    'amount', mo.amount::numeric(18, 2)::text,
    'initialized', base.budget_id IS NOT NULL,
    'fallback_base', coalesce(base.fallback_base, rd.amount, 0)::numeric(18, 2)::text,
    'fallback_source', coalesce(base.fallback_source,
      CASE WHEN rd.category_id IS NULL THEN 'none' ELSE 'recurring_default' END),
    'effective_base', coalesce(base.effective_base, mo.amount)::numeric(18, 2)::text
  ) ORDER BY c.name, mo.category_id), '[]'::jsonb)
  INTO v_rows
  FROM public.budget_month_overrides mo
  JOIN public.categories c ON c.id = mo.category_id
  LEFT JOIN public.budget_category_base_state base
    ON base.budget_month_id = mo.budget_month_id AND base.category_id = mo.category_id
  LEFT JOIN public.budget_recurring_defaults rd ON rd.category_id = mo.category_id
  WHERE mo.budget_month_id = v_month_id;
  RETURN jsonb_build_object(
    'eligible', v_month_start >= v_current_start,
    'month', p_month,
    'overrides', v_rows,
    'count', jsonb_array_length(v_rows)
  );
END;
$$;

-- Preserve the Migration 019 read and extend it with a truthful base
-- composition. This function remains STABLE and creates no planning or
-- financial state when a month is opened.
ALTER FUNCTION public.get_funded_budget_month(TEXT)
  RENAME TO get_funded_budget_month_carryover;

CREATE OR REPLACE FUNCTION public.get_funded_budget_month(p_month TEXT)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_state JSONB := public.get_funded_budget_month_carryover(p_month);
  v_categories JSONB;
BEGIN
  SELECT coalesce(jsonb_agg(
    item || jsonb_build_object(
      'fallback_base', CASE WHEN base.budget_id IS NULL THEN NULL ELSE base.fallback_base::numeric(18, 2)::text END,
      'fallback_source', base.fallback_source,
      'recurring_default', CASE WHEN rd.amount IS NULL THEN NULL ELSE rd.amount::numeric(18, 2)::text END,
      'month_override', CASE WHEN base.current_override IS NULL THEN NULL ELSE base.current_override::numeric(18, 2)::text END,
      'override_adjustment_total', coalesce(base.override_adjustment_total, 0)::numeric(18, 2)::text,
      'effective_base', CASE WHEN base.budget_id IS NULL THEN NULL ELSE base.effective_base::numeric(18, 2)::text END,
      'incoming_carryover', coalesce(base.incoming_carryover, 0)::numeric(18, 2)::text,
      'outgoing_carryover', coalesce(base.outgoing_carryover, 0)::numeric(18, 2)::text,
      'other_adjustments', coalesce(base.other_adjustments, 0)::numeric(18, 2)::text
    ) ORDER BY ordinality
  ), '[]'::jsonb)
  INTO v_categories
  FROM jsonb_array_elements(coalesce(v_state->'categories', '[]'::jsonb))
    WITH ORDINALITY category(item, ordinality)
  LEFT JOIN public.budget_category_base_state base
    ON base.budget_id = NULLIF(item->>'budget_id', '')::bigint
  LEFT JOIN public.budget_recurring_defaults rd
    ON rd.category_id = NULLIF(item->>'category_id', '')::bigint;

  RETURN v_state
    || jsonb_build_object('categories', v_categories)
    || jsonb_build_object('month_overrides', public.get_budget_month_override_preview(p_month));
END;
$$;

CREATE OR REPLACE FUNCTION public.set_budget_month_override(
  p_month TEXT,
  p_category_id BIGINT,
  p_amount NUMERIC,
  p_request_key UUID,
  p_reason TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_month_start DATE := public.budget_month_start_from_key(p_month);
  v_current_start DATE := date_trunc('month', timezone('Asia/Jerusalem', statement_timestamp()))::date;
  v_month_id BIGINT;
  v_budget public.budget_category_state%ROWTYPE;
  v_base public.budget_category_base_state%ROWTYPE;
  v_existing_event public.budget_month_override_events%ROWTYPE;
  v_initialized BOOLEAN;
  v_fingerprint TEXT;
  v_operation_id BIGINT;
  v_delta NUMERIC(18, 2);
  v_unallocated NUMERIC(18, 2);
  v_raw_actual NUMERIC;
  v_effective_actual NUMERIC(18, 2);
  v_base_headroom NUMERIC(18, 2);
  v_total_headroom NUMERIC(18, 2);
  v_eligible_release NUMERIC(18, 2);
  v_fallback NUMERIC(18, 2);
  v_fallback_source TEXT;
  v_prior_override NUMERIC(18, 2);
BEGIN
  IF p_request_key IS NULL OR p_category_id IS NULL OR p_amount IS NULL THEN
    RAISE EXCEPTION 'month, category_id, amount, and request_key are required' USING ERRCODE = '22023';
  END IF;
  IF p_amount::text IN ('NaN', 'Infinity', '-Infinity') OR p_amount < 0
     OR p_amount <> round(p_amount, 2) OR p_amount > 9999999999999999.99 THEN
    RAISE EXCEPTION 'Month override amount must be a finite nonnegative two-decimal value'
      USING ERRCODE = '22023';
  END IF;
  IF v_month_start < v_current_start THEN
    RAISE EXCEPTION 'HISTORICAL_MONTH_OVERRIDE_FORBIDDEN: month overrides are limited to current/future Asia/Jerusalem months'
      USING ERRCODE = '22023';
  END IF;
  v_fingerprint := 'month_override_set|' || p_month || '|' || p_category_id || '|'
    || p_amount::numeric(18, 2)::text;

  -- ROW EXCLUSIVE transaction mutations conflict with SHARE. Taking this
  -- first makes every release calculation stable through its final write and
  -- preserves the same global order used by carryover.
  LOCK TABLE public.transactions IN SHARE MODE;
  INSERT INTO public.budget_months (month_start) VALUES (v_month_start)
  ON CONFLICT (month_start) DO NOTHING;
  SELECT id INTO v_month_id FROM public.budget_months WHERE month_start = v_month_start FOR UPDATE;
  PERFORM 1 FROM public.budgets WHERE budget_month_id = v_month_id ORDER BY id FOR UPDATE;
  PERFORM 1 FROM public.categories WHERE id = p_category_id FOR SHARE;
  IF NOT EXISTS (
    SELECT 1 FROM public.categories
    WHERE id = p_category_id AND type = 'expense' AND is_active = true
  ) THEN
    RAISE EXCEPTION 'Month overrides are available only for active expense categories'
      USING ERRCODE = '23514';
  END IF;
  PERFORM 1 FROM public.budget_recurring_defaults WHERE category_id = p_category_id FOR SHARE;
  PERFORM 1 FROM public.budget_month_overrides
    WHERE budget_month_id = v_month_id AND category_id = p_category_id FOR UPDATE;

  SELECT * INTO v_existing_event
  FROM public.budget_month_override_events WHERE request_key = p_request_key;
  IF FOUND THEN
    IF v_existing_event.request_fingerprint <> v_fingerprint THEN
      RAISE EXCEPTION 'request_key was already used for a different month override request'
        USING ERRCODE = '23505';
    END IF;
    RETURN public.get_funded_budget_month(p_month);
  END IF;

  SELECT EXISTS (
    SELECT 1 FROM public.budget_operations
    WHERE budget_month_id = v_month_id AND operation_type = 'month_initialization'
  ) INTO v_initialized;
  SELECT * INTO v_budget FROM public.budget_category_state
    WHERE budget_month_id = v_month_id AND category_id = p_category_id;
  SELECT amount INTO v_prior_override FROM public.budget_month_overrides
    WHERE budget_month_id = v_month_id AND category_id = p_category_id;

  IF v_budget.budget_id IS NULL AND NOT v_initialized THEN
    SELECT coalesce(amount, 0)::numeric(18, 2),
      CASE WHEN amount IS NULL THEN 'none' ELSE 'recurring_default' END
    INTO v_fallback, v_fallback_source
    FROM (SELECT (SELECT amount FROM public.budget_recurring_defaults
                  WHERE category_id = p_category_id) AS amount) recurring;
    INSERT INTO public.budget_month_overrides (budget_month_id, category_id, amount)
    VALUES (v_month_id, p_category_id, p_amount::numeric(18, 2))
    ON CONFLICT (budget_month_id, category_id) DO UPDATE
    SET amount = EXCLUDED.amount, updated_at = timezone('utc'::text, now());
    INSERT INTO public.budget_month_override_events (
      request_key, request_fingerprint, budget_month_id, category_id, action,
      requested_override_amount, previous_effective_base, resulting_effective_base,
      fallback_base_snapshot, fallback_source, applied_base_delta
    ) VALUES (
      p_request_key, v_fingerprint, v_month_id, p_category_id, 'set', p_amount,
      coalesce(v_prior_override, v_fallback), p_amount, v_fallback, v_fallback_source, 0
    );
    RETURN public.get_funded_budget_month(p_month);
  END IF;

  IF v_budget.budget_id IS NULL THEN
    SELECT coalesce(amount, 0)::numeric(18, 2),
      CASE WHEN amount IS NULL THEN 'none' ELSE 'recurring_default' END
    INTO v_fallback, v_fallback_source
    FROM (SELECT (SELECT amount FROM public.budget_recurring_defaults
                  WHERE category_id = p_category_id) AS amount) recurring;
    SELECT coalesce(unallocated, 0)::numeric(18, 2) INTO v_unallocated
      FROM public.budget_month_funding_state WHERE budget_month_id = v_month_id;
    IF p_amount > v_unallocated THEN
      RAISE EXCEPTION 'MONTH_OVERRIDE_INSUFFICIENT_FUNDS: required %, available %, shortfall %',
        p_amount::numeric(18, 2), v_unallocated, (p_amount - v_unallocated)::numeric(18, 2)
        USING ERRCODE = '23514';
    END IF;
    INSERT INTO public.budget_operations (
      budget_month_id, request_key, request_fingerprint, operation_type, effective_date, reason
    ) VALUES (
      v_month_id, p_request_key, v_fingerprint, 'monthly_override_set', v_month_start, p_reason
    ) RETURNING id INTO v_operation_id;
    INSERT INTO public.budgets (
      category_id, month, amount, budget_month_id, starting_amount, starting_kind, created_by_operation_id
    ) VALUES (
      p_category_id, p_month, p_amount, v_month_id, p_amount, 'monthly_override', v_operation_id
    ) RETURNING id INTO v_budget.budget_id;
    INSERT INTO public.budget_lifecycle_events (operation_id, budget_id, state)
    VALUES (v_operation_id, v_budget.budget_id, 'active');
    INSERT INTO public.budget_month_overrides (budget_month_id, category_id, amount)
    VALUES (v_month_id, p_category_id, p_amount);
    INSERT INTO public.budget_month_override_events (
      request_key, request_fingerprint, budget_month_id, category_id, budget_id,
      financial_operation_id, action, requested_override_amount,
      previous_effective_base, resulting_effective_base, fallback_base_snapshot,
      fallback_source, applied_base_delta
    ) VALUES (
      p_request_key, v_fingerprint, v_month_id, p_category_id, v_budget.budget_id,
      v_operation_id, 'initialize', p_amount, v_fallback, p_amount, v_fallback,
      v_fallback_source, 0
    );
    PERFORM public.budget_assert_reconciled(v_month_id);
    RETURN public.get_funded_budget_month(p_month);
  END IF;

  IF v_budget.lifecycle_state <> 'active' THEN
    RAISE EXCEPTION 'Month override requires an active category budget' USING ERRCODE = '23514';
  END IF;
  SELECT * INTO v_base FROM public.budget_category_base_state WHERE budget_id = v_budget.budget_id;
  v_delta := p_amount::numeric(18, 2) - v_base.effective_base;
  SELECT coalesce(unallocated, 0)::numeric(18, 2) INTO v_unallocated
    FROM public.budget_month_funding_state WHERE budget_month_id = v_month_id;
  IF v_delta > 0 AND v_delta > v_unallocated THEN
    RAISE EXCEPTION 'MONTH_OVERRIDE_INSUFFICIENT_FUNDS: required %, available %, shortfall %',
      v_delta, v_unallocated, (v_delta - v_unallocated)::numeric(18, 2)
      USING ERRCODE = '23514';
  END IF;
  IF v_delta < 0 THEN
    IF EXISTS (
      SELECT 1 FROM public.transactions
      WHERE movement_type = 'expense' AND category_id = p_category_id
        AND transaction_date >= v_month_start
        AND transaction_date < (v_month_start + interval '1 month')::date
        AND total_amount::text IN ('NaN', 'Infinity', '-Infinity')
    ) THEN
      RAISE EXCEPTION 'Month override actual spending contains a non-finite amount' USING ERRCODE = '22003';
    END IF;
    SELECT coalesce(sum(total_amount), 0) INTO v_raw_actual
    FROM public.transactions
    WHERE movement_type = 'expense' AND category_id = p_category_id
      AND transaction_date >= v_month_start
      AND transaction_date < (v_month_start + interval '1 month')::date;
    IF v_raw_actual <> round(v_raw_actual, 2) OR abs(v_raw_actual) > 9999999999999999.99 THEN
      RAISE EXCEPTION 'Month override actual spending must fit finite NUMERIC(18,2) exactly'
        USING ERRCODE = '22003';
    END IF;
    v_effective_actual := greatest(v_raw_actual, 0)::numeric(18, 2);
    v_base_headroom := greatest(v_base.effective_base - v_effective_actual, 0)::numeric(18, 2);
    v_total_headroom := greatest(v_base.final_funded - v_effective_actual, 0)::numeric(18, 2);
    v_eligible_release := least(v_base_headroom, v_total_headroom)::numeric(18, 2);
    IF -v_delta > v_eligible_release THEN
      RAISE EXCEPTION 'MONTH_OVERRIDE_RELEASE_BLOCKED: requested release %, eligible release %, shortfall %',
        -v_delta, v_eligible_release, (-v_delta - v_eligible_release)::numeric(18, 2)
        USING ERRCODE = '23514';
    END IF;
  END IF;

  INSERT INTO public.budget_operations (
    budget_month_id, request_key, request_fingerprint, operation_type, effective_date, reason
  ) VALUES (
    v_month_id, p_request_key, v_fingerprint, 'monthly_override_set', v_month_start, p_reason
  ) RETURNING id INTO v_operation_id;
  IF v_delta <> 0 THEN
    INSERT INTO public.budget_movements (operation_id, source_budget_id, destination_budget_id, amount)
    VALUES (
      v_operation_id,
      CASE WHEN v_delta < 0 THEN v_budget.budget_id ELSE NULL END,
      CASE WHEN v_delta > 0 THEN v_budget.budget_id ELSE NULL END,
      abs(v_delta)
    );
  END IF;
  INSERT INTO public.budget_month_overrides (budget_month_id, category_id, amount)
  VALUES (v_month_id, p_category_id, p_amount::numeric(18, 2))
  ON CONFLICT (budget_month_id, category_id) DO UPDATE
  SET amount = EXCLUDED.amount, updated_at = timezone('utc'::text, now());
  INSERT INTO public.budget_month_override_events (
    request_key, request_fingerprint, budget_month_id, category_id, budget_id,
    financial_operation_id, action, requested_override_amount,
    previous_effective_base, resulting_effective_base, fallback_base_snapshot,
    fallback_source, applied_base_delta
  ) VALUES (
    p_request_key, v_fingerprint, v_month_id, p_category_id, v_budget.budget_id,
    v_operation_id, 'set', p_amount, v_base.effective_base, p_amount,
    v_base.fallback_base, v_base.fallback_source, v_delta
  );
  PERFORM public.budget_assert_reconciled(v_month_id);
  RETURN public.get_funded_budget_month(p_month);
END;
$$;

CREATE OR REPLACE FUNCTION public.remove_budget_month_override(
  p_month TEXT,
  p_category_id BIGINT,
  p_request_key UUID,
  p_reason TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_month_start DATE := public.budget_month_start_from_key(p_month);
  v_current_start DATE := date_trunc('month', timezone('Asia/Jerusalem', statement_timestamp()))::date;
  v_month_id BIGINT;
  v_override NUMERIC(18, 2);
  v_budget public.budget_category_state%ROWTYPE;
  v_base public.budget_category_base_state%ROWTYPE;
  v_existing_event public.budget_month_override_events%ROWTYPE;
  v_fingerprint TEXT;
  v_operation_id BIGINT;
  v_delta NUMERIC(18, 2);
  v_unallocated NUMERIC(18, 2);
  v_raw_actual NUMERIC;
  v_effective_actual NUMERIC(18, 2) := 0;
  v_eligible_release NUMERIC(18, 2);
  v_fallback NUMERIC(18, 2);
  v_fallback_source TEXT;
  v_new_final NUMERIC(18, 2);
BEGIN
  IF p_request_key IS NULL OR p_category_id IS NULL THEN
    RAISE EXCEPTION 'month, category_id, and request_key are required' USING ERRCODE = '22023';
  END IF;
  IF v_month_start < v_current_start THEN
    RAISE EXCEPTION 'HISTORICAL_MONTH_OVERRIDE_FORBIDDEN: month overrides are limited to current/future Asia/Jerusalem months'
      USING ERRCODE = '22023';
  END IF;
  v_fingerprint := 'month_override_remove|' || p_month || '|' || p_category_id;
  LOCK TABLE public.transactions IN SHARE MODE;
  INSERT INTO public.budget_months (month_start) VALUES (v_month_start)
  ON CONFLICT (month_start) DO NOTHING;
  SELECT id INTO v_month_id FROM public.budget_months WHERE month_start = v_month_start FOR UPDATE;
  PERFORM 1 FROM public.budgets WHERE budget_month_id = v_month_id ORDER BY id FOR UPDATE;
  PERFORM 1 FROM public.categories WHERE id = p_category_id FOR SHARE;
  IF NOT EXISTS (SELECT 1 FROM public.categories WHERE id = p_category_id AND type = 'expense') THEN
    RAISE EXCEPTION 'Month overrides are available only for expense categories' USING ERRCODE = '23514';
  END IF;
  PERFORM 1 FROM public.budget_recurring_defaults WHERE category_id = p_category_id FOR SHARE;
  PERFORM 1 FROM public.budget_month_overrides
    WHERE budget_month_id = v_month_id AND category_id = p_category_id FOR UPDATE;

  SELECT * INTO v_existing_event FROM public.budget_month_override_events WHERE request_key = p_request_key;
  IF FOUND THEN
    IF v_existing_event.request_fingerprint <> v_fingerprint THEN
      RAISE EXCEPTION 'request_key was already used for a different month override request'
        USING ERRCODE = '23505';
    END IF;
    RETURN public.get_funded_budget_month(p_month);
  END IF;

  SELECT amount INTO v_override FROM public.budget_month_overrides
    WHERE budget_month_id = v_month_id AND category_id = p_category_id;
  SELECT * INTO v_budget FROM public.budget_category_state
    WHERE budget_month_id = v_month_id AND category_id = p_category_id;
  SELECT coalesce(amount, 0)::numeric(18, 2),
    CASE WHEN amount IS NULL THEN 'none' ELSE 'recurring_default' END
  INTO v_fallback, v_fallback_source
  FROM (SELECT (SELECT amount FROM public.budget_recurring_defaults
                WHERE category_id = p_category_id) AS amount) recurring;

  IF v_budget.budget_id IS NULL THEN
    IF v_override IS NOT NULL THEN
      DELETE FROM public.budget_month_overrides
      WHERE budget_month_id = v_month_id AND category_id = p_category_id;
    END IF;
    INSERT INTO public.budget_month_override_events (
      request_key, request_fingerprint, budget_month_id, category_id, action,
      previous_effective_base, resulting_effective_base, fallback_base_snapshot,
      fallback_source, applied_base_delta
    ) VALUES (
      p_request_key, v_fingerprint, v_month_id, p_category_id, 'remove',
      coalesce(v_override, v_fallback), v_fallback, v_fallback, v_fallback_source, 0
    );
    RETURN public.get_funded_budget_month(p_month);
  END IF;
  SELECT * INTO v_base FROM public.budget_category_base_state WHERE budget_id = v_budget.budget_id;
  IF v_override IS NULL THEN
    INSERT INTO public.budget_month_override_events (
      request_key, request_fingerprint, budget_month_id, category_id, budget_id,
      action, previous_effective_base, resulting_effective_base,
      fallback_base_snapshot, fallback_source, applied_base_delta
    ) VALUES (
      p_request_key, v_fingerprint, v_month_id, p_category_id, v_budget.budget_id,
      'remove', v_base.effective_base, v_base.effective_base,
      v_base.fallback_base, v_base.fallback_source, 0
    );
    RETURN public.get_funded_budget_month(p_month);
  END IF;
  IF v_budget.lifecycle_state <> 'active' THEN
    RAISE EXCEPTION 'Month override removal requires an active category budget' USING ERRCODE = '23514';
  END IF;
  v_delta := v_base.fallback_base - v_base.effective_base;
  IF EXISTS (
    SELECT 1 FROM public.transactions
    WHERE movement_type = 'expense' AND category_id = p_category_id
      AND transaction_date >= v_month_start
      AND transaction_date < (v_month_start + interval '1 month')::date
      AND total_amount::text IN ('NaN', 'Infinity', '-Infinity')
  ) THEN
    RAISE EXCEPTION 'Month override actual spending contains a non-finite amount' USING ERRCODE = '22003';
  END IF;
  SELECT coalesce(sum(total_amount), 0) INTO v_raw_actual
  FROM public.transactions
  WHERE movement_type = 'expense' AND category_id = p_category_id
    AND transaction_date >= v_month_start
    AND transaction_date < (v_month_start + interval '1 month')::date;
  IF v_raw_actual <> round(v_raw_actual, 2) OR abs(v_raw_actual) > 9999999999999999.99 THEN
    RAISE EXCEPTION 'Month override actual spending must fit finite NUMERIC(18,2) exactly'
      USING ERRCODE = '22003';
  END IF;
  v_effective_actual := greatest(v_raw_actual, 0)::numeric(18, 2);
  SELECT coalesce(unallocated, 0)::numeric(18, 2) INTO v_unallocated
    FROM public.budget_month_funding_state WHERE budget_month_id = v_month_id;
  IF v_delta > 0 AND v_delta > v_unallocated THEN
    RAISE EXCEPTION 'MONTH_OVERRIDE_INSUFFICIENT_FUNDS: required %, available %, shortfall %',
      v_delta, v_unallocated, (v_delta - v_unallocated)::numeric(18, 2)
      USING ERRCODE = '23514';
  END IF;
  IF v_delta < 0 THEN
    v_eligible_release := least(
      greatest(v_base.effective_base - v_effective_actual, 0),
      greatest(v_base.final_funded - v_effective_actual, 0)
    )::numeric(18, 2);
    IF -v_delta > v_eligible_release THEN
      RAISE EXCEPTION 'MONTH_OVERRIDE_RELEASE_BLOCKED: requested release %, eligible release %, shortfall %',
        -v_delta, v_eligible_release, (-v_delta - v_eligible_release)::numeric(18, 2)
        USING ERRCODE = '23514';
    END IF;
  END IF;

  INSERT INTO public.budget_operations (
    budget_month_id, request_key, request_fingerprint, operation_type, effective_date, reason
  ) VALUES (
    v_month_id, p_request_key, v_fingerprint, 'monthly_override_remove', v_month_start, p_reason
  ) RETURNING id INTO v_operation_id;
  IF v_delta <> 0 THEN
    INSERT INTO public.budget_movements (operation_id, source_budget_id, destination_budget_id, amount)
    VALUES (
      v_operation_id,
      CASE WHEN v_delta < 0 THEN v_budget.budget_id ELSE NULL END,
      CASE WHEN v_delta > 0 THEN v_budget.budget_id ELSE NULL END,
      abs(v_delta)
    );
  END IF;
  DELETE FROM public.budget_month_overrides
    WHERE budget_month_id = v_month_id AND category_id = p_category_id;
  INSERT INTO public.budget_month_override_events (
    request_key, request_fingerprint, budget_month_id, category_id, budget_id,
    financial_operation_id, action, previous_effective_base, resulting_effective_base,
    fallback_base_snapshot, fallback_source, applied_base_delta
  ) VALUES (
    p_request_key, v_fingerprint, v_month_id, p_category_id, v_budget.budget_id,
    v_operation_id, 'remove', v_base.effective_base, v_base.fallback_base,
    v_base.fallback_base, v_base.fallback_source, v_delta
  );

  v_new_final := v_base.final_funded + v_delta;
  IF v_base.fallback_base = 0 AND v_new_final = 0 AND v_effective_actual = 0
     AND v_base.incoming_carryover = 0 AND v_base.outgoing_carryover = 0
     AND v_base.other_adjustments = 0 THEN
    INSERT INTO public.budget_lifecycle_events (
      operation_id, budget_id, state, actual_spent_snapshot
    ) VALUES (v_operation_id, v_budget.budget_id, 'inactive', 0);
  END IF;
  PERFORM public.budget_assert_reconciled(v_month_id);
  RETURN public.get_funded_budget_month(p_month);
END;
$$;

-- Override-aware recurring preview. A pending override wins even when there is
-- no recurring default, and its exact zero is distinct from no override.
CREATE OR REPLACE FUNCTION public.get_budget_recurring_preview(p_month TEXT)
RETURNS JSONB
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_month_start DATE := public.budget_month_start_from_key(p_month);
  v_current_month DATE := date_trunc('month', timezone('Asia/Jerusalem', statement_timestamp()))::date;
  v_month_id BIGINT;
  v_eligible BOOLEAN;
  v_initialized BOOLEAN := false;
  v_unallocated NUMERIC(18, 2) := 0;
  v_required NUMERIC(18, 2) := 0;
  v_shortfall NUMERIC(18, 2) := 0;
  v_pending JSONB := '[]'::jsonb;
BEGIN
  v_eligible := v_month_start >= v_current_month;
  SELECT id INTO v_month_id FROM public.budget_months WHERE month_start = v_month_start;
  IF v_month_id IS NOT NULL THEN
    SELECT EXISTS (
      SELECT 1 FROM public.budget_operations
      WHERE budget_month_id = v_month_id AND operation_type = 'month_initialization'
    ) INTO v_initialized;
    SELECT coalesce(unallocated, 0)::numeric(18, 2) INTO v_unallocated
    FROM public.budget_month_funding_state WHERE budget_month_id = v_month_id;
  END IF;

  IF v_eligible AND NOT v_initialized THEN
    WITH category_config AS (
      SELECT category_id FROM public.budget_recurring_defaults
      UNION
      SELECT category_id FROM public.budget_month_overrides WHERE budget_month_id = v_month_id
    ), candidates AS (
      SELECT
        c.id AS category_id, c.name, c.icon, c.type,
        CASE WHEN mo.category_id IS NOT NULL THEN mo.amount ELSE rd.amount END::numeric(18, 2) AS amount,
        CASE WHEN mo.category_id IS NOT NULL THEN 'monthly_override' ELSE 'recurring_default' END AS starting_kind,
        coalesce(rd.amount, 0)::numeric(18, 2) AS fallback_base,
        CASE WHEN rd.category_id IS NULL THEN 'none' ELSE 'recurring_default' END AS fallback_source
      FROM category_config keys
      JOIN public.categories c ON c.id = keys.category_id
      LEFT JOIN public.budget_recurring_defaults rd ON rd.category_id = keys.category_id
      LEFT JOIN public.budget_month_overrides mo
        ON mo.budget_month_id = v_month_id AND mo.category_id = keys.category_id
      LEFT JOIN public.budgets b
        ON b.budget_month_id = v_month_id AND b.category_id = keys.category_id
      WHERE c.type = 'expense' AND c.is_active = true AND b.id IS NULL
    )
    SELECT
      coalesce(jsonb_agg(jsonb_build_object(
        'category_id', category_id,
        'category', jsonb_build_object('name', name, 'icon', icon, 'type', type),
        'amount', amount::numeric(18, 2)::text,
        'starting_kind', starting_kind,
        'fallback_base', fallback_base::numeric(18, 2)::text,
        'fallback_source', fallback_source
      ) ORDER BY name, category_id), '[]'::jsonb),
      coalesce(sum(amount), 0)::numeric(18, 2)
    INTO v_pending, v_required
    FROM candidates;
  END IF;

  v_shortfall := greatest(v_required - v_unallocated, 0)::numeric(18, 2);
  RETURN jsonb_build_object(
    'eligible', v_eligible,
    'initialized', v_initialized,
    'pending_categories', v_pending,
    'pending_count', jsonb_array_length(v_pending),
    'required', v_required::numeric(18, 2)::text,
    'unallocated', v_unallocated::numeric(18, 2)::text,
    'shortfall', v_shortfall::numeric(18, 2)::text,
    'can_apply', v_eligible AND NOT v_initialized
      AND jsonb_array_length(v_pending) > 0 AND v_shortfall = 0
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.initialize_budget_recurring_defaults(
  p_month TEXT,
  p_request_key UUID,
  p_reason TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_month_start DATE := public.budget_month_start_from_key(p_month);
  v_current_month DATE := date_trunc('month', timezone('Asia/Jerusalem', statement_timestamp()))::date;
  v_month_id BIGINT;
  v_operation_id BIGINT;
  v_budget_id BIGINT;
  v_existing public.budget_operations%ROWTYPE;
  v_required NUMERIC(18, 2) := 0;
  v_unallocated NUMERIC(18, 2) := 0;
  v_fingerprint TEXT := 'month_initialization|' || p_month;
  candidate RECORD;
BEGIN
  IF p_request_key IS NULL THEN
    RAISE EXCEPTION 'request_key is required' USING ERRCODE = '22023';
  END IF;
  IF v_month_start < v_current_month THEN
    RAISE EXCEPTION 'Recurring budgets cannot be initialized for a historical month'
      USING ERRCODE = '22023';
  END IF;
  INSERT INTO public.budget_months (month_start) VALUES (v_month_start)
  ON CONFLICT (month_start) DO NOTHING;
  SELECT id INTO v_month_id FROM public.budget_months WHERE month_start = v_month_start FOR UPDATE;
  PERFORM 1 FROM public.budgets WHERE budget_month_id = v_month_id ORDER BY id FOR UPDATE;
  PERFORM 1 FROM public.categories c
  WHERE c.id IN (
    SELECT category_id FROM public.budget_recurring_defaults
    UNION SELECT category_id FROM public.budget_month_overrides WHERE budget_month_id = v_month_id
  ) ORDER BY c.id FOR SHARE;
  PERFORM 1 FROM public.budget_recurring_defaults ORDER BY category_id FOR SHARE;
  PERFORM 1 FROM public.budget_month_overrides
    WHERE budget_month_id = v_month_id ORDER BY category_id FOR SHARE;

  SELECT * INTO v_existing FROM public.budget_operations WHERE request_key = p_request_key;
  IF FOUND THEN
    IF v_existing.budget_month_id <> v_month_id
       OR v_existing.operation_type <> 'month_initialization'
       OR v_existing.request_fingerprint <> v_fingerprint THEN
      RAISE EXCEPTION 'request_key was already used for a different budget operation'
        USING ERRCODE = '23505';
    END IF;
    RETURN public.get_funded_budget_month(p_month);
  END IF;
  IF EXISTS (
    SELECT 1 FROM public.budget_operations
    WHERE budget_month_id = v_month_id AND operation_type = 'month_initialization'
  ) THEN
    RETURN public.get_funded_budget_month(p_month);
  END IF;

  WITH category_config AS (
    SELECT category_id FROM public.budget_recurring_defaults
    UNION SELECT category_id FROM public.budget_month_overrides WHERE budget_month_id = v_month_id
  )
  SELECT coalesce(sum(CASE WHEN mo.category_id IS NOT NULL THEN mo.amount ELSE rd.amount END), 0)::numeric(18, 2)
  INTO v_required
  FROM category_config keys
  JOIN public.categories c ON c.id = keys.category_id
  LEFT JOIN public.budget_recurring_defaults rd ON rd.category_id = keys.category_id
  LEFT JOIN public.budget_month_overrides mo
    ON mo.budget_month_id = v_month_id AND mo.category_id = keys.category_id
  LEFT JOIN public.budgets b
    ON b.budget_month_id = v_month_id AND b.category_id = keys.category_id
  WHERE c.type = 'expense' AND c.is_active = true AND b.id IS NULL;
  SELECT coalesce(unallocated, 0)::numeric(18, 2) INTO v_unallocated
  FROM public.budget_month_funding_state WHERE budget_month_id = v_month_id;
  IF v_required > v_unallocated THEN
    RAISE EXCEPTION 'MONTH_OVERRIDE_INSUFFICIENT_FUNDS: required %, available %, shortfall %',
      v_required, v_unallocated, (v_required - v_unallocated)::numeric(18, 2)
      USING ERRCODE = '23514';
  END IF;

  INSERT INTO public.budget_operations (
    budget_month_id, request_key, request_fingerprint, operation_type, effective_date, reason
  ) VALUES (
    v_month_id, p_request_key, v_fingerprint, 'month_initialization', v_month_start, p_reason
  ) RETURNING id INTO v_operation_id;

  FOR candidate IN
    WITH category_config AS (
      SELECT category_id FROM public.budget_recurring_defaults
      UNION SELECT category_id FROM public.budget_month_overrides WHERE budget_month_id = v_month_id
    )
    SELECT
      keys.category_id,
      CASE WHEN mo.category_id IS NOT NULL THEN mo.amount ELSE rd.amount END::numeric(18, 2) AS amount,
      CASE WHEN mo.category_id IS NOT NULL THEN 'monthly_override' ELSE 'recurring_default' END AS starting_kind,
      coalesce(rd.amount, 0)::numeric(18, 2) AS fallback_base,
      CASE WHEN rd.category_id IS NULL THEN 'none' ELSE 'recurring_default' END AS fallback_source,
      mo.category_id IS NOT NULL AS has_override
    FROM category_config keys
    JOIN public.categories c ON c.id = keys.category_id
    LEFT JOIN public.budget_recurring_defaults rd ON rd.category_id = keys.category_id
    LEFT JOIN public.budget_month_overrides mo
      ON mo.budget_month_id = v_month_id AND mo.category_id = keys.category_id
    LEFT JOIN public.budgets b
      ON b.budget_month_id = v_month_id AND b.category_id = keys.category_id
    WHERE c.type = 'expense' AND c.is_active = true AND b.id IS NULL
    ORDER BY keys.category_id
  LOOP
    INSERT INTO public.budgets (
      category_id, month, amount, budget_month_id, starting_amount, starting_kind, created_by_operation_id
    ) VALUES (
      candidate.category_id, p_month, candidate.amount, v_month_id,
      candidate.amount, candidate.starting_kind, v_operation_id
    ) RETURNING id INTO v_budget_id;
    INSERT INTO public.budget_lifecycle_events (operation_id, budget_id, state)
    VALUES (v_operation_id, v_budget_id, 'active');
    IF candidate.has_override THEN
      INSERT INTO public.budget_month_override_events (
        request_key, request_fingerprint, budget_month_id, category_id, budget_id,
        financial_operation_id, action, requested_override_amount,
        previous_effective_base, resulting_effective_base, fallback_base_snapshot,
        fallback_source, applied_base_delta
      ) VALUES (
        public.budget_derived_request_key(p_request_key, 'override-init|' || candidate.category_id),
        'month_override_initialize|' || p_month || '|' || candidate.category_id || '|' || candidate.amount,
        v_month_id, candidate.category_id, v_budget_id, v_operation_id, 'initialize',
        candidate.amount, candidate.fallback_base, candidate.amount,
        candidate.fallback_base, candidate.fallback_source, 0
      );
    END IF;
  END LOOP;
  PERFORM public.budget_assert_reconciled(v_month_id);
  RETURN public.get_funded_budget_month(p_month);
END;
$$;

-- A pending monthly override is a stronger initialization requirement than a
-- recurring default. Carryover may not create carryover_only behind it.
CREATE OR REPLACE FUNCTION public.budget_carryover_candidate_rows(p_destination_month TEXT)
RETURNS TABLE (
  category_id BIGINT, category_name TEXT, category_icon TEXT,
  source_budget_id BIGINT, destination_budget_id BIGINT,
  source_final_funded NUMERIC(18, 2), source_raw_actual_spent NUMERIC(18, 2),
  source_effective_actual_spent NUMERIC(18, 2), eligible_amount NUMERIC(18, 2),
  status TEXT, blocked_reason TEXT
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_destination_start DATE := public.budget_month_start_from_key(p_destination_month);
  v_source_start DATE := (v_destination_start - interval '1 month')::date;
  v_source_id BIGINT;
  v_destination_id BIGINT;
  v_destination_initialized BOOLEAN := false;
BEGIN
  SELECT id INTO v_source_id FROM public.budget_months WHERE month_start = v_source_start;
  SELECT id INTO v_destination_id FROM public.budget_months WHERE month_start = v_destination_start;
  IF v_destination_id IS NOT NULL THEN
    SELECT EXISTS (
      SELECT 1 FROM public.budget_operations
      WHERE budget_month_id = v_destination_id AND operation_type = 'month_initialization'
    ) INTO v_destination_initialized;
  END IF;
  IF EXISTS (
    SELECT 1 FROM public.transactions
    WHERE movement_type = 'expense'
      AND transaction_date >= v_source_start
      AND transaction_date < (v_destination_start + interval '1 month')::date
      AND total_amount::text IN ('NaN', 'Infinity', '-Infinity')
  ) THEN
    RAISE EXCEPTION 'Carryover actual spending contains a non-finite amount' USING ERRCODE = '22003';
  END IF;
  IF EXISTS (
    SELECT 1 FROM public.transactions t
    WHERE t.movement_type = 'expense'
      AND t.transaction_date >= v_source_start
      AND t.transaction_date < (v_destination_start + interval '1 month')::date
    GROUP BY t.category_id, date_trunc('month', t.transaction_date)
    HAVING sum(t.total_amount) <> round(sum(t.total_amount), 2)
      OR abs(sum(t.total_amount)) > 9999999999999999.99
  ) THEN
    RAISE EXCEPTION 'Carryover actual spending must fit finite NUMERIC(18,2) exactly'
      USING ERRCODE = '22003';
  END IF;

  RETURN QUERY
  WITH source_actuals AS (
    SELECT t.category_id, coalesce(sum(t.total_amount), 0)::numeric(18, 2) AS actual
    FROM public.transactions t
    WHERE t.movement_type = 'expense'
      AND t.transaction_date >= v_source_start AND t.transaction_date < v_destination_start
    GROUP BY t.category_id
  ), destination_actuals AS (
    SELECT t.category_id, coalesce(sum(t.total_amount), 0)::numeric(18, 2) AS actual
    FROM public.transactions t
    WHERE t.movement_type = 'expense'
      AND t.transaction_date >= v_destination_start
      AND t.transaction_date < (v_destination_start + interval '1 month')::date
    GROUP BY t.category_id
  ), candidate AS (
    SELECT
      c.id AS category_id, c.name, c.icon,
      src.budget_id AS source_budget_id, dst.budget_id AS destination_budget_id,
      coalesce(src.final_funded, 0)::numeric(18, 2) AS source_final_funded,
      coalesce(sa.actual, 0)::numeric(18, 2) AS source_raw_actual_spent,
      greatest(coalesce(sa.actual, 0), 0)::numeric(18, 2) AS source_effective_actual_spent,
      greatest(coalesce(src.final_funded, 0) - greatest(coalesce(sa.actual, 0), 0), 0)::numeric(18, 2)
        AS eligible_amount,
      c.is_active, src.lifecycle_state AS source_lifecycle,
      dst.lifecycle_state AS destination_lifecycle,
      coalesce(da.actual, 0)::numeric(18, 2) AS destination_actual,
      coalesce(dst.final_funded, 0)::numeric(18, 2) AS destination_final,
      mo.category_id IS NOT NULL AND NOT v_destination_initialized AS override_pending,
      rd.category_id IS NOT NULL AND NOT v_destination_initialized AS recurring_pending,
      EXISTS (
        SELECT 1 FROM public.budget_carryover_transfers original
        WHERE original.source_budget_id = src.budget_id
          AND original.reverses_transfer_id IS NULL
          AND NOT EXISTS (
            SELECT 1 FROM public.budget_carryover_transfers correction
            WHERE correction.reverses_transfer_id = original.id
          )
      ) AS already_applied
    FROM public.budget_carryover_settings setting
    JOIN public.categories c ON c.id = setting.category_id
    LEFT JOIN public.budget_category_state src
      ON src.budget_month_id = v_source_id AND src.category_id = c.id
    LEFT JOIN source_actuals sa ON sa.category_id = c.id
    LEFT JOIN public.budget_category_state dst
      ON dst.budget_month_id = v_destination_id AND dst.category_id = c.id
    LEFT JOIN destination_actuals da ON da.category_id = c.id
    LEFT JOIN public.budget_recurring_defaults rd ON rd.category_id = c.id
    LEFT JOIN public.budget_month_overrides mo
      ON mo.budget_month_id = v_destination_id AND mo.category_id = c.id
    WHERE c.type = 'expense'
  )
  SELECT
    candidate.category_id, candidate.name, candidate.icon,
    candidate.source_budget_id, candidate.destination_budget_id,
    candidate.source_final_funded, candidate.source_raw_actual_spent,
    candidate.source_effective_actual_spent, candidate.eligible_amount,
    CASE
      WHEN candidate.already_applied THEN 'already_applied'
      WHEN NOT candidate.is_active OR candidate.source_budget_id IS NULL
        OR candidate.source_lifecycle <> 'active' OR candidate.eligible_amount <= 0 THEN 'blocked'
      WHEN candidate.destination_budget_id IS NOT NULL
        AND candidate.destination_lifecycle <> 'active' THEN 'blocked'
      WHEN candidate.destination_budget_id IS NULL
        AND (candidate.override_pending OR candidate.recurring_pending) THEN 'blocked'
      WHEN candidate.destination_budget_id IS NULL AND candidate.destination_actual > 0 THEN 'blocked'
      WHEN candidate.destination_budget_id IS NOT NULL
        AND candidate.destination_actual > candidate.destination_final THEN 'blocked'
      ELSE 'ready'
    END,
    CASE
      WHEN candidate.already_applied THEN NULL
      WHEN NOT candidate.is_active THEN 'CATEGORY_INACTIVE'
      WHEN candidate.source_budget_id IS NULL THEN 'SOURCE_BUDGET_MISSING'
      WHEN candidate.source_lifecycle <> 'active' THEN 'SOURCE_BUDGET_INACTIVE'
      WHEN candidate.eligible_amount <= 0 THEN 'NO_ELIGIBLE_BALANCE'
      WHEN candidate.destination_budget_id IS NOT NULL
        AND candidate.destination_lifecycle <> 'active' THEN 'DESTINATION_BUDGET_INACTIVE'
      WHEN candidate.destination_budget_id IS NULL AND candidate.override_pending
        THEN 'MONTH_OVERRIDE_INITIALIZATION_REQUIRED'
      WHEN candidate.destination_budget_id IS NULL AND candidate.recurring_pending
        THEN 'RECURRING_INITIALIZATION_REQUIRED'
      WHEN candidate.destination_budget_id IS NULL AND candidate.destination_actual > 0
        THEN 'UNBUDGETED_ACTUAL_EXISTS'
      WHEN candidate.destination_budget_id IS NOT NULL
        AND candidate.destination_actual > candidate.destination_final THEN 'DESTINATION_DEFICIT'
      ELSE NULL
    END
  FROM candidate
  ORDER BY candidate.name, candidate.category_id;
END;
$$;

-- Copy remains the existing funded operation, but categories with destination
-- override configuration are excluded from both its validation and writes.
CREATE OR REPLACE FUNCTION public.copy_funded_budget_month(
  p_from_month TEXT,
  p_to_month TEXT,
  p_request_key UUID,
  p_reason TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_from_start DATE := public.budget_month_start_from_key(p_from_month);
  v_to_start DATE := public.budget_month_start_from_key(p_to_month);
  v_from_id BIGINT;
  v_to_id BIGINT;
  v_operation_id BIGINT;
  v_existing public.budget_operations%ROWTYPE;
  v_unallocated NUMERIC(18, 2);
  v_additions NUMERIC(18, 2) := 0;
  v_releases NUMERIC(18, 2) := 0;
  v_target_actual NUMERIC(18, 2);
  v_target_id BIGINT;
  v_target_final NUMERIC(18, 2);
  v_target_state TEXT;
  v_delta NUMERIC(18, 2);
  v_fingerprint TEXT;
  v_result JSONB;
  v_skipped JSONB;
  source_row RECORD;
BEGIN
  IF p_request_key IS NULL THEN RAISE EXCEPTION 'request_key is required' USING ERRCODE = '22023'; END IF;
  IF v_from_start = v_to_start THEN
    RAISE EXCEPTION 'Source and target budget months must differ' USING ERRCODE = '22023';
  END IF;
  SELECT id INTO v_from_id FROM public.budget_months WHERE month_start = v_from_start;
  IF NOT FOUND THEN RAISE EXCEPTION 'Source month has no funded budget'; END IF;

  -- Copy can release target funding based on actual spending, so it shares the
  -- transaction-first serialization order used by carryover and overrides.
  LOCK TABLE public.transactions IN SHARE MODE;
  INSERT INTO public.budget_months (month_start) VALUES (v_to_start)
  ON CONFLICT (month_start) DO NOTHING;
  SELECT id INTO v_to_id FROM public.budget_months WHERE month_start = v_to_start;
  PERFORM 1 FROM public.budget_months WHERE id IN (v_from_id, v_to_id) ORDER BY id FOR UPDATE;
  PERFORM 1 FROM public.budgets
    WHERE budget_month_id IN (v_from_id, v_to_id) ORDER BY id FOR UPDATE;
  PERFORM 1 FROM public.budget_month_overrides
    WHERE budget_month_id = v_to_id ORDER BY category_id FOR SHARE;
  PERFORM public.budget_assert_reconciled(v_from_id);
  PERFORM public.budget_assert_reconciled(v_to_id);

  v_fingerprint := 'copy|' || p_from_month || '|' || p_to_month;
  SELECT * INTO v_existing FROM public.budget_operations WHERE request_key = p_request_key;
  IF FOUND THEN
    IF v_existing.budget_month_id <> v_to_id OR v_existing.operation_type <> 'copy'
       OR v_existing.request_fingerprint <> v_fingerprint THEN
      RAISE EXCEPTION 'request_key was already used for a different budget operation'
        USING ERRCODE = '23505';
    END IF;
    v_result := public.get_funded_budget_month(p_to_month);
    SELECT coalesce(jsonb_agg(jsonb_build_object(
      'category_id', mo.category_id, 'amount', mo.amount::numeric(18, 2)::text,
      'reason', 'MONTH_OVERRIDE_PRESERVED'
    ) ORDER BY mo.category_id), '[]'::jsonb) INTO v_skipped
    FROM public.budget_month_overrides mo
    WHERE mo.budget_month_id = v_to_id
      AND EXISTS (
        SELECT 1 FROM public.budget_category_state src
        WHERE src.budget_month_id = v_from_id AND src.category_id = mo.category_id
          AND src.lifecycle_state = 'active'
      );
    RETURN v_result || jsonb_build_object('copy_preserved_overrides', v_skipped);
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM public.budget_category_state
    WHERE budget_month_id = v_from_id AND lifecycle_state = 'active'
  ) THEN
    RAISE EXCEPTION 'Source month has no active category budgets';
  END IF;

  FOR source_row IN
    SELECT src.* FROM public.budget_category_state src
    WHERE src.budget_month_id = v_from_id AND src.lifecycle_state = 'active'
      AND NOT EXISTS (
        SELECT 1 FROM public.budget_month_overrides mo
        WHERE mo.budget_month_id = v_to_id AND mo.category_id = src.category_id
      )
    ORDER BY src.category_id
  LOOP
    SELECT cs.budget_id, cs.final_funded, cs.lifecycle_state
    INTO v_target_id, v_target_final, v_target_state
    FROM public.budget_category_state cs
    WHERE cs.budget_month_id = v_to_id AND cs.category_id = source_row.category_id;
    IF NOT FOUND THEN
      v_additions := v_additions + source_row.final_funded;
    ELSE
      v_delta := source_row.final_funded - v_target_final;
      IF v_delta > 0 THEN
        v_additions := v_additions + v_delta;
      ELSIF v_delta < 0 THEN
        IF EXISTS (
          SELECT 1 FROM public.transactions
          WHERE movement_type = 'expense' AND category_id = source_row.category_id
            AND transaction_date >= v_to_start
            AND transaction_date < (v_to_start + interval '1 month')::date
            AND total_amount::text IN ('NaN', 'Infinity', '-Infinity')
        ) THEN
          RAISE EXCEPTION 'Budget actual spending contains a non-finite amount' USING ERRCODE = '22003';
        END IF;
        SELECT greatest(coalesce(sum(total_amount), 0), 0)::numeric(18, 2)
        INTO v_target_actual
        FROM public.transactions
        WHERE movement_type = 'expense' AND category_id = source_row.category_id
          AND transaction_date >= v_to_start
          AND transaction_date < (v_to_start + interval '1 month')::date;
        IF -v_delta > greatest(v_target_final - v_target_actual, 0) THEN
          RAISE EXCEPTION 'Copy cannot release spent funding from target category %', source_row.category_id
            USING ERRCODE = '23514';
        END IF;
        v_releases := v_releases + (-v_delta);
      END IF;
    END IF;
  END LOOP;
  SELECT unallocated INTO v_unallocated FROM public.budget_month_funding_state WHERE budget_month_id = v_to_id;
  IF v_additions > v_unallocated + v_releases THEN
    RAISE EXCEPTION 'Destination month needs % additional funded money; only % is available',
      v_additions, v_unallocated + v_releases USING ERRCODE = '23514';
  END IF;

  INSERT INTO public.budget_operations (
    budget_month_id, request_key, request_fingerprint, operation_type, effective_date, reason
  ) VALUES (v_to_id, p_request_key, v_fingerprint, 'copy', v_to_start, p_reason)
  RETURNING id INTO v_operation_id;

  FOR source_row IN
    SELECT src.* FROM public.budget_category_state src
    WHERE src.budget_month_id = v_from_id AND src.lifecycle_state = 'active'
      AND NOT EXISTS (
        SELECT 1 FROM public.budget_month_overrides mo
        WHERE mo.budget_month_id = v_to_id AND mo.category_id = src.category_id
      )
    ORDER BY src.category_id
  LOOP
    SELECT cs.budget_id, cs.final_funded, cs.lifecycle_state
    INTO v_target_id, v_target_final, v_target_state
    FROM public.budget_category_state cs
    WHERE cs.budget_month_id = v_to_id AND cs.category_id = source_row.category_id;
    IF NOT FOUND THEN
      INSERT INTO public.budgets (
        category_id, month, amount, budget_month_id, starting_amount,
        starting_kind, created_by_operation_id
      ) VALUES (
        source_row.category_id, p_to_month, source_row.final_funded, v_to_id,
        source_row.final_funded, 'copied', v_operation_id
      ) RETURNING id INTO v_target_id;
      INSERT INTO public.budget_lifecycle_events (operation_id, budget_id, state)
      VALUES (v_operation_id, v_target_id, 'active');
    ELSE
      v_delta := source_row.final_funded - v_target_final;
      IF v_delta <> 0 THEN
        INSERT INTO public.budget_movements (
          operation_id, source_budget_id, destination_budget_id, amount
        ) VALUES (
          v_operation_id,
          CASE WHEN v_delta < 0 THEN v_target_id ELSE NULL END,
          CASE WHEN v_delta > 0 THEN v_target_id ELSE NULL END,
          abs(v_delta)
        );
      END IF;
      IF v_target_state = 'inactive' THEN
        INSERT INTO public.budget_lifecycle_events (operation_id, budget_id, state)
        VALUES (v_operation_id, v_target_id, 'active');
      END IF;
    END IF;
  END LOOP;

  PERFORM public.budget_assert_reconciled(v_to_id);
  v_result := public.get_funded_budget_month(p_to_month);
  SELECT coalesce(jsonb_agg(jsonb_build_object(
    'category_id', mo.category_id, 'amount', mo.amount::numeric(18, 2)::text,
    'reason', 'MONTH_OVERRIDE_PRESERVED'
  ) ORDER BY mo.category_id), '[]'::jsonb) INTO v_skipped
  FROM public.budget_month_overrides mo
  WHERE mo.budget_month_id = v_to_id
    AND EXISTS (
      SELECT 1 FROM public.budget_category_state src
      WHERE src.budget_month_id = v_from_id AND src.category_id = mo.category_id
        AND src.lifecycle_state = 'active'
    );
  RETURN v_result || jsonb_build_object('copy_preserved_overrides', v_skipped);
END;
$$;

ALTER TABLE public.budget_month_overrides ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.budget_month_override_events ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.budget_month_overrides,
  public.budget_month_override_events,
  public.budget_month_overrides_read,
  public.budget_category_base_state
  FROM PUBLIC, anon, authenticated, service_role;
GRANT SELECT ON public.budget_month_overrides,
  public.budget_month_override_events,
  public.budget_month_overrides_read,
  public.budget_category_base_state
  TO service_role;

REVOKE ALL ON FUNCTION public.validate_budget_month_override(),
  public.prevent_category_type_with_month_override(),
  public.validate_budget_month_override_event(),
  public.get_funded_budget_month_carryover(TEXT),
  public.get_budget_recurring_preview(TEXT),
  public.budget_carryover_candidate_rows(TEXT)
  FROM PUBLIC, anon, authenticated, service_role;

REVOKE ALL ON FUNCTION public.get_budget_month_override_preview(TEXT),
  public.set_budget_month_override(TEXT, BIGINT, NUMERIC, UUID, TEXT),
  public.remove_budget_month_override(TEXT, BIGINT, UUID, TEXT),
  public.initialize_budget_recurring_defaults(TEXT, UUID, TEXT),
  public.copy_funded_budget_month(TEXT, TEXT, UUID, TEXT)
  FROM PUBLIC, anon, authenticated;
REVOKE EXECUTE ON FUNCTION public.get_funded_budget_month(TEXT)
  FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.get_funded_budget_month(TEXT),
  public.get_budget_month_override_preview(TEXT),
  public.set_budget_month_override(TEXT, BIGINT, NUMERIC, UUID, TEXT),
  public.remove_budget_month_override(TEXT, BIGINT, UUID, TEXT),
  public.initialize_budget_recurring_defaults(TEXT, UUID, TEXT),
  public.copy_funded_budget_month(TEXT, TEXT, UUID, TEXT)
  TO service_role;
REVOKE EXECUTE ON FUNCTION public.get_funded_budget_month_carryover(TEXT)
  FROM service_role;

DO $$
DECLARE v_month RECORD;
BEGIN
  FOR v_month IN SELECT id FROM public.budget_months ORDER BY id LOOP
    PERFORM public.budget_assert_reconciled(v_month.id);
  END LOOP;
  IF EXISTS (
    SELECT 1 FROM public.budget_category_base_state
    WHERE final_funded <> effective_base + incoming_carryover
      - outgoing_carryover + other_adjustments
  ) THEN
    RAISE EXCEPTION 'Migration 020 reconciliation: base/carryover composition mismatch';
  END IF;
END;
$$;

COMMIT;
