-- Migration 023: explicit resolution of transaction-authoritative unbudgeted expenses.
--
-- A late-created snapshot opens at zero. Funding is recorded only through the
-- existing funded-action ledger. Inactive snapshots are explicitly reactivated
-- without rewriting their immutable opening state.

BEGIN;

DO $$
BEGIN
  IF to_regclass('public.budget_funding_actions') IS NULL
     OR to_regclass('public.budget_funding_action_legs') IS NULL
     OR to_regclass('public.budget_savings_entries') IS NULL
     OR to_regclass('public.budget_month_overrides') IS NULL
     OR to_regprocedure('public.budget_action_month_lifecycle(text)') IS NULL
     OR to_regprocedure('public.get_budget_deficit_resolution_preview(text,bigint,jsonb)') IS NULL
     OR to_regprocedure('public.budget_assert_reconciled(bigint)') IS NULL THEN
    RAISE EXCEPTION 'Migration 023 preflight: Migrations 017 through 022 are required';
  END IF;
  IF to_regclass('public.budget_unbudgeted_resolution_events') IS NOT NULL
     OR to_regclass('public.budget_unbudgeted_resolution_history') IS NOT NULL
     OR to_regprocedure('public.budget_funding_source_rows(text,bigint)') IS NOT NULL
     OR to_regprocedure('public.get_budget_unbudgeted_resolution_preview(text,bigint,numeric,jsonb)') IS NOT NULL
     OR to_regprocedure('public.apply_budget_unbudgeted_resolution(text,bigint,numeric,jsonb,uuid,text,text)') IS NOT NULL
     OR to_regprocedure('public.reverse_budget_unbudgeted_resolution(bigint,uuid,text)') IS NOT NULL THEN
    RAISE EXCEPTION 'Migration 023 preflight: unexpected partial unbudgeted-resolution schema exists';
  END IF;
  IF EXISTS (
    SELECT 1 FROM public.budgets
    WHERE starting_kind NOT IN (
      'manual','legacy_import','copied','recurring_default','carryover_only','monthly_override'
    )
  ) OR EXISTS (
    SELECT 1 FROM public.budget_operations
    WHERE operation_type NOT IN (
      'legacy_import','manual_funding','establish_budget','adjustment','removal',
      'reactivation','copy','reversal','month_initialization','carryover_out',
      'carryover_in','monthly_override_set','monthly_override_remove',
      'unused_return_out','unused_return_in','unused_to_savings',
      'unused_disposition_reversal','budget_reallocation','deficit_resolution',
      'funding_action_reversal'
    )
  ) OR EXISTS (
    SELECT 1 FROM public.budget_funding_actions
    WHERE action_kind NOT IN ('planned_reallocation','deficit_resolution','reversal')
  ) THEN
    RAISE EXCEPTION 'Migration 023 preflight: unexpected funded-budget domain value';
  END IF;
END;
$$;

ALTER TABLE public.budgets
  DROP CONSTRAINT budgets_starting_kind_check,
  ADD CONSTRAINT budgets_starting_kind_check CHECK (starting_kind IN (
    'manual','legacy_import','copied','recurring_default','carryover_only',
    'monthly_override','unbudgeted_resolution'
  ));

ALTER TABLE public.budget_month_override_events
  DROP CONSTRAINT budget_month_override_events_fallback_source_check,
  ADD CONSTRAINT budget_month_override_events_fallback_source_check CHECK (fallback_source IN (
    'none','manual','legacy_import','copied','recurring_default','carryover_only',
    'monthly_override','unbudgeted_resolution'
  ));

ALTER TABLE public.budget_operations
  DROP CONSTRAINT budget_operations_operation_type_check,
  ADD CONSTRAINT budget_operations_operation_type_check CHECK (operation_type IN (
    'legacy_import','manual_funding','establish_budget','adjustment','removal',
    'reactivation','copy','reversal','month_initialization','carryover_out',
    'carryover_in','monthly_override_set','monthly_override_remove',
    'unused_return_out','unused_return_in','unused_to_savings',
    'unused_disposition_reversal','budget_reallocation','deficit_resolution',
    'funding_action_reversal','unbudgeted_resolution','unbudgeted_resolution_reversal'
  ));

ALTER TABLE public.budget_funding_actions
  DROP CONSTRAINT budget_funding_actions_action_kind_check,
  ADD CONSTRAINT budget_funding_actions_action_kind_check CHECK (action_kind IN (
    'planned_reallocation','deficit_resolution','unbudgeted_resolution','reversal'
  ));

CREATE TABLE public.budget_unbudgeted_resolution_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  operation_id BIGINT NOT NULL UNIQUE REFERENCES public.budget_operations(id) ON DELETE RESTRICT,
  funding_action_id BIGINT UNIQUE REFERENCES public.budget_funding_actions(id) ON DELETE RESTRICT,
  budget_month_id BIGINT NOT NULL REFERENCES public.budget_months(id) ON DELETE RESTRICT,
  category_id BIGINT NOT NULL REFERENCES public.categories(id) ON DELETE RESTRICT,
  budget_id BIGINT NOT NULL REFERENCES public.budgets(id) ON DELETE RESTRICT,
  event_kind TEXT NOT NULL CHECK (event_kind IN ('apply','reversal')),
  resolution_mode TEXT NOT NULL CHECK (resolution_mode IN ('created','reactivated')),
  raw_actual_snapshot NUMERIC(18,2) NOT NULL,
  existing_funded_snapshot NUMERIC(18,2) NOT NULL,
  applied_funding NUMERIC(18,2) NOT NULL,
  resulting_final_funded NUMERIC(18,2) NOT NULL,
  resulting_deficit NUMERIC(18,2) NOT NULL,
  reverses_event_id BIGINT UNIQUE REFERENCES public.budget_unbudgeted_resolution_events(id) ON DELETE RESTRICT,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT timezone('utc'::text,now()),
  CHECK (raw_actual_snapshot::text NOT IN ('NaN','Infinity','-Infinity') AND raw_actual_snapshot>0),
  CHECK (existing_funded_snapshot::text NOT IN ('NaN','Infinity','-Infinity') AND existing_funded_snapshot>=0),
  CHECK (applied_funding::text NOT IN ('NaN','Infinity','-Infinity') AND applied_funding>=0),
  CHECK (resulting_final_funded::text NOT IN ('NaN','Infinity','-Infinity') AND resulting_final_funded>=0),
  CHECK (resulting_deficit::text NOT IN ('NaN','Infinity','-Infinity') AND resulting_deficit>=0),
  CHECK ((event_kind='apply' AND resulting_final_funded=existing_funded_snapshot+applied_funding)
      OR (event_kind='reversal' AND resulting_final_funded=existing_funded_snapshot-applied_funding)),
  CHECK (resulting_deficit=greatest(raw_actual_snapshot-resulting_final_funded,0)),
  CHECK ((applied_funding=0 AND funding_action_id IS NULL)
      OR (applied_funding>0 AND funding_action_id IS NOT NULL)),
  CHECK ((event_kind='apply' AND reverses_event_id IS NULL)
      OR (event_kind='reversal' AND reverses_event_id IS NOT NULL))
);

CREATE INDEX idx_budget_unbudgeted_resolution_events_month
  ON public.budget_unbudgeted_resolution_events(budget_month_id,id);
CREATE INDEX idx_budget_unbudgeted_resolution_events_budget
  ON public.budget_unbudgeted_resolution_events(budget_id,id);

CREATE OR REPLACE FUNCTION public.validate_budget_funding_action()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $$
DECLARE v_operation public.budget_operations%ROWTYPE; v_destination public.budgets%ROWTYPE;
BEGIN
  SELECT * INTO v_operation FROM public.budget_operations WHERE id=NEW.operation_id;
  IF v_operation.budget_month_id IS DISTINCT FROM NEW.budget_month_id
     OR (NEW.action_kind='planned_reallocation' AND v_operation.operation_type<>'budget_reallocation')
     OR (NEW.action_kind='deficit_resolution' AND v_operation.operation_type<>'deficit_resolution')
     OR (NEW.action_kind='unbudgeted_resolution' AND v_operation.operation_type<>'unbudgeted_resolution')
     OR (NEW.action_kind='reversal' AND v_operation.operation_type NOT IN (
       'funding_action_reversal','unbudgeted_resolution_reversal'
     )) THEN
    RAISE EXCEPTION 'Funding action does not match its operation' USING ERRCODE='23514';
  END IF;
  IF NEW.destination_budget_id IS NOT NULL THEN
    SELECT * INTO v_destination FROM public.budgets WHERE id=NEW.destination_budget_id;
    IF v_destination.budget_month_id IS DISTINCT FROM NEW.budget_month_id THEN
      RAISE EXCEPTION 'Funding action destination belongs to another month' USING ERRCODE='23514';
    END IF;
  END IF;
  IF NEW.action_kind='reversal' AND NOT EXISTS (
    SELECT 1 FROM public.budget_funding_actions original
    WHERE original.id=NEW.reversed_action_id AND original.action_kind<>'reversal'
      AND original.budget_month_id=NEW.budget_month_id
  ) THEN
    RAISE EXCEPTION 'Funding action reversal does not match an original action' USING ERRCODE='23514';
  END IF;
  RETURN NEW;
END; $$;

CREATE OR REPLACE FUNCTION public.validate_budget_savings_entry()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $$
DECLARE
  v_operation public.budget_operations%ROWTYPE;
  v_budget public.budgets%ROWTYPE;
  v_funding public.budget_funding_entries%ROWTYPE;
  v_movement public.budget_movements%ROWTYPE;
BEGIN
  SELECT * INTO v_operation FROM public.budget_operations WHERE id=NEW.operation_id;
  SELECT * INTO v_funding FROM public.budget_funding_entries WHERE operation_id=NEW.operation_id;
  IF NEW.entry_kind IN ('deposit','reversal') THEN
    SELECT * INTO v_budget FROM public.budgets WHERE id=NEW.source_budget_id;
    SELECT * INTO v_movement FROM public.budget_movements WHERE operation_id=NEW.operation_id;
    IF v_operation.budget_month_id IS DISTINCT FROM NEW.source_budget_month_id
       OR v_budget.budget_month_id IS DISTINCT FROM NEW.source_budget_month_id
       OR v_budget.category_id IS DISTINCT FROM NEW.category_id
       OR v_operation.operation_type NOT IN ('unused_to_savings','unused_disposition_reversal') THEN
      RAISE EXCEPTION 'Savings entry provenance does not match its source' USING ERRCODE='23514';
    END IF;
    IF NEW.entry_kind='reversal' AND NOT EXISTS (
      SELECT 1 FROM public.budget_savings_entries original
      WHERE original.id=NEW.reverses_entry_id AND original.entry_kind='deposit'
        AND original.source_budget_id=NEW.source_budget_id
        AND original.amount_delta=-NEW.amount_delta
    ) THEN
      RAISE EXCEPTION 'Savings reversal does not match its deposit' USING ERRCODE='23514';
    END IF;
    IF v_funding.source_kind<>'savings_transfer'
       OR v_funding.amount_delta<>-NEW.amount_delta
       OR (NEW.entry_kind='deposit' AND (
         v_movement.source_budget_id IS DISTINCT FROM NEW.source_budget_id
         OR v_movement.destination_budget_id IS NOT NULL OR v_movement.amount<>NEW.amount_delta))
       OR (NEW.entry_kind='reversal' AND (
         v_movement.source_budget_id IS NOT NULL
         OR v_movement.destination_budget_id IS DISTINCT FROM NEW.source_budget_id
         OR v_movement.amount<>-NEW.amount_delta)) THEN
      RAISE EXCEPTION 'Savings funding and category movement are not balanced' USING ERRCODE='23514';
    END IF;
  ELSE
    SELECT * INTO v_budget FROM public.budgets WHERE id=NEW.destination_budget_id;
    SELECT * INTO v_movement FROM public.budget_movements WHERE id=NEW.movement_id;
    IF v_operation.budget_month_id IS DISTINCT FROM NEW.destination_budget_month_id
       OR v_budget.budget_month_id IS DISTINCT FROM NEW.destination_budget_month_id
       OR v_budget.category_id IS DISTINCT FROM NEW.category_id
       OR v_movement.operation_id IS DISTINCT FROM NEW.operation_id
       OR v_operation.operation_type NOT IN (
         'deficit_resolution','funding_action_reversal',
         'unbudgeted_resolution','unbudgeted_resolution_reversal'
       )
       OR v_funding.source_kind<>'savings_withdrawal'
       OR v_funding.amount_delta<>-NEW.amount_delta THEN
      RAISE EXCEPTION 'Savings withdrawal provenance is not balanced' USING ERRCODE='23514';
    END IF;
    IF NEW.entry_kind='withdrawal' AND (
      v_movement.source_budget_id IS NOT NULL
      OR v_movement.destination_budget_id IS DISTINCT FROM NEW.destination_budget_id
      OR v_movement.amount<>-NEW.amount_delta
    ) THEN
      RAISE EXCEPTION 'Savings withdrawal movement is not balanced' USING ERRCODE='23514';
    END IF;
    IF NEW.entry_kind='withdrawal_reversal' AND (
      v_movement.source_budget_id IS DISTINCT FROM NEW.destination_budget_id
      OR v_movement.destination_budget_id IS NOT NULL
      OR v_movement.amount<>NEW.amount_delta
      OR NOT EXISTS (
        SELECT 1 FROM public.budget_savings_entries original
        WHERE original.id=NEW.reverses_entry_id AND original.entry_kind='withdrawal'
          AND original.destination_budget_id=NEW.destination_budget_id
          AND original.amount_delta=-NEW.amount_delta
      )
    ) THEN
      RAISE EXCEPTION 'Savings withdrawal reversal does not match its withdrawal' USING ERRCODE='23514';
    END IF;
  END IF;
  RETURN NEW;
END; $$;

CREATE OR REPLACE FUNCTION public.validate_budget_unbudgeted_resolution_event()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $$
DECLARE
  v_operation public.budget_operations%ROWTYPE;
  v_budget public.budgets%ROWTYPE;
  v_action public.budget_funding_actions%ROWTYPE;
BEGIN
  SELECT * INTO v_operation FROM public.budget_operations WHERE id=NEW.operation_id;
  SELECT * INTO v_budget FROM public.budgets WHERE id=NEW.budget_id;
  IF v_operation.budget_month_id IS DISTINCT FROM NEW.budget_month_id
     OR v_budget.budget_month_id IS DISTINCT FROM NEW.budget_month_id
     OR v_budget.category_id IS DISTINCT FROM NEW.category_id THEN
    RAISE EXCEPTION 'Unbudgeted resolution provenance does not match its budget' USING ERRCODE='23514';
  END IF;
  IF NEW.funding_action_id IS NOT NULL THEN
    SELECT * INTO v_action FROM public.budget_funding_actions WHERE id=NEW.funding_action_id;
    IF v_action.operation_id IS DISTINCT FROM NEW.operation_id
       OR v_action.destination_budget_id IS DISTINCT FROM NEW.budget_id THEN
      RAISE EXCEPTION 'Unbudgeted resolution funding action does not match its event' USING ERRCODE='23514';
    END IF;
  END IF;
  IF NEW.event_kind='apply' THEN
    IF v_operation.operation_type<>'unbudgeted_resolution'
       OR (NEW.applied_funding>0 AND v_action.action_kind<>'unbudgeted_resolution')
       OR (NEW.resolution_mode='created' AND (
         v_budget.created_by_operation_id<>NEW.operation_id
         OR v_budget.starting_amount<>0 OR v_budget.starting_kind<>'unbudgeted_resolution'
       )) THEN
      RAISE EXCEPTION 'Unbudgeted resolution apply event is invalid' USING ERRCODE='23514';
    END IF;
  ELSE
    IF v_operation.operation_type<>'unbudgeted_resolution_reversal'
       OR NOT EXISTS (
         SELECT 1 FROM public.budget_unbudgeted_resolution_events original
         WHERE original.id=NEW.reverses_event_id AND original.event_kind='apply'
           AND original.budget_id=NEW.budget_id
       )
       OR (NEW.applied_funding>0 AND (
         v_action.action_kind<>'reversal'
         OR NOT EXISTS (
           SELECT 1 FROM public.budget_unbudgeted_resolution_events original
           WHERE original.id=NEW.reverses_event_id
             AND v_action.reversed_action_id=original.funding_action_id
         )
       )) THEN
      RAISE EXCEPTION 'Unbudgeted resolution reversal event is invalid' USING ERRCODE='23514';
    END IF;
  END IF;
  RETURN NEW;
END; $$;

CREATE TRIGGER budget_unbudgeted_resolution_events_validate
BEFORE INSERT ON public.budget_unbudgeted_resolution_events
FOR EACH ROW EXECUTE FUNCTION public.validate_budget_unbudgeted_resolution_event();
CREATE TRIGGER budget_unbudgeted_resolution_events_immutable
BEFORE UPDATE OR DELETE ON public.budget_unbudgeted_resolution_events
FOR EACH ROW EXECUTE FUNCTION public.prevent_budget_history_mutation();

-- Shared, exact source-capacity material for #23 deficit resolution and #22.
CREATE OR REPLACE FUNCTION public.budget_funding_source_rows(
  p_month TEXT,p_excluded_category_id BIGINT DEFAULT NULL
)
RETURNS TABLE (
  source_kind TEXT,category_id BIGINT,budget_id BIGINT,category_name TEXT,
  final_funded NUMERIC(18,2),raw_actual NUMERIC(18,2),
  effective_actual NUMERIC(18,2),capacity NUMERIC(18,2)
)
LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,public AS $$
WITH params AS (
  SELECT public.budget_month_start_from_key(p_month) month_start
), month_row AS (
  SELECT bm.id FROM public.budget_months bm,params p WHERE bm.month_start=p.month_start
), actuals AS (
  SELECT t.category_id,sum(t.total_amount)::numeric(18,2) raw_actual
  FROM public.transactions t,params p
  WHERE t.movement_type='expense' AND t.transaction_date>=p.month_start
    AND t.transaction_date<(p.month_start+interval '1 month')::date
  GROUP BY t.category_id
), category_sources AS (
  SELECT 'category'::text source_kind,cs.category_id,cs.budget_id,cs.category_name,
    cs.final_funded::numeric(18,2) final_funded,
    coalesce(a.raw_actual,0)::numeric(18,2) raw_actual,
    greatest(coalesce(a.raw_actual,0),0)::numeric(18,2) effective_actual,
    greatest(cs.final_funded-greatest(coalesce(a.raw_actual,0),0),0)::numeric(18,2) capacity
  FROM public.budget_category_state cs
  JOIN month_row mr ON mr.id=cs.budget_month_id
  JOIN public.categories c ON c.id=cs.category_id
  LEFT JOIN actuals a ON a.category_id=cs.category_id
  WHERE cs.lifecycle_state='active' AND cs.category_type='expense' AND c.is_active
    AND cs.category_id IS DISTINCT FROM p_excluded_category_id
)
SELECT * FROM category_sources
UNION ALL
SELECT 'unallocated',NULL,NULL,NULL,NULL,NULL,NULL,
  coalesce((SELECT s.unallocated FROM public.budget_month_funding_state s JOIN month_row mr ON mr.id=s.budget_month_id),0)::numeric(18,2)
UNION ALL
SELECT 'savings',NULL,NULL,NULL,NULL,NULL,NULL,
  coalesce((SELECT balance FROM public.budget_savings_state),0)::numeric(18,2);
$$;

-- Preserve #23's public contract while making its source material shared.
CREATE OR REPLACE FUNCTION public.get_budget_deficit_resolution_preview(
  p_month TEXT,p_destination_category_id BIGINT,p_legs JSONB
)
RETURNS JSONB
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public AS $$
DECLARE
  v_lifecycle TEXT:=public.budget_action_month_lifecycle(p_month);
  v_month_start DATE:=public.budget_month_start_from_key(p_month); v_month_id BIGINT;
  v_destination RECORD; v_raw NUMERIC(18,2):=0; v_deficit NUMERIC(18,2):=0;
  v_unallocated NUMERIC(18,2):=0; v_savings NUMERIC(18,2):=0;
  v_selected JSONB:='[]'::jsonb; v_sources JSONB:='[]'::jsonb;
  v_total NUMERIC(18,2):=0; v_reason TEXT; v_material TEXT:=''; v_seen TEXT[]:='{}';
  item JSONB; v_kind TEXT; v_amount NUMERIC(18,2); v_key TEXT;
  v_source RECORD;
BEGIN
  IF p_legs IS NULL OR jsonb_typeof(p_legs)<>'array' OR jsonb_array_length(p_legs)=0 THEN
    RAISE EXCEPTION 'At least one deficit funding leg is required' USING ERRCODE='22023';
  END IF;
  SELECT id INTO v_month_id FROM public.budget_months WHERE month_start=v_month_start;
  SELECT cs.*,c.is_active INTO v_destination FROM public.budget_category_state cs
  JOIN public.categories c ON c.id=cs.category_id
  WHERE cs.budget_month_id=v_month_id AND cs.category_id=p_destination_category_id;
  IF NOT FOUND THEN v_reason:='NO_BUDGET_DESTINATION';
  ELSIF v_destination.lifecycle_state<>'active' OR v_destination.category_type<>'expense'
        OR NOT v_destination.is_active THEN v_reason:='DESTINATION_BUDGET_NOT_ACTIVE';
  ELSE
    SELECT coalesce(sum(total_amount),0)::numeric(18,2) INTO v_raw FROM public.transactions
    WHERE movement_type='expense' AND category_id=p_destination_category_id
      AND transaction_date>=v_month_start AND transaction_date<(v_month_start+interval '1 month')::date;
    v_deficit:=greatest(v_raw-v_destination.final_funded,0);
    IF v_deficit<=0 THEN v_reason:='NO_ACTIVE_DEFICIT'; END IF;
  END IF;
  SELECT capacity INTO v_unallocated FROM public.budget_funding_source_rows(p_month,p_destination_category_id)
  WHERE source_kind='unallocated';
  SELECT capacity INTO v_savings FROM public.budget_funding_source_rows(p_month,p_destination_category_id)
  WHERE source_kind='savings';
  SELECT coalesce(jsonb_agg(jsonb_build_object(
    'category_id',s.category_id,'budget_id',s.budget_id,'category_name',s.category_name,
    'final_funded',s.final_funded::text,'raw_actual',s.raw_actual::text,
    'effective_actual',s.effective_actual::text,'capacity',s.capacity::text
  ) ORDER BY s.category_name,s.category_id),'[]'::jsonb) INTO v_sources
  FROM public.budget_funding_source_rows(p_month,p_destination_category_id) s
  WHERE s.source_kind='category' AND s.capacity>0;

  FOR item IN SELECT value FROM jsonb_array_elements(p_legs) LOOP
    v_kind:=item->>'source_kind';
    IF jsonb_typeof(item) IS DISTINCT FROM 'object'
       OR v_kind IS NULL OR v_kind NOT IN ('category','unallocated','savings')
       OR jsonb_typeof(item->'amount') IS DISTINCT FROM 'string'
       OR (item->>'amount')!~'^(0|[1-9][0-9]*)(\.[0-9]{1,2})?$' THEN
      RAISE EXCEPTION 'Deficit funding leg has an invalid source or money format' USING ERRCODE='22023';
    END IF;
    v_amount:=(item->>'amount')::numeric;
    IF v_amount<=0 OR v_amount>9999999999999999.99 THEN
      RAISE EXCEPTION 'Deficit funding leg amount must be positive' USING ERRCODE='22023';
    END IF;
    v_key:=v_kind||':'||coalesce(item->>'category_id','');
    IF v_key=ANY(v_seen) THEN RAISE EXCEPTION 'Duplicate deficit funding source' USING ERRCODE='22023'; END IF;
    v_seen:=array_append(v_seen,v_key);
    SELECT * INTO v_source FROM public.budget_funding_source_rows(p_month,p_destination_category_id) s
    WHERE s.source_kind=v_kind
      AND (v_kind<>'category' OR s.category_id=NULLIF(item->>'category_id','')::bigint);
    IF NOT FOUND THEN
      v_reason:=coalesce(v_reason,'SOURCE_BUDGET_NOT_ACTIVE');
      SELECT NULL::text source_kind,NULL::bigint category_id,NULL::bigint budget_id,
        NULL::text category_name,NULL::numeric final_funded,NULL::numeric raw_actual,
        NULL::numeric effective_actual,0::numeric capacity INTO v_source;
    END IF;
    IF v_amount>v_source.capacity THEN v_reason:=coalesce(v_reason,
      CASE WHEN v_kind='savings' THEN 'SAVINGS_INSUFFICIENT' ELSE 'DEFICIT_SOURCE_INSUFFICIENT' END);
    END IF;
    v_total:=v_total+v_amount;
    v_selected:=v_selected||jsonb_build_array(jsonb_build_object(
      'source_kind',v_kind,'category_id',CASE WHEN v_kind='category' THEN v_source.category_id END,
      'source_budget_id',CASE WHEN v_kind='category' THEN v_source.budget_id END,
      'amount',v_amount::numeric(18,2)::text,
      'source_final_funded',CASE WHEN v_kind='category' THEN v_source.final_funded::text END,
      'source_raw_actual',CASE WHEN v_kind='category' THEN v_source.raw_actual::text END,
      'source_effective_actual',CASE WHEN v_kind='category' THEN v_source.effective_actual::text END,
      'source_capacity',v_source.capacity::numeric(18,2)::text));
    v_material:=v_material||'|'||v_key||'|'||v_amount::numeric(18,2)::text||'|'||v_source.capacity::text
      ||'|'||coalesce(v_source.budget_id::text,'')||'|'||coalesce(v_source.final_funded::text,'')
      ||'|'||coalesce(v_source.raw_actual::text,'')||'|'||coalesce(v_source.effective_actual::text,'');
  END LOOP;
  IF v_lifecycle='closed' THEN v_reason:='BUDGET_MONTH_ALREADY_CLOSED';
  ELSIF v_lifecycle NOT IN ('current','immediately_completed_unclosed') THEN v_reason:='BUDGET_ACTION_MONTH_FORBIDDEN';
  ELSIF v_total>v_deficit THEN v_reason:=coalesce(v_reason,'DEFICIT_RESOLUTION_EXCEEDS_DEFICIT');
  END IF;
  RETURN jsonb_build_object(
    'month',p_month,'lifecycle',v_lifecycle,'destination_category_id',p_destination_category_id,
    'destination_budget_id',v_destination.budget_id,
    'current_funded',coalesce(v_destination.final_funded,0)::numeric(18,2)::text,
    'actual',v_raw::text,'deficit',v_deficit::text,'unallocated_capacity',v_unallocated::text,
    'savings_balance',v_savings::text,'eligible_source_categories',v_sources,
    'selected_legs',v_selected,'requested_resolution',v_total::numeric(18,2)::text,
    'resulting_funded',(coalesce(v_destination.final_funded,0)+v_total)::numeric(18,2)::text,
    'remaining_deficit',greatest(v_deficit-v_total,0)::numeric(18,2)::text,
    'fingerprint',md5(concat_ws('|','deficit',p_month,v_lifecycle,p_destination_category_id,
      coalesce(v_destination.budget_id::text,''),coalesce(v_destination.final_funded::text,''),
      v_raw::text,v_deficit::text,v_unallocated::text,v_savings::text,v_material,coalesce(v_reason,''))),
    'can_apply',v_reason IS NULL,'reason',v_reason
  );
END; $$;

CREATE OR REPLACE FUNCTION public.get_budget_unbudgeted_resolution_preview(
  p_month TEXT,p_category_id BIGINT,p_requested_amount NUMERIC,p_legs JSONB
)
RETURNS JSONB
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public AS $$
DECLARE
  v_month_start DATE:=public.budget_month_start_from_key(p_month);
  v_lifecycle TEXT:=public.budget_action_month_lifecycle(p_month);
  v_month_id BIGINT; v_category public.categories%ROWTYPE;
  v_budget_id BIGINT; v_budget_lifecycle TEXT; v_existing_funded NUMERIC(18,2):=0;
  v_mode TEXT:='created'; v_raw NUMERIC(18,2):=0; v_maximum NUMERIC(18,2):=0;
  v_unallocated NUMERIC(18,2):=0; v_savings NUMERIC(18,2):=0;
  v_sources JSONB:='[]'::jsonb; v_selected JSONB:='[]'::jsonb;
  v_total NUMERIC(18,2):=0; v_resulting NUMERIC(18,2):=0; v_deficit NUMERIC(18,2):=0;
  v_reason TEXT; v_material TEXT:=''; v_seen TEXT[]:='{}';
  item JSONB; v_kind TEXT; v_amount NUMERIC(18,2); v_key TEXT; v_source RECORD;
  v_pending_override BOOLEAN:=false;
BEGIN
  IF p_requested_amount IS NULL OR p_requested_amount::text IN ('NaN','Infinity','-Infinity')
     OR p_requested_amount<0 OR p_requested_amount<>round(p_requested_amount,2)
     OR p_requested_amount>9999999999999999.99 THEN
    RAISE EXCEPTION 'requested_amount must be a nonnegative two-decimal value' USING ERRCODE='22023';
  END IF;
  IF p_legs IS NULL OR jsonb_typeof(p_legs)<>'array' THEN
    RAISE EXCEPTION 'legs must be an array' USING ERRCODE='22023';
  END IF;
  SELECT * INTO v_category FROM public.categories WHERE id=p_category_id;
  IF NOT FOUND THEN v_reason:='INVALID_BUDGET_CATEGORY';
  ELSIF v_category.type<>'expense' THEN v_reason:='INVALID_BUDGET_CATEGORY';
  ELSIF NOT v_category.is_active THEN v_reason:='CATEGORY_NOT_ACTIVE';
  END IF;
  SELECT id INTO v_month_id FROM public.budget_months WHERE month_start=v_month_start;
  SELECT cs.budget_id,cs.lifecycle_state,cs.final_funded
    INTO v_budget_id,v_budget_lifecycle,v_existing_funded
  FROM public.budget_category_state cs
  WHERE cs.budget_month_id=v_month_id AND cs.category_id=p_category_id;
  IF FOUND THEN
    IF v_budget_lifecycle='active' THEN v_reason:=coalesce(v_reason,'NO_UNBUDGETED_EXPENSE');
    ELSE v_mode:='reactivated'; END IF;
  ELSE
    v_budget_id:=NULL; v_budget_lifecycle:='no_budget'; v_existing_funded:=0;
  END IF;
  IF EXISTS (
    SELECT 1 FROM public.transactions
    WHERE movement_type='expense' AND category_id=p_category_id
      AND transaction_date>=v_month_start AND transaction_date<(v_month_start+interval '1 month')::date
      AND total_amount::text IN ('NaN','Infinity','-Infinity')
  ) THEN
    RAISE EXCEPTION 'Unbudgeted actual spending contains a non-finite amount' USING ERRCODE='22003';
  END IF;
  SELECT coalesce(sum(total_amount),0)::numeric(18,2) INTO v_raw FROM public.transactions
  WHERE movement_type='expense' AND category_id=p_category_id
    AND transaction_date>=v_month_start AND transaction_date<(v_month_start+interval '1 month')::date;
  IF v_raw<=0 THEN v_reason:=coalesce(v_reason,'NO_UNBUDGETED_EXPENSE'); END IF;
  v_pending_override:=v_budget_id IS NULL AND EXISTS (
    SELECT 1 FROM public.budget_month_overrides
    WHERE budget_month_id=v_month_id AND category_id=p_category_id
  );
  IF v_pending_override THEN v_reason:=coalesce(v_reason,'UNBUDGETED_RESOLUTION_PENDING_OVERRIDE'); END IF;
  v_maximum:=greatest(v_raw-v_existing_funded,0);
  IF p_requested_amount>v_maximum THEN v_reason:=coalesce(v_reason,'UNBUDGETED_RESOLUTION_EXCEEDS_ACTUAL');
  ELSIF p_requested_amount=0 AND (v_mode='created' OR v_existing_funded<v_raw) THEN
    v_reason:=coalesce(v_reason,'UNBUDGETED_RESOLUTION_REQUIRES_FUNDING');
  END IF;
  IF v_lifecycle='closed' THEN v_reason:='BUDGET_MONTH_ALREADY_CLOSED';
  ELSIF v_lifecycle NOT IN ('current','immediately_completed_unclosed') THEN
    v_reason:='BUDGET_ACTION_MONTH_FORBIDDEN';
  END IF;

  SELECT capacity INTO v_unallocated FROM public.budget_funding_source_rows(p_month,p_category_id)
  WHERE source_kind='unallocated';
  SELECT capacity INTO v_savings FROM public.budget_funding_source_rows(p_month,p_category_id)
  WHERE source_kind='savings';
  SELECT coalesce(jsonb_agg(jsonb_build_object(
    'category_id',s.category_id,'budget_id',s.budget_id,'category_name',s.category_name,
    'final_funded',s.final_funded::text,'raw_actual',s.raw_actual::text,
    'effective_actual',s.effective_actual::text,'capacity',s.capacity::text
  ) ORDER BY s.category_name,s.category_id),'[]'::jsonb) INTO v_sources
  FROM public.budget_funding_source_rows(p_month,p_category_id) s
  WHERE s.source_kind='category' AND s.capacity>0;

  FOR item IN SELECT value FROM jsonb_array_elements(p_legs) LOOP
    v_kind:=item->>'source_kind';
    IF jsonb_typeof(item) IS DISTINCT FROM 'object'
       OR v_kind IS NULL OR v_kind NOT IN ('category','unallocated','savings')
       OR jsonb_typeof(item->'amount') IS DISTINCT FROM 'string'
       OR (item->>'amount')!~'^(0|[1-9][0-9]*)(\.[0-9]{1,2})?$' THEN
      RAISE EXCEPTION 'Unbudgeted funding leg has an invalid source or money format' USING ERRCODE='22023';
    END IF;
    v_amount:=(item->>'amount')::numeric;
    IF v_amount<=0 OR v_amount>9999999999999999.99 THEN
      RAISE EXCEPTION 'Unbudgeted funding leg amount must be positive' USING ERRCODE='22023';
    END IF;
    v_key:=v_kind||':'||coalesce(item->>'category_id','');
    IF v_key=ANY(v_seen) THEN RAISE EXCEPTION 'Duplicate unbudgeted funding source' USING ERRCODE='22023'; END IF;
    v_seen:=array_append(v_seen,v_key);
    SELECT * INTO v_source FROM public.budget_funding_source_rows(p_month,p_category_id) s
    WHERE s.source_kind=v_kind
      AND (v_kind<>'category' OR s.category_id=NULLIF(item->>'category_id','')::bigint);
    IF NOT FOUND THEN
      v_reason:=coalesce(v_reason,'UNBUDGETED_RESOLUTION_SOURCE_INSUFFICIENT');
      SELECT NULL::text source_kind,NULL::bigint category_id,NULL::bigint budget_id,
        NULL::text category_name,NULL::numeric final_funded,NULL::numeric raw_actual,
        NULL::numeric effective_actual,0::numeric capacity INTO v_source;
    END IF;
    IF v_amount>v_source.capacity THEN v_reason:=coalesce(v_reason,
      CASE WHEN v_kind='savings' THEN 'SAVINGS_INSUFFICIENT' ELSE 'UNBUDGETED_RESOLUTION_SOURCE_INSUFFICIENT' END);
    END IF;
    v_total:=v_total+v_amount;
    v_selected:=v_selected||jsonb_build_array(jsonb_build_object(
      'source_kind',v_kind,'category_id',CASE WHEN v_kind='category' THEN v_source.category_id END,
      'source_budget_id',CASE WHEN v_kind='category' THEN v_source.budget_id END,
      'amount',v_amount::numeric(18,2)::text,
      'source_final_funded',CASE WHEN v_kind='category' THEN v_source.final_funded::text END,
      'source_raw_actual',CASE WHEN v_kind='category' THEN v_source.raw_actual::text END,
      'source_effective_actual',CASE WHEN v_kind='category' THEN v_source.effective_actual::text END,
      'source_capacity',v_source.capacity::numeric(18,2)::text));
    v_material:=v_material||'|'||v_key||'|'||v_amount::numeric(18,2)::text||'|'||v_source.capacity::text
      ||'|'||coalesce(v_source.budget_id::text,'')||'|'||coalesce(v_source.final_funded::text,'')
      ||'|'||coalesce(v_source.raw_actual::text,'')||'|'||coalesce(v_source.effective_actual::text,'');
  END LOOP;
  IF v_total<>p_requested_amount THEN
    v_reason:=coalesce(v_reason,'UNBUDGETED_RESOLUTION_LEG_TOTAL_MISMATCH');
  END IF;
  v_resulting:=v_existing_funded+p_requested_amount;
  v_deficit:=greatest(v_raw-v_resulting,0);
  RETURN jsonb_build_object(
    'month',p_month,'lifecycle',v_lifecycle,'category_id',p_category_id,
    'category',CASE WHEN v_category.id IS NULL THEN NULL ELSE jsonb_build_object(
      'id',v_category.id,'name',v_category.name,'icon',v_category.icon,'type',v_category.type,
      'is_active',v_category.is_active) END,
    'resolution_mode',v_mode,'budget_id',v_budget_id,'budget_lifecycle',v_budget_lifecycle,
    'raw_actual',v_raw::numeric(18,2)::text,
    'existing_funded',v_existing_funded::numeric(18,2)::text,
    'maximum_allocation',v_maximum::numeric(18,2)::text,
    'requested_allocation',p_requested_amount::numeric(18,2)::text,
    'resulting_funded',v_resulting::numeric(18,2)::text,
    'remaining_deficit',v_deficit::numeric(18,2)::text,
    'unallocated_capacity',v_unallocated::numeric(18,2)::text,
    'savings_balance',v_savings::numeric(18,2)::text,
    'eligible_source_categories',v_sources,'selected_legs',v_selected,
    'pending_override',v_pending_override,
    'fingerprint',md5(concat_ws('|','unbudgeted',p_month,v_lifecycle,p_category_id,
      coalesce(v_category.type,''),coalesce(v_category.is_active::text,''),v_mode,
      coalesce(v_budget_id::text,''),v_budget_lifecycle,v_raw::text,v_existing_funded::text,
      p_requested_amount::numeric(18,2)::text,v_unallocated::text,v_savings::text,
      v_pending_override::text,v_material,coalesce(v_reason,''))),
    'can_apply',v_reason IS NULL,'reason',v_reason
  );
END; $$;

CREATE OR REPLACE FUNCTION public.apply_budget_unbudgeted_resolution(
  p_month TEXT,p_category_id BIGINT,p_requested_amount NUMERIC,p_legs JSONB,
  p_request_key UUID,p_preview_fingerprint TEXT,p_reason TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $$
DECLARE
  v_month_start DATE:=public.budget_month_start_from_key(p_month); v_month_id BIGINT;
  v_existing public.budget_operations%ROWTYPE; v_preview JSONB;
  v_operation_id BIGINT; v_budget_id BIGINT; v_action_id BIGINT; v_event_id BIGINT;
  v_movement_id BIGINT; v_savings_entry_id BIGINT; v_savings_total NUMERIC(18,2):=0;
  v_effective_date DATE; item JSONB;
BEGIN
  IF p_request_key IS NULL OR p_preview_fingerprint IS NULL OR p_preview_fingerprint!~'^[0-9a-f]{32}$' THEN
    RAISE EXCEPTION 'request_key and preview fingerprint are required' USING ERRCODE='22023';
  END IF;
  SELECT * INTO v_existing FROM public.budget_operations WHERE request_key=p_request_key;
  IF FOUND THEN
    IF v_existing.operation_type<>'unbudgeted_resolution'
       OR v_existing.request_fingerprint<>p_preview_fingerprint THEN
      RAISE EXCEPTION 'request_key was already used for a different budget operation' USING ERRCODE='23505';
    END IF;
    RETURN jsonb_build_object(
      'event_id',(SELECT id FROM public.budget_unbudgeted_resolution_events WHERE operation_id=v_existing.id),
      'action_id',(SELECT id FROM public.budget_funding_actions WHERE operation_id=v_existing.id),
      'state',public.get_funded_budget_month(p_month));
  END IF;
  LOCK TABLE public.transactions IN SHARE MODE;
  IF EXISTS(
    SELECT 1 FROM jsonb_array_elements(p_legs) AS leg(value)
    WHERE leg.value->>'source_kind'='savings'
  ) THEN
    PERFORM pg_advisory_xact_lock(hashtext('finance_tracker_budget_savings'));
  END IF;
  INSERT INTO public.budget_months(month_start) VALUES(v_month_start) ON CONFLICT(month_start) DO NOTHING;
  SELECT id INTO v_month_id FROM public.budget_months WHERE month_start=v_month_start FOR UPDATE;
  PERFORM 1 FROM public.budgets WHERE budget_month_id=v_month_id AND category_id IN (
    SELECT p_category_id UNION
    SELECT NULLIF(leg.value->>'category_id','')::bigint
    FROM jsonb_array_elements(p_legs) AS leg(value)
    WHERE leg.value->>'source_kind'='category'
  ) ORDER BY id FOR UPDATE;
  PERFORM 1 FROM public.categories WHERE id IN (
    SELECT p_category_id UNION
    SELECT NULLIF(leg.value->>'category_id','')::bigint
    FROM jsonb_array_elements(p_legs) AS leg(value)
    WHERE leg.value->>'source_kind'='category'
  ) ORDER BY id FOR UPDATE;
  v_preview:=public.get_budget_unbudgeted_resolution_preview(
    p_month,p_category_id,p_requested_amount,p_legs
  );
  IF v_preview->>'fingerprint'<>p_preview_fingerprint THEN
    RAISE EXCEPTION 'UNBUDGETED_RESOLUTION_PREVIEW_STALE: refresh the preview before applying'
      USING ERRCODE='40001';
  END IF;
  IF NOT (v_preview->>'can_apply')::boolean THEN
    RAISE EXCEPTION '%: unbudgeted resolution cannot be applied',v_preview->>'reason' USING ERRCODE='23514';
  END IF;
  v_effective_date:=CASE WHEN v_preview->>'lifecycle'='current'
    THEN timezone('Asia/Jerusalem',statement_timestamp())::date
    ELSE (v_month_start+interval '1 month - 1 day')::date END;
  INSERT INTO public.budget_operations(
    budget_month_id,request_key,request_fingerprint,operation_type,effective_date,reason
  ) VALUES(v_month_id,p_request_key,p_preview_fingerprint,'unbudgeted_resolution',v_effective_date,p_reason)
  RETURNING id INTO v_operation_id;
  IF v_preview->>'resolution_mode'='created' THEN
    INSERT INTO public.budgets(
      category_id,month,amount,budget_month_id,starting_amount,starting_kind,created_by_operation_id
    ) VALUES(p_category_id,p_month,0,v_month_id,0,'unbudgeted_resolution',v_operation_id)
    RETURNING id INTO v_budget_id;
  ELSE
    v_budget_id:=(v_preview->>'budget_id')::bigint;
  END IF;
  INSERT INTO public.budget_lifecycle_events(operation_id,budget_id,state)
  VALUES(v_operation_id,v_budget_id,'active');

  IF p_requested_amount>0 THEN
    INSERT INTO public.budget_funding_actions(
      operation_id,action_kind,budget_month_id,destination_budget_id,requested_amount,applied_amount,
      destination_final_funded_snapshot,destination_raw_actual_snapshot,deficit_before,deficit_after
    ) VALUES(v_operation_id,'unbudgeted_resolution',v_month_id,v_budget_id,
      p_requested_amount,p_requested_amount,(v_preview->>'existing_funded')::numeric,
      (v_preview->>'raw_actual')::numeric,NULL,(v_preview->>'remaining_deficit')::numeric)
    RETURNING id INTO v_action_id;
    SELECT coalesce(sum((leg.value->>'amount')::numeric),0) INTO v_savings_total
    FROM jsonb_array_elements(v_preview->'selected_legs') AS leg(value)
    WHERE leg.value->>'source_kind'='savings';
    IF v_savings_total>0 THEN
      INSERT INTO public.budget_funding_entries(operation_id,amount_delta,source_kind,source_label)
      VALUES(v_operation_id,v_savings_total,'savings_withdrawal','Explicit Savings-funded unbudgeted resolution');
    END IF;
    FOR item IN SELECT value FROM jsonb_array_elements(v_preview->'selected_legs') LOOP
      INSERT INTO public.budget_movements(operation_id,source_budget_id,destination_budget_id,amount)
      VALUES(v_operation_id,NULLIF(item->>'source_budget_id','')::bigint,v_budget_id,(item->>'amount')::numeric)
      RETURNING id INTO v_movement_id;
      v_savings_entry_id:=NULL;
      IF item->>'source_kind'='savings' THEN
        INSERT INTO public.budget_savings_entries(
          operation_id,category_id,amount_delta,entry_kind,destination_budget_month_id,
          destination_budget_id,movement_id
        ) VALUES(v_operation_id,p_category_id,-(item->>'amount')::numeric,'withdrawal',
          v_month_id,v_budget_id,v_movement_id) RETURNING id INTO v_savings_entry_id;
      END IF;
      INSERT INTO public.budget_funding_action_legs(
        action_id,source_kind,source_budget_id,amount,source_final_funded_snapshot,
        source_raw_actual_snapshot,source_effective_actual_snapshot,source_capacity_snapshot,
        movement_id,savings_entry_id
      ) VALUES(v_action_id,item->>'source_kind',NULLIF(item->>'source_budget_id','')::bigint,
        (item->>'amount')::numeric,NULLIF(item->>'source_final_funded','')::numeric,
        NULLIF(item->>'source_raw_actual','')::numeric,NULLIF(item->>'source_effective_actual','')::numeric,
        (item->>'source_capacity')::numeric,v_movement_id,v_savings_entry_id);
    END LOOP;
  END IF;
  INSERT INTO public.budget_unbudgeted_resolution_events(
    operation_id,funding_action_id,budget_month_id,category_id,budget_id,event_kind,resolution_mode,
    raw_actual_snapshot,existing_funded_snapshot,applied_funding,resulting_final_funded,resulting_deficit
  ) VALUES(v_operation_id,v_action_id,v_month_id,p_category_id,v_budget_id,'apply',
    v_preview->>'resolution_mode',(v_preview->>'raw_actual')::numeric,
    (v_preview->>'existing_funded')::numeric,p_requested_amount,
    (v_preview->>'resulting_funded')::numeric,(v_preview->>'remaining_deficit')::numeric)
  RETURNING id INTO v_event_id;
  PERFORM public.budget_assert_reconciled(v_month_id);
  IF (SELECT balance FROM public.budget_savings_state)<0 THEN
    RAISE EXCEPTION 'Savings ledger cannot have a negative balance' USING ERRCODE='23514';
  END IF;
  RETURN jsonb_build_object('event_id',v_event_id,'action_id',v_action_id,
    'applied_amount',p_requested_amount::numeric(18,2)::text,
    'remaining_deficit',v_preview->>'remaining_deficit','state',public.get_funded_budget_month(p_month));
END; $$;

CREATE OR REPLACE FUNCTION public.reverse_budget_unbudgeted_resolution(
  p_event_id BIGINT,p_request_key UUID,p_reason TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public AS $$
DECLARE
  v_original public.budget_unbudgeted_resolution_events%ROWTYPE;
  v_existing public.budget_operations%ROWTYPE; v_month public.budget_months%ROWTYPE;
  v_operation_id BIGINT; v_action_id BIGINT; v_event_id BIGINT; v_fingerprint TEXT;
  v_current_final NUMERIC(18,2); v_current_raw NUMERIC(18,2); v_movement_id BIGINT; v_savings_entry_id BIGINT;
  v_savings_total NUMERIC(18,2):=0; v_original_funding public.budget_funding_entries%ROWTYPE;
  original_leg RECORD;
BEGIN
  IF p_event_id IS NULL OR p_request_key IS NULL THEN
    RAISE EXCEPTION 'event_id and request_key are required' USING ERRCODE='22023';
  END IF;
  SELECT * INTO v_original FROM public.budget_unbudgeted_resolution_events
  WHERE id=p_event_id AND event_kind='apply';
  IF NOT FOUND THEN RAISE EXCEPTION 'Unbudgeted resolution does not exist' USING ERRCODE='P0002'; END IF;
  v_fingerprint:='unbudgeted_resolution_reverse|'||p_event_id::text;
  SELECT * INTO v_existing FROM public.budget_operations WHERE request_key=p_request_key;
  IF FOUND THEN
    IF v_existing.operation_type<>'unbudgeted_resolution_reversal'
       OR v_existing.request_fingerprint<>v_fingerprint THEN
      RAISE EXCEPTION 'request_key was already used for a different budget operation' USING ERRCODE='23505';
    END IF;
    RETURN jsonb_build_object(
      'event_id',(SELECT id FROM public.budget_unbudgeted_resolution_events WHERE operation_id=v_existing.id),
      'action_id',(SELECT id FROM public.budget_funding_actions WHERE operation_id=v_existing.id),
      'state',public.get_funded_budget_month((SELECT to_char(month_start,'YYYY-MM') FROM public.budget_months WHERE id=v_original.budget_month_id)));
  END IF;
  LOCK TABLE public.transactions IN SHARE MODE;
  IF v_original.funding_action_id IS NOT NULL AND EXISTS(
    SELECT 1 FROM public.budget_funding_action_legs
    WHERE action_id=v_original.funding_action_id AND source_kind='savings'
  ) THEN PERFORM pg_advisory_xact_lock(hashtext('finance_tracker_budget_savings')); END IF;
  SELECT * INTO v_month FROM public.budget_months WHERE id=v_original.budget_month_id FOR UPDATE;
  PERFORM 1 FROM public.budgets WHERE budget_month_id=v_month.id ORDER BY id FOR UPDATE;
  PERFORM 1 FROM public.categories WHERE id IN (
    SELECT v_original.category_id UNION
    SELECT b.category_id FROM public.budget_funding_action_legs l
    JOIN public.budgets b ON b.id=l.source_budget_id WHERE l.action_id=v_original.funding_action_id
  ) ORDER BY id FOR UPDATE;
  IF public.budget_action_month_lifecycle(to_char(v_month.month_start,'YYYY-MM'))='closed' THEN
    RAISE EXCEPTION 'BUDGET_MONTH_ALREADY_CLOSED: closed months require a historical correction workflow' USING ERRCODE='23514';
  ELSIF public.budget_action_month_lifecycle(to_char(v_month.month_start,'YYYY-MM'))
        NOT IN ('current','immediately_completed_unclosed') THEN
    RAISE EXCEPTION 'BUDGET_ACTION_MONTH_FORBIDDEN: action is outside the allowed month lifecycle' USING ERRCODE='23514';
  END IF;
  IF EXISTS(SELECT 1 FROM public.budget_unbudgeted_resolution_events WHERE reverses_event_id=p_event_id) THEN
    RAISE EXCEPTION 'Unbudgeted resolution has already been reversed' USING ERRCODE='23505';
  END IF;
  SELECT final_funded INTO v_current_final FROM public.budget_category_state
  WHERE budget_id=v_original.budget_id AND lifecycle_state='active';
  IF NOT FOUND OR v_current_final<v_original.applied_funding THEN
    RAISE EXCEPTION 'UNBUDGETED_RESOLUTION_REVERSAL_BLOCKED: destination funding or lifecycle changed'
      USING ERRCODE='23514';
  END IF;
  SELECT coalesce(sum(total_amount),0)::numeric(18,2) INTO v_current_raw
  FROM public.transactions
  WHERE movement_type='expense' AND category_id=v_original.category_id
    AND transaction_date>=v_month.month_start
    AND transaction_date<(v_month.month_start+interval '1 month')::date;
  INSERT INTO public.budget_operations(
    budget_month_id,request_key,request_fingerprint,operation_type,effective_date,reason,
    reverses_operation_id
  ) VALUES(v_month.id,p_request_key,v_fingerprint,'unbudgeted_resolution_reversal',
    CASE WHEN v_month.month_start=date_trunc('month',timezone('Asia/Jerusalem',statement_timestamp()))::date
      THEN timezone('Asia/Jerusalem',statement_timestamp())::date
      ELSE (v_month.month_start+interval '1 month - 1 day')::date END,
    p_reason,v_original.operation_id) RETURNING id INTO v_operation_id;
  IF v_original.funding_action_id IS NOT NULL THEN
    INSERT INTO public.budget_funding_actions(
      operation_id,action_kind,budget_month_id,destination_budget_id,requested_amount,applied_amount,
      destination_final_funded_snapshot,destination_raw_actual_snapshot,deficit_before,deficit_after,
      reversed_action_id
    ) VALUES(v_operation_id,'reversal',v_month.id,v_original.budget_id,
      v_original.applied_funding,v_original.applied_funding,v_current_final,
      v_original.raw_actual_snapshot,NULL,NULL,v_original.funding_action_id)
    RETURNING id INTO v_action_id;
    SELECT coalesce(sum(amount),0) INTO v_savings_total FROM public.budget_funding_action_legs
    WHERE action_id=v_original.funding_action_id AND source_kind='savings';
    IF v_savings_total>0 THEN
      SELECT * INTO v_original_funding FROM public.budget_funding_entries
      WHERE operation_id=v_original.operation_id;
      INSERT INTO public.budget_funding_entries(
        operation_id,amount_delta,source_kind,source_label,reverses_funding_entry_id
      ) VALUES(v_operation_id,-v_savings_total,'savings_withdrawal',
        'Reverse Savings-funded unbudgeted resolution',v_original_funding.id);
    END IF;
    FOR original_leg IN
      SELECT l.*,m.source_budget_id original_source,m.destination_budget_id original_destination
      FROM public.budget_funding_action_legs l JOIN public.budget_movements m ON m.id=l.movement_id
      WHERE l.action_id=v_original.funding_action_id ORDER BY l.id
    LOOP
      INSERT INTO public.budget_movements(operation_id,source_budget_id,destination_budget_id,amount)
      VALUES(v_operation_id,original_leg.original_destination,original_leg.original_source,original_leg.amount)
      RETURNING id INTO v_movement_id;
      v_savings_entry_id:=NULL;
      IF original_leg.source_kind='savings' THEN
        INSERT INTO public.budget_savings_entries(
          operation_id,category_id,amount_delta,entry_kind,reverses_entry_id,
          destination_budget_month_id,destination_budget_id,movement_id
        ) VALUES(v_operation_id,v_original.category_id,original_leg.amount,'withdrawal_reversal',
          original_leg.savings_entry_id,v_month.id,v_original.budget_id,v_movement_id)
        RETURNING id INTO v_savings_entry_id;
      END IF;
      INSERT INTO public.budget_funding_action_legs(
        action_id,source_kind,source_budget_id,amount,source_final_funded_snapshot,
        source_raw_actual_snapshot,source_effective_actual_snapshot,source_capacity_snapshot,
        movement_id,savings_entry_id
      ) VALUES(v_action_id,original_leg.source_kind,original_leg.source_budget_id,original_leg.amount,
        original_leg.source_final_funded_snapshot,original_leg.source_raw_actual_snapshot,
        original_leg.source_effective_actual_snapshot,original_leg.source_capacity_snapshot,
        v_movement_id,v_savings_entry_id);
    END LOOP;
  END IF;
  INSERT INTO public.budget_lifecycle_events(operation_id,budget_id,state,actual_spent_snapshot)
  VALUES(v_operation_id,v_original.budget_id,'inactive',greatest(v_current_raw,0));
  INSERT INTO public.budget_unbudgeted_resolution_events(
    operation_id,funding_action_id,budget_month_id,category_id,budget_id,event_kind,resolution_mode,
    raw_actual_snapshot,existing_funded_snapshot,applied_funding,resulting_final_funded,
    resulting_deficit,reverses_event_id
  ) VALUES(v_operation_id,v_action_id,v_month.id,v_original.category_id,v_original.budget_id,
    'reversal',v_original.resolution_mode,v_current_raw,
    v_current_final,v_original.applied_funding,
    v_current_final-v_original.applied_funding,
    greatest(v_current_raw-(v_current_final-v_original.applied_funding),0),p_event_id)
  RETURNING id INTO v_event_id;
  PERFORM public.budget_assert_reconciled(v_month.id);
  IF (SELECT balance FROM public.budget_savings_state)<0 THEN
    RAISE EXCEPTION 'Savings ledger cannot have a negative balance' USING ERRCODE='23514';
  END IF;
  RETURN jsonb_build_object('event_id',v_event_id,'action_id',v_action_id,
    'state',public.get_funded_budget_month(to_char(v_month.month_start,'YYYY-MM')));
END; $$;

CREATE OR REPLACE VIEW public.budget_category_funding_action_state AS
WITH movements AS (
  SELECT cs.budget_id,m.source_budget_id,m.destination_budget_id,m.amount,
    CASE WHEN a.action_kind='reversal' THEN original.action_kind ELSE a.action_kind END effective_kind
  FROM public.budget_category_state cs
  LEFT JOIN public.budget_movements m
    ON m.source_budget_id=cs.budget_id OR m.destination_budget_id=cs.budget_id
  LEFT JOIN public.budget_funding_actions a ON a.operation_id=m.operation_id
  LEFT JOIN public.budget_funding_actions original ON original.id=a.reversed_action_id
  WHERE a.id IS NOT NULL OR m.id IS NULL
)
SELECT budget_id,
  coalesce(sum(amount) FILTER (WHERE destination_budget_id=budget_id
    AND effective_kind IN ('planned_reallocation','deficit_resolution')),0)::numeric(18,2)
    AS incoming_reallocation_resolution,
  coalesce(sum(amount) FILTER (WHERE source_budget_id=budget_id
    AND effective_kind IN ('planned_reallocation','deficit_resolution')),0)::numeric(18,2)
    AS outgoing_reallocation,
  (coalesce(sum(amount) FILTER (WHERE destination_budget_id=budget_id),0)
   -coalesce(sum(amount) FILTER (WHERE source_budget_id=budget_id),0))::numeric(18,2)
    AS net_funding_action_adjustment,
  coalesce(sum(amount) FILTER (WHERE destination_budget_id=budget_id
    AND effective_kind='unbudgeted_resolution'),0)::numeric(18,2)
    AS incoming_unbudgeted_resolution,
  coalesce(sum(amount) FILTER (WHERE source_budget_id=budget_id
    AND effective_kind='unbudgeted_resolution'),0)::numeric(18,2)
    AS outgoing_unbudgeted_resolution
FROM movements GROUP BY budget_id;

CREATE VIEW public.budget_unbudgeted_resolution_history AS
SELECT e.id AS event_id,e.event_kind,e.resolution_mode,
  to_char(bm.month_start,'YYYY-MM') AS month,e.category_id,e.budget_id,
  e.raw_actual_snapshot::numeric(18,2)::text AS raw_actual_snapshot,
  e.existing_funded_snapshot::numeric(18,2)::text AS existing_funded_snapshot,
  e.applied_funding::numeric(18,2)::text AS applied_funding,
  e.resulting_final_funded::numeric(18,2)::text AS resulting_final_funded,
  e.resulting_deficit::numeric(18,2)::text AS resulting_deficit,
  e.funding_action_id,e.reverses_event_id,e.created_at
FROM public.budget_unbudgeted_resolution_events e
JOIN public.budget_months bm ON bm.id=e.budget_month_id;

CREATE OR REPLACE FUNCTION public.get_funded_budget_month(p_month TEXT)
RETURNS JSONB
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public AS $$
DECLARE
  v_state JSONB:=public.get_funded_budget_month_disposition(p_month);
  v_categories JSONB; v_action_history JSONB; v_resolution_history JSONB;
BEGIN
  SELECT coalesce(jsonb_agg(item||jsonb_build_object(
    'incoming_reallocation_resolution',coalesce(a.incoming_reallocation_resolution,0)::numeric(18,2)::text,
    'outgoing_reallocation',coalesce(a.outgoing_reallocation,0)::numeric(18,2)::text,
    'incoming_unbudgeted_resolution',coalesce(a.incoming_unbudgeted_resolution,0)::numeric(18,2)::text,
    'outgoing_unbudgeted_resolution',coalesce(a.outgoing_unbudgeted_resolution,0)::numeric(18,2)::text,
    'funding_action_adjustment_total',coalesce(a.net_funding_action_adjustment,0)::numeric(18,2)::text,
    'other_adjustments',(
      coalesce(NULLIF(item->>'other_adjustments','')::numeric,0)
      -coalesce(a.net_funding_action_adjustment,0)
    )::numeric(18,2)::text
  ) ORDER BY ordinality),'[]'::jsonb) INTO v_categories
  FROM jsonb_array_elements(coalesce(v_state->'categories','[]'::jsonb))
    WITH ORDINALITY category(item,ordinality)
  LEFT JOIN public.budget_category_funding_action_state a
    ON a.budget_id=NULLIF(item->>'budget_id','')::bigint;
  SELECT coalesce(jsonb_agg(to_jsonb(h) ORDER BY h.action_id),'[]'::jsonb) INTO v_action_history
  FROM public.budget_funding_action_history h WHERE h.month=p_month;
  SELECT coalesce(jsonb_agg(to_jsonb(h) ORDER BY h.event_id),'[]'::jsonb) INTO v_resolution_history
  FROM public.budget_unbudgeted_resolution_history h WHERE h.month=p_month;
  RETURN v_state||jsonb_build_object(
    'categories',v_categories,'funding_action_history',v_action_history,
    'unbudgeted_resolution_history',v_resolution_history,
    'action_lifecycle',public.budget_action_month_lifecycle(p_month));
END; $$;

ALTER TABLE public.budget_unbudgeted_resolution_events ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.budget_unbudgeted_resolution_events,
  public.budget_unbudgeted_resolution_history FROM PUBLIC,anon,authenticated,service_role;
GRANT SELECT ON public.budget_unbudgeted_resolution_events,
  public.budget_unbudgeted_resolution_history TO service_role;

REVOKE ALL ON FUNCTION public.budget_funding_source_rows(TEXT,BIGINT),
  public.validate_budget_unbudgeted_resolution_event()
  FROM PUBLIC,anon,authenticated,service_role;
REVOKE ALL ON FUNCTION public.get_budget_unbudgeted_resolution_preview(TEXT,BIGINT,NUMERIC,JSONB),
  public.apply_budget_unbudgeted_resolution(TEXT,BIGINT,NUMERIC,JSONB,UUID,TEXT,TEXT),
  public.reverse_budget_unbudgeted_resolution(BIGINT,UUID,TEXT)
  FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.get_budget_unbudgeted_resolution_preview(TEXT,BIGINT,NUMERIC,JSONB),
  public.apply_budget_unbudgeted_resolution(TEXT,BIGINT,NUMERIC,JSONB,UUID,TEXT,TEXT),
  public.reverse_budget_unbudgeted_resolution(BIGINT,UUID,TEXT)
  TO service_role;

DO $$
DECLARE v_month RECORD;
BEGIN
  FOR v_month IN SELECT id FROM public.budget_months ORDER BY id LOOP
    PERFORM public.budget_assert_reconciled(v_month.id);
  END LOOP;
  IF EXISTS(SELECT 1 FROM public.budget_unbudgeted_resolution_events)
     OR EXISTS(SELECT 1 FROM public.budget_funding_actions WHERE action_kind='unbudgeted_resolution')
     OR EXISTS(SELECT 1 FROM public.budgets WHERE starting_kind='unbudgeted_resolution')
     OR EXISTS(SELECT 1 FROM public.budget_operations
       WHERE operation_type IN ('unbudgeted_resolution','unbudgeted_resolution_reversal')) THEN
    RAISE EXCEPTION 'Migration 023 must not create historical unbudgeted-resolution state';
  END IF;
END; $$;

COMMIT;
